[novafinedust] Test for optimizations on access to the serial port
openhab/openhab-addons pull request #10005
Opened 2021-01-31 15:27 UTC by t2000

- retry logic if port does not yet exist on startup
- do not write sleep command on shutdown if port has issues
- no not register data listener on port but wait for data instead to be
  compatible with RFC2217 serial over network implementation (see https://github.com/openhab/openhab-core/issues/2170)
- ignore all buffered data from device during initialization to get the
  device into a defined state

Signed-off-by: Stefan Triller <github@stefantriller.de>

2021-01-31 15:30 UTC, t2000 commented
This PR makes the usage of the binding MUCH more reliable, i.e. I do not fear restarting my openHAB installation where I had to pray whether or not the device is still working afterwards.
Also the RC2217 implementation (via ser2net) for the serial port works much better as the direct access to the port.

2021-02-01 02:52 UTC, cpmeister requested changes

2021-02-01 02:52 UTC, cpmeister commented on bundles/org.openhab.binding.novafinedust/src/main/java/org/openhab/binding/novafinedust/internal/sds011protocol/SDS011Communicator.java
> +        logger.debug("Initializing with mode={}, interval={}", mode, interval);
I suggest changing the logging level of most of these to `trace` instead.

My general rule for logging levels is:
* trace - used for normal expected execution paths
* debug - used for unexepected execution paths, but well within normal operation
* info - used for notable points in an execution path, like a milestone. (in openhab we try reserve this logging level for the core, so bindings should rarely ever call this.)
* warn - used for notable unexpected execution paths that a regular user (not just a developer) should be notified of. Warnings should be used to indicate that something not-normal occurred and user intervention is required to resolve. Warnings do not indicate a failure to operate merely an abnormal condition of operation that can still be handled by the binding. Failures in binding operation should be indicated by changing the thing status to offline.
* error - used to indicate catastrophic program failure. This should be used to indicate a catastrophic failure in openhab's ability to operate. A failure in a binding would never cause openhab as a whole to fail so a failure in a bindings should never log an error. Instead that failure should be indicated by changing the thing status.

2021-02-01 02:52 UTC, cpmeister commented on bundles/org.openhab.binding.novafinedust/src/main/java/org/openhab/binding/novafinedust/internal/sds011protocol/SDS011Communicator.java
> +                sleepJob = localScheduler.submit(new Runnable() {
Please use a lambda here instead.

2021-02-01 15:15 UTC, t2000 commented
Thanks for your review. I have moved most logging to TRACE and changed the scheduling of the sleepjob to use a lambda.

I would appreciate if you can have another look. Thanks!

2021-02-04 06:45 UTC, cpmeister requested changes
Only a few last changes I'd like.

2021-02-04 06:45 UTC, cpmeister commented on bundles/org.openhab.binding.novafinedust/src/main/java/org/openhab/binding/novafinedust/internal/sds011protocol/SDS011Communicator.java
> +            logger.debug("Got an exception while writing a command, will not try to fetch a reply for it.");
You should include the exception message in the log so that it is easier to know what went wrong.

2021-02-04 06:45 UTC, cpmeister commented on bundles/org.openhab.binding.novafinedust/src/main/java/org/openhab/binding/novafinedust/internal/SDS011Handler.java
> +                                "Cannot query data from device");
You should include the exception message in the status detail so that users have a better idea of what went wrong.

2021-02-04 07:34 UTC, t2000 commented
@cpmeister Thank you very much, I have integrated your changes.

2021-02-04 19:49 UTC, cpmeister approved these changes

2021-02-04 19:49 UTC, merged