[smartmeter] Fix trying to create channels from invalid data
openhab/openhab-addons pull request #10008
Opened 2021-01-31 16:13 UTC by t2000

Fixes #6762

Signed-off-by: Stefan Triller <github@stefantriller.de>

2021-01-31 16:29 UTC, msteigenberger approved these changes

2021-01-31 21:06 UTC, Hilbrand approved these changes
LGTM

2021-01-31 21:08 UTC, Hilbrand requested changes
3 unit tests failed. Related to your changed?

2021-01-31 21:55 UTC, t2000 commented
Yes they were indeed related to my changes :(

Good that we had them! @msteigenberger could you please have another look again, since I had to split the method into 2 now because to me it looks like they were used for 2 different purposes. Thanks.

2021-02-01 20:43 UTC, msteigenberger requested changes

2021-02-01 21:42 UTC, t2000 commented on bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/SmartMeterBindingConstants.java
> +        return obis.replaceAll("\\.", "-").replaceAll(":|\\*", "_").replaceAll("[^\\w-]", "");
Indeed, makes sense. I have added another commit with the change. Thanks.

2021-02-01 22:17 UTC, msteigenberger approved these changes

2021-02-01 22:17 UTC, msteigenberger commented
Lgtm. Thanks!

2021-02-03 20:22 UTC, t2000 commented
@Hilbrand Since the tests are green now and the changes have been approved again, may I kindly ask you to click the merge button? Thank you!

2021-02-03 20:36 UTC, Hilbrand approved these changes
LGTM. Good to give me a trigger. Due to the amount of messages I sometimes miss things :wink:

2021-02-03 20:37 UTC, merged