[miio] add support for zhimi.airpurifier.vb2 Mi Air Purifier Pro H
openhab/openhab-addons pull request #10183
Opened 2021-02-16 22:43 UTC by marcelrv

close #10152

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

2021-02-17 08:18 UTC, marcelrv commented
@theater updated the modes to the ones visible in the app

2021-02-18 15:06 UTC, theater commented
Hi Marcel,
Sorry for the confusion. I played a bit with the Mode and it seems that I have provided you false information for the Mode.

0, 1 are OK. 
2 Should be "Favourite" because when enabled it automatically turns the Fan level to the one set in the fan_level channel.
3 should be "Manual" maybe because when turned on in the UI it provides you a slider which you can define the mode based on room square feet.

All in all the settings work and look great.

Thank you very much for adding this to the DB!

2021-02-18 15:42 UTC, theater approved these changes

2021-02-25 21:52 UTC, cpmeister requested changes

2021-02-25 21:52 UTC, cpmeister commented on bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.vb2-miot.json
> +				"type": "Number:Duration",
```suggestion
				"type": "Number:Time",
```
Please update elsewhere as appropriate.

2021-02-26 10:05 UTC, marcelrv commented on bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.vb2-miot.json
> +				"type": "Number:Duration",
Yep, this one also had it

2021-02-26 18:58 UTC, cpmeister approved these changes

2021-02-26 18:58 UTC, merged