[chromecast] Added play URL actions to chromecast binding
openhab/openhab-addons pull request #10245
Opened 2021-02-26 03:11 UTC by computergeek1507

Added play URL actions to chromecast binding. URL and mimeType can be passed to the chromecast binding.

Signed-off-by: Scott Hanson <scooter_seh@yahoo.com> (github: computergeek1507)

2021-03-13 18:58 UTC, fwolter requested changes

2021-03-13 18:58 UTC, fwolter commented on bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/action/ChromecastActions.java
> +            logger.info("Handler is null, cannot play.");
Logging to info should be used sparsely e.g. a newly started component or a user file that has been loaded. This could be warn. Same for below.

2021-03-14 12:05 UTC, fwolter approved these changes
LGTM

@kaikreuzer Do you want to take another look, as the code owner? 135 lines

2021-03-14 17:16 UTC, kaikreuzer approved these changes
lgtm, thanks!

2021-03-14 17:16 UTC, merged