[Tesla] Add SSO handler to authenticate against Tesla SSO service
openhab/openhab-addons pull request #10259
Opened 2021-02-28 11:58 UTC by cguedel

Signed-off-by: Christian Güdel <cg@dmesg.ch>

Fixes #10016

Adds authentication against the Tesla SSO service as described here https://tesla-api.timdorr.com/api-basics/authentication

2021-02-28 16:09 UTC, kaikreuzer commented
Looks like a productive weekend, thanks!
Will try to (start to) test & review tonight.

2021-02-28 16:28 UTC, kaikreuzer commented
First feedback: Creating an account thing (without filling in credentials or token) in the UI immediately results in two errors in the log:
```
17:26:27.024 [-thingHandler-1] ERROR o.o.b.t.i.handler.TeslaSSOHandler:253 - An exception occurred while invoking a HTTP request: 'java.lang.IllegalArgumentException: Buffering capacity 16384 exceeded'
17:26:27.024 [-thingHandler-1] ERROR o.o.b.t.i.handler.TeslaSSOHandler:178 - Failed to obtain code from SSO login page when submitting form, response status code: no response
```

2021-02-28 16:35 UTC, kaikreuzer commented
Second feedback: Vehicle discovery crashes with an exception:
```
17:33:47.439 [-thingHandler-3] WARN  o.o.c.i.c.WrappedScheduledExecutorService:67 - Scheduled runnable ended with an exception: 
javax.ws.rs.ProcessingException: java.io.IOException: IOException invoking https://owner-api.teslamotors.com/api/1/vehicles: HTTPS hostname wrong:  should be <owner-api.teslamotors.com>
	at org.apache.cxf.jaxrs.client.AbstractClient.checkClientException(AbstractClient.java:633)
	at org.apache.cxf.jaxrs.client.AbstractClient.preProcessResult(AbstractClient.java:607)
	at org.apache.cxf.jaxrs.client.WebClient.doResponse(WebClient.java:1145)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1082)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:927)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:896)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:461)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:135)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:130)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.get(SyncInvokerImpl.java:50)
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.get(InvocationBuilderImpl.java:88)
	at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler.queryVehicles(TeslaAccountHandler.java:209)
	at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler.lambda$1(TeslaAccountHandler.java:155)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: IOException invoking https://owner-api.teslamotors.com/api/1/vehicles: HTTPS hostname wrong:  should be <owner-api.teslamotors.com>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapException(HTTPConduit.java:1402)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1386)
	at org.apache.cxf.io.AbstractWrappedOutputStream.close(AbstractWrappedOutputStream.java:77)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:673)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:705)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1081)
	... 15 common frames omitted
Caused by: java.io.IOException: HTTPS hostname wrong:  should be <owner-api.teslamotors.com>
	at java.base/sun.net.www.protocol.https.HttpsClient.checkURLSpoofing(HttpsClient.java:648)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:581)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream$2.run(URLConnectionHTTPConduit.java:377)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream$2.run(URLConnectionHTTPConduit.java:373)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.getResponseCode(URLConnectionHTTPConduit.java:373)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.doProcessResponseCode(HTTPConduit.java:1599)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1627)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1572)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1373)
	... 22 common frames omitted
```

2021-02-28 16:55 UTC, cguedel commented
Interesting... could be that you get throttled by Tesla's WAF and the logon page now looks different. Will need to see if I can reproduce that.

The second thing looks very odd and not really related to the changes, more like a certificate issue?

2021-02-28 16:57 UTC, kaikreuzer commented
Will try to investigate myself as well. FTR: I am running the binding from within the IDE.

2021-02-28 16:59 UTC, cguedel commented
I was doing the same, Eclipse on Windows with Java 11, FWIW.

2021-02-28 17:04 UTC, cguedel commented
I know there is still one problem with the SSO handler. In case you successfully logged in on the SSO endpoint using username/password and try this again, it directly skips the sign in step upon fetching the login form. This is currently not (yet) handled by the handler.

But never saw those two issues/exceptions you just posted

2021-02-28 17:20 UTC, kaikreuzer commented
The exceptions are not fully reproducible. Now the discovery starts and I can see in the debugger that it has the correct vehicleArray, but the call in [this line](https://github.com/openhab/openhab-addons/pull/10259/files#diff-7ac9af9aea4bd8cf22da6ddde6ee480b06287b656312f1862f72410c5d362b45L395) results in an HTTP 408, which again makes the discovery return no results. Pretty weird...

2021-02-28 17:35 UTC, cguedel commented
Ah, the 408 means that the vehicle is asleep and you need to wake it up first. That's a trap that was in there before and I also fell into it the first time the discovery of the account actually worked :)

2021-02-28 18:19 UTC, kaikreuzer commented
Thanks - indeed, waking up the vehicle made it being discovered. Maybe something that could be improved, but not within this PR.
So good news is that account+vehicle things are now online. Will see if it stays like that and will meanwhile do the code review!

2021-02-28 18:23 UTC, kaikreuzer commented
Another exception that asks to be fixed:
```
19:18:47.000 [-thingHandler-3] ERROR o.o.b.t.i.h.TeslaAccountHandler:472 - An exception occurred while executing a request to the vehicle: 'null'
java.lang.NullPointerException: null
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.getVehicleId(TeslaVehicleHandler.java:227)
	at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler$Request.run(TeslaAccountHandler.java:466)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openhab.binding.tesla.internal.throttler.QueueChannelThrottler.lambda$0(QueueChannelThrottler.java:45)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

2021-02-28 19:06 UTC, kaikreuzer requested changes
Code wise it looks excellent! Looking forward to more contributions from you ;-)
A few small change requests below.

2021-02-28 19:06 UTC, kaikreuzer commented on bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/SSO/AuthorizationCodeExchangeRequest.java
> + * @author Christian Güdel
```suggestion
 * @author Christian Güdel - Initial contribution
```

2021-02-28 19:06 UTC, kaikreuzer commented on bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/SSO/AuthorizationCodeExchangeResponse.java
> + * @author Christian Güdel
```suggestion
 * @author Christian Güdel - Initial contribution
```

2021-02-28 19:06 UTC, kaikreuzer commented on bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/SSO/RefreshTokenRequest.java
> + * @author Christian Güdel
```suggestion
 * @author Christian Güdel - Initial contribution
```

2021-02-28 19:06 UTC, kaikreuzer commented on bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/SSO/AuthorizationCodeExchangeResponse.java
> +package org.openhab.binding.tesla.internal.protocol.SSO;
Please stick to lower case package names.
```suggestion
package org.openhab.binding.tesla.internal.protocol.sso;
```

2021-02-28 19:06 UTC, kaikreuzer commented on bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/SSO/TokenExchangeRequest.java
> + * @author Christian Güdel
```suggestion
 * @author Christian Güdel - Initial contribution
```

2021-03-01 07:23 UTC, cguedel commented on bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaSSOHandler.java
> +import org.apache.commons.lang.RandomStringUtils;
Oh sorry, did not see that. Of course, now replaced with pure java

2021-03-01 07:24 UTC, cguedel commented on bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaSSOHandler.java
> +            logger.error("An exception occurred while invoking a HTTP request: '{}'", e.getMessage());
Done, most of the logging changed to debug. If the SSO login or token renewal return null, the binding will go to OFFLINE stating a configuration error. I need this so the handler doesn't retry over and over again to login and then hit the WAF of Tesla (stated in the API docs).

2021-03-01 07:24 UTC, cguedel commented on bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaSSOHandler.java
> +public class TeslaSSOHandler {
Done

2021-03-01 07:24 UTC, cguedel commented on bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/SSO/AuthorizationCodeExchangeRequest.java
> +@SuppressWarnings("unused")
Done

2021-03-01 07:26 UTC, cguedel commented
@kaikreuzer Thanks for the quick review! I added the changes requested. Not sure what to do about the exceptions though. The very first one with the buffer capacity error seems very weird. The others I would say were already in :)

2021-03-01 14:18 UTC, kaikreuzer commented
> The very first one with the buffer capacity error seems very weird.

I haven't seen it ever again, so let's ignore it.
The "HTTPS hostname wrong" occurs quite regular for me, though, and it makes the vehicle Thing go OFFLINE for a while.
I traced it down to `HttpsClient.checkURLSpoofing()`, where there are no peer certificates available and the session is marked as invalidated. No idea how this happens, though.

I am fine to merge it like it is, though, and we can see what testing by others bring up. I might do a follow-up PR for handling this exception gracefully then.

2021-03-01 14:18 UTC, kaikreuzer approved these changes
Many thanks, let's get that into the SNAPSHOT distro and have people test it!

2021-03-01 14:19 UTC, merged

2021-03-01 16:24 UTC, kaikreuzer commented
FTR: The fix is now included in distro build 2230 - would be great if everyone could test it!

2021-03-01 16:31 UTC, kaikreuzer commented
@cguedel For the hostname exception, I have created https://github.com/openhab/openhab-addons/issues/10264 for further tracking. It also occurs on my production system, so it wasn't due to IDE or something like that.

Checking my log file, it occurs as often as every 4 minutes, so I guess we'll need to do something about it...

2021-03-01 17:06 UTC, phuongpham commented
Just downloaded the lastest snapshot from  https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.tesla/3.1.0-SNAPSHOT/org.openhab.binding.tesla-3.1.0-SNAPSHOT.jar

Everything works fine!
@cguedel and @kaikreuzer  great work!

2021-03-02 08:12 UTC, kaikreuzer commented
Cherry-picked it to `3.0.x`.

2021-03-03 20:48 UTC, mrphil81 commented
@cguedel and @kaikreuzer Thank you very much for your effort! I installed the snapshot jar file on my openhab version 3.0.1. Works like a charm again since 2 days. I also recognized the 408 exception (timeout due to sleeping vehicle), but it wakes up within a short time. I use it mainly to start/stop charging and display some vehicle information.
Thanks again, highly appreciated!

2022-01-06 21:12 UTC, ScanxTaz commented
Stupid question, but is there any update on this binding ?