Adding Co2 measurement
openhab/openhab-addons pull request #10324
Opened 2021-03-14 10:24 UTC by bjoernbrings

Added CO2 measurement and corrected one bug for humidity measurement (in fact it was working but seems like it was using a wrong register).

I don't have a unit with CO2 measurement but it has been tested by a user [here](https://community.openhab.org/t/vallox-mv-binding-co2-reading/118782/6).

Signed-off-by: bjoernbrings <bjoernbrings@web.de>

2021-03-15 22:50 UTC, fwolter requested changes

2021-03-15 22:50 UTC, fwolter commented on bundles/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVWebSocket.java
> +                updateChannel(ValloxMVBindingConstants.CHANNEL_CO2, new DecimalType(iCo2));
```suggestion
                updateChannel(ValloxMVBindingConstants.CHANNEL_CO2, new QuantityType<>(iHumidity, Units.PARTS_PER_MILLION));
```

2021-03-15 22:50 UTC, fwolter commented on bundles/org.openhab.binding.valloxmv/src/main/resources/OH-INF/i18n/valloxmv_de.properties
> +channel-type.valloxmv.co2.label = Co2
```suggestion
channel-type.valloxmv.co2.label = CO2
```

2021-03-15 22:50 UTC, fwolter commented on bundles/org.openhab.binding.valloxmv/src/main/resources/OH-INF/i18n/valloxmv_de.properties
> +channel-type.valloxmv.co2.description = Aktueller Kohlenstoffdioxid Gehalt in der Abluft
```suggestion
channel-type.valloxmv.co2.description = Aktueller Kohlenstoffdioxidgehalt in der Abluft
```

2021-03-15 22:50 UTC, fwolter commented on bundles/org.openhab.binding.valloxmv/src/main/resources/OH-INF/thing/thing-types.xml
> +            <channel id="co2" typeId="co2"/>
The rest of the file uses tabs for indentation, although spaces are correct. You could invoke `mvn spotless:apply` to fix the formatting.

2021-03-15 22:50 UTC, fwolter commented on bundles/org.openhab.binding.valloxmv/src/main/resources/OH-INF/thing/thing-types.xml
> +        <state readOnly="true" pattern="%d"/>
```suggestion
        <state readOnly="true" pattern="%d %unit%"/>
```

2021-03-17 08:35 UTC, bjoernbrings commented
Thanks for your input

2021-03-19 20:24 UTC, fwolter approved these changes
LGTM

2021-03-19 20:24 UTC, merged