[KNX][WIP] Add BAOS support and use Calimero 2.5
openhab/openhab-addons pull request #10407
Opened 2021-03-28 20:06 UTC by petero-dk

Upgrade the calimero dependency to 2.5 which uses java11 and fixes many many things.

2021-03-28 20:08 UTC, petero-dk commented
For now it uses the 2.5-M1 release until the official 2.5 release.

https://search.maven.org/artifact/com.github.calimero/calimero-core/2.5-M1/jar

2021-12-20 19:41 UTC, petero-dk commented
@wborn since calimero is now at 2.5 and now officially part of openhab, the baos changes are minor, and backwards compatible.

2021-12-21 08:14 UTC, lolodomo commented
Is it now finished or still work in progress?

2021-12-21 08:16 UTC, lolodomo requested changes

2021-12-21 08:16 UTC, lolodomo commented on bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialClient.java
> +                return KNXNetworkLinkFT12.newCemiLink(serialPort, settings); // , deviceType);
Please suppress the ending comment

2021-12-21 08:19 UTC, lolodomo commented
Can you fix DCO check? 

The default translations should be updated.

2021-12-21 08:20 UTC, lolodomo commented
@sjka ; any comment?

2021-12-21 08:32 UTC, J-N-K commented
What is the deviceType for? It's not used as far as I can see.

2021-12-21 12:49 UTC, petero-dk commented
The device type is an addition that is waiting for a change in calimero, that is also why it is commented out but there for future easy implementation - some BAOS devices handle commands differently, but support for that has not been implemented in Calimero yet.

I can completely remove it, if that is better?

2021-12-21 12:57 UTC, petero-dk commented on bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialClient.java
> +                return KNXNetworkLinkFT12.newCemiLink(serialPort, settings); // , deviceType);
Done

2021-12-21 12:57 UTC, petero-dk commented
Cleaned code and removed unused deviceType

2021-12-21 22:12 UTC, lolodomo requested changes
Please also add 2 lines in the default properties file, for the label and description of your new parameter.

2021-12-21 22:12 UTC, lolodomo commented on bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/SerialBridgeConfiguration.java
> +    public Boolean getUseCEMI() {
boolean

2021-12-21 22:14 UTC, lolodomo commented
And please fix build by running man spotless:apply

2022-01-02 22:50 UTC, petero-dk commented
> Please also add 2 lines in the default properties file, for the label and description of your new parameter.

Where is that, I have added description and label in the serial.xml file

2022-01-03 23:58 UTC, petero-dk commented
I see changes are already merged in another PR, so closing this - THANKS!

2022-01-03 23:58 UTC, closed without merging

2022-01-04 08:08 UTC, lolodomo commented
No there was no other KNX PR merged in the openHAB repo.