[rachio] Initial contribution
openhab/openhab-addons pull request #10434
Opened 2021-04-02 14:31 UTC by markus7017

This binding integrates Rachio sprinkler controllers. The binding uses the Rachio Cloud API. Event callback can be configured to utilized myopenhab.org as a proxy.

2021-04-11 01:00 UTC, robnielsen commented
@markus7017, I'm trying out the rachio binding, and noticed some messages getting logged with INFO. These will need to be changed to debug or higher.

2021-04-13 18:03 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/README.md
> +    Thing rachio:zone:1:XXXXXXXXXXXX-8 "Rachio zone 8" @ "Sprinkler"
I'm seeing the following in openhab.log with my 8 zone rachio:
```
2021-04-13 12:47:27.271 [INFO ] [el.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'rachio.things', using it anyway:
Provide a thing type ID and a thing ID in this format:
 <thingTypeId> <thingId>
Provide a thing type ID and a thing ID in this format:
 <thingTypeId> <thingId>
Provide a thing type ID and a thing ID in this format:
 <thingTypeId> <thingId>
Provide a thing type ID and a thing ID in this format:
 <thingTypeId> <thingId>
Provide a thing type ID and a thing ID in this format:
 <thingTypeId> <thingId>
Provide a thing type ID and a thing ID in this format:
 <thingTypeId> <thingId>
Provide a thing type ID and a thing ID in this format:
 <thingTypeId> <thingId>
Provide a thing type ID and a thing ID in this format:
 <thingTypeId> <thingId>
Provide a thing type ID and a thing ID in this format:
 <thingTypeId> <thingId>

```

2021-04-13 18:06 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/discovery/RachioDiscoveryService.java
> +    private static final int DISCOVERY_REFRESH_SEC = 900;
Why is this necessary every 15 minutes? Once a controller is configured why does this need to continually occur?

2021-04-13 18:09 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/discovery/RachioDiscoveryService.java
> +                    if (zone.getEnabled() == OnOffType.ON) {
Shouldn't all zones be added, even if they are currently be disabled?  The zones can be ignored in the inbox if needed.

2021-04-13 18:14 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/discovery/RachioDiscoveryService.java
> +                    logger.info("Zone#{} '{}' (id={}) added, enabled={}", zone.zoneNumber, zone.name, zone.id,
logger.debug

2021-04-13 18:15 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/discovery/RachioDiscoveryService.java
> +                        logger.info("Zone#{} '{}' is disabled, skip thing creation", zone.name, zone.id);
logger.debug

2021-04-13 18:15 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/discovery/RachioDiscoveryService.java
> +            logger.info("{}  Rachio device initialized.", deviceList.size());
logger.debug

2021-04-13 18:15 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/discovery/RachioDiscoveryService.java
> +                logger.info(" Rachio device discovered: '{}' (id {}), S/N={}, MAC={}", dev.name, dev.id,
logger.debug

2021-04-13 18:15 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/discovery/RachioDiscoveryService.java
> +                logger.info("   device status={}, paused/sleep={}, on={}", dev.status, dev.getSleepMode(),
logger.debug

2021-04-13 18:16 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioZoneHandler.java
> +                    logger.info("{}: Zone {} STARTED watering ({}).", thingId, zoneName, event.timestamp);
logger.debug

2021-04-13 18:16 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioZoneHandler.java
> +                    logger.info(
logger.debug

2021-04-13 18:17 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioZoneHandler.java
> +                    logger.info("{}: Event for zone {}: {} (status={}, duration = {}sec)", thingId, event.zoneName,
logger.debug

2021-04-13 18:17 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioZoneHandler.java
> +                logger.info("{}: DELTA Event for zone {}: {}.{}", thingId, zone.name, event.category, event.action);
logger.debug

2021-04-13 18:24 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioBridgeHandler.java
> +            logger.info("RachioCloud: Connector initialized");
logger.debug

2021-04-13 18:24 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioBridgeHandler.java
> +                    logger.info("RachioCloud: New device detected: {} - {}", checkDev.id, checkDev.name);
logger.debug

2021-04-13 18:24 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioBridgeHandler.java
> +        logger.info("RachioCloud: Shutting down");
logger.debug

2021-04-13 18:27 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioDeviceHandler.java
> +                    logger.info("STOP watering for device '{}'", dev.name);
logger.debug

2021-04-13 18:27 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioDeviceHandler.java
> +                    logger.info("Start rain delay cycle for {} sec", command.toString());
logger.debug

2021-04-13 18:27 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioBridgeHandler.java
> +                    logger.info("RachioCloud: API limit is getting critical -> skip update ({} / {})", skipCalls,
logger.debug

2021-04-13 18:28 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioDeviceHandler.java
> +                    logger.info("{}: Device {}  was restarted, ip={}/{}, gw={}, dns={}/{}, wifi rssi={}.", thingId,
logger.debug

2021-04-13 18:28 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioDeviceHandler.java
> +                    logger.info("{}: Device is ONLINE.", thingId);
logger.debug

2021-04-13 18:28 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioDeviceHandler.java
> +                    logger.info("{}: Device is OFFLINE (subType = '{}').", thingId, event.subType);
logger.debug

2021-04-13 18:28 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioDeviceHandler.java
> +                    logger.info("{}: Device switch to sleep mode.", thingId);
logger.debug

2021-04-13 18:28 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioDeviceHandler.java
> +                    logger.info("{}: Device was resumed (exit from sleep mode).", thingId);
logger.debug

2021-04-13 18:28 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioDeviceHandler.java
> +                    logger.info("{}: Device reporterd Rain Delay ON.", thingId);
logger.debug

2021-04-13 18:28 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioDeviceHandler.java
> +                    logger.info("{}: Device reporterd Rain Delay OFF.", thingId);
logger.debug

2021-04-13 18:29 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioDeviceHandler.java
> +                    logger.info("{}: Device reporterd a Rain Sensor ON.", thingId);
logger.debug

2021-04-13 18:29 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioDeviceHandler.java
> +                    logger.info("{}: Device reporterd Rain Sensor OFF.", thingId);
logger.debug

2021-04-13 18:29 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/handler/RachioDeviceHandler.java
> +                logger.info("{}: Status {} for schedule {}: {} (start={}, end={}, duration={}min)", thingId,
logger.debug

2021-04-13 19:30 UTC, robnielsen commented on bundles/org.openhab.binding.rachio/src/main/java/org/openhab/binding/rachio/internal/discovery/RachioDiscoveryService.java
> +
Missing:

```
    @Override
    protected void stopBackgroundDiscovery() {
        logger.debug("Stopping background discovery for new Rachio controllers");
        if (discoveryJob != null) {
            discoveryJob.cancel(true);
            discoveryJob = null;
        }
    }
```

2021-06-21 19:18 UTC, kaikreuzer commented
@markus7017 Did you see @robnielsen's review comments?

2021-12-11 11:58 UTC, fwolter commented
@markus7017 Did you see @kaikreuzer's question if you saw @robnielsen comments?

2022-02-02 20:32 UTC, jlaur requested changes
Setting PR status according to pending review comments.

2022-06-11 07:12 UTC, lolodomo commented
Marked as "stale", last activity was 14 months ago and there were no answers to review comments.

2022-07-08 21:56 UTC, markus7017 commented
Hi gusy, sorry. I set other priorities, but just some people asked for OH 3.3 support so I'll work on this shortly

2022-07-10 08:16 UTC, wborn commented on bundles/org.openhab.binding.rachio/pom.xml
> +    <version>3.1.0-SNAPSHOT</version>
```suggestion
    <version>3.4.0-SNAPSHOT</version>
```

2022-12-23 15:49 UTC, jlaur commented on bundles/org.openhab.binding.rachio/pom.xml
> +  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```suggestion
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
```

See #11833

2022-12-29 10:52 UTC, wborn commented on bundles/org.openhab.binding.rachio/pom.xml
> +    <version>3.4.0-SNAPSHOT</version>
```suggestion
    <version>4.0.0-SNAPSHOT</version>
```

2023-01-16 15:55 UTC, lsiepel commented on bundles/org.openhab.binding.rachio/src/main/resources/OH-INF/binding/binding.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This needs to be adapted to the new `addon.xml`, the PR to adapt the developer docs is not merged yet, so if you need more details, the corresponding issue is here: https://github.com/openhab/openhab-core/issues/2058
But you can also update your branch and look at another binding's `addon.xml` and adapt it to this initial contribution.

2023-12-29 09:07 UTC, lsiepel commented
This PR is 2,5 years old. In https://github.com/openhab/openhab-addons/pull/10434#issuecomment-1179388515 @markus7017 (PR author) commented that his priorities have changed. Now (over a year later) the status quo has not changed. As this PR needs some work (review, fixes etc), i don't think some one else will bring it to a mergable state.
If ever needed it can be re-opened at any time.

2023-12-29 09:07 UTC, closed without merging