[espmilighthub] Describe group 0 handling
openhab/openhab-addons pull request #10473
Opened 2021-04-06 07:37 UTC by DrRSatzteil

Created a new PR since I messed up the old one...

This PR aims to add documentation for the handling of group 0 / ALL group.

2021-04-16 19:39 UTC, fwolter commented
@Skinah Can you take a look?

@DrRSatzteil You need to sign-off your commits. See https://www.openhab.org/docs/developer/contributing.html#sign-your-work The necessary commands are listed when you click on "Details" at the DCO check below. You can also post the sign-off tag here in the comments.

2021-04-16 19:49 UTC, DrRSatzteil commented
Signed-off-by: Thomas Lauterbach <thomas_lauterbach@arcor.de>

2021-04-16 19:52 UTC, DrRSatzteil commented
Just like this? I only edited the README in the browser so I did not clone the repository locally. Last time I tried the signoff from cli I somehow completely messed up the PR XD

2021-04-16 19:54 UTC, fwolter commented
That should be sufficient. Next time you could paste the sign-off message in the commit description whithin the web interface.

2021-04-16 19:55 UTC, DrRSatzteil commented
It says "Verified" now so I think this worked... Thank you for your help!

2021-04-24 05:03 UTC, Skinah commented on bundles/org.openhab.binding.mqtt.espmilighthub/README.md
> +While this functionality can also be achieved by using openHAB groups with even greater flexibility the group 0 must be setup if you want to capture remote events for the ALL group to keep physical d
```suggestion
While this functionality can also be achieved by using openHAB groups with even greater flexibility, the group 0 must be setup if you want to capture physical remote control events for the ALL group, and keep physical devices synchronized to their openHAB representations.
```

2021-04-24 05:10 UTC, Skinah commented on bundles/org.openhab.binding.mqtt.espmilighthub/README.md
> +To create the group manually proceed as described in section [Important for Textual Configuration](#important-for-textual-configuration) or use the openHAB 3 MainUI for this purpose.
Do not mention a version of openHAB, as when V4 is released this becomes outdated and hard to know it needs updating.

```suggestion
To create the group, use textual files or the openHAB UI to manually add a Thing with the correct Unique ID as described in section [Important for Textual Configuration](#important-for-textual-configuration).
```

2021-04-24 05:13 UTC, Skinah commented on bundles/org.openhab.binding.mqtt.espmilighthub/README.md
> +To create a Thing for the group 0 via MainUI simply create a new Thing that has the same type as one of autodiscovered Things of the same remote and modify the ThingUID as described in section linked
```suggestion
To create a Thing for the group 0, simply create a new Thing that has the same type as one of the auto discovered Things of the same remote and modify the ThingUID as described in section linked above.
```

2021-04-24 05:18 UTC, Skinah requested changes
Thank you for the submission/contribution. If you accept any of the suggestions, please make sure your approval comment has the signoff as the last line.

2021-04-24 10:15 UTC, DrRSatzteil commented
Signed-off-by: Thomas Lauterbach thomas_lauterbach@arcor.de

2021-04-24 15:58 UTC, DrRSatzteil commented
Sorry I don't get it how to sign off these commits correctly... I added the sign-off virtually everywhere, any help would be appreciated.

2021-04-28 09:42 UTC, Skinah commented
First why it has happened:
You have done 4 commits, the inital one and then 3 of my suggestions. The very first initial commit was missing the signoff completely. Then the three suggestions it appears you did try and my guess is you did not add the triangles around your email... 

Wont work
```
Signed-off-by: Thomas Lauterbach thomas_lauterbach@arcor.de
```

Should work if that name and email matches your github account.
```
Signed-off-by: Thomas Lauterbach <thomas_lauterbach@arcor.de>
```

It is easy to forget and it must be the very last line.

As to how to fix I am no expert and it can be done with git on the command line and how to do it is outlined by clicking on the details link next to where it tells you it failed...

https://github.com/openhab/openhab-addons/pull/10473/checks?check_run_id=2426281192

If you can not do it, just wait till the second person comes to review as sometimes it is waived for first time contributions. Hopefully the above makes it clear why it went wrong so next time it is a smooth process.

2021-04-28 09:44 UTC, DrRSatzteil reviewed
Signed-off-by: Thomas Lauterbach <thomas_lauterbach@arcor.de>

2021-04-28 09:49 UTC, DrRSatzteil reviewed
Signed-off-by: Thomas Lauterbach <lauterbachthomas@gmail.com>

2021-04-28 09:52 UTC, DrRSatzteil commented
> First why it has happened:
> You have done 4 commits, the inital one and then 3 of my suggestions. The very first initial commit was missing the signoff completely. Then the three suggestions it appears you did try and my guess is you did not add the triangles around your email...
> 
> Wont work
> 
> ```
> Signed-off-by: Thomas Lauterbach thomas_lauterbach@arcor.de
> ```
> 
> Should work if that name and email matches your github account.
> 
> ```
> Signed-off-by: Thomas Lauterbach <thomas_lauterbach@arcor.de>
> ```
> 
> It is easy to forget and it must be the very last line.
> 
> As to how to fix I am no expert and it can be done with git on the command line and how to do it is outlined by clicking on the details link next to where it tells you it failed...
> 
> https://github.com/openhab/openhab-addons/pull/10473/checks?check_run_id=2426281192
> 
> If you can not do it, just wait till the second person comes to review as sometimes it is waived for first time contributions. Hopefully the above makes it clear why it went wrong so next time it is a smooth process.

Thank you for your explanations. Since I messed up the first PR by trying to sign from the CLI (by following the steps described in the failing check) I think I will prefer the waiting option. However I noticed that I indeed used a different mail address in the comments than the one that I used for my GitHub account...

2021-04-28 09:53 UTC, Skinah approved these changes
All looks good here.

2021-04-28 09:53 UTC, Skinah commented on bundles/org.openhab.binding.mqtt.espmilighthub/README.md
> +## Using the group 0
```suggestion
## Using Group 0
```
Headings have each word capitalised. If you accept the change, be sure to add the signoff as the last line.

2021-04-28 09:57 UTC, DrRSatzteil reviewed
Signed-off-by: Thomas Lauterbach <2452988+DrRSatzteil@users.noreply.github.com>

2021-04-29 07:54 UTC, fwolter approved these changes

2021-04-29 07:55 UTC, merged