Add Co2 measurement for ValloxMV binding
openhab/openhab-addons pull request #10532
Opened 2021-04-16 11:18 UTC by mikaelgu80

[ValloxMV] Add support for Co2 measurement

Bugfix: Co2 measurement was added to the binding for 3.1.0, but there was an erroneus line that resulted in humidity reading being used as Co2. This PR is meant to fix that issue.

2021-04-16 11:30 UTC, bjoernbrings commented
My first two commits are already included in #10324

2021-04-16 11:30 UTC, bjoernbrings commented
Thanks for fetching that mistake

2021-04-16 20:45 UTC, fwolter requested changes
Can you fix the conflicting files?

2021-04-16 20:45 UTC, fwolter commented on bundles/org.openhab.binding.valloxmv/src/main/resources/OH-INF/i18n/valloxmv_de.properties
> +binding.valloxmv.description = Binding für das Online-Interface von Vallox Lüftungsanlagen
The properties file shall be ISO 8859-1. You made it UTF-8.

2021-04-17 04:41 UTC, closed without merging

2021-04-17 04:42 UTC, mikaelgu80 commented
I'll try this again.