[hue] Changed default color mode for color commands to XY
openhab/openhab-addons pull request #10608
Opened 2021-04-28 12:42 UTC by cweitkamp

- Changed default color mode for color commands to XY

Fixes #10159 

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

2021-05-04 09:50 UTC, lolodomo requested changes
Just an ultra minor typo in a comment.
Was this change validated with official hue color lights ?

2021-05-04 09:50 UTC, lolodomo commented on bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/LightStateConverter.java
> +        // XY color more is the implicit default: Use XY color mode if i) no color mode is set or ii) if the bulb is in
is more

2021-05-04 14:28 UTC, cweitkamp commented on bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/LightStateConverter.java
> +        // XY color more is the implicit default: Use XY color mode if i) no color mode is set or ii) if the bulb is in
fixed

2021-05-04 14:29 UTC, cweitkamp commented
>  Was this change validated with official hue color lights ?

Yes. I am running this for couple of days in my environment and it is working nice. You can find some links to Hue API docs to clarify on the change in https://github.com/openhab/openhab-addons/issues/10159#issuecomment-814787490.

2021-05-04 14:31 UTC, lolodomo approved these changes

2021-05-04 14:32 UTC, lolodomo commented
I am confident on you ;) I will let you know if I encounter problem once it is merged.

2021-05-09 18:05 UTC, fwolter approved these changes

2021-05-09 18:08 UTC, merged