[somfytahoma] Open to Connexoon and Cozytouch portals
openhab/openhab-addons pull request #10611
Opened 2021-04-28 18:38 UTC by lolodomo

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

2021-04-28 18:40 UTC, lolodomo commented
@octa22 : please have a look, I added the ability to choose other portals, Somfy Connexoon and Cozytouch.
Please note that for Connexoon the only difference is the URL; I applied the same session logic as for TahomaLink. I don't know if it will work.

2021-04-28 23:14 UTC, lolodomo commented
@octa22 : please have a look.
In addition to the different portals, I added an advanced option to use or not the session cookie. I thought it was required for the Cozytouch portal but then I tried to disable it (and so to use the same code as for TahomaLink) and I was surprised to discover it was apparently working. So maybe this option is useless but it is only an advanced option, disabled by default (meaning your original code is used by default).

2021-05-04 09:54 UTC, lolodomo commented
@octa22 : kind reminder

2021-05-05 20:44 UTC, octa22 commented on bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
>                  logger.debug("SomfyTahoma version: {}", data.getVersion());
I don't think the extra cookie handling is necessary. Tahoma needs the cookie as well but the jetty HttpClient handles this out of the box (unlike HttpURLConnection which I used before)

2021-05-05 20:45 UTC, octa22 commented on bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
> +        } else {
see above

2021-05-05 20:46 UTC, octa22 commented on bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
> +                || configurationParameters.containsKey("cookieRequired")) {
see above

2021-05-05 20:46 UTC, octa22 commented on bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/config/config.xml
> +			<advanced>true</advanced>
see above

2021-05-05 20:49 UTC, octa22 requested changes
Thanks  for the nice PR. Overall it looks good to me, I have just comment to the extra cookie handling. Not necessary in my opinion and makes the code more complex for nothing.

2021-05-06 09:25 UTC, lolodomo commented
> I have just comment to the extra cookie handling. Not necessary in my opinion and makes the code more complex for nothing.

Are you sure that your initial code will work with any portal ?
I will try again with Cozytouch.

2021-05-09 11:33 UTC, lolodomo commented
@octa22 : I removed the advanced setting.

2021-05-09 17:57 UTC, octa22 approved these changes
LGTM. Thanks!

2021-05-09 18:16 UTC, fwolter approved these changes

2021-05-09 18:16 UTC, merged