[powermax] Introduce some new channels for better status reporting
openhab/openhab-addons pull request #10624
Opened 2021-05-01 03:53 UTC by ronisaacson

Closes #9250 .

* New panel channels:
    - Ringing indicator (the siren is currently sounding)
    - Date/time the last message was received from the panel
    - List of all active alarms and alerts (similar to panel's
      Memory list, but items get removed from the list as conditions
      resolve)
* New zone channels:
    - Alarmed indicator (zone is in alarm, or has an alarm in memory)
    - Tamper alarm indicator (same but for a tamper condition)
    - Inactive indicator
    - Tamper indicator (zone is actively tampered right now)
    - Last status message received for this zone, and when
* Use descriptive names for zones in log messages. If you create a
  Thing for a zone, it will use that Thing's label in all reporting
  for that zone. If there's no Thing then it will attempt to use the
  zone label from the panel (e.g. "Basement").
* Clear all channels during startup to keep from displaying stale
  values loaded from persistence
* Also includes some minor SAT fixes (checkstyle, spotbugs)

Signed-off-by: Ron Isaacson <isaacson.ron@gmail.com>

2021-05-01 05:46 UTC, ronisaacson commented
Note: the CI build for this binding was [successful](https://ci.openhab.org/job/PR-openHAB-Addons/3977/org.openhab.addons.bundles$org.openhab.binding.powermax/). Build 3977 failed due to an unrelated error in a different binding.

2021-05-01 10:21 UTC, lolodomo commented
>     * Clear all channels during startup to keep from displaying stale
>       values loaded from persistence

This looks like a bad setup of your persistence stuff. You are not forced to persist your items and you are not forced to setup "restoreOnStaryp" on all your items.
There is no reason for a binding to implement something because a supposed usage of a persistence service or even a bad setup of the persistence service.
By the way, I will see which channels are concerned by this change and if it really makes sense.

2021-05-01 14:53 UTC, ronisaacson commented
> This looks like a bad setup of your persistence stuff. You are not forced to persist your items and you are not forced to setup "restoreOnStaryp" on all your items.

I'm open to suggestions on this. Right now it just uses the defaults, which I think persist all non-string items in rrd4j (more or less). I didn't do anything related to persistence but I notice that when OH restarts or the binding reloads or reconnects, all of the previous values come back.

If there's a way to disable persistence for some or all channels, that would probably be fine too.

2021-07-13 16:18 UTC, ronisaacson commented
Hey @lolodomo, just want to see if you have any additional feedback. I've been running this build for a few months now and I'm happy with it. I have it send me a text message whenever the `active_alerts` channel changes. That one channel is enough to get detailed info on all alerts (trouble conditions) and alarms.

Is there anything else you want to see to move forward with this?

2021-07-15 13:07 UTC, lolodomo commented
Needs to find more courage and time to test. M'y review has to be very serious as we are on a very sensitive (security) binding. But I will do, I have just forgotten.

2021-07-18 10:44 UTC, lolodomo requested changes
Review part 1 : channels

2021-07-18 10:44 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/channels.xml
> +	<channel-type id="last_message">
I would prefer last_message_time

Could be rather an advanced channel ?

2021-07-18 10:44 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/channels.xml
> +		<label>System Last Message Received</label>
Last Message Time

2021-07-18 10:44 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/channels.xml
> +	<channel-type id="ringing" advanced="true">
Could rather be not advanced ?

2021-07-18 10:44 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/channels.xml
> +	<channel-type id="zone_last_message">
I suggest last_status

2021-07-18 10:44 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/channels.xml
> +	<channel-type id="zone_last_message_time">
I suggest last_status_time

2021-07-18 10:44 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/ip.xml
> +			<channel id="last_message" typeId="last_message"/>
To be coherent with my suggestion: `<channel id="last_message_time" typeId="last_message_time"/>`

2021-07-18 10:44 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/serial.xml
> +			<channel id="last_message" typeId="last_message"/>
To be coherent with my suggestion: `<channel id="last_message_time" typeId="last_message_time"/>`

2021-07-18 10:44 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/zone.xml
> +			<channel id="zone_last_message" typeId="zone_last_message"/>
To be coherent with my suggestion: `<channel id="last_status" typeId="last_status"/>`

2021-07-18 10:44 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/zone.xml
> +			<channel id="zone_last_message_time" typeId="zone_last_message_time"/>
To be coherent with my suggestion: `<channel id="last_status_time" typeId="last_status_time"/>`

2021-07-18 10:44 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/state/PowermaxZoneState.java
> +    public StringValue lastMessage = new StringValue(this, ZONE_LAST_MESSAGE);
To be coherent with my suggestion: LAST_STATUS

2021-07-18 10:44 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/state/PowermaxZoneState.java
> +    public DateTimeValue lastMessageTime = new DateTimeValue(this, ZONE_LAST_MESSAGE_TIME);
To be coherent with my suggestion: LAST_STATUS_TIME

2021-07-18 10:44 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowermaxBindingConstants.java
> +    public static final String ZONE_LAST_MESSAGE = "zone_last_message";
To be coherent with my suggestion: LAST_STATUS = "last_status"

2021-07-18 10:44 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowermaxBindingConstants.java
> +    public static final String ZONE_LAST_MESSAGE_TIME = "zone_last_message_time";
To be coherent with my suggestion: LAST_STATUS_TIME = "last_status_time"

2021-07-18 10:44 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowermaxBindingConstants.java
> +    public static final String LAST_MESSAGE = "last_message";
To be coherent with my suggestion: LAST_MESSAGE_TIME = "last_message_time"

2021-08-07 12:40 UTC, lolodomo requested changes
Final part of my review.

2021-08-07 12:40 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/state/PowermaxState.java
> +    public void setInitialState() {
To be suppressed

2021-08-07 12:56 UTC, lolodomo commented
@ronisaacson : my review is now finished and that looks very good in general. To summarize, I am suggesting new names for only few added channels and your workaround introduced in the binding to fix one problem you have with persistence is not welcome ;)
I will now test your changes, at least partially, as I don't really want to make my alarm ringing...

2021-08-07 18:49 UTC, lolodomo requested changes
Anoter request change after testing

2021-08-07 18:49 UTC, lolodomo commented on bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/state/PowermaxState.java
> +        }
Please return "None" when `activeAlertList` is null too, it allows having the channel initialized to "None" after binding startup.

2021-08-07 19:04 UTC, lolodomo commented
Even after suppressing `setInitialState`, all channels are set as expected after binding startup except the "ringing" channel which is still not set. It would be better if it could be set to OFF after the init sequence.

2021-08-17 18:56 UTC, ronisaacson commented
@lolodomo thanks for your patience. Now that the persistence discussion is wrapped up, let's get this finished. If you have a branch with some or all of your changes, yes I'll happily take a PR. I'll look at the initialization of Ringing as well.

2021-08-23 19:08 UTC, lolodomo commented
I can prepare one during this week.

2021-08-23 20:23 UTC, ronisaacson commented
No don't go to any trouble, I'll start working on the changes shortly.

2021-08-28 08:03 UTC, lolodomo commented
I checked again what channels are not initialized (with my updated version opf the PR) after a full init sequence (reading of panel setup):

- new channel "ringing": my feeling is that this one should be set properly
- event_log_X but this is expected (will be set only when requesting the events history)
- update-event_logs and download_setup but this is expected as they are not channels with a real state
- last_trip but this is normal (will be set the next tiume the zone is tripped)
- new channels last_message and mast_message_time but this is normal (will be set when a new event will be received)

So except for the new channel "ringing", everything looks good to me.

Note that in "standard" mode (not powerlink mode), maybe more channels are not initialized, I have not tested it. Maybe something to test, especially for the new channels introduced by this PR.

2021-08-28 08:51 UTC, lolodomo commented
Just tested with the "standard" mode and good news, it makes no difference regarding channels initialization.

2021-09-08 16:57 UTC, lolodomo approved these changes
LGTM

2021-09-08 16:58 UTC, merged

2021-09-08 16:58 UTC, lolodomo commented
Thank you