[touchwand] - add support for risco alarm system sensors and AcWand thermostat
openhab/openhab-addons pull request #10748
Opened 2021-05-23 12:29 UTC by roieg

Add support for risco alarmsystem sensors and AcWand thermostat.

Improvement    - now support tow additional device types
* Risco alarm system sensors can be used as smoke , motion and door/window sensors 
* [AcWand](http://www.touchwand.com/products/touchwand-acwand/) thermostat fully supported ,able to control and read thermostat status , target room temperature , mode and fan level

2021-05-29 18:20 UTC, kaikreuzer requested changes
Thank you! Just some very small review comments.

2021-05-29 18:20 UTC, kaikreuzer commented on bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandBSensorHandler.java
> + *
```suggestion
```

2021-05-29 18:20 UTC, kaikreuzer commented on bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandBSensorHandler.java
> + *
```suggestion
```

2021-05-29 18:20 UTC, kaikreuzer commented on bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandBSensorHandler.java
> +        logger.info("recieved status {} from door unit {} ", isOpen, unitData.getName());
```suggestion
        logger.debug("received status {} from door unit {} ", isOpen, unitData.getName());
```

2021-05-29 18:20 UTC, kaikreuzer commented on bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandBSensorHandler.java
> +        logger.info("recieved status {} from motion unit {} ", motion, unitData.getName());
```suggestion
        logger.debug("received status {} from motion unit {} ", motion, unitData.getName());
```

2021-05-29 18:20 UTC, kaikreuzer commented on bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandThermostatHandler.java
> + *
```suggestion
```

2021-05-29 18:20 UTC, kaikreuzer commented on bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandThermostatHandler.java
> + *
```suggestion
```

2021-05-29 18:20 UTC, kaikreuzer commented on bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/discovery/TouchWandUnitDiscoveryService.java
> +                            logger.info("Unit discovery skipping unsupported unit type : {} ", type);
Please keep debug here.

```suggestion
                            logger.debug("Unit discovery skipping unsupported unit type : {} ", type);
```

2021-05-29 20:30 UTC, roieg commented on bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandBSensorHandler.java
> + *
done

2021-05-29 20:30 UTC, roieg commented on bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandBSensorHandler.java
> + *
done

2021-05-30 09:46 UTC, kaikreuzer approved these changes
Thanks!

2021-05-30 09:46 UTC, merged