[homeconnect] Factorize handling of power command
openhab/openhab-addons pull request #10747
Opened 2021-05-23 10:58 UTC by lolodomo

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

2021-05-23 11:06 UTC, lolodomo commented
@bruestel : I see the channel "power_state" for the cooktop (hob) with no handling of commands in the corresponding handler. Is it a read-only information for the cooktop or is something missing ?

2021-05-27 16:17 UTC, bruestel requested changes

2021-05-27 16:17 UTC, bruestel commented on bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectOvenHandler.java
>          // turn coffee maker on and standby
Could you please correct this comment. Copy and paste error by me.

2021-05-27 16:17 UTC, bruestel commented on bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java
> +            final HomeConnectApiClient apiClient, String stateNotOn)
Good idea. Should work for all appliances.
![Bildschirmfoto-20210527175827-1142x240](https://user-images.githubusercontent.com/2088078/119861230-71d6fd00-bf17-11eb-94e3-cd44fc26dce4.png)

2021-05-28 08:29 UTC, bruestel commented
> > Would you be so kind and add it?
> 
> I must use OFF or standby ?

Please just remove `// turn coffee maker on and standby`

2021-05-28 08:31 UTC, lolodomo commented
> 
> 
> > > Would you be so kind and add it?
> > 
> > 
> > I must use OFF or standby ?
> 
> Please just remove `// turn coffee maker on and standby`

I was asking for the cooktop. You told me you forgot th ehandling of the power command. So I will add it but I don't know if I should use OFF or Standby.

2021-05-28 08:40 UTC, lolodomo commented
I choose ON+standby for the cooktop, let me know if this is correct.

2021-05-28 09:34 UTC, lolodomo commented
Checking the API documentation, OFF must be considered for cooktop.

2021-05-28 09:38 UTC, bruestel commented
> Checking the API documentation, OFF must be considered for cooktop.

yes, OFF is correct

2021-05-28 11:59 UTC, lolodomo commented
@bruestel : please approve if this is now ok for you.

2021-05-28 13:00 UTC, merged