[pushsafer] Initial Contribution of Pushsafer Binding
openhab/openhab-addons pull request #10790
Opened 2021-06-01 18:33 UTC by cweitkamp

- Initial Contribution of Pushsafer Binding

Supersedes #9994

// CC @appzer

Signed-off-by: Pushsafer.com (Kevin Siml) <info@appzer.de>
Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

2021-07-10 16:03 UTC, fwolter requested changes

2021-07-10 16:03 UTC, fwolter commented on bundles/org.openhab.binding.pushsafer/src/main/resources/OH-INF/binding/binding.xml
> +	<description>Pushsafer - Notifications.</description>
Could you be a bit more verbose, so that somebody who hasn't heard about it gets a clue what this is about?

2021-07-10 16:03 UTC, fwolter commented on bundles/pom.xml
> -    <module>org.openhab.binding.qbus</module>
Can you revert this?

2021-07-11 12:57 UTC, cweitkamp commented on bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/connection/PushsaferCommunicationException.java
> +public class PushsaferCommunicationException extends RuntimeException {
Yes, in [PushsaferAPIConnection::getFromCache(...)](https://github.com/openhab/openhab-addons/pull/10790/files#diff-17f7e9cc1b5db91f18d42b881b63344aac0f4cf38f4d78af68065c7700e4ab64R151-R153) there is a call to `ExpiringCacheMap::putIfAbsentAndGet(..., ...)` which does not allow to throw checked exceptions. I added some additional `throws` and try-catch-blocks to indicate relevant places in the code.

2021-07-11 19:45 UTC, fwolter approved these changes
LGTM

2021-07-11 19:45 UTC, merged