[ihc] Improved command handling when controller is not ready
openhab/openhab-addons pull request #10895
Opened 2021-06-21 18:07 UTC by paulianttila

When connection from binding to IHC controller is open, but controller
is in programming state, things state is offline with special status to
indicate that binding can't send or receive any resource updates at the
moment. Things status check during command sending will prevent
unnecessary resource updates which will eventually fail and binding then
tries to restart the connection.

Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com>

2021-06-22 06:08 UTC, kaikreuzer requested changes

2021-06-22 06:08 UTC, kaikreuzer commented on bundles/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/handler/IhcHandler.java
> +            logger.warn("Controller is not ONLINE state, abort resource value update for channel '{}'!", channelUID);
```suggestion
            logger.debug("Controller is not ONLINE, aborting resource value update for channel '{}'!", channelUID);
```

2021-06-22 14:08 UTC, paulianttila commented on bundles/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/handler/IhcHandler.java
> +            logger.warn("Controller is not ONLINE state, abort resource value update for channel '{}'!", channelUID);
Done

2021-07-15 17:49 UTC, kaikreuzer approved these changes
Thank you!

2021-07-15 17:50 UTC, merged