[goecharger] Changed unit of SESSION_CHARGE_CONSUMPTION / Current_session_charged_energy
openhab/openhab-addons pull request #10903
Opened 2021-06-26 08:50 UTC by chilobo

2021-06-26 09:11 UTC, SamuelBrucksch requested changes
Looks good, thanks for that contribution. I proposed some changes.

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/README.md
> +Number:ElectricCurrent     GoEChargerMaxCurrTemp                "Maximum current temporary"                       {channel="goecharger:goe:garage:maxCurrentTemp"}
Rename a bit, this sounds like current temperature, for example `MaxCurrentTemporary`

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/README.md
> +    MaxCurrTemp.sendCommand(receivedCommand.state)
Please rename, sounds like current temperature

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/GoEChargerBindingConstants.java
> +    public static final String MAX_CURR_TEMP = "maxCurrTemp";
please rename to be more clear what this is, sounds like current temperature

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/api/GoEStatusResponseDTO.java
> +    public Integer maxCurrTemp;
please rename to be more clear what it means

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/api/GoEStatusResponseDTO.java
> +    public Double[] temptma;
java normally uses camel case naming conventions like tempTma when there are two different words

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerHandler.java
> +import static org.openhab.binding.goecharger.internal.GoEChargerBindingConstants.MAX_CURR_TEMP;
please rename

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerHandler.java
> +            case MAX_CURR_TEMP:
please rename

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerHandler.java
> +                if ((goeResponse.temptma == null) | (goeResponse.temptma.length == 0)) {
`||` instead of `|`
```suggestion
                if ((goeResponse.temptma == null) || (goeResponse.temptma.length == 0)) {
```

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerHandler.java
> +                if ((goeResponse.temptma == null) | (goeResponse.temptma.length <= 1)) {
```suggestion
                if ((goeResponse.temptma == null) || (goeResponse.temptma.length <= 1)) {
```

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerHandler.java
> +            case MAX_CURR_TEMP:
please rename

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerHandler.java
> +            ContentResponse contentResponse = httpClient.newRequest(urlStr).method(HttpMethod.GET)
Last time i used this i think only post worked, do new firmwares support get now? is this backwards compatible to old hardware?

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/thing/thing-types.xml
> +			<channel id="maxCurrTemp" typeId="amx"/>
please rename

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/thing/thing-types.xml
> +			<channel id="temptma1" typeId="tma1"/>
consider naming conventions

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/thing/thing-types.xml
> +		<label>Maximum Current Temporary</label>
```suggestion
		<label>Maximum Temporary Current</label>
```

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/thing/thing-types.xml
> +		<description>Maximum current per phase not stored in EEPROM</description>
```suggestion
		<description>Maximum current per phase. Not stored in EEPROM. Recommended to be used over "ama" when set often, for example during photovoltaic charging.</description>
```

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/thing/thing-types.xml
> +		<description>Power on all phases</description>
```suggestion
		<description>Accumulated power on all phases</description>
```

2021-06-26 09:11 UTC, SamuelBrucksch commented on bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/thing/thing-types.xml
> +		<label>Temperature_tma1</label>
i think this name should be chosen in a human readable format

2021-06-30 11:08 UTC, chilobo commented
I do not understand the DCO and PR-oepnHAB-Addons checks which failed. 
The Details links do not lead to anything I can understand.
Do I have to resolve that or is it done automatically once the reviewert accepts my changes?

2021-07-07 07:14 UTC, chilobo commented
> Looks good, thanks for that contribution. I proposed some changes. Mainly naming issues and documentation enhancements.

I resolved all the mentioned remarks and for one week nothing happens...

2021-07-07 07:25 UTC, SamuelBrucksch commented
You will find instructions how to fix the DCO voter by clicking on  `details`

2021-07-07 07:27 UTC, SamuelBrucksch commented
Also it does not look like you adressed all the points i mentioned. Did you push your changes?

2021-07-17 15:14 UTC, SamuelBrucksch commented
Please check again my review. You can also click on "commit suggestion" where it is proposed if you like my proposed changes.

2021-08-25 07:08 UTC, chilobo commented
GO-E changed the provided value of sessionChargeConsumption back, so I changed the calculation back too.
I do not understand why the submits are not merged.

2021-12-11 12:09 UTC, fwolter commented
@chilobo Is this ready for review?

2022-02-28 09:53 UTC, closed without merging

2022-02-28 09:55 UTC, chilobo commented
I am trying to get another, new pull-request after leaving this open for 9 month because I did not accomplish to get this one through, hopefully the new one will be successful.

2022-02-28 10:55 UTC, fwolter commented
No need to open a new one. Please stick to this PR.