Update README.md Signed-off-by: Ryan Johnston <github@shopandlearn.net>
openhab/openhab-addons pull request #10922
Opened 2021-07-01 14:57 UTC by freak3dot

Fix repeated word. Signed-off-by: Ryan Johnston <github@shopandlearn.net>

2021-07-01 16:06 UTC, robnielsen requested changes

2021-07-01 16:06 UTC, robnielsen commented on bundles/org.openhab.binding.insteon/README.md
> +If you can't build a new device out of the existing device features (for a complete list see `device_features.xml`) you can add new features by specifying a file (let's call it `my_own_features.xml`)
Please change to **can not** instead of **can't**

2021-07-02 12:59 UTC, Skinah approved these changes
Thanks for taking the time to fix. I'll approve any of the following:
can't = cannot = can not

2021-07-06 17:57 UTC, fwolter approved these changes
Thanks! @robnielsen can you file a follow-up PR?

2021-07-06 17:57 UTC, merged