[influxdb] Fix for influxdbv1 retention and table names containing keywords or special chars
openhab/openhab-addons pull request #11139
Opened 2021-08-21 20:24 UTC by fremel75

Bugfix for using itemnames beginning with numbers or having retention namnes beginning with numbers
Also solves if using old db where retention was named default wich is now a influxQL keyword

Solves
#https://github.com/openhab/openhab-addons/issues/9790
#https://github.com/openhab/openhab-addons/issues/10398

Added doubleqoutes for retention and table name as documentation for influxQL states
https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#identifiers

2021-08-22 10:32 UTC, J-N-K commented
IIRC item names are not allowed to start with a number.

2021-08-22 18:27 UTC, lujop requested changes
Thanks for the PR.
I think that the retentionPolicy doesn't need to be escaped because it's covered by the `appendName` function logic.
About the tablename it's ok to escape for the default keyword that isn't covered by the `appendName` but only when `escapeTableName` is true.
When it's false it's because tableName it's `/.*/` and it must not be escaped.

2021-08-22 21:23 UTC, fremel75 commented
Thanks for the feedback
I have reverted the code for escapeTableName function

But the appendName function doesent seem to work for this properly i guess since its not escaped?
Since it does not work without this change

From influx code
`  public static StringBuilder appendName(final String name, final StringBuilder stringBuilder) {
    String trimmedName = name.trim();
    if (trimmedName.startsWith("\"") || COLUMN_NAME_PATTERN.matcher(trimmedName).matches()) {
      stringBuilder.append(trimmedName);
    } else {
      stringBuilder.append('"').append(trimmedName).append('"');
    }
    return stringBuilder;
  }`

2021-08-23 16:09 UTC, lujop commented
> Thanks for the feedback
> I have reverted the code for escapeTableName function
> 
> But the appendName function doesent seem to work for this properly i guess since its not escaped?
> Since it does not work without this change
> 
> From influx code
> ` public static StringBuilder appendName(final String name, final StringBuilder stringBuilder) { String trimmedName = name.trim(); if (trimmedName.startsWith("\"") || COLUMN_NAME_PATTERN.matcher(trimmedName).matches()) { stringBuilder.append(trimmedName); } else { stringBuilder.append('"').append(trimmedName).append('"'); } return stringBuilder; }`

The way it is now looks good to me, except that I think that the escaping inside the `escapeTablename` if it's redundant.

Can you provide a case where it isn't working with the inputs?

2021-08-24 22:03 UTC, fremel75 commented
I have tested with "default" as retention name since this is a keyword now for the default retention in influx.
14:52:45.806 [DEBUG] [e.influxdb.InfluxDBPersistenceService] - Got a query for historic points!
14:52:45.829 [ERROR] [.internal.JSONResponseExceptionMapper] - Unexpected exception occurred while processing REST request.
org.influxdb.InfluxDBException: error parsing query: found DEFAULT, expected identifier at line 1, char 40


And with my item named "1WireOutsideTempSensor_Temperature"
```
23:47:15.841 [DEBUG] [e.influxdb.InfluxDBPersistenceService] - Got a query for historic points!
23:47:15.844 [ERROR] [.internal.JSONResponseExceptionMapper] - Unexpected exception occurred while processing REST request.
org.influxdb.InfluxDBException: error parsing query: found .1, expected ; at line 1, char 47
```
or by rest api
`"{\"error\":{\"message\":\"error parsing query: found .1, expected ; at line 1, char 47\",\"http-code\":500,\"exception\":{\"class\":\"org.influxdb.InfluxDBException\",\"message\":\"error parsing query: found .1, expected ; at line 1, char 47\",\"localized-message\":\"error parsing query: found .1, expected ; at line 1, char 47\"}}}"`

I see now that Documentation for Openhab states "Names must not begin with number" i did create this in Webui so i thought it was ok and in rrd4j it was working
https://www.openhab.org/docs/configuration/items.html#name

2021-08-28 14:03 UTC, lujop commented
> I have tested with "default" as retention name since this is a keyword now for the default retention in influx.
> 
> ```
> 14:52:45.806 [DEBUG] [e.influxdb.InfluxDBPersistenceService] - Got a query for historic points!
> 14:52:45.829 [ERROR] [.internal.JSONResponseExceptionMapper] - Unexpected exception occurred while processing REST request.
> org.influxdb.InfluxDBException: error parsing query: found DEFAULT, expected identifier at line 1, char 40
> ```
> 
> And with my item named "1WireOutsideTempSensor_Temperature"
> 
> ```
> 23:47:15.841 [DEBUG] [e.influxdb.InfluxDBPersistenceService] - Got a query for historic points!
> 23:47:15.844 [ERROR] [.internal.JSONResponseExceptionMapper] - Unexpected exception occurred while processing REST request.
> org.influxdb.InfluxDBException: error parsing query: found .1, expected ; at line 1, char 47
> ```
> 
> or by rest api
> `"{\"error\":{\"message\":\"error parsing query: found .1, expected ; at line 1, char 47\",\"http-code\":500,\"exception\":{\"class\":\"org.influxdb.InfluxDBException\",\"message\":\"error parsing query: found .1, expected ; at line 1, char 47\",\"localized-message\":\"error parsing query: found .1, expected ; at line 1, char 47\"}}}"`
> 
> I see now that Documentation for Openhab states "Names must not begin with number" i did create this in Webui so i thought it was ok and in rrd4j it was working
> https://www.openhab.org/docs/configuration/items.html#name

But with current PR code the retentionPolicy isn't escaped, isn't it?
I can't see why the default isn't escaped with current PR code.

2021-08-29 08:42 UTC, fremel75 commented
> 
> But with current PR code the retentionPolicy isn't escaped, isn't it?
> I can't see why the default isn't escaped with current PR code.
This PR adds ecaped doubleqoutes on retentionpolicy and item name
Since influx function appendName only adds doubleqoutes and that is not good enough
As you could see the appendName function does deal with if it called with "\"" so there is no problem doing it this way

2021-08-29 09:01 UTC, lujop commented
> > But with current PR code the retentionPolicy isn't escaped, isn't it?
> > I can't see why the default isn't escaped with current PR code.
> > This PR adds ecaped doubleqoutes on retentionpolicy and item name
> > Since influx function appendName only adds doubleqoutes and that is not good enough
> > As you could see the appendName function does deal with if it called with """ so there is no problem doing it this way

Excuseme, my last comment was incorrect, I wanted to say, the retentionPolicy **is** escaped, isn't it?

I think that we have some confusion in latest comments. For my the actual PR is ok, I only think that the doublequotes inside the `escapetablename` are redundant but not problematic.

When you say that you have problems, do you mean with this PR code or with actual code?

2021-08-31 17:12 UTC, fremel75 commented
First i experience no problems with the PR
I understand that you wonder about `escapetablename` but the appender function used there is not working for this plugin.
I dont understand either but it needs to be escaped doubleqoute for the plugin to work and the appenderfunction does not do that as it only doubleqoutes.

2021-08-31 22:22 UTC, lujop commented
I don't understand what do you mean with:
`the appenderfunction does not do that as it only doubleqoutes.`
The PR is doing exactly that, doublequoting the tablename. Why do you say that the appenderfunction does not work?

That's the code of the appended function:
```
private static final Pattern COLUMN_NAME_PATTERN = Pattern.compile("\\w+(?:\\[.+\\])?");
public static StringBuilder appendName(String name, StringBuilder stringBuilder) {
        String trimmedName = name.trim();
        if (!trimmedName.startsWith("\"") && !COLUMN_NAME_PATTERN.matcher(trimmedName).matches()) {
            stringBuilder.append('"').append(trimmedName).append('"');
        } else {
            stringBuilder.append(trimmedName);
        }

        return stringBuilder;
    }
```

Can you debug or check logs and say for which input it doesn't work?
For words, it's not escaped, but in theory, it isn't needed.
I'm fine with the escaping, but want to know in which case it's needed and not done by the `appendName`

2021-12-11 13:52 UTC, fwolter commented
@lujop Your proposed changes are now part of this PR. Are you confident that these will work? Can you test them?

2021-12-19 20:59 UTC, lujop commented
Hi fwolter, I'm pretty sure, but I hadn't time to test.
I will try next week, and also check if I can finish the SQL part on DBQuery addon.

2022-01-07 22:59 UTC, lujop commented
@fwolter I've done some little tests and it seems to work and escape it's done:
```2022-01-07 23:51:31.025 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query SELECT "value"::field,"item"::tag FROM "autogen"."LocalMoon_StartTime" ORDER BY time DESC LIMIT 1;```

2022-01-07 22:59 UTC, lujop approved these changes

2022-01-09 09:12 UTC, fwolter commented
There are some formatting issues. You can fix them with `mvn spotless:apply`.

2022-03-04 19:32 UTC, lsiepel commented
@lujop could you fix the formatting to get this build going?

2022-05-08 11:41 UTC, jlaur commented
@fwolter, @lsiepel - applied spotless.

2022-05-29 18:54 UTC, fwolter approved these changes

2022-05-29 18:54 UTC, merged