[mqtt.homeassistant] Implement Vacuum discovery for Homeassistant MQTT
openhab/openhab-addons pull request #11216
Opened 2021-09-07 15:54 UTC by t2000

Closes #8988

Automatically discovers vacuum robots running on Valetudo (RE) with enabled MQTT

Signed-off-by: Stefan Triller <github@stefantriller.de>

2021-11-03 18:25 UTC, t2000 commented
@fwolter I have rebased my changes and resolved the conflict.

2021-11-06 13:44 UTC, fwolter requested changes

2021-11-06 13:44 UTC, fwolter commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
> +    public static final String vacuumStateChannelID = "state";
Constants should be all upper case.

2021-11-06 13:44 UTC, fwolter commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
> +        protected String state_topic = "";
Normal members should be camelCase.

2021-11-07 14:14 UTC, t2000 commented
Thanks for the review, I have fixed the format error as well and rebased against the latest `main` branch too.

2021-11-07 14:57 UTC, fwolter approved these changes

2021-11-07 14:57 UTC, merged

2021-11-08 21:17 UTC, jochen314 commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
> +        protected String stateTopic = "";
Does this work?
Don't we need a @SerializedName("state_topic") vor the deserialization to work?

2021-11-09 11:52 UTC, antroids commented
> Closes #8988
> 
> Automatically discovers vacuum robots running on Valetudo (RE) with enabled MQTT
> 
> Signed-off-by: Stefan Triller [github@stefantriller.de](mailto:github@stefantriller.de)

Hi, 
thank you for your contribution!

Could you please show where you found specification of status attributes, like time or usage counters? 
I'm not 100% sure, but looks like these attributes were removed in latest Valetudo versions and they still exists only for Homie. Unfortunately, I'm far away from home and can't check this. 
There is also lack of full support of Home Assistant mqtt.vacuum specification in your implementation.

I have a branch with mqtt.vacuum specification fully implemented: https://github.com/antroids/openhab-addons/tree/mqtt_vacuum
We could merge status attributes into the branch, if there is specification on them somewhere.

2021-11-09 17:02 UTC, t2000 commented
>Could you please show where you found specification of status attributes, like time or usage counters?

I have used https://www.home-assistant.io/integrations/vacuum.mqtt/ and he output of my valetudo running vacuum cleaners :)

> I'm not 100% sure, but looks like these attributes were removed in latest Valetudo versions and they still exists only for Homie. Unfortunately, I'm far away from home and can't check this.

You are right! Just when I had finished my implementation and when I was searching for possibilities to overcome the map rotation issues in the robots, I also saw that valetudo has changed the mqtt schema to homie. But that shouldn't be an issue, since we could also implement this too.

> There is also lack of full support of Home Assistant mqtt.vacuum specification in your implementation.
my implementation was never meant to cover 100% of any spec. I built it to support the robots out of the box with all the features I need. Feel free to add more, it is OSS.

> I have a branch with mqtt.vacuum specification fully implemented: https://github.com/antroids/openhab-addons/tree/mqtt_vacuum
> We could merge status attributes into the branch, if there is specification on them somewhere.

I didn't know that? How can one know this if you do not leave a comment on the issue that I have closed? and why did you not create a PR yourself earlier or have commented on mine?

Anyway, feel free to add your stuff from your branch, which is missing in my implementation. I mean, in the end this is how OSS works, right? :)

2021-11-09 20:24 UTC, antroids commented
Maybe you have a mqtt messages from new Valetudo version? 
I would like to figure out how to handle these schema extensions, because they are specific for particular firmware version.
Maybe enable them based on manufacturer and topic prefix.