Kostalinverter binding redesigned 20210906 by Örjan Backsell
openhab/openhab-addons pull request #11217
Opened 2021-09-07 18:12 UTC by basse04

Kostalinverter binding redesigned 20210906 by Örjan Backsell

Signed-off-by: basse04 orjan.backsell@gmail.com
Also-by: Christian Schneider <>
Also-by: René Stakemeier <>
Also-by: Christoph Weitkamp <>

This is changes done because of problems with hanging communication with
inverter-type of Second generation PIKO 10-20.
The changes are done regarded to Exceptions for HttpClient.

Bugfix

2021-09-07 18:22 UTC, fwolter commented
The title of this PR will show up in the changelog. Can you give it a concise, meaningful name?

2021-09-20 05:46 UTC, kaikreuzer requested changes
Introducing a dedicated HttpClient is very expensive - this comes with a huge number of additional threads.
What's the problem with the shared client? Is it only that you need to set other values for the timeouts? Can't you do this for the individual requests instead?

2021-10-03 09:26 UTC, lolodomo requested changes

2021-10-03 09:26 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
> +
Please suppress this added blank line

2021-10-03 09:26 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
> +                    }
Please move your try before your switch so that you will have only one try/catch. This makes sense especially when all your catch code are similar.

2021-10-03 09:26 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
> +                    } catch (Exception handleCommandException) {
Please avoid catching a generic Exception but rather list more specific exceptions.
Same for all your added "catch"

2021-10-03 09:26 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
> +                                handleCommandException.getMessage());
Looks like you use httpClient as a channel name ???

2021-10-03 09:26 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
> +            } catch (Exception handleCommandException) {
Please do not catch Exception but rather a list of more specific exceptions like for example: `InterruptedException  | ExecutionException  | TimeoutException e`

2021-10-03 09:26 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
> +    private void refresh() throws Exception {
Ok, here is the source of the problem. Why did you make this change ?

2021-10-03 09:26 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/config/SecondGeneration.xml
> +		<parameter name="hasBattery" type="boolean" required="false">
If not required, please define a default value (to false ?).

2021-10-03 09:26 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationInverterConfig.java
> +    public int refreshInterval;
Please set it to 60, the default value defined in the XML file.
Note that you should remove the "required" tag for this parameter in the XML file.

2021-10-03 09:26 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PIKO1020.xml
> +
Added blank lines not expected

2021-10-03 09:26 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
> +            }
You are using the common HTTP client. There is no reason to add this code. The HTTP client is started when your thing is initialized.

2021-10-03 09:26 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
> +    private final String callURL(String dxsEntriesCall, HttpClient httpClient) throws Exception {
Same thing here regarding Exception

2021-10-03 09:26 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
> +                    closedChannelException.getMessage());
Mismatch with the parameters.

2021-12-11 15:03 UTC, fwolter commented
You wrote an answer to the review feedback in the commit message. I'm not sure if everbody noticed that. Better post comments via the normal GitHub comment form. Did you address all review comments?

2021-12-13 10:05 UTC, basse04 commented
Hi,
Thank's, I will do as you describe further on.
All comments with the latest included is addressed.
Do you want me to do a new commit regarded to this latest changes?

Br Basse

2021-12-17 08:04 UTC, lolodomo requested changes

2021-12-17 08:04 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
> +            e.printStackTrace();
Please do not do that. 
If you want to log the stack, just add your exception object as last parameter of your log.

2021-12-17 08:04 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
> +            e.printStackTrace();
Same here

2021-12-19 15:59 UTC, basse04 commented
Binding redesigned 20211219 by Örjan Backsell, regarded to requested changes.

2021-12-20 20:15 UTC, lolodomo requested changes
To finish this PR, please fix the still marked as unresolved comment, consider the next following improvement and sign your PR properly to avoid failing DCO check (squash your different commits in one if necessary).

2021-12-20 20:15 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
>          }
Please group like that as you are doing the same thing in each case:
```
        } catch (InterruptedException | ExecutionException | TimeoutException e) {
            logger.debug("Connection to inverter disturbed during configuration");
        }
```

2021-12-20 20:16 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/config/SecondGeneration.xml
> +		<parameter name="hasBattery" type="boolean" required="false">
Please add `<default>false</default>`

2021-12-20 21:15 UTC, basse04 commented
Thank's for your advices. I thought for some reason that I just had to Sign-off the very first commit in an PR and not the following ones. I see that I have like 6 with no Sign-off, could you Please advice me how to correct this.

2021-12-20 21:37 UTC, lolodomo approved these changes
LGTM

2021-12-20 21:39 UTC, lolodomo commented
> Thank's for your advices. I thought for some reason that I just had to Sign-off the very first commit in an PR and not the following ones. I see that I have like 6 with no Sign-off, could you Please advice me how to correct this.

The easiest way would be to squash all your commits in one with the correct sign-off-by.
If you do that, please do not change the code, I do not want to redo a full review.

2021-12-20 21:42 UTC, basse04 commented
Thank's again. I will have a look and try, but no new code ;-)

2022-01-12 10:33 UTC, basse04 commented
Hi @lolodomo,
I think I found the reason to the faulty Signed-off's, I have had an faulty configured Git-part in Eclipse( configured by myself)
And my problem is right now that I can't have these commits go clean throw the DCO test. I have as you can see tried a lot of different way's found on net to have it fixed, but with no good result. Please, advice me how to have it fixed.
I also found another problem, pom.xml for 3.3.0 has jsoup like 1.14.3 and I have not seen that change and still have jsoup like 1.8.3 in this version.
I have promised you to not change the code, so how do you think I will handle this?
I'm sorry for to take your time with this, but Thank's a lot for all advices.
BR Basse

2022-01-14 07:43 UTC, lolodomo commented
> Please, advice me how to have it fixed.

You changed only 5 files. I suggest that you backup your changed files, closes this PR and  create a new PR from a fresh new branch created from an uptodate main branch..

2022-01-24 12:24 UTC, closed without merging