[WIP] [Yeelight] Add support for ceiling11 devices
openhab/openhab-addons pull request #11245
Opened 2021-09-13 08:10 UTC by tmp-hallenser

Objective:
* Enhance Yeelight binding to support ceiling11 devices, e.g. Yeelight YLXD41YL model

Changes have been made by adjusting code based on previously supported devices types.

2021-09-19 09:49 UTC, martinvw requested changes

2021-09-19 09:49 UTC, martinvw commented on bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/discovery/YeelightDiscoveryService.java
> +            case ceiling11:
Are you sure this builds fine locally, was this already an existing field?

2021-09-19 09:49 UTC, martinvw commented on bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightHandlerBase.java
> +              return DeviceType.ceiling11;
This value does not actually appear in https://github.com/openhab/openhab-addons/blob/4ed24f878d72bf1a67d2270a37acf2f37eb3db24/bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/enums/DeviceType.java#L21

2021-12-29 18:24 UTC, lolodomo commented
@tmp-hallenser : are you still available to finish your proposal and consider review comments?

2022-01-01 21:09 UTC, closed without merging