[somfytahoma] Fixed rssi channels creation & properties updating
openhab/openhab-addons pull request #11254
Opened 2021-09-17 12:42 UTC by octa22

This PR fixes two bugs relating to the Somfy Tahoma binding
- RSSI dynamic channel creation was not working since OH 3.x
- server side of the Somfy Tahoma cloud has started sending an empty value which was not interpretted correctly

Signed-off-by: Ondrej Pecta <opecta@gmail.com>

2021-09-17 17:46 UTC, lolodomo requested changes

2021-09-17 17:46 UTC, lolodomo commented on bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
> +            logger.info("{} Creating a rssi channel", url);
Please keep a DEBUG level

2021-09-18 07:56 UTC, octa22 commented on bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
> +            logger.info("{} Creating a rssi channel", url);
of course, fixed

2021-09-18 08:55 UTC, lolodomo approved these changes
LGTM

2021-09-18 11:56 UTC, merged