[dbquery] JDBC database bridge
openhab/openhab-addons pull request #11428
Opened 2021-10-23 13:46 UTC by lujop

Introduce a Bridge to allow JDBC queries.

Implementation is nearly finished and it's working at my home device but needs some cleaning and documentation

2022-01-07 20:57 UTC, lujop commented
JDBC implementation is finished and ready for review

2022-05-27 19:53 UTC, jlaur requested changes
Thanks for your contribution and patience. I'm sorry you have not received any feedback after several months, and yet I don't have the expertise to assess all parts of this PR, especially the dependencies towards external libraries. I hope a more seasoned maintainer (ping @openhab/add-ons-maintainers) can step in and help. I must say that the code looks pretty good to me though.

2022-05-27 19:53 UTC, jlaur commented on bundles/org.openhab.binding.dbquery/README.md
> +JDBC driver must be installed in your OpenHab server. For convenience, if you only need one driver the addon provides several features with JDBC driver included for each of the previous databases.
Minor, but please reformat to one sentence per line.

2022-05-27 19:53 UTC, jlaur commented on bundles/org.openhab.binding.dbquery/README.md
> +JDBC driver must be installed in your OpenHab server. For convenience, if you only need one driver the addon provides several features with JDBC driver included for each of the previous databases.
```suggestion
JDBC driver must be installed on your openHAB server. For convenience, if you only need one driver the addon provides several features with JDBC driver included for each of the previous databases.
```

2022-05-27 19:53 UTC, jlaur commented on bundles/org.openhab.binding.dbquery/README.md
> +If you need more than one driver you must install them manually from OpenHab console.
```suggestion
If you need more than one driver you must install them manually from the openHAB console. 
```

2022-05-27 19:53 UTC, jlaur commented on bundles/org.openhab.binding.dbquery/README.md
> +### The Simplest case InfluxDB2
This covers also JDBC now, so why is InfluxDB2 added to chapter name?

2022-05-27 19:53 UTC, jlaur commented on bundles/org.openhab.binding.dbquery/TODO
> +Si la configuració de la bbdd és buida el item no es connecta pero el log es molt dolent
Please remove this.

2022-08-01 20:19 UTC, jlaur commented
@lujop - are you still interested in a review?

2024-07-08 16:22 UTC, lsiepel commented
As there has been no activity for over two years, I guess we cannot get this to the finish line. I close this PR for now. If ever needed it can be re-opened again.

2024-07-08 16:22 UTC, closed without merging