[jsscripting] JS script engine no longer watches subdirs for scripts
openhab/openhab-addons pull request #11830
Opened 2021-12-21 10:23 UTC by jpg0

Fixed bug where subdirs (include node_modules) are watched for scripts. This change prevents subdirs being watched (libraries are still watched elsewhere).

Signed-off-by: Jonathan Gilbert <jpg@trillica.com>

2021-12-21 10:27 UTC, csowada commented
Here the bug report #11831

2021-12-21 15:31 UTC, digitaldan approved these changes
LGTM

2021-12-21 15:46 UTC, JamieTemple commented
a bit out of my depth here, but this change looks like it will stop watching all folders under `automation/js` - I have a lot of subfolders for organising my scripts - will these no longer be loaded?

2021-12-21 16:15 UTC, jpg0 commented
Yeah, this does remove watching of all subdirectories under `automation/js`.

I guess the two options are:
- only watch the root, meaning that all scripts need to go in this single directory
- watch whole tree except for `node_modules` and everything under it

I submitted this PR as it was the simplest way forward to fix the (major imo) bug, and I personally don't use scripts in multiple directories, so didn't really think about it. However, I understand that this was the way original scripts works, so maybe the second option would be better. It also looks like its possible to do without changing code in core (override `processWatchEvent`).

Happy to resubmit with the second option if this would be preferred?

2021-12-21 16:44 UTC, JamieTemple commented
> Yeah, this does remove watching of all subdirectories under `automation/js`.
> 
> I guess the two options are:
> 
> * only watch the root, meaning that all scripts need to go in this single directory
> * watch whole tree except for `node_modules` and everything under it
> 
> Happy to resubmit with the second option if this would be preferred?

Second option def sounds right to me :)

2021-12-21 22:13 UTC, digitaldan requested changes
Waiting on changes to support sub dirs, but exclude "node_modules"

2021-12-22 10:41 UTC, jpg0 commented
I've updated the PR to the new behaviour.

Whilst doing this I noticed that the library change watching doesn't seem to be working, I'm guessing that it was broken at some point in all this recent activity.

2021-12-23 21:57 UTC, moonraker46 commented
How can I fix this issue with a workaround? 
I have downloaded the 3.2 sources of the add-on, then changed the mentioned file https://raw.githubusercontent.com/openhab/openhab-addons/a130a224485520a0218e1ee8237c9eba792350c3/bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSScriptFileWatcher.java within the src directory and did a build of the 3.2*.jar with "man clean install" and dropped it into the OH  addons folder to install it.

But after a OH restart there was still the same behavior, every *.js from automation/js/node_modules was imported as a rule?

What have I to do to fix this? This behavior is crashing my complete OH system due to the resulting Java memory leaks. 

Thanks!

2021-12-24 09:12 UTC, jpg0 commented
@moonraker46 I'm not sure why this is occuring; can you use the OH cli to ensure that you have the correct version (and only one!) running?

2021-12-24 10:02 UTC, jpg0 commented
I've modified this change to ensure that module reloading is functioning. Unfortunately the issue was due to problems much lower level in `WatchQueueReader` so has required more complexity at this level (without needing to make changes in core).

2021-12-24 17:26 UTC, digitaldan commented
So i'm not seeing any change in behavior either.  I added some logging and it doesn't seem like the JSScriptFileWatcher is ever called, at least "processWatchEvent" never gets called.  I'm still debugging on my end to see why the service is not registering

2021-12-24 20:56 UTC, jpg0 commented
Something that I found out is that you cannot have two things watching the same path; the last one will replace the first. The updated code that I pushed ensured that the library listener gets activated after the script listener. However if there is anything else listening to that path it would cause problems.

Weird that it's not working at all though; I have it running against 3.3.0-SNAPSHOT on a clean docker install.

2021-12-24 21:10 UTC, J-N-K commented
@jpg0: https://github.com/openhab/openhab-core/issues/2466

2021-12-24 22:03 UTC, jpg0 commented
@J-N-K that is precisely the behaviour I observed. My workaround was to explicitly control the registration behaviour, however I suspect the state of individual systems (with additional watchers) may subvert this.

2021-12-25 21:11 UTC, florian-h05 commented
Another idea of how to fix this:
What about having two folders in `automation/js`?

E.g., having `node_modules` for the libs and sth like `scripts` for the scripts?

2021-12-26 15:05 UTC, jpg0 commented
@florian-h05 good idea, however if you move scripts to `automation/js/scripts`, then libraries need to also move to `automation/js/scripts/node_modules`. Don't worry about it though, it can certainly be fixed. First I'd like to see why my fix is not working for others, as it may require a simple change to get it working for all.

@digitaldan the problem I had before is exactly as @J-N-K describes - in the WatchQueueReader it could only handle a single service per directory. Try looking into it's execution as soon as it sees a change in `automation/js` and see why it's not propagating the event to the watcher (it's in the loop inside `WatchQueueReader.run()`).

2021-12-26 18:44 UTC, digitaldan commented
@jpg0 will do, i have some time today to look.

2021-12-30 07:13 UTC, moonraker46 commented
> @jpg0 will do, i have some time today to look.

Did you have success with fixing the root cause of this issue?

2022-01-01 18:22 UTC, florian-h05 commented
@digitaldan @jpg0 

Did you hace any success?

2022-01-01 18:25 UTC, digitaldan commented
I'm  working on it right now actually.  I modified the WatchQueueReader service to support multiple Watch Services as suggested, but am still running into issues where we try and load everything under node_modules.  Its a little slow going.

2022-01-01 19:26 UTC, jpg0 commented
Do you _need_ to make the fix to WatchQueueReader? Have you figured out why my PR is not working for you?

2022-01-01 19:27 UTC, digitaldan commented
@jpg0 I have a temporary fix while i continue trying to work on the WatchQueueReader

In JSScriptFileWatcher.java
```java
@Override
    protected boolean createAndLoad(ScriptFileReference ref) {
        if (ref.getScriptFileURL().getPath().startsWith(ignorePath)) {
            return false;
        }
        return super.createAndLoad(new ScriptFileReference(ref.getScriptFileURL()) {
            @Override
            public Optional<String> getScriptType() {
                assert super.getScriptType().get().equalsIgnoreCase("js");
                assert !super.getScriptFileURL().getPath().startsWith(ignorePath);
                return Optional.of(GraalJSScriptEngineFactory.MIME_TYPE);
            }
        });
    }
```

I'm assuming this should not be called if processWatchEvents is set to ignore that path, but even with my changes to WatchQueueReader , its still happening (likely i still need to tweak it) .  This is new territory  for me, so its a little slow going to debug.

2022-01-01 19:29 UTC, digitaldan commented
We posted at the same time, as you can see from above, for me processWatchEvent is called, but then so is createAndLoad, event though processWatchEvent ignored it.

2022-01-01 19:31 UTC, jpg0 commented
Can you see why it would have worked for me but not you? If so I could certainly modify the PR.

2022-01-01 19:35 UTC, digitaldan commented
I could never get it to work for me, or rather it might have worked at system startup, but if the binding gets restarted, you install a new version, etc... Then the issue would happen.   I tend to restart stuff a lot when debugging , maybe thats the difference?

2022-01-02 21:59 UTC, digitaldan commented
So i think we should add at a minimum the following (or something like it) as a fix for the time being to make the binding useable when using libraries.  I'm sure we will be doing a patch release to 3.2, and this would be a good one to get in. 
```java
 if (ref.getScriptFileURL().getPath().startsWith(ignorePath)) {
            return false;
        }
```

2022-01-03 10:44 UTC, jpg0 commented
@digitaldan the behaviour that you're seeing certainly seems strange. Do you have a configuration that I may be able to replicate? I ask because I'm loathe to support adding in code to avoid a situation we don't understand. Technically this code block should not be necessary as the existing code explicitly requests to not monitor subdirectories. Stepping though this stuff in a debugger should highlight the problem very quickly? (this is how I diagnosed the initial problems)

2022-01-03 18:47 UTC, digitaldan commented
Yeah, i have not run it through a debugger yet, i don't usually have my IDE setup for running core , so I'll probably do that soon.  

To reproduce I download a nightly snapshot
`wget "https://ci.openhab.org/job/openHAB3-Distribution/lastSuccessfulBuild/artifact/distributions/openhab/target/openhab-3.3.0-SNAPSHOT.zip"`

 unzip it and start it up.  I then install the shipped JSScripting binding through the UI which ensures any dependencies are installed, then i use the karaf console to install my compiled version of the binding like:

`bundle:update org.openhab.core file:///Users/daniel/openhab-main/git/openhab-core/bundles/org.openhab.core/target/org.openhab.core-3.3.0-SNAPSHOT.jar`

If you then move a library (say openhab-js) into the node_modules folder, i think things look ok until you  restart the binding (or the system)  then it tries to load everything.

2022-01-03 20:19 UTC, csowada commented
Maybe it is helpful, but I've not really checked it. On start of the binding the modified function ```processWatchEvent``` is not called. With the first update of a file it works as expected.

I think that we must also filter the root folder in ```ScriptFileWatcher.java``` 

```js
    private synchronized void onStartLevelChanged(int newLevel) {
        int previousLevel = currentStartLevel;
        currentStartLevel = newLevel;

        if (previousLevel < StartLevelService.STARTLEVEL_MODEL) { // not yet started
            if (newLevel >= StartLevelService.STARTLEVEL_MODEL) { // start
                ScheduledExecutorService localScheduler = executorFactory.get();
                scheduler = localScheduler;

                // ************** LOADS all incl. node.modules ?????
                // ***************************************************************
                localScheduler.submit(() -> importResources(new File(pathToWatch)));


                localScheduler.scheduleWithFixedDelay(() -> checkFiles(currentStartLevel), 0, RECHECK_INTERVAL,
                        TimeUnit.SECONDS);
            }
        } else { // already started
            assert scheduler != null;
            if (newLevel < StartLevelService.STARTLEVEL_MODEL) { // stop
                scheduler.shutdown();
                scheduler = null;
            } else if (newLevel > previousLevel) {
                scheduler.submit(() -> checkFiles(newLevel));
            }
        }
    }
```

2022-01-04 10:21 UTC, jpg0 commented
Ok, I just had another quick look at this. @csowada you were on the right track, that code is required to load scripts at startup, but there was other code in ScriptFileWatcher which assumed that subdirectories should be always processed.

I've submitted a PR to fix this: https://github.com/openhab/openhab-core/pull/2664

(I also noticed that in an update to this PR I had also managed to lose the code to ignore watching subdirs which I just readded.)

@digitaldan I would appreciate it if you could have another go at verifying this.

2022-01-08 00:04 UTC, digitaldan commented
Hi, just getting some time now to look. I'll give this a try now that the weekend is here and let you know, thanks!

2022-01-09 16:49 UTC, digitaldan commented
Nice Work!  Yes, along with https://github.com/openhab/openhab-core/pull/2664  i am not seeing these errors any more.

2022-01-09 16:49 UTC, digitaldan approved these changes

2022-01-15 10:05 UTC, wborn commented on bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSFileWatcher.java
> + * Copyright (c) 2010-2021 Contributors to the openHAB project
```suggestion
 * Copyright (c) 2010-2022 Contributors to the openHAB project
```

2022-01-15 12:31 UTC, janwo commented
@wborn Can we retrigger the build? I want to try this out ♥️

2022-01-15 12:49 UTC, wborn commented
> Can we retrigger the build?

That build would fail because of the invalid license header. :wink:

2022-01-16 18:47 UTC, jpg0 commented on bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSFileWatcher.java
> + * Copyright (c) 2010-2021 Contributors to the openHAB project
@wborn done

2022-01-17 18:07 UTC, digitaldan commented
👍

2022-01-17 20:57 UTC, moonraker46 commented
So basically there is no ready jsscripting  jar and depending core jar with included bug fix for OH3.2 to download yet?

2022-01-21 00:02 UTC, moonraker46 commented
> So basically there is no ready jsscripting jar and depending core jar with included bug fix for OH3.2 to download yet?

Builded the core org.openhab.core.automation.module.script.rulesupport-3.2.0.jar package https://file.io/F49ZdSzJcrq3 and and the scripting add-on  org.openhab.automation.jsscripting-3.2.0.jar https://file.io/BhvZpkGukD8x by myself (for OH 3.2.0).

Everything seems to work like a charm now.

2022-01-21 07:52 UTC, janwo commented
> > Can we retrigger the build?
> 
> That build would fail because of the invalid license header. 😉

Can we merge it now?😁

2022-01-22 17:38 UTC, digitaldan commented
@wborn this looks good to me 👍

2022-01-23 10:45 UTC, wborn approved these changes
Thanks for the fix! :+1:

2022-01-23 10:46 UTC, merged

2022-01-23 23:54 UTC, digitaldan commented
@jpg0 So this  is strange, i just downloaded the latest snapshot and am having issue loading any rules.  When starting up, no file based rules are loaded, i see nothing in the logs, and no rules show up in the UI.  If i edit a file based rule, then the script watcher does see it and loads the rule file, but i get the following exception:

```
15:49:31.500 [INFO ] [.rulesupport.loader.ScriptFileWatcher] - Loading script '/Users/daniel/openhab-main/openhab-3.3.0-SNAPSHOT/conf/automation/js/test.js'
15:49:31.501 [WARN ] [ommon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.IllegalStateException: The Context is already closed.
	at com.oracle.truffle.polyglot.PolyglotEngineException.illegalState(PolyglotEngineException.java:129) ~[?:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.checkClosed(PolyglotContextImpl.java:1025) ~[?:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.enterThreadChanged(PolyglotContextImpl.java:608) ~[?:?]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.enterCached(PolyglotEngineImpl.java:1885) ~[?:?]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.enterIfNeeded(PolyglotEngineImpl.java:1813) ~[?:?]
	at com.oracle.truffle.polyglot.PolyglotValueDispatch.hostEnter(PolyglotValueDispatch.java:1228) ~[?:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.getBindings(PolyglotContextImpl.java:966) ~[?:?]
	at com.oracle.truffle.polyglot.PolyglotContextDispatch.getBindings(PolyglotContextDispatch.java:97) ~[?:?]
	at org.graalvm.polyglot.Context.getBindings(Context.java:540) ~[?:?]
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.invokeFunction(GraalJSScriptEngine.java:548) ~[?:?]
	at org.openhab.automation.jsscripting.internal.scriptengine.DelegatingScriptEngineWithInvocableAndAutocloseable.invokeFunction(DelegatingScriptEngineWithInvocableAndAutocloseable.java:116) ~[?:?]
	at org.openhab.automation.jsscripting.internal.scriptengine.InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.invokeFunction(InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.java:119) ~[?:?]
	at org.openhab.automation.jsscripting.internal.scriptengine.DelegatingScriptEngineWithInvocableAndAutocloseable.invokeFunction(DelegatingScriptEngineWithInvocableAndAutocloseable.java:116) ~[?:?]
	at org.openhab.automation.jsscripting.internal.scriptengine.InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.invokeFunction(InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.java:119) ~[?:?]
	at org.openhab.core.automation.module.script.internal.ScriptEngineManagerImpl.removeEngine(ScriptEngineManagerImpl.java:207) ~[?:?]
	at org.openhab.core.automation.module.script.internal.ScriptEngineManagerImpl.createScriptEngine(ScriptEngineManagerImpl.java:127) ~[?:?]
	at org.openhab.core.automation.module.script.rulesupport.loader.ScriptFileWatcher.createAndLoad(ScriptFileWatcher.java:229) ~[?:?]
	at org.openhab.automation.jsscripting.internal.fs.watch.JSScriptFileWatcher.createAndLoad(JSScriptFileWatcher.java:55) ~[?:?]
	at org.openhab.core.automation.module.script.rulesupport.loader.ScriptFileWatcher.importFile(ScriptFileWatcher.java:213) ~[?:?]
	at org.openhab.core.automation.module.script.rulesupport.loader.ScriptFileWatcher.lambda$2(ScriptFileWatcher.java:205) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at org.openhab.core.automation.module.script.rulesupport.loader.ScriptFileWatcher.importFileWhenReady(ScriptFileWatcher.java:203) ~[?:?]
	at org.openhab.core.automation.module.script.rulesupport.loader.ScriptFileWatcher.processWatchEvent(ScriptFileWatcher.java:180) ~[?:?]
	at org.openhab.automation.jsscripting.internal.fs.watch.JSScriptFileWatcher.processWatchEvent(JSScriptFileWatcher.java:49) ~[?:?]
	at org.openhab.core.service.WatchQueueReader.lambda$3(WatchQueueReader.java:319) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

Further edits will not be picked up by the script watcher at this point.   I'm not sure what is going on.

2022-02-02 14:47 UTC, attilabalazsy commented
Guys, what is the good place putting my own library? Previously it was inside the node_modules/myfolder, now it is not loading even if I move the folder a level up (to the same level as node_modules). The library is simply not loading ...