[tplinksmarthome] Added KL430 lightstrip support
openhab/openhab-addons pull request #12000
Opened 2022-01-09 11:01 UTC by Hilbrand

Closes #8709

Additional:
Added action to send and receive json commands to a tplink device.
This can be used for test purposes or to run commands not available through channels.

Changed retry getting values 5 times before setting the device offline..Reduced socket time out to 2 seconds as it normally should react quickly and if it times out it tries again.

2022-02-03 00:02 UTC, dustinsoftware requested changes

2022-02-03 00:02 UTC, dustinsoftware commented on bundles/org.openhab.binding.tplinksmarthome/README.md
> +### KL400 Kasa Smart LED Light Strip, 16 Color Zones
```suggestion
### KL430 Kasa Smart LED Light Strip, 16 Color Zones
```

2022-02-05 09:12 UTC, lolodomo commented
@Hilbrand : is it still work in progress ?

2022-02-07 07:44 UTC, Hilbrand commented
I've remove the label work-in-progress as it's ready for review/merge.

2022-02-07 20:02 UTC, lolodomo commented on bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/handler/TPLinkSmartHomeActions.java
> +    @RuleAction(label = "@text/actions.send.label", description = "@text/actions.send.description")
actions.send.label and actions.send.description have to be added in tplinksmarthome.properties

2022-02-07 20:08 UTC, lolodomo commented on bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/handler/TPLinkSmartHomeActions.java
> +    private @Nullable ThingHandler handler;
Just a suggestion: You could use type `SmartHomeHandler` and in `setThingHandler` you then check if parameter "handler" is an instance of `SmartHomeHandler`.

2022-02-09 17:39 UTC, lolodomo approved these changes
LGTM

2022-02-09 20:02 UTC, lolodomo commented
@Hilbrand : my intention was to merge. What did you change after my review ? Why a force push which I have no way to see what you changed since my last review ?

2022-02-09 20:47 UTC, Hilbrand commented
@lolodomo I've only squashed to make sure it gets the commit message I preferred. You can see here there are o differences: https://github.com/hilbrand/openhab-addons/compare/fd7c251..5859a02

2022-02-10 18:58 UTC, lolodomo approved these changes

2022-02-10 18:58 UTC, merged

2022-02-11 00:33 UTC, dustinsoftware commented
Just FYI by squashing and force pushing, my name on the contribution was lost, would have been cool to keep that on the contributor page. :(

2022-02-11 06:10 UTC, lolodomo commented
Sorry for that but unfortunately the squashing was not done by myself.

2022-02-11 07:40 UTC, Hilbrand commented
@dustinsoftware that would have been inevitable. Even if I wouldn't have squashed it, it would have happened when @lolodomo would merge this pr. Because all pr's in this repository are squashed before merging.

2022-02-11 07:57 UTC, lolodomo commented
@Hilbrand : when squashing, we can keep the mention of several contributors, signed-off- by for the main author and another (sorry I do not remember the exact tag) for additional contributors.

2022-02-11 08:59 UTC, Hilbrand commented
@lolodomo Yes adding the other contributors is required, with `Also-by`, as is described on the [openHAB contribution page](https://www.openhab.org/docs/developer/contributing.html#sign-your-work), and that is what I put in the squash commit. But what @dustinsoftware is referring to is the [contributors page](https://github.com/openhab/openhab-addons/graphs/contributors) here on GitHub. If there are multiple contributors when the pr is merged and squashed it will register the commit to the original creator of the pr, and that will show up in git blame and therefor the contributors page.

2022-02-11 09:28 UTC, lolodomo commented
Ok, that is clearer now.