Nodon rollershutter repeater mode
openhab/openhab-addons pull request #12133
Opened 2022-01-27 08:45 UTC by SoCsOnFPGAsGuy

For NODONs in Wall Modules SIN-2-2-00 and SIN-2-1-0x it is already possible to adjust the repeater mode. For NODONs roller-shutter (SIN-2-RS-01) this wasn't possibly with openhab so far - this series of commits enables the repeater mode setting in openhab also for NODONs roller-shutter modules, the same way it is done for the other two in Wall Modules.

Correctness also tested physically with some of the roller-shutter modules in my own house.

2022-01-27 19:40 UTC, lolodomo requested changes
Just 2 minor comments

2022-01-27 19:40 UTC, lolodomo commented on bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_05/D2_05_00_NodON.java
> +        if (channelId.equalsIgnoreCase(CHANNEL_REPEATERMODE)) {
`equals` would be ok

2022-01-27 19:40 UTC, lolodomo commented on bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_05/D2_05_00_NodON.java
> +            if (command instanceof RefreshType) {
if (command == RefreshType.REFRESH) {

2022-01-28 12:31 UTC, lolodomo approved these changes
LGTM

2022-01-28 12:32 UTC, lolodomo commented
@fruggy83 ; is it ok for you?

2022-01-28 12:33 UTC, SoCsOnFPGAsGuy commented on bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_05/D2_05_00_NodON.java
> +        if (channelId.equalsIgnoreCase(CHANNEL_REPEATERMODE)) {
fixed

2022-01-28 12:33 UTC, SoCsOnFPGAsGuy commented on bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_05/D2_05_00_NodON.java
> +            if (command instanceof RefreshType) {
fixed

2022-01-30 10:12 UTC, merged

2022-01-30 16:38 UTC, fruggy83 reviewed
@SoCsOnFPGAsGuy thanks a lot for your work and sorry for my late review. Maybe my comments are helpful for another PR in the future :)

@lolodomo Thanks a lot for your review and pushing this PR. Sorry, I just came back from a short trip today.

2022-01-30 16:38 UTC, fruggy83 commented on bundles/org.openhab.binding.enocean/README.md
> +|                                 | receivingEEPId¹   |                             | A5_3F_7F_EltakoFSB, A5_3F_7F_EltakoFRM, A5_11_03, D2_05_00_NODON |
According to the rollershutter.xml the D2_05_00 EEP is still valid.

2022-01-30 16:38 UTC, fruggy83 commented on bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_05/D2_05_00_NodON.java
> +        if (channelId.equals(CHANNEL_REPEATERMODE)) {
I know that channelId should currently never be NULL, however I would just switch the comparision.