Better support for Legrand CAD protocol
openhab/openhab-addons pull request #12178
Opened 2022-01-31 09:43 UTC by jpenninkhof

# Title

Better support for Legrand CAD protocol

# Description

Improvement: Le Grand CAD is a relatively old protocol, supported by the RFXComXL device. The protocol as applies by LeGrand doesn't use certain fields such as Unitcode and a Command. Whenever a CAD message is sent, it is always of type TOGGLE (On or Off doesn't exist). This does cause a couple of challenges within OH3, but with this patch OH at least doesn't throw exceptions anymore when a CAD command is received.

Signed-off-by: Jan Penninkhof <jan@penninkhof.com>

2022-01-31 11:29 UTC, lolodomo commented
PR not properly signed

2022-02-05 08:07 UTC, lolodomo commented
@martinvw : is it ok for you?

2022-02-20 15:39 UTC, martinvw commented
> @martinvw : is it ok for you? 

Sorry, completely missed this one, I'll take a look now

2022-02-20 15:52 UTC, martinvw requested changes
My proposal would be to just add the two enum values, I would not expect the other changes to be needed.

2022-02-20 15:52 UTC, martinvw commented on bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5Message.java
> +        switch (subType) {
For a single case this repo normally just uses an if

2022-02-20 15:52 UTC, martinvw commented on bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5Message.java
> +                unitCode = 0x01;
Is this really needed, reading the SDK unit-codes are not used with a lot the sub-types so this distinction is not perse correct

2022-02-20 15:52 UTC, martinvw commented on bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5Message.java
> +                command = fromByte(Commands.class, data[8], subType);
I would expect hope this call could also be used for the newly added command

2022-03-05 09:38 UTC, lolodomo commented
@jpenninkhof : did you see the review comments form @martinvw ?

2022-11-05 13:13 UTC, lolodomo commented
Closing this PR as there was no activity/feedback since 9 months.
@penninkhof : reopen it in case you would like to finish that PR.

2022-11-05 13:13 UTC, closed without merging