[MCD] Added MCD Binding (#12201)
openhab/openhab-addons pull request #12202
Opened 2022-02-04 16:54 UTC by simon-dengler

## [MCD] Initial Contribution

### Description

This contribution adds the MCD Binding to the project.
No changes to previously existing bindings have been made.

2022-03-26 11:04 UTC, fwolter requested changes
Thanks for your contribution! I reviewed your code and here is my feedback.

There are some checkstyle warnings left. You could take a look at `target/code-analysis/report.html` after building it with `mvn clean install`.

There are some compiler warnings about null access left. You could take a look at `mvn clean install`. To fix these, you need to store the field to a local variable and do the null check on that.

2022-06-13 14:46 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeConfiguration.java
> +public class McdBridgeConfiguration {
Added the annotation

2022-06-13 14:47 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandler.java
> +        updateStatus(ThingStatus.UNKNOWN, ThingStatusDetail.BRIDGE_UNINITIALIZED, "initializing...");
I kept the details but changed the status from unknown to offline

2022-06-13 14:48 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandler.java
> +                updateStatus(ThingStatus.UNKNOWN, ThingStatusDetail.COMMUNICATION_ERROR, "an error occurred");
I changed the status to be set OFFLINE

2022-06-13 14:57 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandler.java
> +                                        "wrong credentials");
Ah I misunderstood that. I changed it to COMMUNICATION_ERROR.

2022-06-13 15:02 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandler.java
> +                logger.warn("Thread interrupted: {}", e.getMessage());
I followed your advice and now use a listener instead of this, so this problem is gone.

2022-06-13 15:04 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/SensorThingHandler.java
> +                    break;
I changed the whole structure to a stateless channel, so this endless statement is now completely gone.

2022-06-13 15:06 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/resources/OH-INF/i18n/mcd_xx.properties
> +# FIXME: please substitute the xx with a proper locale, ie. de
I removed that file.

2022-06-13 15:07 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/resources/OH-INF/thing/thing-types.xml
> +					sensor in MCD.</description>
Fixed it.

2022-06-13 15:10 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/resources/OH-INF/thing/thing-types.xml
> +		<label>Empty battery</label>
I fixed this for all labels.

2022-06-13 15:11 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/resources/OH-INF/thing/thing-types.xml
> +		</channel-type> -->
Removed it.

2022-06-13 15:11 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/resources/OH-INF/thing/thing-types.xml
> +	<!--<channel-type id="airPressure"> -->
Removed them.

2022-06-13 15:12 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/test/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandlerTest.java
> +            request.send(new BufferingResponseListener() {
Deleted all HTTP requests from the test classes.

2022-06-13 15:13 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/test/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandlerTest.java
> +                logger.error("{}", e);
Removed that statement.

2022-06-13 15:21 UTC, simon-dengler commented
Thank you @fwolter for the feedback. I'm now finally working on fixing the issues and will inform you, as soon as I'm done. 
BR Simon

2022-06-14 05:26 UTC, fwolter commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandler.java
> +        updateStatus(ThingStatus.UNKNOWN, ThingStatusDetail.BRIDGE_UNINITIALIZED, "initializing...");
Unknown is correct when trying to connect initially. You can set the status to offline or online in `logMeIn()`.

2022-06-14 05:29 UTC, fwolter commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandler.java
> +                logger.warn("{}", e.getMessage());
It's better to put the exception's message into the status detail message of `updateStatus()`. Then, the exception's message is displayed in the UI *and* is automatically logged. Then, you can remove your extra logging.

2022-07-01 13:59 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/README.md
> +| loginStatus | Switch | login status of the bridge (ON for logged in) |
I have removed this channel

2022-07-01 13:59 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/README.md
> +This binding allows you to send sensor events from your openHAB environment to the cloud application Managing Care Digital (MCD) by [C&S Computer und Software GmbH](https://www.managingcare.de/).
I have tried to explain it in more detail.

2022-07-01 14:02 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/README.md
> +| alarmAir       | Switch | set ON to send event for bad air quality, will be reset to OFF automatically after sending                               |
I have removed those channels and added one stateless channel to send all kinds of events by passing a String-type command, which can contain the event name or the respective ID.

2022-07-01 14:05 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/README.md
> +[//]: # (## Discovery)
I removed those lines

2022-07-01 14:07 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandler.java
> +        httpClient.setFollowRedirects(false);
The framework's client is being used now

2022-07-01 14:51 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandler.java
> +                                    timer.schedule(new TimerTask() {
Now the framework's scheduler is used.

2022-07-01 14:52 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandler.java
> +                logger.warn("{}", e.getMessage());
That's a great hint. I've changed that lines.

2022-07-01 14:53 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/SensorThingHandler.java
> +                mcdBridgeHandler.waitForAccessToken();
Now a listener is used.

2022-07-01 14:58 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/resources/OH-INF/binding/binding.xml
> +		application.</description>
I have described it in more detail.

2022-07-01 15:23 UTC, simon-dengler commented
@fwolter it seems as if I had messed something up with git here. I will close this pull request and try it again with a fresh one. Sorry for the mess!

2022-07-01 15:23 UTC, closed without merging