[bluetooth.airthings] Catch all exceptions in a scheduled task to prevent future executions from being suppressed.
openhab/openhab-addons pull request #12261
Opened 2022-02-12 04:49 UTC by s-pw

Fixes #9862

Signed-off-by: Pawel Switalski <switalski.pw@gmail.com>

2022-02-12 05:30 UTC, s-pw commented
https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.bluetooth.airthings/3.2.0-SNAPSHOT

2022-02-15 20:39 UTC, lolodomo requested changes

2022-02-15 20:39 UTC, lolodomo commented on bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AbstractAirthingsHandler.java
> +        try {
Following your (good) argument, the try/catch should be put in method executePeridioc, not method execute

2022-02-16 06:28 UTC, lolodomo approved these changes
LGTM

2022-02-16 06:30 UTC, merged