[hdpowerview] Remove unnecessary init checks and fix Thing status detail
openhab/openhab-addons pull request #12331
Opened 2022-02-20 18:37 UTC by fwolter

This PR is based on #12330.

@jlaur @andrewfg I made the following changes:

- Change the Thing status detail of the *bridge* to COMMUNICATION_ERROR. It was BRIDGE_OFFLINE, which is only intended for *child* Things showing they cannot go online, because their bridge is offline.
- Remove the configuration validation. This is done also for textual configuration from OH 3.3.0 on by using the XML constraints.
- Remove the check in the Things' `initialize()` if the Bridge type is correct. The UI doesn't let you configure a wrong type and the syntax of the .things file doesn't let you specify a wrong type either, because you can't even configure the binding ID for child Things. For example, use a Bridge of the LCN binding and configure a shade. The child Thing definition is ignored by the framework:
```
Bridge lcn:pckGateway:myPCHK [ hostname="serial-raspi", port=4114, username="lcn", password="p", mode="native200" ] {
    Thing shade s50150 "Living Room Shade" @ "Living Room" [id="501"]
}
```
- Set the Thing status detail to CONFIGURATION_ERROR, when the user didn't configure a bridge.

2022-02-20 19:31 UTC, jlaur commented
@fwolter, thanks for these improvements. Especially with this change, everything seems to be falling into place:

> Remove the configuration validation. This is done also for textual configuration from OH 3.3.0 on by using the XML constraints.

When recently doing 271d0271c23c1c4a47685e05d0649710f6f6cbf7, this kind of validation by the framework is exactly what I was missing.

2022-02-23 14:49 UTC, jlaur commented
@fwolter - I tested with core 3.3 (latest snapshot, build 2764) and this configuration:

```
Bridge hdpowerview:hub:hub [host="192.168.0.239"] {
    Thing shade blind1 [id="38196"]
    Thing shade blind2 [id="0"]
    Thing shade blind3 [id="-1"]
    Thing shade blind4 [id="1"]
}
```

blind1 correctly came **ONLINE** as configured with a valid ID. blind4 was correctly marked as **GONE** as ID doesn't exist. But blind2 and blind3 were left with status **UNKNOWN** while they should probably have been marked as **OFFLINE** with configuration error?

2022-02-23 15:09 UTC, jlaur requested changes
Please see comments.

2022-02-27 16:07 UTC, fwolter commented
> But blind2 and blind3 were left with status **UNKNOWN** while they should probably have been marked as **OFFLINE** with configuration error?

I would agree. Sounds like a bug in the core.

2022-02-27 16:14 UTC, fwolter commented on bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewRepeaterHandler.java
> -                    "@text/offline.conf-error.invalid-id");
Fixed.

2022-02-27 20:09 UTC, jlaur commented
> I would agree. Sounds like a bug in the core.

So maybe we should park this PR until core is fixed, since right now the validation within the binding is actually needed?

2022-02-27 20:51 UTC, fwolter commented
Yeah, do you open an issue?

2022-02-28 19:42 UTC, jlaur commented
> I would agree. Sounds like a bug in the core.

Getting prepared to create issue - were you able to reproduce the problem also?

2022-02-28 19:46 UTC, fwolter commented
No, I didn't test it.

2022-02-28 20:12 UTC, jlaur commented
@fwolter - I did one more test, latest 3.3-snapshot (build 2774) and this time from a clean installation. Now with different result - same config:

```
Bridge hdpowerview:hub:hub [host="192.168.0.239"] {
    Thing shade blind1 [id="38196"]
    Thing shade blind2 [id="0"]
    Thing shade blind3 [id="-1"]
    Thing shade blind4 [id="1"]
}
```

- blind1: **ONLINE**
- blind2: **UNINITIALIZED**, HANDLER_CONFIGURATION_PENDING, "Missing or invalid configuration."
- blind3: **UNINITIALIZED**, HANDLER_CONFIGURATION_PENDING, "Missing or invalid configuration."
- blind4: **OFFLINE**, GONE, "Shade is unknown to Hub"

I then tried reverting #12364 from your branch to see if `config-description` vs. `config-description-ref` would make any difference, but it didn't. I then tried editing the things file in multiple steps to see if dumping a new file would be handled differently than reloading the file after editing, but still everything works correctly.

So I'm sorry, I don't know why my previous test failed. Perhaps my test installation had some left-overs after simply overwriting all files with new snapshot.

**Conclusion:** No issue to be created and I think this PR is ready to be merged.

2022-02-28 21:31 UTC, fwolter commented
I think that's the best outcome we can get!

2022-02-28 21:53 UTC, jlaur approved these changes
Thanks for this improvement!

2022-02-28 21:53 UTC, merged