[homekit] add support for complex accessories
openhab/openhab-addons pull request #12346
Opened 2022-02-22 11:18 UTC by yfre

HomeKit accessory can be combination of multiple accessories, e.g. fan with light, sensor with battery, irrigation with multiple valves
iOS home app would show such complex accessory as one tile on the home screen that opens a view with multiple controls. 

this PR adds support for such complex accessories. 

in openHAB complex accessory would be modelled by adding additional HomeKit tag to the group metadata, e.g. 

```xtend
Group           FanWithLight        "Fan with Light"                           {homekit = "Fan,Light"}
Switch          FanActiveStatus     "Fan Active Status"     (FanWithLight)     {homekit = "Fan.ActiveStatus"}
Number          FanRotationSpeed    "Fan Rotation Speed"    (FanWithLight)     {homekit = "Fan.RotationSpeed"}
Switch          Light               "Light"                 (FanWithLight)     {homekit = "Lighting.OnState"}
```

it is backward compatible. all existing HomeKit configurations have only one tag at group level and should work as before.

2022-03-14 14:43 UTC, yfre commented
@andylintner @lolodomo 
could please review this PR. 
the UI part for this got merged already https://github.com/openhab/openhab-webui/pull/1317

im afraid, UI configurations that are not supported by the binding could confuse users.

2022-03-15 00:53 UTC, andylintner approved these changes
LGTM

2022-03-27 17:54 UTC, lolodomo requested changes
Only few typo

2022-03-27 17:54 UTC, lolodomo commented on bundles/org.openhab.io.homekit/README.md
> +For example, ceiling fans often include lighting functionality. Such fans can be modelled as:
I think it is "modeled" with only one l

2022-03-27 17:54 UTC, lolodomo commented on bundles/org.openhab.io.homekit/README.md
> +iOS home app use by default the type of the first accessory on the list for the tile on home screen.
... uses ...

2022-03-27 17:54 UTC, lolodomo commented on bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
> +     * accessory defined by that group and dont need to be created as accessory here.
... don't ...

2022-03-27 21:38 UTC, yfre commented
> Only few typo

thank you [lolodomo](https://github.com/lolodomo) for the review.

2022-03-27 22:11 UTC, merged

2022-04-12 10:29 UTC, JacekKac commented
Hi @yfre can you post an example of Valve grouping which are already in a group ?

```

Group                   gLawn1          "Zraszacz 1"                                            {homekit = "Valve" [homekitValveType="Irrigation", homekitTimer="true"]}
Switch                  Lawn1           "Valve active"                          (gLawn1)        {homekit = "Valve.ActiveStatus, Valve.InUseStatus"}
Number                  Lawn1_duration  "Valve duration"                        (gLawn1)        {homekit = "Valve.Duration" [homekitDefaultDuration = 300]}

Group                   gLawn2          "Zraszacz 2"                                            {homekit = "Valve" [homekitValveType="Irrigation", homekitTimer="true"]}
Switch                  Lawn2           "Valve active"                          (gLawn2)        {homekit = "Valve.ActiveStatus, Valve.InUseStatus"}
Number                  Lawn2_duration  "Valve duration"                        (gLawn2)        {homekit = "Valve.Duration" [homekitDefaultDuration = 300]}


```

2022-04-17 10:14 UTC, yfre commented
> Hi @yfre can you post an example of Valve grouping which are already in a group ?
> 
> ```
> 
> Group                   gLawn1          "Zraszacz 1"                                            {homekit = "Valve" [homekitValveType="Irrigation", homekitTimer="true"]}
> Switch                  Lawn1           "Valve active"                          (gLawn1)        {homekit = "Valve.ActiveStatus, Valve.InUseStatus"}
> Number                  Lawn1_duration  "Valve duration"                        (gLawn1)        {homekit = "Valve.Duration" [homekitDefaultDuration = 300]}
> 
> Group                   gLawn2          "Zraszacz 2"                                            {homekit = "Valve" [homekitValveType="Irrigation", homekitTimer="true"]}
> Switch                  Lawn2           "Valve active"                          (gLawn2)        {homekit = "Valve.ActiveStatus, Valve.InUseStatus"}
> Number                  Lawn2_duration  "Valve duration"                        (gLawn2)        {homekit = "Valve.Duration" [homekitDefaultDuration = 300]}
> ```
so, if you want to get something like this then this is currently not possible. this requires one more accessory type called "IrrigationSystem" which is not supported by homekit binding yet.  i have it on my todo list. 

![image](https://user-images.githubusercontent.com/11726616/163710113-e76b5cfc-68f4-49dc-b30a-f61cd6e5b0ec.png)

2022-04-17 12:46 UTC, JacekKac commented
thank you, 
i think ( i have only photo of such configuration left) it was build on homebridge without irrigation item support (no settings button at the bottom). Let's try on other items - is it possible to configure 2 homekit = "Lightning" items Lamp 1 and Lamp 2 under one grouped accessories GUI allows to Select Multiple accessories (many types ) but only one type occuring once). If i put "homekit="Lighting, Lighting" in text config GUI addoptes and allows to define 2 separate Lighting groups but it's not working in Home app

2022-04-19 09:34 UTC, yfre commented
> thank you, i think ( i have only photo of such configuration left) it was build on homebridge without irrigation item support (no settings button at the bottom). Let's try on other items - is it possible to configure 2 homekit = "Lightning" items Lamp 1 and Lamp 2 under one grouped accessories GUI allows to Select Multiple accessories (many types ) but only one type occuring once). If i put "homekit="Lighting, Lighting" in text config GUI addoptes and allows to define 2 separate Lighting groups but it's not working in Home app

multiple accessories of the same type is currently not supported. here we would need to have support group of groups as discussed here

https://community.openhab.org/t/does-openhab-support-grouping-homekit-accessories-in-different-types/132367/4?u=yfre

something like this

```
group combinedLights {homekit="Lighting, Lighting"}

group light1 (combinedLights) {homekit="Lighting"}
switch light1_switch (light1)

group light2  (combinedLights) {homekit="Lighting"}
switch light2_switch (light2)
```

it still looks complex to me but i dont have any better ideas for complex items of the same type