[http] Allow pre-escaped URLs
openhab/openhab-addons pull request #12350
Opened 2022-02-22 20:56 UTC by jamesmelville

Whilst it's helpful that the binding automatically escapes characters in URLs for us, there are some scenarios where it doesn't escape characters which need to be escaped for a specific API call. Because the binding escapes the URL for us, any attempts to include escaped characters ourselves result in the % sign also being included.

An example is an API I wanted to use which expects a query in this format:
https://example.com/api/query?q=deleted%3Dfalse%26creatorId%3Djames&sort=updatedTime+desc&count=1

`%3D` is `=`, and `%25` is `&`, these are both valid characters in a URL (see other examples in the URL), so reverting them to their unescaped values results in the API request being rejected.

Using the URL with the HTTP binding results in an error because of the use of java's string.format to include the date in the URL:
`Creating request for 'https://example.com/api/query?q=deleted%3Dfalse%26creatorId%3Djames&sort=updatedTime+desc&count=1' failed: Conversion = 'D'`

Including a double percentage sign results in the wrong URL being called and the API returning 400, as the remaining % is also encoded:
Requesting 'https://example.com/api/query?q=deleted%253Dfalse%2526creatorId%253Djames&sort=updatedTime+desc&count=1' (method='GET', content='null') failed: 400 null

I'm not the only one who needs a similar capability: https://community.openhab.org/t/oh3-http-binding-in-url/133503

I wanted to propose this PR to allow those who need to to escape the URL themselves. It's a fairly simple change to add an extra parameter on the channel to flag that the URL formed from the baseURL and it's extensions is already escaped.

2022-02-22 21:01 UTC, jamesmelville commented
Zipped Jar file of built code [org.openhab.binding.http-3.3.0-SNAPSHOT.zip](https://github.com/openhab/openhab-addons/files/8120144/org.openhab.binding.http-3.3.0-SNAPSHOT.zip)

2022-05-08 07:14 UTC, lolodomo requested changes
Only few remarks about updated documentation.

2022-05-08 07:14 UTC, lolodomo commented on bundles/org.openhab.binding.http/README.md
> +In certain scenarios you may need to manually escape your URL, for example if you need to include an escaped `=` (`%3D`) in this scenario include `%%3D` in the URL to preserve the `%` during formatti
r example if you need to include an escaped `=` (`%3D`)**.
I**n this scenario**,** include

2022-05-08 07:14 UTC, lolodomo commented on bundles/org.openhab.binding.http/README.md
> +| `escapedUrl`            | yes      |      -      | This specifies whether the URL is already escaped. |
You set a default, which is false

2022-05-08 07:14 UTC, lolodomo commented on bundles/org.openhab.binding.http/README.md
> +| `headers`         | yes      |    -    | Additional headers that are sent along with the request. Format is "header=value". Multiple values can be stored as `headers="key1=value1", "key2=value2", "
This is something fully unrelated to your enhancedment. I would suggest you exclude from this PR and you either propose a simple update of the doc for this or even better you could open an issue.

2022-05-16 15:00 UTC, lolodomo commented
@jamesmelville : did you see my review comments?

2022-05-29 06:58 UTC, lolodomo commented
As there is no feedback but my comments were relatively minor and only about documentation, I propose to merge.

2022-05-29 06:58 UTC, merged