[somfytahoma] added support for turning off unsupported devices logging
openhab/openhab-addons pull request #12372
Opened 2022-02-25 19:13 UTC by octa22

This PR adds a parameter logUnsupported to the bridge configuration so you can turn off unsupported devices definition logging.
This can be very useful in case you have an unsupported devices which floods your openhab.log with its definition.
By default it is enabled so we can add the support.

Discussed here: https://github.com/openhab/openhab-addons/issues/12213

Signed-off-by: Ondrej Pecta <opecta@gmail.com>

2022-02-26 08:59 UTC, lolodomo commented
@octa22 : why not rather log that with DEBUG level ? This would be more natural IMHO. Like that, this will not be logged by default. And users who have devices not discovered will just enable DEBUG logs to try having more information.

2022-02-27 14:28 UTC, octa22 commented
You are right. The device support is pretty broad, let's change the severity to DEBUG.

2022-02-27 15:09 UTC, lolodomo requested changes

2022-02-27 15:09 UTC, lolodomo commented on bundles/org.openhab.binding.somfytahoma/README.md
> +If you are missing some device, check the debug log during the discovery and create an issue with the information about an unsupported thing form the log.
Typo: form vs from

2022-02-27 16:44 UTC, lolodomo approved these changes
LGTM

2022-02-27 16:44 UTC, merged