Possibly wrong use of isHoliday instaed of canChangeTemp
openhab/openhab-addons pull request #12413
Opened 2022-03-04 16:50 UTC by seime

Fix for #12166

2022-03-04 19:45 UTC, jlaur commented on bundles/org.openhab.binding.millheat/src/main/java/org/openhab/binding/millheat/internal/model/Heater.java
> +        canChangeTemp = dto.canChangeTemp; // Was dto.holiday
I would drop this comment, since this was a bug and can only lead to confusion. It can be tracked in git history.

2022-03-05 08:56 UTC, lolodomo requested changes

2022-03-05 08:56 UTC, lolodomo commented on bundles/org.openhab.binding.millheat/src/main/java/org/openhab/binding/millheat/internal/dto/DeviceDTO.java
> +    public boolean canChangeTemp = false;
No need to set it explicitly to false as it is implicitly done.

2022-03-06 19:55 UTC, jlaur commented
@seime - signoff missing for last commit.

2022-03-07 20:30 UTC, lolodomo approved these changes
LGTM

2022-03-07 20:37 UTC, merged