[openwebnet] handle monitoring messages
openhab/openhab-addons pull request #12485
Opened 2022-03-16 18:13 UTC by aconte80

Enhance OpenWebNet binding to support thermoregulation with 4/99 zone central unit, e.g. BTicino 3550 model.

The Central Unit provides some information on the on-board display:

- at least one probe in OFF mode (WHAT = AT_LEAST_ONE_PROBE_OFF)
- at least one probe in PROTECTION mode (WHAT = AT_LEAST_ONE_PROBE_ANTIFREEZE)
- at least one probe in MANUAL mode (WHAT = AT_LEAST_ONE_PROBE_MANUAL)
- a generic FAILURE was detected on the system (WHAT = FAILURE_DISCOVERED)

For each case a specific read-only channel was added.

This PR depends on https://github.com/openhab/openhab-addons/pull/12483

2022-03-16 18:20 UTC, lolodomo commented
Conflicts to be resolved first.

2022-03-17 12:12 UTC, lolodomo requested changes

2022-03-17 12:12 UTC, lolodomo commented on bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
> +            logger.debug("updateCUBatteryStatus(): {}", status);
Please surround with {}

2022-03-17 12:12 UTC, lolodomo commented on bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
> +            logger.debug("updateCUFailureDiscovered(): {}", status);
Please surround with {}

2022-03-17 12:12 UTC, lolodomo commented on bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
> +                updateCUAtLeastOneProbeOFF(OnOffType.OFF);
Rather use isEmpty()

2022-03-17 12:12 UTC, lolodomo commented on bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
> +            if (probesInProtection.size() == 0) {
Rather use isEmpty()

2022-03-17 12:12 UTC, lolodomo commented on bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
> +            if (probesInManual.size() == 0) {
Rather use isEmpty()

2022-03-17 18:28 UTC, lolodomo requested changes

2022-03-17 18:28 UTC, lolodomo commented on bundles/org.openhab.binding.openwebnet/README.md
> +Switch iCU_3550_at1off    "At least one probe in OFF"         (gCentralUnit) { channel="openwebnet:bus_thermo_cu:mybridge:CU_3550:atLeastOneProbeOFF" }
Please also add a line for new channel failureDiscovered.

2022-03-17 18:29 UTC, lolodomo commented
@mvalla : is it ok for you ?

2022-03-17 19:56 UTC, lolodomo approved these changes
LGTM

2022-03-18 08:27 UTC, mvalla requested changes
I would only change the capital OFF in the name of the channel, just to make it similar to the other channels.  For the rest it looks good, excellent improvement thanks!

2022-03-18 08:27 UTC, mvalla commented on bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
> +		<description>At least one probe in Protection (Anti Freeze/Thermal Protection) indicator in Central Unit (read only)</description>
```suggestion
		<description>At least one probe in PROTECTION (Anti Freeze/Thermal Protection) indicator in Central Unit (read only)</description>
```

2022-03-18 08:27 UTC, mvalla commented on bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoCentralUnit.xml
> +			<channel id="atLeastOneProbeOFF" typeId="atLeastOneProbeOFF"/>
What about changing `atLeastOneProbeOFF ` -> `atLeastOneProbeOff ` similar to the other channels?

2022-03-18 08:27 UTC, mvalla commented on bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
> +    public static final String CHANNEL_CU_AT_LEAST_ONE_PROBE_OFF = "atLeastOneProbeOFF";
What about changing `atLeastOneProbeOFF ` -> `atLeastOneProbeOff ` similar to the other channels?
see other comment below

2022-03-18 08:27 UTC, mvalla commented on bundles/org.openhab.binding.openwebnet/README.md
> +| `atLeastOneProbeOFF`         | `bus_thermo_cu`                        | Switch             | Indicates if at least one probe is in OFF mode: `ON`, `OFF`
What about changing `atLeastOneProbeOFF ` -> `atLeastOneProbeOff ` similar to the other channels?
see other comment below

2022-03-18 10:01 UTC, aconte80 commented
@mvalla I've updated string upper/lowercase as suggested

2022-03-18 10:37 UTC, mvalla commented
ok. @lolodomo: his LGTM and for me can be merged

2022-03-18 18:00 UTC, merged