[openwebnet] added channel "function" for Central Unit
openhab/openhab-addons pull request #12483
Opened 2022-03-15 19:52 UTC by aconte80

Enhance OpenWebNet binding to support thermoregulation with 4/99 zone central unit, e.g. BTicino 3550 model.

This PR adds the `function` channel  (allowed values HEATING/COOLING) to the binding. 
It is a readonly channel, the value can only be changed manually acting on the Central Unit.

2022-03-16 07:34 UTC, lolodomo requested changes

2022-03-16 07:34 UTC, lolodomo commented on bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
> +                logger.info("handleMessage() Ignoring unsupported WHAT {}. Frame={}", msg.getWhat(), msg);
Please DEBUG level

2022-03-16 12:58 UTC, mvalla reviewed
I have reviewed the changes and do not have any specific comment. LGTM.

2022-03-16 18:10 UTC, lolodomo approved these changes
LGTM

2022-03-16 18:10 UTC, merged

2022-03-16 18:40 UTC, mvalla commented
> As a side note, this binding is still missing a full default translations file.

can you provide a reference/doc about this point and how to provide the translations file ?

2022-03-16 18:57 UTC, lolodomo commented
This is only a mvn command to run. 
I will copy / paste the command later.

2022-03-22 19:52 UTC, lolodomo commented
@mvalla : thge command to generate defaylt translation properties is: mvn org.openhab.core.tools:i18n-maven-plugin:3.2.0:generate-default-translations