[openthermgateway] Various improvements
openhab/openhab-addons pull request #12507
Opened 2022-03-22 12:47 UTC by andrewfg

This PR addresses one potential issue, and makes a few slight improvements as follows..
- As described in #12457 there was a risk of sending new commands before the gateway had finished processing prior commands. Now all commands are pipelined via a FIFO queue to prevent that.
- Added a Thing Property to display the OpenTherm Gateway identification / version string.
- Now a `logger.warn()` message is reported if the gateway watchdog timer triggers a self reset.
- Improved `logger.trace()` reporting of messages read from / written to, the OpenTherm Gateway.
- Bumped the binding version property.

Closes #12457

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

2022-03-27 17:11 UTC, jlaur requested changes
Code looks good, only a few minor comments.

2022-03-27 17:11 UTC, jlaur commented on bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/OpenThermGatewaySocketConnector.java
> +        protected final long expiryTime = System.currentTimeMillis() + COMMAND_RESPONSE_MAX_WAIT_TIME_MILLISECONDS;
Consider if `Instant` would be more reliable (and perhaps even readable) as based on a timeline, not wall clock: https://www.baeldung.com/java-measure-elapsed-time. See also #12493.

2022-03-28 12:18 UTC, andrewfg commented on bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/OpenThermGatewaySocketConnector.java
> +        boolean isCommandAcknowlegement = (message.length() > 2) && (message.charAt(2) == ':');
Ok.

2022-03-28 19:40 UTC, jlaur approved these changes
Looks good, thanks for these improvements.

2022-03-28 19:40 UTC, merged

2022-03-28 21:44 UTC, andrewfg commented
@jlaur many thanks.