[sunsa] Added sunsa binding
openhab/openhab-addons pull request #12554
Opened 2022-04-01 00:33 UTC by jirom

# Description

This is a new binding to support controlling [Sunsa blinds](https://www.sunsahomes.com/).

Currently the binding requires making requests to the [Sunsa cloud APIs](https://app.swaggerhub.com/apis/Sunsa/Sunsa/1.0.4) as the local API is not available yet.

2022-04-02 16:23 UTC, lsiepel requested changes
Didn't have time to look at all files, but here are some toughts.

2022-04-02 16:23 UTC, lsiepel commented on bundles/org.openhab.binding.sunsa/src/main/java/org/openhab/binding/sunsa/internal/device/SunsaDeviceHandler.java
> +                LOGGER.debug("Attempting update to raw position to: {}", rawPosition);
Not sure if the logging should be here. As the framework allready logs the event. Same for other switch options

2022-04-02 16:23 UTC, lsiepel commented on bundles/org.openhab.binding.sunsa/src/main/java/org/openhab/binding/sunsa/internal/device/SunsaDeviceHandler.java
> +            case CHANNEL_BATTERY_LEVEL: {
According to the README this is a read only channel, so i don't think it should be in this switch statement. the RefreshType command is allready handled at the top.

2022-04-02 16:23 UTC, lsiepel commented on bundles/org.openhab.binding.sunsa/src/main/java/org/openhab/binding/sunsa/internal/device/SunsaDeviceHandler.java
> +            throw new IllegalArgumentException("Unknown command: " + command);
What happens if this Exception is thrown? It doesn't looks like it is handled upstream so it causses a thread crash? Similar for the other IllegalArgumentException

2022-04-02 16:23 UTC, lsiepel commented on bundles/org.openhab.binding.sunsa/src/main/java/org/openhab/binding/sunsa/internal/device/SunsaDeviceHandler.java
> +            LOGGER.error("Could not update position for device: {}", config.id, e);
The logging should be removed. All info is allready present at the updateStatus. 
Should the device really be set to offline? Is there no possible way the value is rejected, while the cloud/device is perfectly healthy?

2022-04-02 16:23 UTC, lsiepel commented on bundles/org.openhab.binding.sunsa/src/main/java/org/openhab/binding/sunsa/internal/device/SunsaDeviceHandler.java
> +            LOGGER.error("Could not get info for device: {}", config.id, e);
Remove logging please.

2022-04-02 16:23 UTC, lsiepel commented on bundles/org.openhab.binding.sunsa/.gitignore
> +/org
Don't think this file was meant to be part of the commit

2022-04-03 14:00 UTC, lsiepel requested changes
Reviewed the remaining files.

2022-07-10 08:21 UTC, wborn commented on bundles/org.openhab.binding.sunsa/pom.xml
> +    <version>3.3.0-SNAPSHOT</version>
```suggestion
    <version>3.4.0-SNAPSHOT</version>
```

2022-12-12 21:41 UTC, lsiepel commented
@jirom  Are you able to proceeed with the PR? Anything you need help with?

2023-07-24 09:53 UTC, wborn commented on bundles/org.openhab.binding.sunsa/pom.xml
> +    <version>4.0.0-SNAPSHOT</version>
```suggestion
    <version>4.1.0-SNAPSHOT</version>
```

2023-11-15 21:02 UTC, lsiepel commented
@jirom Some months have passed. are you still planning to bring this PR to the finish line?

2024-03-10 18:03 UTC, lsiepel commented
@jirom would you be able to update this branch and remove the excess commits that should not be part of this PR?

2024-09-08 20:38 UTC, lsiepel commented
Closed due to no response to open comments and excess commits. Feel free to re-open when this got sorted on your feature branch. Still think this binding can be a good addition to openHAB, so i hope you will manage to fix this. Ping me when you need any help to proceed.

2024-09-08 20:38 UTC, closed without merging