Dwdunwetter docs improvement
openhab/openhab-addons pull request #12588
Opened 2022-04-08 19:38 UTC by florian-h05

# [dwdunwetter] Update docs to clarify CellID selection

# Description

This PR updates the docs to be more clear about which CellID to choose for the binding to work correctly.
It also updates the German README and the description in the Thing configuration.

Those changes were made out of the motivation that I had problems with the binding because of I used a CellID that was not supported, the docs were not clear enough about that point.

2022-04-24 08:02 UTC, lolodomo requested changes

2022-04-24 08:02 UTC, lolodomo commented on bundles/org.openhab.binding.dwdunwetter/src/main/resources/OH-INF/i18n/dwdunwetter_de.properties
> +thing-type.config.dwdunwetter.dwdwarnings.cellId.description = ID der abzufragende Zelle. Siehe https\://www.dwd.de/DE/leistungen/opendata/help/warnungen/cap_warncellids_csv, nur IDs die mit einer 8
Can you please remove this change ?
After the PR is merged, you can then update it in Crowdin.

2022-04-24 08:03 UTC, lolodomo commented
@limdul79 : is it ok for you ?

2022-04-24 10:51 UTC, florian-h05 commented
@lolodomo 
All your requested changes are addressed now.

2022-04-25 07:56 UTC, limdul79 approved these changes
It's ok for me

2022-04-25 12:34 UTC, merged