[pulseaudio] Allow flexible parameters to find a given pulseaudio device
openhab/openhab-addons pull request #12598
Opened 2022-04-11 10:14 UTC by dalgwen

Following the request of a user, who had difficulties with its pulseaudio devices and the random naming occuring (#12555) , I would like to add some (non breaking) possibilities in the way to choose a pulseaudio device corresponding to a thing description.

To identify the device on the pulseaudio server, with this PR, you can now use the description instead of the technical id (a.k.a. "name").
To filter furthermore, you can also use the parameter additionalFilters (optional regular expressions that need to match a property value of a device on the pulseaudio server).
As you can see in the related discussion, these two modifications were necessary to match an interesting use case (playing sound to airplay device with the help of the RAOP pulseaudio module as an intermediary)

Closes #12555

[A snapshot is here](https://github.com/dalgwen/openhab-addons/releases/tag/3.3.0_SNAPSHOT-pulseaudio_12555)

Signed-off-by: Gwendal Roulleau <gwendal.roulleau@gmail.com>

2022-04-25 16:06 UTC, lolodomo requested changes
Just 2 minor comments

2022-04-25 16:06 UTC, lolodomo commented on bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioClient.java
> +                    "Cannot select exactly one audio device, so, choosing the first. To choose without ambiguity between the {} devices matching the identifier {}, you can maybe use a more restrictiv
That is minor but I think there is a comma to suppress : ... audio device, so choosing the first.

2022-04-28 21:06 UTC, dalgwen commented on bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/DeviceIdentifier.java
> +    public DeviceIdentifier(String nameOrDescription, @Nullable String additionalFilters) {
Indeed

2022-04-28 21:06 UTC, dalgwen commented
Thank you again @lolodomo

2022-04-28 21:24 UTC, lolodomo approved these changes
LGTM, thank you

2022-04-28 21:25 UTC, merged