[renault] API key to configuration parameter and rule update.
openhab/openhab-addons pull request #12636
Opened 2022-04-22 07:04 UTC by dougculnane

The API key changes once a year apparently... This causes a communication error and a qucik API update patch.  I have moved the API key from constants to config. This allows it to be updated with the new value without a re-compile.  I have documented this in the README.

I also updated the charge limit rule to better cope with NULL values in the ChargeMode.

Signed-off-by: Doug Culnane <doug@culnane.net>

2022-04-22 13:40 UTC, lolodomo requested changes

2022-04-23 06:55 UTC, dougculnane commented on bundles/org.openhab.binding.renault/README.md
> + * Set up an active 15 minute charge schedule in the MyRenault App.
A 15 minute thing takes 15 minutes...  I think this is correct. (I used to be English...)

I will change to "dummy charge schedule" which is hopefully clearer about what we are trying to create.

2022-04-23 06:58 UTC, dougculnane commented on bundles/org.openhab.binding.renault/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="kamereonApiKey" type="text" required="true">
I forgot about that.  Thanks for noticing it.

2022-04-23 06:59 UTC, dougculnane commented
@lolodomo Thanks for you Review.  I have pushed changes to resolve the issues.

Merci Doug.

2022-04-23 07:08 UTC, lolodomo commented on bundles/org.openhab.binding.renault/README.md
> + * Set up an active 15 minute charge schedule in the MyRenault App.
I should clearly stop commenting on English speaking lol

2022-04-23 07:10 UTC, lolodomo approved these changes
LGTM

2022-04-23 07:10 UTC, dougculnane commented on bundles/org.openhab.binding.renault/README.md
> + * Set up an active 15 minute charge schedule in the MyRenault App.
@lolodomo  I do make a lot of typos so keep up the good work. :-)

2022-04-23 07:10 UTC, merged