[nest] Fix for missing refresh token after reauthorization
openhab/openhab-addons pull request #12711
Opened 2022-05-10 14:30 UTC by mhilbush

By default, the Google OAuth API returns the refresh token only on the first authorization. On subsequent authorizations using the same Client ID and Secret, Google does not return the refresh token in the access token response. This causes the binding to fail on the first refresh of the access token after a reauthorization.

This affects the SDM and Pub/Sub APIs. However, the failure is more spectacular with the Pub/Sub API as it causes the binding to repeatedly do a pub/sub request against the Google API every 20-40 msec.

This PR adds a new query parameter (prompt=consent) to the URL used to get the authorization code. This parameter causes Google to always return the refresh token in the authorization response (via `oAuthService.getAccessTokenResponseByAuthorizationCode`).

In addition, this PR adds checks to make sure the refresh token in present in the access token response in order to fail more quickly and gracefully if the refresh token is missing.

Further details of my analysis are here.
https://community.openhab.org/t/nest-binding-throwing-pub-sub-errors-repeatedly/135721

I know @wborn is pretty time-constrained right now, but I'm hopeful he can find a few minutes to review. 😉 

Signed-off-by: Mark Hilbush <mark@hilbush.com>

2022-05-14 21:25 UTC, lolodomo commented
I do not see in the code the addition of the prompt query parameter.

2022-05-14 21:44 UTC, mhilbush commented
That's correct. It's not in the code, but only in the URL in the documentation. You need to copy/paste the URL from the documentation into your browser's address bar, then replace the `<ProjectID>` and `<ClientID>` in the URL with your specific values. It's a completely manual process.

2022-05-15 11:12 UTC, lolodomo requested changes
LGTM

2022-05-15 11:12 UTC, lolodomo approved these changes

2022-05-15 11:14 UTC, lolodomo commented
I let a chance to @wborn to review.

2022-05-15 20:01 UTC, wborn approved these changes
Thanks for the fix!

2022-05-15 20:03 UTC, merged