[netatmo] Add translations for config parameters
openhab/openhab-addons pull request #12768
Opened 2022-05-20 12:05 UTC by lolodomo

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

2022-05-20 16:13 UTC, clinique approved these changes
LGTM

2022-05-20 20:40 UTC, jlaur commented
Reason for this PR was found in [this comment](https://github.com/openhab/openhab-addons/pull/12726#discussion_r876023219).

2022-05-20 20:45 UTC, jlaur requested changes
Thanks. Minor comment added to try to preserve a similar structure to ordinary generated channel type keys.

2022-05-21 08:14 UTC, lolodomo commented on bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/config/config.xml
> +				<option value="30min">@text/config.period.30min</option>
Done

2022-05-21 08:20 UTC, jlaur approved these changes
LGTM, thanks.

2022-05-21 08:20 UTC, merged