[sncf] Align XML description and default translations
openhab/openhab-addons pull request #12887
Opened 2022-06-05 07:42 UTC by lolodomo

Re-run of the i18n tool will then trigger no change.

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

2022-06-05 09:01 UTC, clinique approved these changes

2022-06-05 10:08 UTC, clinique approved these changes

2022-06-06 07:48 UTC, wborn requested changes

2022-06-06 07:48 UTC, wborn commented on bundles/org.openhab.binding.sncf/src/main/resources/OH-INF/thing/station.xml
> +				<description>Informations regarding next arrival at the station.</description>
```suggestion
				<description>Information regarding the next arrival at the station.</description>
```

2022-06-06 07:48 UTC, wborn commented on bundles/org.openhab.binding.sncf/src/main/resources/OH-INF/thing/station.xml
> +				<description>Informations regarding next departure from the station.</description>
```suggestion
				<description>Information regarding the next departure from the station.</description>
```

2022-06-06 10:46 UTC, lolodomo commented on bundles/org.openhab.binding.sncf/src/main/resources/OH-INF/thing/station.xml
> +				<description>Informations regarding next arrival at the station.</description>
Fixed

2022-06-06 10:47 UTC, lolodomo commented on bundles/org.openhab.binding.sncf/src/main/resources/OH-INF/thing/station.xml
> +				<description>Informations regarding next departure from the station.</description>
Fixed

2022-06-06 11:16 UTC, wborn approved these changes
Thank you!

2022-06-06 11:17 UTC, merged