[netatmo] Adding smoke detector module
openhab/openhab-addons pull request #12984
Opened 2022-06-21 13:46 UTC by clinique

2022-06-22 20:31 UTC, lolodomo approved these changes
LGTM

2022-06-22 20:32 UTC, lolodomo commented
Normally, features for OH 3.3 are already frozen but considering my relative good knowledge of the code of this binding, I see no risk of regression with this PR and so I would be in favour to merge it. @jlaur: can you have a look yourself and confirm you agree with me ?

2022-06-22 20:59 UTC, jlaur requested changes
LGTM. Only some minor text issues.

2022-06-22 20:59 UTC, jlaur commented on bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/channels.xml
> +				<option value="SOUND_TEST_OK">Alarm test successfull</option>
```suggestion
				<option value="SOUND_TEST_OK">Alarm test successful</option>
```

2022-06-22 20:59 UTC, jlaur commented on bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/channels.xml
> +				<option value="WIFI_STATUS_OK">Wifi status ok</option>
```suggestion
				<option value="WIFI_STATUS_OK">Wi-Fi status ok</option>
```

2022-06-22 20:59 UTC, jlaur commented on bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/channels.xml
> +				<option value="WIFI_STATUS_ERROR">Wifi status error</option>
```suggestion
				<option value="WIFI_STATUS_ERROR">Wi-Fi status error</option>
```

2022-06-22 20:59 UTC, jlaur commented on bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/channels.xml
> +				<option value="WIFI_STATUS">Wifi status</option>
```suggestion
				<option value="WIFI_STATUS">Wi-Fi status</option>
```

2022-06-22 22:42 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/channels.xml
> +				<option value="WIFI_STATUS_ERROR">Wifi status error</option>
Corrected

2022-06-22 22:42 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/channels.xml
> +				<option value="WIFI_STATUS">Wifi status</option>
Corrected

2022-06-23 05:41 UTC, jlaur approved these changes
Nice last-minute addition! :-)

2022-06-23 06:37 UTC, merged