[pidcontroller] Implement previous state recovery on startup
openhab/openhab-addons pull request #13003
Opened 2022-06-24 12:53 UTC by lnagel

This feature allows the PID controller parameters to be updated and
OpenHAB to be restarted without losing the current controller state.

This is especially important for systems with a long response time.
For example it might take up to a day for an underfloor heating
controller to stabilise after losing state and having to build up
the integrator value from zero.

In case the controller instance has configured OpenHAB items for the integral part, derivative part and error inspectors, then we can query the previous value from the persistance layer for these items and restore them during the controller startup.

2022-06-26 16:18 UTC, fwolter requested changes
Looks like a handy solution!

Can you add a short note to the readme, that you need to enable the inspector items to recover the values? And maybe add a reference to the core documentation how to setup persistence on Items?

2022-06-26 16:18 UTC, fwolter commented on bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerTriggerHandler.java
> +            logger.info("Item '{}' value {} recovered by PID controller", itemName, value);
This should be debug or trace.

2022-06-26 19:37 UTC, lnagel commented on bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerTriggerHandler.java
> +            logger.info("Item '{}' value {} recovered by PID controller", itemName, value);
Fixed.

2022-06-26 20:02 UTC, lnagel commented
Well I fixed everything, but it seems that builds are failing now (and I have a feeling that it's related to the build failures in main).

2022-07-02 09:26 UTC, fwolter requested changes

2022-07-02 09:28 UTC, fwolter approved these changes
LGTM, thanks!

2022-07-02 09:28 UTC, merged

2022-07-02 10:15 UTC, lnagel commented
Cheers!