[goecharger] fix data type for energy (nrg)
openhab/openhab-addons pull request #13052
Opened 2022-07-01 20:30 UTC by ranzen84

energy (nrg) need to be double for V2
(tested with version 053.4 (Beta)

Signed-off-by: Reinhard Plaim <reinhardplaim@gmail.com>

2022-07-02 06:34 UTC, lolodomo requested changes

2022-07-02 06:34 UTC, lolodomo commented on bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerV2Handler.java
> +                return new QuantityType<>((goeResponse.sessionChargeConsumption / 1000d), Units.KILOWATT_HOUR);
Can you please remove useless parenthesis. 
Same for your other changes.

2022-07-02 06:37 UTC, lolodomo commented
@SamuelBrucksch: would you like to review these changes? In particular, is it normal to remove "* 1000" or "/ 1000".

2022-07-02 06:50 UTC, SamuelBrucksch commented
I have no idea why it is removed. Also I did not follow up the changes for V3, as I don't own that charger anymore, so I can't verify if this makes sense.

2022-07-03 10:04 UTC, cribskip commented
I can help out with testing, however, the last build is not in jfrog anymore. How can I get a current build from this PR? Thanks :)

@lolodomo The factor 1000 is appearently not needed anymore as the values are already transmitted as needed.

2022-07-06 13:37 UTC, marcus-oh3 commented
I can also test. Will the change show up in a snapshot? If yes, are you able to guess which date?

2022-07-08 07:09 UTC, lolodomo approved these changes
Code looks good to me.

2022-07-08 07:10 UTC, lolodomo commented
@ranzen84 : if you are sure of your changes, I will merge. No risk to impact handling of API V1 ?

2022-07-08 19:55 UTC, merged