Added new MCD binding
openhab/openhab-addons pull request #13051
Opened 2022-07-01 16:12 UTC by simon-dengler

Signed-off-by: Simon Dengler 

# [MCD] Initial Contribution

# Description

This contribution adds the MCD Binding to the project.
No changes to previously existing bindings have been made.

2022-07-01 16:33 UTC, simon-dengler commented
@fwolter here is finally a clean new pull request on the new MCD binding (issue #12202 )
I have worked through all your feedback from the last submit. Thanks for your helpful hints!
best regards
Simon

2022-07-02 10:01 UTC, fwolter requested changes
There are some checkstyle warnings left. You could take a look at `target/code-analysis/report.html` after building it with `mvn clean install`.

You could create the default translations file by running `org.openhab.core.tools:i18n-maven-plugin:3.3.0:generate-default-translations` in your binding's directory. Then, [Crowdin](https://crowdin.com/project/openhab-addons) will pick up the English "translation" and users can help to translate your binding in Crowdin. If you want you can use Crowdin, too to translate your binding as soon as this PR is merged.

2022-07-05 06:37 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/README.md
> +No binding configuration required.
Done

2022-07-05 06:37 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/README.md
> +| parent bridge  | parent MCD bridge is required      |
Done

2022-07-05 06:40 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/README.md
> +| serial number  | serial number of the sensor in MCD |
Fixed this and checked the bridge's parameters, too

2022-07-05 06:47 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/feature/feature.xml
> +	<feature name="openhab-binding-mcd" description="MCD Binding" version="${project.version}">
Done

2022-07-05 06:48 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandler.java
> +                 */
Done

2022-07-05 06:57 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandler.java
> +                                    scheduler.schedule(task, delay, TimeUnit.MILLISECONDS);
Done

2022-07-05 07:21 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/SensorThingHandler.java
> +                            logger.info("Invalid Command!");
Changed all

2022-07-05 07:23 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/SensorThingHandler.java
> +            // }
Removed all commented code

2022-07-05 07:24 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/SensorThingHandler.java
> +                             */
Done

2022-07-05 07:24 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/SensorThingHandler.java
> +                        // .header(HttpHeader.HOST, "cunds-syncapi.azurewebsites.net")
Removed it

2022-07-05 07:26 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/src/main/resources/OH-INF/thing/thing-types.xml
> +		<label>MCD Sensor Thing</label>
Done

2022-07-05 08:12 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/README.md
> +| 2 | BEDEXIT |
Removed the ID column

2022-07-05 08:12 UTC, simon-dengler commented on bundles/org.openhab.binding.mcd/README.md
> +The channel `sendEvents` accepts valid Sensor Event Definitions as well as the corresponding ID. The following table contains allcurrently accepted Sensor Event Definitions and their respective ID. A
Done

2022-07-10 18:20 UTC, fwolter approved these changes
LGTM
Now, you could add your binding's logo to the openHAB website. See https://www.openhab.org/docs/developer/bindings/#add-your-binding-s-logo-to-the-openhab-website

2022-07-10 18:20 UTC, merged

2022-07-11 13:03 UTC, simon-dengler commented
Thanks for merging. Here is the pull request with the mcd logo:
https://github.com/openhab/openhab-docs/pull/1862