[nibeheatpump] Added PRODINo ESP32 Ethernet v1 board support
openhab/openhab-addons pull request #13190
Opened 2022-07-29 18:21 UTC by paulianttila

Also added:
- telnet debug support (UDP debug removed)
- new configuration model
- OTA update support for PRODINo ESP32 Ethernet v1 board

Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com>

2022-08-02 15:04 UTC, jlaur requested changes
Thanks! Unfortunately the provided C++ example code is too specialized for me to review, but on the surface it looks good to me. :) Do you know anyone who could possibly review this? Otherwise let's merge it as is, since it doesn't change the binding itself.

2022-08-02 15:04 UTC, jlaur commented on bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW/Config.h
> +  #define RS485_PORT            Serial1
General observation: In existing example code preprocessor directives were not indented. I'm fine either way, just noticed this difference.

2022-08-06 09:52 UTC, paulianttila commented on bundles/org.openhab.binding.nibeheatpump/README.md
> +ProDiNo boards has build in Ethernet and RS-485 ports.
KMP Electronics have changed the spelling. Older board use ProDiNo and new board PRODINo

2022-08-06 09:54 UTC, paulianttila commented on bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW/NibeGw.h
> +//#define HARDWARE_SERIAL
Old board is already obsolete, so changed default to meet latest boards by default.

2022-08-06 10:03 UTC, paulianttila commented
> Do you know anyone who could possibly review this?

No, but Arduino NibeGW is used many other open source projects as well, so most probably I will get immediate feedback if something is broken.

2022-08-06 11:40 UTC, jlaur commented on bundles/org.openhab.binding.nibeheatpump/README.md
> +ProDiNo boards has build in Ethernet and RS-485 ports.
"built-in" (with t) needs to be fixed still after latest commit.

2022-08-06 11:55 UTC, paulianttila commented on bundles/org.openhab.binding.nibeheatpump/README.md
> +ProDiNo boards has build in Ethernet and RS-485 ports.
Yes, you are right. Hopefully now fixed :)

2022-08-06 13:46 UTC, jlaur commented on bundles/org.openhab.binding.nibeheatpump/README.md
> +ProDiNo boards has built-in Ethernet and RS-485 ports.
Sorry, missed spelling of PRODINo for consistency and grammar:
```suggestion
PRODINo boards have built-in Ethernet and RS-485 ports.
```

2022-08-06 13:49 UTC, jlaur commented on bundles/org.openhab.binding.nibeheatpump/README.md
> +PRODINo ESP32 Ethernet v1 support also dynamic configuration and OTA updates via WiFi access point.
Sorry, half resolved, I believe it should be "also supports" as suggested rather than "supports also".

2022-08-07 09:34 UTC, jlaur approved these changes
LGTM - thanks!

2022-08-07 09:35 UTC, merged