[shelly] Minor bugfixes from hardening
openhab/openhab-addons pull request #13200
Opened 2022-07-31 16:31 UTC by markus7017

This PR brings some minor bug fixes for Bulbs/RGBW2

2022-07-31 18:15 UTC, fwolter requested changes

2022-07-31 18:15 UTC, fwolter commented on bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
>              setThingOffline(ThingStatusDetail.CONFIGURATION_ERROR, "offline.conf-error-access-denied");
What's the reason for adding the log message? `updateStatus()` already generates a log message.

2022-08-01 22:43 UTC, markus7017 commented
@fwolter changes applied

2022-08-04 06:42 UTC, fwolter approved these changes

2022-08-04 06:42 UTC, merged

2022-08-04 06:43 UTC, fwolter commented
I removed the labels to let the changes from refactoring not show up in the changelog.