Added how to configure InfluxDB Persistance via Web-UI
openhab/openhab-addons pull request #13213
Opened 2022-08-03 20:14 UTC by krikk

added a paragraph about configuring InfluxDB Settings in Web-UI

2022-08-03 21:18 UTC, jlaur requested changes
Thanks! I'm wondering if it would make sense to simplify this, by just adapting:

```
This service can be configured in the file `services/influxdb.cfg`.
```

to:

```
This service can be configured in the file `services/influxdb.cfg` or in the UI under `Settings` → `Other Services` → `InfluxDB Persistence Service`.
The file-based configuration overrides the UI configuration.
```

Would that be sufficient?

2022-08-03 21:18 UTC, jlaur commented on bundles/org.openhab.persistence.influxdb/README.md
> +### Configuration via Web-Interface:
```suggestion
### Configuration via web interface
```

Or perhaps use term "UI" like you did in header "### File based configuration (not needed when done via UI)" to not mix terms "UI" and "web interface"?

2022-08-03 21:18 UTC, jlaur commented on bundles/org.openhab.persistence.influxdb/README.md
> +All settings for this Persistance Service can be found under `Settings` → `Other Services` → `InfluxDB Persistance Service`
```suggestion

All settings for this Persistence Service can be found under `Settings` → `Other Services` → `InfluxDB Persistence Service`
```

2022-08-03 21:18 UTC, jlaur commented on bundles/org.openhab.persistence.influxdb/README.md
> +Attention: The File based Configuration (described below) overrides the Configuration in the Web-Interface!
```suggestion
Attention: The file-based configuration (described below) overrides web interface configuration.
```

2022-08-03 21:18 UTC, jlaur commented on bundles/org.openhab.persistence.influxdb/README.md
> +### File based configuration (not needed when done via UI)
```suggestion
### File-based configuration
```

I would then suggest to move the sentence " (not needed when done via UI)" after next line, i.e.:
```
This service can be configured in the file `services/influxdb.cfg`.
This is not needed when configured in UI.
```

2022-08-03 21:36 UTC, krikk commented
i would strongly suggest to put the UI approach first, because the config via UI is much more fool-proof than the file based approach (especially with influxDB2)

2022-08-04 21:11 UTC, jlaur commented
@lujop - does it look fine to you?

2022-08-07 09:37 UTC, jlaur commented on bundles/org.openhab.persistence.influxdb/README.md
> +Attention: The file-based configuration overrides the UI configuration!
```suggestion
Attention: The file-based configuration overrides the UI configuration.
```

2022-08-07 09:37 UTC, jlaur approved these changes
Thanks!

2022-08-07 09:38 UTC, merged