[tapocontrol] included P115 smart-socket
openhab/openhab-addons pull request #13225
Opened 2022-08-06 14:24 UTC by wildcs

This PR now added the Tapo P115 smart-socket to tapocontrol.
Also fixed thing configuration warning occured since OH3.3

2022-08-07 06:55 UTC, lolodomo commented
> Also fixed thing configuration warning occured since OH3.3

The configuration parameter is defined as an integer, there is no real sense to consider in the binding it could be a decimal.
Maybe the root cause leading to a decimal value in your setup should rather be determined and fixed.

If not, this would mean we have to fix all bindings to habdle something that should not happen.

2022-08-07 06:58 UTC, lolodomo commented
Could exclude the new parameter handling and put it in a separate PR so that I can at least merge the PR which is about adding P115 smart socket ?

2022-08-07 10:18 UTC, jlaur requested changes
Thanks! I have added a few minor comments.

2022-08-07 10:18 UTC, jlaur commented on bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoBridgeConfiguration.java
> +            discoveryIntervalM = (int) Double.parseDouble(config.get(CONFIG_DISCOVERY_INTERVAL).toString());
This work-around should not be needed in 3.4 as fixed by openhab/openhab-core#3024. See also #13112.

2022-08-07 10:18 UTC, jlaur commented on bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoDeviceConfiguration.java
> +            this.pollingInterval = (int) Double.parseDouble(config.get(CONFIG_UPDATE_INTERVAL).toString());
This work-around should not be needed in 3.4 as fixed by openhab/openhab-core#3024. See also #13112.

2022-08-07 10:18 UTC, jlaur commented on bundles/org.openhab.binding.tapocontrol/README.md
> +### P110/P115 EnergyMonitoring SmartPlug (WiFi)
```suggestion
### P110/P115 EnergyMonitoring SmartPlug (Wi-Fi)
```

2022-08-07 11:34 UTC, jlaur commented
@lolodomo - sorry, I missed your comments when checking the PR. At least our comments are consistent. :)

2022-08-07 15:38 UTC, jlaur approved these changes
LGTM

2022-08-07 15:38 UTC, merged

2022-08-07 15:43 UTC, wildcs commented
removed the parameter handling workaround.
But without that i get still an error:
`NumberFormatException@203 "java.lang.NumberFormatException: For input string: "20.0"`
So the setting is useless?

2022-08-07 15:47 UTC, jlaur commented
@wildcs - I assume you are running the binding in openHAB 3.3? The mentioned bugfix is included in 3.4. You could try to run a snapshot version to verify this. Probably the first 3.4 milestone release is not far away.

2022-08-07 18:02 UTC, wildcs commented
@jlaur - no i'm using OH3.4 Build #3034 on my coding pc

2022-08-11 19:44 UTC, jlaur commented
> no i'm using OH3.4 Build 3034 on my coding pc and there i can reproduce and debug the error.

Sorry, I missed that openhab/openhab-core#3024 is not merged yet. So we expect to have a generic fix for 3.4 so that we don't have to fix all bindings, but the PR needs review with the possibility of more work to be done.

2022-09-27 06:54 UTC, jlaur commented
> > no i'm using OH3.4 Build 3034 on my coding pc and there i can reproduce and debug the error.
> 
> Sorry, I missed that [openhab/openhab-core#3024](https://github.com/openhab/openhab-core/pull/3024) is not merged yet. So we expect to have a generic fix for 3.4 so that we don't have to fix all bindings, but the PR needs review with the possibility of more work to be done.

openhab/openhab-core#3024 was recently merged, so this should be fixed now. Perhaps you could verify with latest snapshot - otherwise it will be included in next milestone.

2022-09-27 15:52 UTC, wildcs commented
Hi,
testet with Snapshot #3103. Issue is still there when reading "discoveryIntervalM" :
![image](https://user-images.githubusercontent.com/40909464/192574780-f1a4f2c7-8361-4480-8a64-815d88dbd7ce.png)
Object x is for debugging only

2022-09-27 17:03 UTC, jlaur commented
> Hi,
> testet with Snapshot #3103. Issue is still there when reading "discoveryIntervalM"

Did you test with latest snapshot of core, or only binding?

2022-09-27 17:06 UTC, wildcs commented
Downloaded latest snapshot from oh-homepage and put it into debugging enviroment
![image](https://user-images.githubusercontent.com/40909464/192590856-a1eb51b2-2494-41ce-9661-ed41516e6182.png)