[homekit] support actual booleans for inverted config
openhab/openhab-addons pull request #13228
Opened 2022-08-07 19:36 UTC by ccutrer

as well as strings, too.

reduces confusion, if someone doesn't know it needed to be a string

2022-08-07 23:35 UTC, ccutrer commented
Don't bother reviewing yet... I need to push up another commit that applies it to other booleans

2022-08-08 02:04 UTC, ccutrer commented
okay, it's better now

2022-08-08 07:21 UTC, yfre approved these changes
LGTM

2022-08-08 07:22 UTC, yfre commented
@ccutrer thank you for this fix. 
it was indeed confusing, even i lost few hours myself trying to understand why "inverted = true" is not working :)

2022-08-08 07:31 UTC, lolodomo requested changes

2022-08-08 07:31 UTC, lolodomo commented on bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
> +     * return configuration as booelan if exists otherwise return defaultValue
Typo: boolean
And "**Returns** configuration **value** as..."

2022-08-08 07:31 UTC, lolodomo commented on bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
> +     * @return value
`@return configuration value as boolean`

2022-08-08 18:48 UTC, lolodomo approved these changes
LGTM, thank you

2022-08-08 18:50 UTC, merged