Bug rollup
openhab/openhab-addons pull request #13327
Opened 2022-08-27 15:39 UTC by danieldemus

Bugfix: Replace illegal characters in generated ids with "-"
Bugfix: Not all channel metadata was included on generated channels
Bugfix: The synthetic LAST_QUERY channel was being re-created repetitively

Minor updates to the documentation reflect the changes.

2022-08-28 16:58 UTC, danieldemus commented
Fixes #13214

2022-09-08 20:33 UTC, jlaur requested changes
Thanks! Only a minor README and question about POM change. Additionally, would you be able to change the PR title to something which could go into the release notes?

2022-09-08 20:33 UTC, jlaur commented on bundles/org.openhab.binding.wundergroundupdatereceiver/README.md
> +Fx. AqPM2.5 has a channel named `AqPM2-5`.
```suggestion
For example, AqPM2.5 has a channel named `AqPM2-5`.
```

2022-09-08 20:33 UTC, jlaur commented on pom.xml
> +  </pluginRepositories>
Why is this added?

2022-09-30 03:03 UTC, s-pw commented
@danieldemus did you test your changes? I've built the binding from [danieldemus:bug-rollup](https://github.com/danieldemus/openhab-addons/tree/bug-rollup) and while the error is gone the channel is gone too.
Adding the channel manually logs error:
Channel type wundergroundupdatereceiver:AqPM2-5 could not be resolved.

2022-12-01 20:08 UTC, danieldemus commented on pom.xml
> +  </pluginRepositories>
By mistake...

2022-12-01 20:29 UTC, jlaur commented on bundles/org.openhab.binding.wundergroundupdatereceiver/README.md
> +For example AqPM2.5 has a channel named `AqPM2-5`.
```suggestion
For example, AqPM2.5 has a channel named `AqPM2-5`.
```

2022-12-01 21:45 UTC, jlaur approved these changes
Thanks for the fixes.

2022-12-01 21:47 UTC, merged