[fsinternetradio] Add Ruark R5 to tested devices & mode list
openhab/openhab-addons pull request #13325
Opened 2022-08-26 19:48 UTC by grssnbchr

Signed-off-by: Timo Grossenbacher <timo@timogrossenbacher.ch>

# [fsinternetradio] Add Ruark R5 to tested devices & mode list

# Description

This merely updates the README with the Ruark R5 model since I own one of these and tested it successfully with that binding.

2022-09-03 12:46 UTC, lolodomo requested changes

2022-09-03 12:46 UTC, lolodomo commented on bundles/org.openhab.binding.fsinternetradio/README.md
> +| Ruark R5                 | Internet Radio | TIDAL                   | Deezer       | Amazon Music | Spotify   | Local Music | Music Player | DAB Radio | FM Radio   | Bluetooth | AUX in  | Phono | O
Please add the missing `|` at the end of this added line.

2022-09-16 04:39 UTC, grssnbchr commented
Thank you for your feedback. 
Sorry, I forgot the DCO with this latest commit. Should I make another commit on top?

2022-09-24 09:38 UTC, lolodomo approved these changes
LGTM

2022-09-24 09:38 UTC, merged

2022-09-24 09:40 UTC, lolodomo commented
> Sorry, I forgot the DCO with this latest commit. Should I make another commit on top?

I merged even if DCO check was wrong as your PR is only a small enhancement of the documentation.
Thank you.