[shelly] Add Plus/Pro support, some bugfixes
openhab/openhab-addons pull request #13439
Opened 2022-09-25 12:07 UTC by markus7017

This PR replaces #12842

The PR adds support for the Shelly Generation 2 Plus/Pro Devices .

I tried to separate it from other changes (previous PRs), but it still has a relevant size.

2022-09-25 12:25 UTC, jlaur commented
@markus7017 - can you close the PR being replaced?

2022-09-30 08:34 UTC, markus7017 commented
@fwolter @lolodomo I fixed the merge conflict and ready to start the review. Pinged you both, because you were in previous PRs.

2022-10-02 16:03 UTC, fwolter requested changes
Can you say a few words about how Gen2 devices connect in general? Do the devices connect to the OH instance? Is there some authentification? Is it save to expose the servlet to the internet?

2022-10-03 12:41 UTC, markus7017 commented
> Can you say a few words about how Gen2 devices connect in general? Do the devices connect to the OH instance? Is there some authentification? Is it save to expose the servlet to the internet?

The binding supports Generation 1 (first series) and Plus / Pro series of devices, which are Generation 2. Both generations uses complete different APIs
- Generation 1: Uses http-based communication with basic authentication. In addition the devices implement CoIoT version 1 + 2, a Allterco specific IoT protocol based on Coap. Therefore the Californium framework is integrated to handle the CoAP protocol. CoAP supports multicast mode and peer mode. Using the peer mode is an easy way to have specific firewall rules protecting the device access.
- Generation 2: Complete different API, which is based on http POSTs for device control and an WebSocket interface for event messages. In addition the binding implements an inbound WebSocket, which is required to receive wakeup / status notifications from battery powered devices, which go into sleep mode. Gen2 uses digest authentication if restricted access has been enabled in the device setup. The user is "admin" (hard-code for whatever reason) and password is taken from the binding or thing configuration.  The device also supports secure WebSocket communication (wss, incl. X.5409 certificates), but this is not yet implemented in the binding. In general you might access a Shelly device directly from the Internet or exposing the servlet entry point using protected device setup. However, I would prefer a VPN in between.
- ShellyManager is also based on a Servlet and implements some advanced device diagnostic and control functions. The Manager runs in the openHAB context so you need to login as usual being able to access the UI (http / https).

Short note on the API. Due to the fact that APIs are different, also the data formats, but device functionality is similar I decided to implement a mapping layer. Data structures are mapped form Gen2 format to Gen1 format for further processing on the upper code layers. Otherwise I would have to re-implement the complete logic, in fact redundant. Gen1 devices are still in production so removing Gen1 support was no option. Also creating a 2nd binding would increase maintenance efforts and may confuses the users.
I separate Gen1 and Gen2 APIs in packages
- api1 = Gen1-specific 
- api2 = Gen2-spcific
- apu = Common code
- ShellyApiInterface defines the API interface, which then has 2 implementations

Please feel free to ask further questions if this gets a better understanding for the review.

2022-10-03 12:53 UTC, markus7017 commented on bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen2_relay.xml
> +		<label>ShellyPlus 1 (SNSW-001X16EU")</label>
Technically yes, but from a user's point of view no, so I removed all incl. those for Gen 1 devices

2022-10-03 12:56 UTC, markus7017 commented
@fwolter requested changes are resolved

2022-10-03 16:28 UTC, fwolter commented on bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2RpcSocket.java
> +        } catch (/* IOException | */Exception e) {
Can you comment on this?

2022-10-03 19:16 UTC, markus7017 commented on bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2RpcSocket.java
> +        } catch (/* IOException | */Exception e) {
removed (not yet checked in)

2022-10-03 22:17 UTC, markus7017 commented
@fwolter I pushed the changes, also removing some other left overs from development phase :-)

2022-10-04 06:00 UTC, fwolter approved these changes
Sounds good!

2022-10-04 06:00 UTC, merged