New branch kostalinverter_20220929
openhab/openhab-addons pull request #13464
Opened 2022-09-29 20:02 UTC by basse04

Changes to  check in:
	changed:        ../../../../../../../../../README.md
	changed:        SecondGenerationHandler.java
Signed-off-by: Örjan Backsell <orjan.backsell@gmail.com>

2022-09-30 10:55 UTC, lolodomo commented
Please update your title to explain what this PR is fixing or enhancing.

2022-10-01 11:18 UTC, lolodomo requested changes

2022-10-01 11:18 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
> +            } catch (InterruptedException e) {
Please add that just as first instruction in the block:
```
Thread.currentThread().interrupt();
```

2022-10-01 11:18 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
> +                logger.debug("Updating inverter status failed: ", e);
Maybe a more appropriate message ?
Something like : "Refresh was interrupted"

2022-10-01 11:18 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
>          } catch (final RuntimeException e) {
In fact, `refresh` is called only by the scheduled job by initialize.
You have to choose where do you catch `RuntimeException`; doing it at both places has no real sense.
I would suggest to remove the exception handling here.

2022-10-01 11:18 UTC, lolodomo commented on bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
> +            }
Never do that when the binding is using the common HTTP client (common to all bindings).
The common HTTP client will be already started when the binding is started.

2022-10-01 12:09 UTC, lolodomo commented
Please also note you did not sign off properly your PR.

2022-10-03 15:02 UTC, basse04 commented
Hi, 
looks strange with 7 commits and it is, but I got a message that I wasn't allowed to log in a couple of times, do not know why, but suddenly it works and then maybe with all the earlier not allowed ones also sent.
Br Basse

2022-10-03 17:37 UTC, lolodomo commented
Don't know what you did, but that PR is totally different to what it was yesterday. 
And you have now conflicts.

2022-10-03 17:52 UTC, basse04 commented
I had problems to get the changes uploaded, I did it from Eclipse and that had been a nightmare sometimes before also, probebly depending on me.
But what I can understand so are the changes now at basse04:kostalinverter_20220929, should I have make another branch like kostalinverter_20221003 and upload the changes to there?

2022-10-03 20:12 UTC, lolodomo commented
You must keep the same branch. 
If not, a new PR will be created. 
So do it only if you cannot restore something clean in your current branch.

2022-10-03 20:24 UTC, basse04 commented
Thanks for your help, so you can use the changes I have uploaded today to basse04:kostalinverter_20220929 ? Otherwise, Please, just let me know.

2022-10-03 20:47 UTC, lolodomo commented
What you have in your original branch is what we see now here. 
If you have a backup of your expected changes, you can remove your local branch, create it again with the same name, apply again your changes, commit and finally force push your branch.

2022-10-04 15:23 UTC, closed without merging

2022-10-04 16:36 UTC, basse04 commented
Hi,
my best excuses. I was not able to save kostalinverter_20220929. I have totally meshed it up and I finally found the reason, I have updated it with an old branch 20220129 by mistake without to note that until just now. So I will close this PR and make a new one with the advices you have give me in 20220929.
Br Basse