WIP [voskstt] redownload armv7 vosk native lib
openhab/openhab-addons pull request #13556
Opened 2022-10-16 09:52 UTC by GiviMAD

Try to fix error on armv7.

Signed-off-by: Miguel Álvarez <miguelwork92@gmail.com>

2022-10-17 07:17 UTC, lolodomo commented
After an update of the bundle, a clean of `.cache/JNA` folder and a restart of openHAB, the exception is no more present, the bundle is active and I have this warning:
```
09:10:31.660 [WARN ] [voice.voskstt.internal.VoskSTTService] - Missing native dependency: /home/xxx/.cache/JNA/temp/jna511182918146398935.tmp: undefined symbol: __atomic_load_8
```

2022-10-17 17:20 UTC, GiviMAD commented
This last version works fine for me, only requirement is have libatomic installed.

2022-10-17 17:41 UTC, lolodomo commented
Please update README to mention the prerequisite and how to install the missing library.

2022-10-17 18:19 UTC, GiviMAD commented
> Please update README to mention the prerequisite and how to install the missing library.

Ok I'll add a "supported platforms" sectione with this information.

2022-10-17 18:54 UTC, lolodomo requested changes
No need to update the library finally?

2022-10-17 18:54 UTC, lolodomo commented on bundles/org.openhab.voice.voskstt/src/main/java/org/openhab/voice/voskstt/internal/VoskSTTService.java
> +            if (osName.contains("linux") && osArch.equals("arm") || osArch.equals("armv7l")) {
I believe parenthesis are missing around the 2 last conditions.

2022-10-17 19:14 UTC, GiviMAD commented
> No need to update the library finally?

No I checked it agains and outdated branch, the binary was correctly downloaded. Once I merge master to this branch that change was the same, also the call to 'LibVosk.setLogLevel(LogLevel.WARNINGS);' was missed in this branch, that is why it failed different earlier. The problem was always the missing libatomic library. Sorry for the whole confusion.

2022-10-18 17:25 UTC, lolodomo approved these changes
LGTM

2022-10-18 17:29 UTC, merged

2022-10-23 09:06 UTC, lolodomo commented
After installing snapshot 3143, I can tell you that I have no warning/error in logs at startup.
I did not install libatomic.
That being said, I can't tell you if the service is working or not (not tested).

2022-10-24 07:38 UTC, GiviMAD commented
> After installing snapshot 3143, I can tell you that I have no warning/error in logs at startup.
> I did not install libatomic.
> That being said, I can't tell you if the service is working or not (not tested).

Thank you for the confirmation, in my tests I enabled the model load and it works without errors, so I think it will work well.
Probably libatomic is already installed in raspbian, you can check if the library is present using the path:
```
ls /usr/lib/arm-linux-gnueabihf/libatomic.so.1
```

2022-10-24 11:30 UTC, lolodomo commented
Confirmed, the file already exists in my system (RPI3).