Update yeelink.light.light15.json
openhab/openhab-addons pull request #13554
Opened 2022-10-15 19:10 UTC by michiii1337

changed Datatype form "Number" to "Dimmer" at channel "ambientBrightness" same issue openhab#9936 (but already fixed)

2022-10-21 07:15 UTC, marcelrv requested changes
Hi @michiii1337 
I recognize the issue with the dimmer vs number. I recall the problem is that I wanted to make it 2 ways, meaning that setting the dimming level in the app is also reflected in the dimming level in OH. As the device reports the level in whole number I believe it did not work well which is why I made it a number.

Can you test on your end and confirm that setting the dimming level via the app is properly reflected in OH.
If not, we prob need to add some calc to multiply/divided by 100... which is nowadays supported by the binding so I expect doable.

Also would be great to check some of the other yeelights if you have a chance for the same matter.
Lastly, once we have confirmed it all working right, please run the readme maker (in the test folder) to update the readme documentation accordingly.

2022-10-23 14:04 UTC, michiii1337 commented
I tested the dimming level via app and openhab. When the datatype is set to Dimmer, both in Xiaomi Home app and Openhab is the same/correct value. Unfortunately, I have no other Yeelights so I can only test this type.

2022-10-25 18:08 UTC, michiii1337 commented
the readme is now up to date. Hope I did everything right as this is my first pullreqest.

2022-10-27 20:13 UTC, marcelrv commented
I think code wise it is fine.
There are some oddities wrt to the automatic generated readme but they are not caused by you and should be fixed by translating the relevant values and than it fixes itself

There is a commit signoff issue with 2 of the commits.  You can try to 'squash' in eclipse and update the the commit comment to include the signoff-by (like you did in your last commit)
Or if whoever is merging this agrees you can just click accept DCO and it will be fine as well. (I don't have rights to merge the PR)

2022-10-27 20:13 UTC, marcelrv approved these changes

2022-10-28 11:03 UTC, jlaur requested changes
Thanks! There seem to be some character set issues that would need to be resolved, and also the DCO check must pass.

2022-10-28 11:03 UTC, jlaur commented on bundles/org.openhab.binding.miio/README.md
> +| language             | Number               | Language - Language                      | Value mapping `["0"="English","1"="ç®€ä½“ä¸­æ–‡","2"="EspaÃ±ol","3"="Ð ÑƒÑ�Ñ�ÐºÐ¸Ð¹","4"="Italiano","5"="Fra
Something seems to have gone wrong here with the non-Western languages?

2022-10-28 11:03 UTC, jlaur commented on bundles/org.openhab.binding.miio/README.md
> +| remember-state       | Switch               | Viomi Vacuum - Remember State            | Value mapping ["0"="å…³","1"="å¼€"] |
And here.

2022-10-28 11:03 UTC, jlaur commented on bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
> +option.mijia.vacuum.v2-miot.language-1 = ç®€ä½“ä¸­æ–‡
And here.

2022-10-28 11:03 UTC, jlaur commented on bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
> +option.mijia.vacuum.v2-miot.language-3 = Ð ÑƒÑ�Ñ�ÐºÐ¸Ð¹
And here.

2022-10-28 11:03 UTC, jlaur commented on bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
> +option.mijia.vacuum.v2-miot.language-5 = FranÃ§ais
And here.

2022-10-28 11:03 UTC, jlaur commented on bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
> +option.mijia.vacuum.v2-miot.language-7 = í•œêµ­ì–´
And here.

2022-10-28 17:13 UTC, michiii1337 commented
I fixed the characters in the readme. How can i fix the DCO? I can not edit the 3 commits without my sign.

2022-10-28 21:14 UTC, marcelrv commented
You can try to 'squash' in eclipse and update the the commit comment to include the signoff-by (like you did in your last commit)

2022-10-28 22:06 UTC, michiii1337 commented
i tried already to squash the commits but i received a error message: "Unable to squash. Squashing replays all commits up to the last one required for the squash. A merge commit cannot exist among those commits"

2022-10-28 22:12 UTC, jlaur commented
> I fixed the characters in the readme. How can i fix the DCO? I can not edit the 3 commits without my sign.

You could try to click "Details" in the DCO check line and follow the steps described, or you could have a look at this:
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

2022-10-29 16:34 UTC, michiii1337 commented
i followed the instructions under "Details" and now the DCO failed again... is it easier to start from zero and make an new PR?

2022-10-29 17:42 UTC, marcelrv commented
Maybe what's working is to do first a rebase, than I think it will allow you to do the squash.
Making a new branch from current and copy the free changes is indeed also a way

2022-10-29 18:06 UTC, michiii1337 commented
i have done a rebase and i got the same error message when i try to squash

2022-10-29 18:16 UTC, michiii1337 commented
ok, now i have done a rebase. before that i seem to have done only a merge. Sorry for the many questions and problem in the PR I am still learning. Hope now the commits can be merged.

2022-10-29 18:43 UTC, jlaur commented
> ok, now i have done a rebase

I'm sorry, but that did no go well, as there are now changes from other bindings included. Perhaps at this point it would be best to:
- Backup your changes files.
- Delete your branch locally.
- Create a new branch from main with the **same name** as the deleted branch.
- Apply your changes again (by copying the changed files).
- Force push the new branch.

2022-10-29 20:54 UTC, michiii1337 commented
my branch is "main". if i delete this branch how should i create new branch from main?

2022-10-29 21:26 UTC, jlaur commented
> my branch is "main". if i delete this branch how should i create new branch from main?

Ah, sorry, I didn't see that. Assuming your fork is new and you don't have other branches to keep, for this PR I would adapt the plan to:
- Backup your repository.
- Delete your fork.
- Create a new fork.
- Apply your changes again (by copying the changed files).
- Commit again to main while making sure signoff is correct.
- Force push main.

I don't know if it will work, but it might be worth a shot. After that, I would then suggest to recreate the fork again, and make sure you don't commit anything to main, as it will most likely cause problems for you. Instead you should create a new branch, and use this when creating a PR.

2022-10-29 21:41 UTC, Hilbrand commented
It looks like only 1 commit is wrong. You can also just remove that one commit. Use `git rebase -i HEAD~6`. This will open an editor with the list of commits. Replace `pick` with `d` on the commit you want to remove. Than save the file. After that do a push force.

2022-10-29 23:00 UTC, michiii1337 commented
Thanks @Hilbrand and @jlaur removed the wrong commit.

2022-10-30 19:40 UTC, jlaur approved these changes
Thank you!

2022-10-30 19:41 UTC, merged