[homekit] add BasicFan accessory
openhab/openhab-addons pull request #13564
Opened 2022-10-18 15:49 UTC by ccutrer

This is Fan v1. It's a subset of FanV2, except that Home allows you to customize the icon to show a ceiling fan.

2022-10-18 20:45 UTC, jlaur requested changes
Thanks!

Build failed with `Error:  Failed to execute goal on project org.openhab.io.homekit: Could not resolve dependencies for project org.openhab.addons.bundles:org.openhab.io.homekit:jar:3.4.0-SNAPSHOT: Could not find artifact io.github.hap-java:hap:jar:2.0.2-SNAPSHOT in openhab-snapshot`

2022-10-18 20:45 UTC, jlaur commented on bundles/org.openhab.io.homekit/pom.xml
> +      <version>2.0.2-SNAPSHOT</version>
```suggestion
      <version>2.0.2</version>
```

probably? Seems released:
https://github.com/hap-java/HAP-Java/releases/tag/hap-2.0.2

2022-10-18 20:45 UTC, jlaur commented on bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitBasicFanImpl.java
> +class HomekitBasicFanImpl extends AbstractHomekitAccessoryImpl implements BasicFanAccessory {
`@NonNullByDefault`?

2022-10-18 21:58 UTC, ccutrer commented
Yeah, sorry, I forgot I had built a snapshot locally. It actually needs 2.0.3. I'll update this PR when I get a chance.

2022-11-26 19:02 UTC, ccutrer commented
This should be ready for review now, but should not be merged until https://github.com/openhab/openhab-addons/pull/13484 because the HAP-Java update will cause brokenness without that PR going first.

2022-11-27 18:56 UTC, yfre approved these changes
pretty straight forward. 
LGTM 
thank you @ccutrer

2022-12-08 12:58 UTC, lolodomo commented
I suppose you have to release now that #13484 is merged? (the change of hap version is already done in the merged PR).

2022-12-09 15:07 UTC, ccutrer commented
@lolodomo : no, nothing needs to be released.  The BasicFan support was already in HAP 2.0.4 (that openhab-addons started depending on in #13484). I also don't need to rebase or merge, since the "conflicting" diff is the same, so will just resolve itself.

2022-12-09 18:16 UTC, lolodomo approved these changes
LGTM

2022-12-09 18:17 UTC, merged