[miio] add support Xiaomi Smart Air Purifier 4 (modelId: zhimi.airp.mb5)
openhab/openhab-addons pull request #13717
Opened 2022-11-14 19:30 UTC by marcelrv

Adding support for the following models:
* Xiaomi Smart Air Purifier 4 (modelId: zhimi.airp.mb5)

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

close #12818

2022-11-18 08:12 UTC, marcelrv commented
@lolodomo if someone can merge this one as well, I happily leave the top 10 :-)

2022-11-20 20:13 UTC, lolodomo requested changes

2022-11-20 20:13 UTC, lolodomo commented on bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airp.mb5-miot.json
> +				"property": "moto-speed-rpm",
motor?

2022-11-20 20:13 UTC, lolodomo commented on bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airp.mb5-miot.json
> +				"channel": "moto_speed_rpm",
motor?

2022-11-25 07:40 UTC, lolodomo commented
@marcelrv : any chance you looked at my comments before Sunday?

2022-11-25 08:09 UTC, marcelrv commented
@lolodomo Thanks, I missed your comments indeed. Will aim to look at that indeed before sunday.
I did this as bit quick one... so the values are right from the published spec.. jinglish indeed ;-)

2022-11-26 05:59 UTC, lolodomo approved these changes
LGTM, thank you

2022-11-26 05:59 UTC, merged