[vitotronic] Add channel "currentmode" to thing "circuit"
openhab/openhab-addons pull request #13739
Opened 2022-11-18 00:16 UTC by Fejitatete

Signed-off-by: Fejitatete <fejitatete@msn.com>

2022-11-18 16:29 UTC, lolodomo commented
A new thing channel with no Java code to manage it?

2022-11-18 20:17 UTC, jlaur commented
See also #13735.

2022-11-20 00:03 UTC, Fejitatete commented
Sry guys, I don't understand why this need some Java code. Could you explain or take a look in sources plz.
Thx

2022-11-20 07:59 UTC, Hilbrand commented
@Fejitatete is right. It doesn't need code. The binding derives the channel from the data it receives from the device. It would be nice to add the channel to the readme. Also the channel seems to represent a mode. I suspect the mode numbers represent textuale description of what each number means. In that case you can add the option to the channel, so the user sees the textual description instead of just a number

2022-11-21 12:28 UTC, lolodomo requested changes

2022-11-21 12:28 UTC, lolodomo commented on bundles/org.openhab.binding.vitotronic/src/main/resources/OH-INF/thing/thing-types.xml
> +		<description>Currentmode</description>
Description to be removed if it adds no value to the label.
At least, use correct English, that is current mode (2 words).

2022-11-21 12:28 UTC, lolodomo commented on bundles/org.openhab.binding.vitotronic/src/main/resources/OH-INF/thing/thing-types.xml
> +		<state pattern="%d" readOnly="true" max="3" min="0" step="1"/>
As it is read only, min/max/step have no real interest, U believe,

2022-11-26 11:21 UTC, lolodomo commented
The vitotronic.properties file has to be updated to include the new channel type and the 4 states.

New channel has to be also added in documentation (README.md file).

@Hilbrand : can you take the lead to review/merge this PR as you are apparently more aware than us how it is implemented ?

2022-12-08 23:07 UTC, Fejitatete commented
> The vitotronic.properties file has to be updated to include the new channel type and the 4 states.
> 
> New channel has to be also added in documentation (README.md file).
> 
> @Hilbrand : can you take the lead to review/merge this PR as you are apparently more aware than us how it is implemented ?

2022-12-10 07:39 UTC, lolodomo commented
No chance to have a proper signing ?

2022-12-10 12:07 UTC, lolodomo approved these changes
Thing definition and translation file are not in sync (label/description) for the new channel type.
I will merge as it is and provide a fix in a separate PR.

2022-12-10 12:07 UTC, lolodomo commented
Making an exception and merge the PR even if not properly signed off.

2022-12-10 12:08 UTC, merged