[homekit] support stop for blinds
openhab/openhab-addons pull request #13788
Opened 2022-11-27 19:15 UTC by yfre

home app never sends "STOP" but always sends the target position, e.g. 100% or 0% for fully open or closed blinds. 
Rollershutter in openHAB and some device do support stop. 
this PR adds emulation of stop if user click on blind icons in the home app while blinds is moving. 
report and discussion here
https://community.openhab.org/t/oh3-rollershutter-and-apple-homekit/112376/31

this PR also fix one potential NPE and a typo in the docu "light -> lighting"

2022-11-27 20:01 UTC, lolodomo requested changes

2022-11-27 21:16 UTC, yfre commented on bundles/org.openhab.io.homekit/README.md
> +If you add configuration parameter "stop=true", openHAB will emulate stop and send "STOP" command to rollenshutter item if you click on the blind icon in the home app while the blind is moving.
the apple app on iphone / ipad for HomeKit 
is iOS home app better. or maybe HomeKit home app..

2022-11-27 22:31 UTC, lolodomo approved these changes
LGTM

2022-11-27 22:33 UTC, lolodomo commented
@ccutrer : would you like to review?

2022-11-27 22:37 UTC, ccutrer approved these changes
LGTM

2022-11-27 22:39 UTC, merged

2022-11-27 22:39 UTC, ccutrer commented
> @ccutrer : would you like to review?

Even though I'm in CODEOWNERS now, I was not notified of the PR until you tagged me, and I'm still not showing as a code owner in the GitHub UI. Do you know if I just need to be added to the openHAB GitHub organization? Or do I need to actually be added to this specific repo with some amount of access? And if so, can you do that, or does it need to be someone else?

2022-11-27 22:45 UTC, lolodomo commented
> Even though I'm in CODEOWNERS now, I was not notified of the PR until you tagged me, and I'm still not showing as a code owner in the GitHub UI. Do you know if I just need to be added to the openHAB GitHub organization? Or do I need to actually be added to this specific repo with some amount of access? And if so, can you do that, or does it need to be someone else?

Normally there is nothing to do, but there is apparently a problem with your account, for example if I try to filter PR by author, I do not find you in the list. Maybe @jlaur or @fwolter has an idea what's wrong?

2022-11-28 09:19 UTC, jlaur commented
@ccutrer is not a member of the contributors group, @kaikreuzer can you add?

2022-11-28 09:35 UTC, lolodomo commented
> @ccutrer is not a member of the contributors group, @kaikreuzer can you add?

There is a manual action to do each time a new contributor contributes?

2022-12-10 23:07 UTC, kaikreuzer commented
Done.

> There is a manual action to do each time a new contributor contributes?

@lolodomo Yes, indeed - everybody needs to be added to this group: https://github.com/orgs/openhab/teams/contributors

2022-12-11 01:30 UTC, ccutrer commented
Thanks @kaikreuzer!