[enocean] Bugfix - messages with MSC RORG (#13786)
openhab/openhab-addons pull request #13792
Opened 2022-11-28 11:25 UTC by lovery

Setting senderId for MSC RORG and set rorg to Unknown when there is no mach with the supported(handled) RORG types.
Fixes #13786

2022-11-28 14:03 UTC, jlaur requested changes
Thanks for the fix! Only one minor suggestion to consider.

2022-11-28 14:03 UTC, jlaur commented on bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/messages/ERP1Message.java
> +                    senderId = Arrays.copyOfRange(payload, dataLength - 5, dataLength - 1);
Since it seems to be handled the exact same way as **SIG**, perhaps these two cases could be joined to avoid duplication?

2022-11-28 16:29 UTC, jlaur commented
@fruggy83 - would you like to review this PR?

2022-11-30 19:53 UTC, fruggy83 approved these changes
Thanks a lot for your work @lovery 
LGTM

2022-11-30 19:55 UTC, jlaur approved these changes
LGTM

2022-11-30 19:55 UTC, merged