[Insteon Binding Documentation] Updated I/O Linc Section
openhab/openhab-addons pull request #13811
Opened 2022-12-01 06:10 UTC by Hawkinzw

The I/O Linc has a feature to match or invert the status of the contact with its control messages. The binding was written expecting the messages to be inverted. This is the opposite of how insteon recommends setting up the garage kit, and not described well by the original "Note" at the bottom of the section. Updated the instructions to specify the input is OFF when linking in order to invert the messages, and changed the note to better describe what happens if you don't. All based off of my own experience with the sensor: https://community.openhab.org/t/insteon-io-linc-garage-door-contact-slow-update/141469

2022-12-01 14:57 UTC, robnielsen requested changes

2022-12-01 14:57 UTC, robnielsen commented on bundles/org.openhab.binding.insteon/README.md
> +To get the status of the contact, the the modem must also be linked as a responder to the I/O Linc. The I/O linc has a feature to invert the contact or match the contact when it sends commands to any
Please put each sentence on it's own line.

2022-12-01 14:57 UTC, robnielsen commented on bundles/org.openhab.binding.insteon/README.md
> +> NOTE: If the I/O Linc contact status appears delayed, or returns the wrong value when the sensor changes states, the contact was likely ON (status LED lit) when the modem was linked as a responder.
Please put each sentence on it's own line.

2022-12-01 14:57 UTC, robnielsen commented on bundles/org.openhab.binding.insteon/README.md
> +To resolve this behavior the I/O Linc will need to be unlinked and then re-linked to the modem with the contact OFF (stats LED off). That would be with the door open when using the insteon garage kit
Please put each sentence on it's own line.

2022-12-01 14:59 UTC, robnielsen commented
Updates look good, other than each sentence needs to be on its own line.  You also need to sign your commit. See DCO under checks for the PR.

2022-12-03 13:52 UTC, robnielsen approved these changes

2022-12-03 17:36 UTC, Hawkinzw commented
Yeah, having trouble working out signing. First time setting that up. Got it to work finally. Trying to rebase as recommended in the DCO. I'll mark ready to review again when I've got it sorted out.

2022-12-04 10:47 UTC, lsiepel approved these changes
LGTM

2022-12-05 19:55 UTC, jlaur requested changes
Thanks! A few typos found.

2022-12-05 19:55 UTC, jlaur commented on bundles/org.openhab.binding.insteon/README.md
> +To get the status of the contact, the the modem must also be linked as a responder to the I/O Linc.
```suggestion
To get the status of the contact, the modem must also be linked as a responder to the I/O Linc.
```

2022-12-05 19:55 UTC, jlaur commented on bundles/org.openhab.binding.insteon/README.md
> +Ensure the contact is OFF (status LED is dark/garage door open) when linking the the modem as a responder to the I/O Linc in order for it to function properly.
```suggestion
Ensure the contact is OFF (status LED is dark/garage door open) when linking the modem as a responder to the I/O Linc in order for it to function properly.
```

2022-12-08 01:26 UTC, Hawkinzw commented on bundles/org.openhab.binding.insteon/README.md
> +Ensure the contact is OFF (status LED is dark/garage door open) when linking the the modem as a responder to the I/O Linc in order for it to function properly.
good catch

2022-12-08 20:17 UTC, merged