[homekit] allow configuring secondary services as members of a group
openhab/openhab-addons pull request #13879
Opened 2022-12-08 14:58 UTC by ccutrer

Required introduction of AccessoryGroup to represent the base AccessoryInformationService for ease of configuring multiple of the same service.

This is also "breaking" in that someone who previously had HomeKit accessories nested directly inside of a group that was itself a HomeKit accessory will now have those items grouped within the Home app.

2022-12-08 15:04 UTC, yfre commented
but have already support for complex accessories with several services,
https://www.openhab.org/addons/integrations/homekit/#complex-accessory

is it improvement or replacement?

2022-12-08 15:08 UTC, ccutrer commented
This allows multiple of the _same_ accessory type in a single group. it's an improvement on the original implementation, and a lead-up to supporting IrrigationService and TVService (which require multiple Valves and Inputs respectively). but it can stand alone. for example, I have an accessory group called "Dining Room Shades" that's just a group, and contains 6 individual WindowCoverings. then in the Home app I can control the entire group at once, or each one individually. technically you can do that in the home app by group items together, but this way it just publishes it the same way. another added bonus is it only counts as one accessory on the bridge, reducing your count towards the 149 limit.

2022-12-11 19:23 UTC, yfre requested changes
the homekit logic looks good for me. 
please update the documentation so that we have only one section on complex accessories

2022-12-12 20:31 UTC, ccutrer commented on bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
> +                .sorted((lhs, rhs) -> lhs.getName().compareTo(rhs.getName())).collect(Collectors.toList())) {
so that the IIDs we publish to HomeKit remain stable across reboots of openHAB. There's no guarantees about the order of group members.

2022-12-12 21:28 UTC, yfre commented on bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
> +                .sorted((lhs, rhs) -> lhs.getName().compareTo(rhs.getName())).collect(Collectors.toList())) {
ok. makes sense.

2022-12-12 21:28 UTC, yfre approved these changes

2022-12-23 19:31 UTC, ccutrer commented
@lolodomo : I'd appreciate if you could get around to reviewing this sometime. I'm accumulating quite a stack of other fixes that I can't even send as a PR until this one is submitted.

2022-12-23 20:10 UTC, jlaur requested changes
Thanks! I have left some minor comments mostly suggesting proper language (by convention) for syntax highlighting.

2022-12-23 20:10 UTC, jlaur commented on bundles/org.openhab.io.homekit/README.md
> +```xtend
```suggestion
```java
```

2022-12-23 20:10 UTC, jlaur commented on bundles/org.openhab.io.homekit/README.md
> +```xtend
```suggestion
```java
```

2022-12-23 20:10 UTC, jlaur commented on bundles/org.openhab.io.homekit/README.md
> +```xtend
```suggestion
```java
```

2022-12-23 20:10 UTC, jlaur commented on bundles/org.openhab.io.homekit/README.md
> +```xtend
```suggestion
```java
```

2022-12-23 20:10 UTC, jlaur commented on bundles/org.openhab.io.homekit/README.md
> +```xtend
```suggestion
```java
```

2022-12-23 20:10 UTC, jlaur commented on bundles/org.openhab.io.homekit/README.md
> +e.g. an accessory defined as `homekit="Fan,Light"` will be shown as a fan and an accessory defined as `homekit="Light,Fan"` will be shown as a light in the Home app.
```suggestion
E.g. an accessory defined as `homekit="Fan,Light"` will be shown as a fan and an accessory defined as `homekit="Light,Fan"` will be shown as a light in the Home app.
```

2022-12-23 20:10 UTC, jlaur commented on bundles/org.openhab.io.homekit/README.md
> +```xtend
```suggestion
```java
```

2022-12-23 20:10 UTC, jlaur commented on bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
> +            return;
```suggestion
        if (accessoryTypes.isEmpty()) {
            return;
        }
```

2022-12-23 20:10 UTC, jlaur commented on bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
> +        if (!itemIsForThisBridge(item, itemConfiguration))
I can't create suggestion because GitHub sees half old code, but can we also add `{ }` here?

2022-12-23 20:10 UTC, jlaur commented on bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
> +                                }
Can you add a comment here?
```suggestion
                                } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException e) {
                                    // Ignore
                                }
```

2022-12-23 20:10 UTC, jlaur commented on bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
> +            }
And here?
```suggestion
            } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException e) {
                // Ignore
            }
```

2022-12-23 21:23 UTC, ccutrer commented
@jlaur: thanks! all comments addressed.

2022-12-23 22:41 UTC, jlaur approved these changes
LGTM

2022-12-23 22:41 UTC, merged