[jrubyscripting] allow disabling dependency tracking
openhab/openhab-addons pull request #13944
Opened 2022-12-13 16:18 UTC by ccutrer

in case your helper library doesn't support it. or you just don't like the behavior.

2022-12-13 23:25 UTC, jimtng commented
Don't forget to update README

2022-12-15 12:06 UTC, boc-tothefuture commented
LGTM pending the answer to @jimtng's questions.

2022-12-16 03:42 UTC, ccutrer commented
Sure. Turning off dependency tracking _only_ turns off dependency tracking. The other changes (to the script file watcher) that were made to accommodate the dependency tracker will still be in place.

2022-12-16 04:29 UTC, jimtng approved these changes
LGTM

2023-01-03 22:00 UTC, ccutrer commented
@boc-tothefuture : @jimtng hasn't been added to the GitHub Contributors team, so his approval doesn't count as far as GitHub is concerned. Can you plz approve?

2023-01-04 14:26 UTC, boc-tothefuture approved these changes
lgtm

2023-01-29 19:23 UTC, lolodomo requested changes

2023-01-29 19:23 UTC, lolodomo commented on bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/config/config.xml
> +			</options>
This is a boolean parameter. No need to define options.

2023-01-30 22:19 UTC, lolodomo approved these changes
LGTM thank you

2023-01-30 22:24 UTC, merged