[bluetooth.govee] null annotations
openhab/openhab-addons pull request #13978
Opened 2022-12-16 21:51 UTC by lsiepel

Signed-off-by: Leo Siepel [leosiepel@gmail.com](mailto:leosiepel@gmail.com)

null annotations
checkstyle fixes

Part of multiple PR's for bluetooth bundles. Can be merged independent.

2022-12-16 21:53 UTC, lsiepel commented
ThingTypeTableGenerator.java has two compile warnings left. If they need to get fixed, i could use some suggestions.

2022-12-18 09:56 UTC, lolodomo requested changes

2022-12-18 09:56 UTC, lolodomo commented on bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/command/hygrometer/GetOrSetHumWarningCommand.java
> +        if (localSettins == null || localSettins.min == null || localSettins.max == null) {
Min and max are checked just after.

2022-12-18 16:51 UTC, lsiepel commented on bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/command/hygrometer/GetOrSetHumWarningCommand.java
> +        if (localSettins == null || localSettins.min == null || localSettins.max == null) {
Fixed.

2022-12-22 07:57 UTC, lolodomo approved these changes
LGTM

2022-12-22 07:58 UTC, merged