[nanoleaf] handle and provide QuantityType for color-temperature-abs channel
openhab/openhab-addons pull request #14026
Opened 2022-12-20 21:24 UTC by ccutrer

see https://github.com/openhab/openhab-core/pull/3129

It should be noted I don't have LifX, so I have not tested this.

2022-12-20 21:42 UTC, jlaur commented
> It should be noted I don't have LifX, so I have not tested this.

Having Nanoleaf would be even better. 😉 @austvik, @stefan-hoehn - would one of you be able to test this?

2022-12-20 22:30 UTC, stefan-hoehn commented
Sure, and, I definitely want to test this first, so it doesn't break anything but I need a few days before I'll have the time.

2022-12-21 12:32 UTC, lolodomo requested changes

2022-12-21 12:32 UTC, lolodomo commented on bundles/org.openhab.binding.nanoleaf/README.md
> +| colorTemperatureAbs | Number:Temperature | Color temperature (in Kelvin, 1200 to 6500) of all light panels                                           | No        |
Please also update the exemple (nonaleaf.items) at the end of README.

2022-12-21 12:32 UTC, lolodomo commented on bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java
> +                    state.setValue(tempKelvin.toBigDecimal().intValue());
Any difference with `tempKelvin.intValue()` ?

2022-12-21 15:32 UTC, ccutrer commented
> How is this related to Lifx, @ccutrer ?

Just that LifX is one of the other bindings that uses the color-temperature-abs system channel, and I'm going through and making all the bindings that use it compatible with QuantityType. I lost track of which PR I was sending when I wrote the original comment. Edited now for clarity.

2022-12-21 19:24 UTC, lolodomo approved these changes
LGTM, thank you

2022-12-21 19:26 UTC, lolodomo commented
@raepple @stefan-hoehn: would you like to test the fix before I merge ?

2022-12-21 19:49 UTC, stefan-hoehn commented
Yes, I do, 
at: @ccutrer

 I just added that channel to one of my nanoleafs without your fix and shows already the Kelvin Unit

<img width="770" alt="image" src="https://user-images.githubusercontent.com/5937600/208988897-3b36f692-47a1-4082-a3e2-8298d238a3f0.png">

What I noticed though. when I tested this, is that my bundle actually throws a warning:

```
2022-12-21 20:40:05.143 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'AZ_Trio_Canvas_Color_TemperatureAbs' changed from 3965 K to 1733 K

==> /var/log/openhab/openhab.log <==

2022-12-21 20:40:05.967 [WARN ] [al.handler.NanoleafControllerHandler] - Unhandled command type: org.openhab.core.library.types.QuantityType

```

So, I bet that even fixes a bug in the handler. Let me check.

2022-12-21 20:47 UTC, stefan-hoehn commented
> would you like to test the fix before I merge ?

It was a bit hard to test because that branch is already on Java 17 as a requirement, so I needed to backport the changes to a 3.4.0.RC1 before I was able to deploy and test it on my side.

In essence, @ccutrer, thanks for finding this because it is actually a bug and prevented the channel to work. I can confirm that it does work now and I am happy to have it merged, @lolodomo

2022-12-21 20:49 UTC, ccutrer commented
> In essence, @ccutrer, thanks for finding this because it is actually a bug and prevented the channel to work. I can confirm that it does work now and I am happy to have it merged, @lolodomo

Heh, you're too generous. It's a bug I caused with https://github.com/openhab/openhab-core/pull/3129. Prior to 3.4.0 your channel wouldn't default to a Number:Temperature, and thus wouldn't have the Kelvin, and thus wouldn't have been sent a QuantityType command at all. Just cleaning up my messes.

2022-12-21 21:43 UTC, merged