[hue] Allow handling of QuantityType for color temperature channel
openhab/openhab-addons pull request #14024
Opened 2022-12-20 19:38 UTC by cweitkamp

- Allow handling of QuantityType for color temperature channel

see https://github.com/openhab/openhab-core/pull/3129

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

2022-12-20 20:12 UTC, jlaur requested changes
Thanks for the quick fix, only one very minor comment.

2022-12-20 20:12 UTC, jlaur commented on bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/LightStateConverter.java
>       * Transforms the given {@link DecimalType} into a light state containing
Can you update Javadoc also here, since it's no longer the given `DecimalType`?

2022-12-20 20:19 UTC, lolodomo commented
@jlaur : let me have a look before merging. There was an inappropriate log that should also be fixed.

2022-12-20 20:33 UTC, jlaur approved these changes
LGTM - @lolodomo, please merge when you have checked what you need to check.

2022-12-20 21:35 UTC, ccutrer commented
Implementation LGTM. May want to update the README to note that the item type should be Number:Temperature now.

2022-12-20 21:53 UTC, jlaur commented
> May want to update the README to note that the item type should be Number:Temperature now.

Oh, right - thanks for spotting this.

2022-12-21 11:40 UTC, cweitkamp commented
I checked the README, fixed the logging messages and reduced log level.

2022-12-21 14:58 UTC, ccutrer commented on bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java
> +                            .toUnit(Units.KELVIN);
Yes it needs to be toInvertibleUnit. Mireds are technically of dimension 1/Temperature, so the dimension changes and you have to use the method that allows that to happen.  Good catch @lolodomo; I was paying more attention to if he got the command and the update in both handler types.

2022-12-21 15:16 UTC, cweitkamp commented on bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java
> +                            .toUnit(Units.KELVIN);
Thanks for the hint. I changed it and added another unit test for sending Mired command to the channel.

2022-12-21 19:08 UTC, lolodomo approved these changes
LGTM, thank you

2022-12-21 19:10 UTC, merged

2022-12-21 19:11 UTC, lolodomo commented
Can you please submit the same change to the branch 3.4.x so that you can include it in a 3.4 patch ?

2022-12-21 19:51 UTC, lolodomo commented
@cweitkamp : did you test the fix?

2022-12-21 19:55 UTC, cweitkamp commented
We should cherry-pick such patches to the 3.4.0 branch and not create additional pull requests.

No, I did not test it in a real environment. I am sure it will work because of the unit tests.

2022-12-22 15:31 UTC, jlaur commented
I have cherry-picked the commit into 3.4.x and built a JAR: [org.openhab.binding.hue-3.4.1-SNAPSHOT.jar](https://drive.google.com/file/d/1fHvwYTWWC3oQh90afaH8D8dVm0kbEJ7x/view?usp=sharing)

2022-12-26 23:42 UTC, lolodomo commented
> I have cherry-picked the commit into 3.4.x

@jlaur : did you do that for all PRs marked with the "patch" label? 
You do that with Git or directly with GitHub?

2022-12-27 08:28 UTC, jlaur commented
@lolodomo - yes, all PR's which are currently merged and labelled with "patch" have been cherry-picked. You can see them here: https://github.com/openhab/openhab-addons/commits/3.4.x

I used Git for that.