[WIP] [knx] remove gnu.io.RXTXVersion dependency for serial transport
openhab/openhab-addons pull request #14051
Opened 2022-12-23 17:35 UTC by holgerfriedrich

This is still work in progress.
The goal is to remove dependency on  gnu.io.RXTXVersion.
Two steps are necessary:
* remove our code in the KNX binding (easy, only used to show available com ports)
* remove the transitive dependency imported with the Calimero library.

Calimero introduced a new way to handle pluggable serial transport classes via the java.util.ServiceLoader in release 2.5.1.
This is in principle working and I was able to connect to our serial communication classes,
*but* Serviceloader fails once we reload the KNX plugin. I could not get this fixed, so right now openHAB needs a restart to reload the KNX plugin! Any suggestions welcome....

Calimero seems to change the interface again, after 2.5.1 this was removed. I need to have a look how to proceed.

2022-12-23 20:09 UTC, wborn commented
> Serviceloader fails once we reload the KNX plugin. I could not get this fixed, so right now openHAB needs a restart to reload the KNX plugin!

IIRC there is a similar issue with [Mary TTS](https://www.openhab.org/addons/voice/marytts/) which also uses a ServiceLoader. It was only an issue during development when updating the bundle but not for normal users whenever they (un)install the add-on.

2022-12-23 20:14 UTC, wborn commented
There are some known issues with the ServiceLoader mechanism in OSGi in which [SPI Fly](https://aries.apache.org/documentation/modules/spi-fly.html) can help.
There are also plans to add better support for it in OSGi R9, see https://github.com/osgi/osgi/issues/372.

2022-12-23 20:28 UTC, holgerfriedrich commented
Thanks @wborn for giving me some pointers.
I have seen SPI Fly, but for sure am am lacking the deeper knowledge of OSGI.....

Let's see if I can get this implemented. Otherwise, I will try to get this PR to a mergeable state and open a separate ticket for the issue during binding reload. We already have this issue in the code base, as Calimero 2.5.1 is already in use #14015.

2022-12-25 08:07 UTC, holgerfriedrich commented
@wborn it seems that adding ```bnd.bnd``` as in https://github.com/openhab/openhab-addons/pull/14051/commits/7da7dc04c4f3fe83d14a8cdb0353de4c33b51330 does the job....
I have seen this being used in jsscripting as well.
Not sure if this is the correct approach, bit it seems to work.

2022-12-29 09:48 UTC, wborn requested changes

2022-12-29 09:48 UTC, wborn commented on bundles/org.openhab.binding.knx/bnd.bnd
> +DynamicImport-Package: *
I think this will do more harm than good. 

```suggestion
```

2022-12-29 09:48 UTC, wborn commented on bundles/org.openhab.binding.knx/bnd.bnd
> +-fixupmessages "Unused Export-Package instructions"
Are these fixups really used?

2023-01-06 17:29 UTC, holgerfriedrich commented
@wborn I have now changed the serviceloader registration as implemented for marytts in #14064.
In addition knx binding uses the ```@ServiceProvider``` annotation to create the required metadata file automatically.

This changes the global ```pom.xml```, maybe it would be cleaner to merge #14064 before this one as we have the full discussion about serviceloader registrtion over there.

2023-01-14 11:34 UTC, wborn commented
I'll have a look if it is possible to reduce the amount of bnd instruction duplication.

2023-02-19 14:33 UTC, wborn approved these changes
Thanks!

2023-02-19 14:45 UTC, merged

2023-02-19 23:13 UTC, holgerfriedrich commented
@wborn Don't mind. I am happy to see this finally merged, as it was blocking my next PR for this binding.
I appreciate all the review work also here in the addons repo, especially as there is a lot of work done in the core as well. Thanks again.