[tplinksmarthome] Document sending raw commands to devices
openhab/openhab-addons pull request #14062
Opened 2022-12-25 09:49 UTC by timcharper

Signed-off-by: Tim Harper <timcharper@gmail.com>

2022-12-25 12:46 UTC, timcharper commented
https://community.openhab.org/t/tplink-plugin-turns-on-dimmer-when-sending-brightness/142454/8

2022-12-26 11:45 UTC, fwolter requested changes

2022-12-26 11:45 UTC, fwolter commented on bundles/org.openhab.binding.tplinksmarthome/README.md
> +TPLinkSmarthome Things can be sent a raw JSON string to control a device in a way not directly supported by this binding. You can find several JSON commands in the [test fixtures](https://github.com/
If you put each sentence in a separate line, reading the diffs would be easier.

2022-12-26 11:45 UTC, fwolter commented on bundles/org.openhab.binding.tplinksmarthome/README.md
> +```
```suggestion
```java
```

2022-12-27 09:25 UTC, fwolter approved these changes
LGTM

2022-12-27 09:25 UTC, merged