[easee] Update README.md - added status values for "state#chargerOpMode"
openhab/openhab-addons pull request #14175
Opened 2023-01-07 14:41 UTC by WoKe77

added status values for "state#chargerOpMode"

2023-01-08 10:26 UTC, lolodomo commented on bundles/org.openhab.binding.easee/README.md
> +| state#chargerOpMode                         | Number                   | no       | Offline=0, Disconnected=1, AwaitingStart=2, Charging=3, Completed=4, Error=5, ReadyToCharge=6
Maybe rather something like: 0 for offline, 1 for disconnected, ... ?

2023-01-13 18:11 UTC, alexf2015 requested changes
as commented please change bthe syntax according to my comment. Apart from that I am fine with your changes

2023-01-14 08:22 UTC, lolodomo commented on bundles/org.openhab.binding.easee/README.md
> +| state#chargerOpMode                         | Number                   | no       | Offline=0, Disconnected=1, AwaitingStart=2, Charging=3, Completed=4, Error=5, ReadyToCharge=6
Would also be ok for me using 0=Offline...

2023-02-04 05:39 UTC, lolodomo commented on bundles/org.openhab.binding.easee/README.md
> +| state#chargerOpMode                         | Number                   | no       | Offline=0, Disconnected=1, AwaitingStart=2, Charging=3, Completed=4, Error=5, ReadyToCharge=6
As there was no feedback, I fixed myself.

2023-02-04 05:40 UTC, lolodomo commented
@alexf2015 : please approve my change.

2023-02-04 09:54 UTC, jlaur approved these changes
Thanks all.

2023-02-04 09:54 UTC, merged