[squeezebox] New channels for additional tags
openhab/openhab-addons pull request #14201
Opened 2023-01-10 21:53 UTC by mhilbush

Resolves #13353 

Signed-off-by: Mark Hilbush <mark@hilbush.com>

2023-01-10 22:10 UTC, jlaur requested changes
Thank you. Looks simple and good to me! I have added comments for a request to use camelCase for the two multi-worded new channels.

2023-01-10 22:10 UTC, jlaur commented on bundles/org.openhab.binding.squeezebox/README.md
> +| albumartist            | String    | Main artist of the entire album                                                              |
Please adopt camelCase like for most other existing channels.
```suggestion
| albumArtist            | String    | Main artist of the entire album                                                              |
```

2023-01-10 22:10 UTC, jlaur commented on bundles/org.openhab.binding.squeezebox/README.md
> +| trackartist            | String    | Main artist of the track                                                                     |
```suggestion
| trackArtist            | String    | Main artist of the track                                                                     |
```

2023-01-10 22:10 UTC, jlaur commented on bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxBindingConstants.java
> +    public static final String CHANNEL_ALBUMARTIST = "albumartist";
```suggestion
    public static final String CHANNEL_ALBUMARTIST = "albumArtist";
```

2023-01-10 22:10 UTC, jlaur commented on bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxBindingConstants.java
> +    public static final String CHANNEL_TRACKARTIST = "trackartist";
```suggestion
    public static final String CHANNEL_TRACKARTIST = "trackArtist";
```

2023-01-10 22:10 UTC, jlaur commented on bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerEventListener.java
> +    void albumartistChangeEvent(String mac, String albumartist);
```suggestion
    void albumArtistChangeEvent(String mac, String albumartist);
```

2023-01-10 22:10 UTC, jlaur commented on bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerEventListener.java
> +    void trackartistChangeEvent(String mac, String trackartist);
```suggestion
    void trackArtistChangeEvent(String mac, String trackartist);
```

2023-01-10 22:10 UTC, jlaur commented on bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/thing/thing-types.xml
> +			<channel id="albumartist" typeId="albumartist"/>
```suggestion
			<channel id="albumArtist" typeId="albumArtist"/>
```

2023-01-10 22:10 UTC, jlaur commented on bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/thing/thing-types.xml
> +			<channel id="trackartist" typeId="trackartist"/>
```suggestion
			<channel id="trackArtist" typeId="trackArtist"/>
```

2023-01-10 22:10 UTC, jlaur commented on bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/thing/thing-types.xml
> +	<channel-type id="albumartist" advanced="true">
```suggestion
	<channel-type id="albumArtist" advanced="true">
```

2023-01-10 22:10 UTC, jlaur commented on bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/thing/thing-types.xml
> +	<channel-type id="trackartist" advanced="true">
```suggestion
	<channel-type id="trackArtist" advanced="true">
```

2023-01-10 22:10 UTC, jlaur commented on bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
> +            String remoteTitle = "", artist = "", album = "", genre = "", year = "", albumartist = "", trackartist = "",
```suggestion
            String remoteTitle = "", artist = "", album = "", genre = "", year = "", albumArtist = "", trackArtist = "",
```

2023-01-11 00:04 UTC, mhilbush commented
Ha ha. I actually started down the camelCase path. But I changed it to be consistent with the tag naming convention in the LMS, and also because I didn't want to change remotetitle and coverartdata to camelCase, as that would be a breaking change.

I admit that the binding is a bit inconsistent in how the channels are named. Some are camelCase and some are not. 

But I'm happy to change the new channels to camelCase if that's the recommendation. Just let me know.

2023-01-11 07:35 UTC, jlaur commented
> Ha ha. I actually started down the camelCase path. But I changed it to be consistent with the tag naming convention in the LMS, and also because I didn't want to change remotetitle and coverartdata to camelCase, as that would be a breaking change.

Correct, it's a pickle staying consistent and conforming to naming conventions and at the same time without breaking backwards compatibility. 🙂 However, one thing we shouldn't do is adopting naming conventions from the API's we implement in bindings. We have our own, making openHAB consistent across bindings and being API agnostic.

> I admit that the binding is a bit inconsistent in how the channels are named. Some are camelCase and some are not.

For consistency we will have to choose one of the two (camelCase or lowercase). See below.

> But I'm happy to change the new channels to camelCase if that's the recommendation. Just let me know.

Yes, that's the recommendation. And since it's already in use for some of the channels, this would be the preferred way going forward. See also https://community.openhab.org/t/naming-convention-for-channels/128841/10.

Had all the existing channel been lowercased (or underscore_separated or dash-separated), the situation would be different. Here I would recommend to prioritize consistency higher than the current recommendation.

2023-01-11 12:50 UTC, jlaur approved these changes
LGTM

2023-01-11 12:56 UTC, merged