[ism8] Add UoM support
openhab/openhab-addons pull request #14206
Opened 2023-01-11 22:52 UTC by lsiepel

Signed-off-by: lsiepel <leosiepel@gmail.com>

- Adds UoM to all applicable channels.
- Adds several units tests for in- and outgoing messages.
- Minor re4factoring of Thing handler.

Due to the change in channels, this is not backwards compatible. Channel configuration and linked Items have to be adapted.

Fixes: https://github.com/openhab/openhab-addons/issues/9598

2023-01-13 17:06 UTC, holgerfriedrich commented
As this is a breaking change, did you think of adding a note to update.lst in distro repo?
https://github.com/openhab/openhab-distro/blob/main/distributions/openhab/src/main/resources/bin/update.lst

2023-01-13 19:09 UTC, lsiepel commented
> As this is a breaking change, did you think of adding a note to update.lst in distro repo? https://github.com/openhab/openhab-distro/blob/main/distributions/openhab/src/main/resources/bin/update.lst

Yeah, thought about it, never done that before, hope it is right.

2023-02-06 08:28 UTC, Confectrician reviewed
Looks good for the docs part.

2023-03-13 16:49 UTC, lsiepel commented
Wanted to add the ` instructions.xml` update instructions, but i fail to find any documentation how to do this. @jlaur can you share some links/hints ?

2023-03-14 07:32 UTC, jlaur commented
> Wanted to add the ` instructions.xml` update instructions, but i fail to find any documentation how to do this. @jlaur can you share some links/hints ?

There is no documentation: https://github.com/openhab/openhab-core/pull/3330#issuecomment-1432033039

A few sources for information:
- openhab/openhab-core#3330 - see unit tests.
- #14572
- #14473
- https://github.com/openhab/openhab-addons/pull/14583#discussion_r1134688331

2023-05-27 11:01 UTC, jlaur commented
> > Wanted to add the ` instructions.xml` update instructions, but i fail to find any documentation how to do this. @jlaur can you share some links/hints ?
> 
> There is no documentation: [openhab/openhab-core#3330 (comment)](https://github.com/openhab/openhab-core/pull/3330#issuecomment-1432033039)

Now there is: https://next.openhab.org/docs/developer/bindings/thing-xml.html#updating-thing-types

2023-08-01 20:11 UTC, lsiepel commented
> a

Oke, i have read some more and used it elsewhere. So i can understand the basics, but now this binding is different, it adds the channels during setup dynamically.

I have this problem with the following scenario:
For example old channel-type `number-readonly`  is split into multiple channel-types `percentage-r`, `temperature-r` and `flowrate-r`. Maybe i can make some rules to determine those rules, but i don't think the instructions.xml features some conditional logic, does it?

If not, this PR is ready to review/merge and the breaking change PR will still be needed.

2023-10-13 20:45 UTC, lsiepel commented
@openhab/add-ons-maintainers This PR has been tested and confirmed to be working as expected. Can we get this merged?

2023-11-09 20:53 UTC, lsiepel commented
Seen some other PR's and for those cases when channels where automatically added the thing upgrade was not needed. So i think this is all set now.

2023-11-09 21:06 UTC, jlaur requested changes
Not a review, sorry, but I noticed two old comments pending, so thought I'd "flush" them. 🙂

2023-11-11 14:09 UTC, lsiepel commented on bundles/org.openhab.binding.ism8/README.md
> +| Number | DpId004 | "Kesseltemperatur" |               |
true

2023-11-11 14:17 UTC, lsiepel commented on bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/util/Ism8DomainMap.java
> + * The {@link DataPointBase} is the base class for all data points
Copy/paste error.

2024-02-21 19:11 UTC, lsiepel commented
@openhab/add-ons-maintainers It would be nice to have this available in 4.2 M1 Anyone able to review ?

2024-02-24 12:51 UTC, kaikreuzer requested changes
Thank you - just some minor comments.

2024-02-24 18:31 UTC, lsiepel commented on bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8BindingConstants.java
> +     */
Done

2024-02-24 18:32 UTC, lsiepel commented on bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Handler.java
> +                this.logger.warn(
Done

2024-02-24 18:32 UTC, lsiepel commented on bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Handler.java
> +            this.logger.debug("Ism8: ID or type missing - Channel={}  Cfg={}", description, config);
Done

2024-02-24 18:33 UTC, lsiepel commented on bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Handler.java
> +                this.logger.debug("Writting to Ism8 DataPoint '{}' failed. '{}'", dataPoint.getId(), e.getMessage());
Done

2024-02-24 18:33 UTC, lsiepel commented on bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Handler.java
> +            this.logger.debug("Ism8: ID or type missing - Channel={}  Cfg={}", channel.getLabel(),
Done

2024-02-24 18:33 UTC, lsiepel commented on bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Handler.java
> +                this.logger.debug("Ism8 channel: {} and DataPoint do not have a matching Id: {} vs {}",
Done

2024-02-24 18:33 UTC, lsiepel commented on bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Handler.java
> +        this.logger.debug("Ism8: no channel was found for DataPoint id: {}", dataPoint.getId());
Done

2024-02-24 18:33 UTC, lsiepel commented on bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Handler.java
> +            this.logger.warn(
Done

2024-02-24 18:33 UTC, lsiepel commented on bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Handler.java
> +                    this.logger.debug("Ism8: updating channel {} with datapoint: {}", channel.getUID().getAsString(),
Done

2024-02-24 18:33 UTC, lsiepel commented on bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Handler.java
> +        this.logger.debug("Ism8: Handle command = {} {}", channelUID.getId(), command);
Done

2024-02-25 10:56 UTC, kaikreuzer approved these changes
Thanks!

2024-02-25 10:56 UTC, merged