Fix SAT warnings
openhab/openhab-addons pull request #14202
Opened 2023-01-10 23:53 UTC by holgerfriedrich

Reduce number of warnings.

- PMD.SimplifyBooleanReturns where reasonable, suppress where readability is better without change
- PMD.SimplifyBooleanExpressions
- checkstyle.OneStatementPerLineCheck
- checkstyle.NeedBracesCheck
- PMD.UseStandardCharsets
- PMD.UseCollectionIsEmpty
- PMD.UnusedLocalVariable
- checkstyle.ModifierOrderCheck

2023-01-11 00:05 UTC, RSStephens approved these changes
Lgtm

2023-01-11 07:15 UTC, theater approved these changes

2023-01-11 09:00 UTC, andrewfg approved these changes
Gardena LGTM

2023-01-11 16:30 UTC, druciak approved these changes
Satel LGTM

2023-01-11 18:33 UTC, GerdZanker approved these changes
boschshc LGTM

2023-01-11 18:45 UTC, hypetsch approved these changes
bsblan LGTM

2023-01-11 20:32 UTC, ccutrer approved these changes
homekit LGTM

2023-01-11 20:37 UTC, Markinus approved these changes
km200 LGTM

2023-01-12 06:55 UTC, jlaur requested changes
LGTM - thanks. Two minor comments to consider.

2023-01-12 06:55 UTC, jlaur commented on bundles/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/Util.java
> +        return !((value < min) || (value > max));
Consider if:
```suggestion
        return value >= min && value <= max;
```

would be more readable.

2023-01-12 06:55 UTC, jlaur commented on bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_11/A5_11_03.java
> +    @SuppressWarnings("PMD.SimplifyBooleanReturns")
Wouldn't this be quite straight-forward here?
```java
// TODO: display error state on thing
return state != 0;
```

2023-01-12 16:42 UTC, Wolfgang1966 approved these changes
Approved for tacmi Binding. Thank you

2023-01-12 21:26 UTC, jlaur approved these changes
LGTM

2023-01-13 00:16 UTC, rmichalak approved these changes
digiplex LGTM

2023-01-13 07:11 UTC, merged