[mqtt.homeassistant] add support for Update component
openhab/openhab-addons pull request #14241
Opened 2023-01-17 23:06 UTC by ccutrer

This component is fairly non-standard - it doesn't add any channels. Instead, it provides several properties to the thing, and also adds a thing configuration allowing you to trigger an OTA update on a Home Assistant device from MainUI.

2023-11-14 14:36 UTC, ccutrer commented
Ping @antroids 🙏

2023-11-18 23:28 UTC, ccutrer commented
Rebased (with no changes), then new commit added to fix compilation problems caused by now being on top of #15427

2023-11-19 15:47 UTC, antroids requested changes
Are these configs changes merged from another PR?

2023-11-19 15:47 UTC, antroids commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Update.java
> +        public static String PROPERTY_LATEST_VERSION = "latestFirmwareVersion";
Add final

2023-11-19 15:47 UTC, antroids commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Update.java
> +        public static String PROPERTY_TITLE = "firmwareTitle";
Add final

2023-11-19 15:47 UTC, antroids commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Update.java
> +        public static String PROPERTY_RELEASE_SUMMARY = "firmwareSummary";
Add final

2023-11-19 15:47 UTC, antroids commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Update.java
> +        public static String PROPERTY_RELEASE_URL = "firmwareURL";
Add final

2023-11-19 16:22 UTC, ccutrer commented
> Are these .xml configs changes merged from another PR?

No, they're intentionally part of this PR. The "doUpdate" parameter is part of the thing's config description. The XML changes change the config description from being inline in the thing's XML, to be a ref to a separate config description, and then duplicated to have a separate config description that adds the doUpdate parameter. Then all the thing handler has to do to "add" the doUpdate parameter is change the refed config description on the thing from the base one to the one that has the doUpdate parameters, instead of having to generate a new config description on the fly.

2023-11-19 17:52 UTC, antroids requested changes

2023-11-19 17:52 UTC, antroids commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
> +            if (value instanceof Boolean && ((Boolean) value) == true) {
Remove comparison with true: `if (value instanceof Boolean doUpdate && doUpdate) {`

2023-11-19 18:00 UTC, antroids approved these changes
LGTM,
I didn't test it, hope these dynamic thing configs works well on the UI

2023-11-27 18:22 UTC, ccutrer commented
Anything pending before this can be merged?

2023-12-14 21:53 UTC, lolodomo requested changes
Just a small comment

2023-12-14 21:53 UTC, lolodomo commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/config/homeassistant-thing-config.xml
> +			<description></description>
Please remove this empty description

2023-12-14 21:54 UTC, lolodomo commented
@ccutrer : please consider my comment before Sunday if you would like that PR being part of OH 4.1.

2023-12-14 22:40 UTC, lolodomo approved these changes
LGTM, thank you

2023-12-14 22:53 UTC, merged