[tibber] Fix NPE on server issues
openhab/openhab-addons pull request #14273
Opened 2023-01-25 09:28 UTC by lsiepel

Signed-off-by: lsiepel <leosiepel@gmail.com>

The server might send an unexpected JSON result. Due to not properly checking the json properties, a NPE is thrown.

Fixes: https://github.com/openhab/openhab-addons/issues/14267

2023-01-27 12:41 UTC, lolodomo requested changes

2023-01-27 12:41 UTC, lolodomo commented on bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
> +                            JsonObject featuresObject = viewerObject.getAsJsonObject("features");
homeObject instead of viewerObject

2023-01-29 09:04 UTC, lolodomo approved these changes
LGTM

2023-01-29 09:12 UTC, lolodomo commented
@lsiepel : do you still want to wait for a positive test by someone ?

2023-01-29 09:23 UTC, lsiepel commented
> @lsiepel : do you still want to wait for a positive test by someone ?

Can be merged, thanks!

2023-01-29 09:24 UTC, merged