[jdbc] working version of PG schema check and TIMESTAMPTZ as default to match MySQL
openhab/openhab-addons pull request #14294
Opened 2023-01-30 16:29 UTC by henfiber

This patch fixes two issues in the PostgreSQL implementation of the JDBC service addon.

## 1. TIMESTAMPTZ should be used as default type to match MySQL defaults

The  closest equivalent type to [MySQL](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) `TIMESTAMP` is `TIMESTAMPTZ`in [PostgreSQL](https://www.postgresql.org/docs/current/datatype-datetime.html)  (`timestamp with time zone`).

With TIMESTAMPTZ, PostgreSQL converts the input timestamp to UTC, stores the UTC timestamp, and converts back to the timezone of the session on query time. Exactly what [MySQL does](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) with `TIMESTAMP`.

In contrast, the PG `TIMESTAMP` type (the default we had up to now) discards any time zone information in the input timestamp and thus stores local time or whatever it was given ignoring any offsets (e.g. 10:00:00-0500 and 10:00:00 are stored as the same value despite being different moments in time).

This is better illustrated by running in Pg the examples from the MySQL manual: https://dev.mysql.com/doc/refman/8.0/en/date-and-time-literals.html

```
CREATE TABLE dt (id INTEGER serial, col TIMESTAMP);
CREATE TABLE ts (id INTEGER serial, col TIMESTAMPTZ);

SET TIME ZONE 'EST';
INSERT INTO ts (col) VALUES ('2020-01-01 10:10:10'), ('2020-01-01 10:10:10+05:30'), ('2020-01-01 10:10:10-08:00');

SET TIME ZONE '+00:00';
INSERT INTO ts (col) VALUES ('2020-01-01 10:10:10'), ('2020-01-01 10:10:10+05:30'), ('2020-01-01 10:10:10-08:00');

SET time zone 'EST';
INSERT INTO dt (col) VALUES ('2020-01-01 10:10:10'), ('2020-01-01 10:10:10+05:30'), ('2020-01-01 10:10:10-08:00');

SET TIME ZONE '+00:00';
INSERT INTO dt (col) VALUES ('2020-01-01 10:10:10'), ('2020-01-01 10:10:10+05:30'), ('2020-01-01 10:10:10-08:00');

SET time zone 'EST';
show timezone;

ohtest=> select col, extract(epoch from col) from dt;
         col         |      extract
---------------------+-------------------
 2020-01-01 10:10:10 | 1577873410.000000
 2020-01-01 10:10:10 | 1577873410.000000
 2020-01-01 10:10:10 | 1577873410.000000
 2020-01-01 10:10:10 | 1577873410.000000
 2020-01-01 10:10:10 | 1577873410.000000
 2020-01-01 10:10:10 | 1577873410.000000
(6 rows)

ohtest=> select col, extract(epoch from col) from ts;
          col           |      extract
------------------------+-------------------
 2020-01-01 10:10:10-05 | 1577891410.000000
 2019-12-31 23:40:10-05 | 1577853610.000000
 2020-01-01 13:10:10-05 | 1577902210.000000
 2020-01-01 05:10:10-05 | 1577873410.000000
 2019-12-31 23:40:10-05 | 1577853610.000000
 2020-01-01 13:10:10-05 | 1577902210.000000
(6 rows)
```

As one can verify above, the table `ts` with `TIMESTAMPTZ` matches the `TIMESTAMP` results from the [MySQL manual](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-literals.html), unlike the `dt` table which always stores the same value regardless of timezone in the literal or the session.

This patch changes the default to TIMESTAMPTZ (for new tables). The 2nd issues that is mentioned below allows users to convert existing TIMESTAMP columns to TIMESTAMPTZ.

## 2nd issue. Non-working Schema check and fix (console)

Console commands `jdbc schema check` and `jdbc schema fix` (and the associated internal functions) were not working since the sqlGetTableColumnTypes, doGetTableColumns and doAlterTableColumn were written according to the MySQL `information_schema.columns` but they are slightly different in PG.

Moreover, PostgreSQL uses aliases for types (e.g. "varchar" is equivalent "Character Varying") and these have to be checked as well as valid schema types.

This patch fixes the above issues and includes a `checkItemTables` function which is called on activation of the Persistence service and prints a message in the logs for every table that does not pass the schema validation (equivalent to `jdbc schema check` but automatically running on startup).

2023-01-31 16:25 UTC, jlaur requested changes
Thanks for the fixes.

I would suggest to reduce the scope of this PR so that it only fixes the PostgreSQL bugs. This could then be backported to 3.4.x easily.

The more controversial change with auto-check on startup could then be discussed further as a possible enhancement. This should not target 3.4.

2023-02-01 16:21 UTC, jlaur requested changes
Updating status as comments are not addressed or answered.

2023-02-01 17:45 UTC, jlaur commented
> Hello @jlaur . Did you see my latest commits and my answers? Could you specify which comments are not addressed or answered?

Yes, I did. Are you sure you published your comments, or are they still pending?

2023-02-01 17:54 UTC, henfiber reviewed
Please let me know if the updated approach satisfies any concerns or whether you would still prefer me to split into two  separate PRs.

2023-02-01 17:55 UTC, henfiber commented
> Are you sure you published your comments, or are they still pending?

Thanks for the hint. Apparently I fell victim of this: https://github.com/community/community/discussions/10369. 
Published now, thanks.

2023-02-01 17:58 UTC, henfiber commented on bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java
> +                .collect(Collectors.<PersistenceItemInfo>toSet());
(Fixed manually)

2023-02-01 19:25 UTC, jlaur commented on bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
> +                }
Adding an option to have the schema and/or item consistency checked on startup sounds with default value `false` like a good compromise. My argument was both about log entries **and** resource waste. I usually don't monitor logs during restarts, so for me that's an artificial time. I'd rather see these issues when I want to see them, i.e. when going to the console and checking things.

I would suggest to do this in a separate PR, i.e. to completely remove this part from this PR, which I could then cherry-pick for 3.4.x when merged.

2023-02-01 20:02 UTC, henfiber commented on bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
> +                }
Alright @jlaur. I will remove the check at startup and create a separate PR 
(with a potential optimization for the check which I am seeing now).

2023-02-02 06:14 UTC, henfiber reviewed
@jlaur I removed the check at startup.

2023-02-02 07:26 UTC, jlaur approved these changes
Thanks again for the fixes. LGTM!

2023-02-02 07:27 UTC, merged

2023-02-02 07:29 UTC, jlaur commented
@lolodomo - to be considered for 3.4.x. I would opt for backporting since it fixes the `schema check` console command for PostgreSQL. Additionally it fixes time-zone issues when new tables are created in PostgreSQL or when using the `schema fix` console command to migrate.

2023-02-04 09:47 UTC, jlaur commented
@lolodomo - gentle ping. 🙂

2023-02-04 11:28 UTC, lolodomo commented
> @lolodomo - to be considered for 3.4.x. I would opt for backporting since it fixes the `schema check` console command for PostgreSQL. Additionally it fixes time-zone issues when new tables are created in PostgreSQL or when using the `schema fix` console command to migrate.

OK