[fineoffsetweatherstation] Fix java.lang.IllegalMonitorStateException
openhab/openhab-addons pull request #14326
Opened 2023-02-03 11:46 UTC by Andy2003

This fix ensures, that the `ReentrantLock::unlock` method is only called, when the Thread is owning the lock.

resolves: #14322

2023-02-03 23:00 UTC, jlaur requested changes
Thanks for the fix! I have only two questions about the log level.

2023-02-03 23:00 UTC, jlaur commented on bundles/org.openhab.binding.fineoffsetweatherstation/src/main/java/org/openhab/binding/fineoffsetweatherstation/internal/service/GatewayQueryService.java
> +            logger.info("executeCommand({}): was interrupted while getting the lock", command);
It seems to me that log level could be reduced to **debug** here. For reference: https://www.openhab.org/docs/developer/guidelines.html#f-logging

2023-02-03 23:00 UTC, jlaur commented on bundles/org.openhab.binding.fineoffsetweatherstation/src/main/java/org/openhab/binding/fineoffsetweatherstation/internal/service/GatewayQueryService.java
> +                logger.warn("executeCommand({}): timed out while getting the lock", command);
Under which circumstances does this happen? Is it really something the user should be warned about?

2023-02-04 17:02 UTC, jlaur approved these changes
LGTM

2023-02-04 17:03 UTC, merged

2023-02-04 17:03 UTC, jlaur commented
@Andy2003, @lolodomo - do you agree we should cherry-pick this into the 3.4.x branch?

2023-02-04 17:48 UTC, Andy2003 commented
> @Andy2003, @lolodomo - do you agree we should cherry-pick this into the 3.4.x branch?

Definitly