Update README.md
openhab/openhab-addons pull request #14359
Opened 2023-02-06 19:02 UTC by pjgueno

Replaced all the occurence of Luftdaten.
The project name is Sensor.Community. Please help us to remove all Luftdaten once for all...

2023-02-06 19:03 UTC, pjgueno commented
I continue to check for Luftdaten.info everywhere

2023-02-06 19:07 UTC, pjgueno commented
Please also update the file name. Lukas Mocek lukas@sensor.community asked me to do this PR

2023-02-06 19:12 UTC, pjgueno commented
Please also update the URLs etc. It is a never ending strory since January 2020... "Luftdaten" appears again and again...

2023-02-06 19:46 UTC, lolodomo commented
"LuftdatenInfo" Is the name of the binding and packages include this name. Changing that would be a breaking change for OH users. 
@weymann as maintainer of this binding.

2023-02-06 21:07 UTC, pjgueno commented
It is the reason why people should answer our E-Mails and participate directly in SC. We try to avoid this for the past 3 years. Please find a solution. Luftdaten is a dead name.

2023-02-06 21:45 UTC, lolodomo commented
> Please find a solution. Luftdaten is a dead name.

Solution is to create a PR that will rename the binding. You need to find a volunteer to do that in case you do not want to do it yourself.

2023-02-06 21:49 UTC, lolodomo commented
Changing README is a first step but you can't change the thing UID without changing the binding code itself.

2023-02-14 20:39 UTC, jlaur requested changes
Please revert changes in thing and channel names in the documentation until the binding itself is potentially renamed and updated for this.

2023-02-14 20:39 UTC, jlaur commented on bundles/org.openhab.binding.luftdateninfo/README.md
> +Thing sensorcommunity:noise:noise_sensor      "Noise Sensor"      [ sensorid=39745 ]
This example cannot be changed without changing the underlying naming in code, otherwise it won't work.

2023-02-14 20:39 UTC, jlaur commented on bundles/org.openhab.binding.luftdateninfo/README.md
> +Number:Dimensionless LDI_NoiseMax   "Noise max"             { channel="sensorcommunity:noise:noise_sensor:noise-max" }
The same here.

2023-05-21 21:26 UTC, jlaur commented
Obsoleted by #15012.

2023-05-21 21:26 UTC, closed without merging