[xmpp] Improve reconnection logic
openhab/openhab-addons pull request #14397
Opened 2023-02-15 10:03 UTC by lsiepel

- Improves reconnection logic
 - Add null annotations

Fixes: https://github.com/openhab/openhab-addons/issues/9378
Fixes: https://github.com/openhab/openhab-addons/issues/10482 

Test jar files:
openHAB 3.4.2: https://1drv.ms/u/s!AnMcxmvEeupwjqVFDy9C1Eh--QOA5g?e=P1pKSa
openHAB 4.0.0: https://1drv.ms/u/s!AnMcxmvEeupwjqVFDy9C1Eh--QOA5g?e=7j3aZM

2024-08-10 09:47 UTC, lsiepel commented
@lolodomo are you able to review?

2024-08-11 12:56 UTC, lolodomo commented
Will do it during next week.

2024-08-13 15:50 UTC, lolodomo requested changes
Just 2 minor comments

2024-08-13 15:50 UTC, lolodomo commented on bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/internal/client/XMPPClientEventlistener.java
> + * The {@link XMPPClientEventlistener} is lib for handling XMPP connection events
Rather "interface" ?

2024-08-13 15:50 UTC, lolodomo commented on bundles/org.openhab.binding.xmppclient/README.md
> +| port     | Security Mode      | Sets the TLS security mode: `required`, `ifpossible` or `disabled` | false    | `required`            |
Typo: parameter name is: securityMode

2024-08-18 19:31 UTC, lsiepel commented on bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/internal/client/XMPPClientEventlistener.java
> + * The {@link XMPPClientEventlistener} is lib for handling XMPP connection events
Fixed.

2024-08-18 19:32 UTC, lsiepel commented on bundles/org.openhab.binding.xmppclient/README.md
> +| port     | Security Mode      | Sets the TLS security mode: `required`, `ifpossible` or `disabled` | false    | `required`            |
Fixed.

2024-08-19 06:19 UTC, lolodomo approved these changes
LGTM, thank you

2024-08-19 06:21 UTC, merged