[openwebnet] light switch updates are now triggered
openhab/openhab-addons pull request #14390
Opened 2023-02-13 18:33 UTC by mvalla

Removed the variable used to check if switch state has changed. 
Now for each light switch update `updateState()` is correctly called on switch channel
Fixes #14102

2023-02-13 20:27 UTC, jlaur requested changes
Thanks for the fix! I have added a very minor completely optional suggestion.

2023-02-13 20:27 UTC, jlaur commented on bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetLightingHandler.java
> +                updateState(channelId, (msg.isOn() ? OnOffType.ON : OnOffType.OFF));
Could even be simplified to:
```suggestion
                updateState(channelId, OnOffType.from(msg.isOn()));
```

🙂

2023-02-13 21:11 UTC, mvalla commented on bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetLightingHandler.java
> +                updateState(channelId, (msg.isOn() ? OnOffType.ON : OnOffType.OFF));
ok!

2023-02-13 21:27 UTC, jlaur approved these changes
LGTM

2023-02-13 21:28 UTC, merged

2023-04-02 16:57 UTC, mvalla commented
@jlaur I suggest to backport this to 3.4.x, thanks.

2023-04-02 19:32 UTC, jlaur commented
> I suggest to backport this to 3.4.x, thanks.

Done.