[velux] Update documentation
openhab/openhab-addons pull request #14478
Opened 2023-02-22 13:59 UTC by andrewfg

Resolves #14404

As stated in Issue #14404 a user found the binding documentation concerning the `inverted` parameter to be confusing.

So this PR adds further information to the readme file to better explain the meaning of the `inverted` parameter.

Note: this PR includes all the changes from #14371 in order to (hopefully) avoid a merge conflict.

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

2023-02-26 21:30 UTC, jirikraus requested changes
Thanks @andrewfg this addresses my confusion and #14404 . As the table is inconsistent with the provided `Bathroom_Roof_Window_Position` example I am suggestion some updates to that.

2023-02-26 21:30 UTC, jirikraus commented on bundles/org.openhab.binding.velux/README.md
>  1. To enable a complete inversion of all parameter values (i.e. for Velux windows), use the property `inverted` or add a trailing star to the eight-byte serial number.
```suggestion
1. To enable a complete inversion of all parameter values, use the property `inverted` or add a trailing star to the eight-byte serial number.
```
I would suggest to drop `(i.e. for Velux windows)` as windows don't need to be inverted to work as expected.

2023-02-26 21:30 UTC, jirikraus commented on bundles/org.openhab.binding.velux/README.md
>    For an example, see the Thing definition for 'Bathroom_Roof_Window' below.
```suggestion
```
See comment above. I would suggest to drop this and update the example as the inverted property is not needed for windows.

2023-02-26 21:30 UTC, jirikraus commented on bundles/org.openhab.binding.velux/README.md
>      Thing window Bathroom_Roof_Window "Bathroom Roof Window" @ "Bathroom" [serial="56:36:13:5A:11:2A:05:70", inverted=true]
```suggestion
    Thing window Bathroom_Roof_Window "Bathroom Roof Window" @ "Bathroom" [serial="56:36:13:5A:11:2A:05:70"]
```
Inverted should not be needed see my comment above.

2023-03-07 22:17 UTC, jlaur approved these changes
LGTM, thanks.

2023-03-07 22:17 UTC, merged