[Pushsafer] add latest parameter answeroptions and answerforce
openhab/openhab-addons pull request #14578
Opened 2023-03-11 15:00 UTC by appzer

- [Pushsafer] add latest parameter answeroptions and answerforce
ao = https://www.pushsafer.com/en/pushapi_ext#API-AO
af = https://www.pushsafer.com/en/pushapi_ext#API-AF

2023-03-11 20:27 UTC, lsiepel requested changes
Thanks for the contribution, just some mainly documentaiton related comments.

2023-03-11 20:27 UTC, lsiepel commented on bundles/org.openhab.binding.pushsafer/README.md
> +| `answerforce`                | integer | 1 = force an answer. The user will be prompted to answer, the message will be open directly. (default: `0`). **advanced**
Please correct spaces, use http://markdowntable.com/ or similar.
I think (not 100% sure) that you  don't need to use the html escaped tags for pipes

2023-03-11 20:27 UTC, lsiepel commented on bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/connection/PushsaferMessageBuilder.java
> +		body.addFieldPart(MESSAGE_KEY_ANSWEROPTIONS, new StringContentProvider(String.valueOf(answeroptions)), null);
Please apply spotless for proper indentation.

2023-03-11 20:27 UTC, lsiepel commented on bundles/org.openhab.binding.pushsafer/src/main/resources/OH-INF/i18n/pushsafer_de.properties
> +thing-type.config.pushsafer.pushsafer-account.answeroptions.label = Antwort Optionen
Please revert changes to this file, only default trranslation is provided by PR's all other languages are provided by crowdin.

2023-05-03 11:57 UTC, lolodomo commented
This PR is in a wrong state, DCO error and even more important the build failed.
I try to trigger a rebuild.

2023-05-06 15:27 UTC, lolodomo commented
You need to run spotless: `mvn spotless:apply`

2023-05-07 08:34 UTC, appzer commented
> You need to run spotless: `mvn spotless:apply`

already done!
i made this locally and uploaded it afterwards without success. Can someone from the authorized members run and check it again themselves? Thanks very much.
Regards Kevin

2024-09-29 19:02 UTC, lsiepel commented
The last commit you tried to push (spotless) was probably rejected because your branch is 1753 commits behind and has some merge conflicts that need manual interaction.  I just triedd to merge your branch from current main, but i don;t have write permission to your branch.
You could do the same by merging openhab main into your fork at github, into your local fork, into your feature branch. The conflict is in the addon.xml
My vscode wen nuts due to the amount of commits and i had to manually merge in ~400 commits per step to get it up to date.
Let me know if you need any help.

2024-09-30 08:22 UTC, appzer commented
@lsiepel how i can give you permission to my branch. I dont know what i have to do!
Thanks Kevin

2024-09-30 16:00 UTC, lsiepel commented
> @lsiepel how i can give you permission to my branch. I dont know what i have to do! Thanks Kevin

https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-access-to-your-projects#granting-a-collaborator-access-to-your-project

2024-09-30 19:09 UTC, appzer commented
> > @lsiepel how i can give you permission to my branch. I dont know what i have to do! Thanks Kevin
> 
> https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-access-to-your-projects#granting-a-collaborator-access-to-your-project

**done**

Please let me know if and how I can help you.

Thank you
Kevin

2024-10-02 18:17 UTC, lsiepel commented
Merged updatream into your reposity. Still some issues that you need to look at:
1. DCO, see here: https://github.com/openhab/openhab-addons/pull/14578/checks?check_run_id=30987719374
2. Spotless / build fix. 
3. Open review comments.

2024-10-02 18:47 UTC, appzer commented
> Merged updatream into your reposity. Still some issues that you need to look at:
> 
> 1. DCO, see here: https://github.com/openhab/openhab-addons/pull/14578/checks?check_run_id=30987719374
> 2. Spotless / build fix.
> 3. Open review comments.

How to solve this?

2024-10-11 13:52 UTC, lsiepel commented
@appzer sorry, somehow i edited your post instead of quoting, reverted this and here is the quote ;-)  

> How to solve this?
> 1. DCO, see here: https://github.com/openhab/openhab-addons/pull/14578/checks?check_run_id=30987719374

There is a description how to fix it at the link

> 2. Spotless / build fix.

mvn spotless:apply for reference: https://www.openhab.org/docs/developer/guidelines.html#code-format

> 3. Open review comments.

Don't think this needs explenation.


Please let me know if you can proceed or if you need anything else.

2024-10-17 18:09 UTC, appzer commented
> @appzer sorry, somehow i edited your post instead of quoting, reverted this and here is the quote ;-)
> 
> > How to solve this?
> > 
> > 1. DCO, see here: https://github.com/openhab/openhab-addons/pull/14578/checks?check_run_id=30987719374
> 
> There is a description how to fix it at the link
> 
> > 2. Spotless / build fix.
> 
> mvn spotless:apply for reference: https://www.openhab.org/docs/developer/guidelines.html#code-format
> 
> > 3. Open review comments.
> 
> Don't think this needs explenation.
> 
> Please let me know if you can proceed or if you need anything else.

Hi @lsiepel,

Unfortunately I can't figure it out! Can you take over this module and make it public?

Thank you 
Kevin

2024-10-17 18:34 UTC, lsiepel commented
> ver this module and make it public?
> 
> Thank you

I rather give you support so that we can fix it together. Can you try to explain what you did and where you struggle? Maybe best to try to fix 2 and 3 first. The DCO can be fixed at any time.

2024-10-18 07:25 UTC, appzer commented
> > ver this module and make it public?
> > Thank you
> 
> I rather give you support so that we can fix it together. Can you try to explain what you did and where you struggle? Maybe best to try to fix 2 and 3 first. The DCO can be fixed at any time.

How i can use a CLI? I only use the web interface.

2024-10-18 07:32 UTC, lsiepel commented
> > > ver this module and make it public?
> > > Thank you
> > 
> > 
> > I rather give you support so that we can fix it together. Can you try to explain what you did and where you struggle? Maybe best to try to fix 2 and 3 first. The DCO can be fixed at any time.
> 
> How i can use a CLI? I only use the web interface.

AFAIK these steps can only be done from the IDE/CLI, not the webinterface. 

Are you using vs code as IDE? Within vs code you can open a terminal/CLI to start maven with different options. The one mentioned is to run mvn with the spotless plugin. 

Vs code documentation is here
https://www.openhab.org/docs/developer/ide/vscode.html

2024-11-29 14:30 UTC, appzer commented
> > > > ver this module and make it public?
> > > > Thank you
> > > 
> > > 
> > > I rather give you support so that we can fix it together. Can you try to explain what you did and where you struggle? Maybe best to try to fix 2 and 3 first. The DCO can be fixed at any time.
> > 
> > 
> > How i can use a CLI? I only use the web interface.
> 
> AFAIK these steps can only be done from the IDE/CLI, not the webinterface.
> 
> Are you using vs code as IDE? Within vs code you can open a terminal/CLI to start maven with different options. The one mentioned is to run mvn with the spotless plugin.
> 
> Vs code documentation is here https://www.openhab.org/docs/developer/ide/vscode.html

Hi @lsiepel 

i only use the web interface.
I give you write access to my repository, i hope you get the update published.
https://github.com/Pushsafer/openhab-addons

Kind Regards
Kevin

2025-03-22 22:57 UTC, lsiepel commented
All branches are up to date. Just made a trivial change to verify all is fine. But somehow CI is complaining about spotless, while locally builds are fine and spotless does not find anything to fix.

What am i missing here?

2025-03-26 19:17 UTC, lsiepel approved these changes
Ok. Thanks! LGTM.

Some weird stuff going on. CI complained about spotless, locally i had no problem. So iended up in removing the problematic file and adding it again. Now CI builds fine :-s

Anyway, as i performed these trivial changes to trigger CI  i doubt i should merge this. Maybe some other @openhab/add-ons-maintainers can merge this, i already reviewd the code.

2025-03-29 20:17 UTC, merged