[tapocontrol] support display light effects for L530
openhab/openhab-addons pull request #14596
Opened 2023-03-13 17:25 UTC by wildcs

- Integrated L530 SmartBulb into LightEffects class.
  Show active FX (ReadOnly)
  Bugfix:  Color change is now possible if effect was already enabled by app

- L920 and L930 add effect-names to XML File

- Removed effects from global xml file cause of different effects for each devicetype

2023-03-20 08:03 UTC, jlaur commented on bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L530.xml
> +		<label>Ligth Effect Theme</label>
```suggestion
		<label>Light Effect Theme</label>
```

2023-03-20 08:03 UTC, jlaur commented on bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L530.xml
> +		<description>Name of active LightningEffect</description>
```suggestion
		<description>Name of active lightning effect</description>
```

2023-03-20 08:04 UTC, jlaur commented on bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L930.xml
> +		<description>Name of LightningEffect</description>
```suggestion
		<description>Name of lightning effect</description>
```

2023-03-20 08:04 UTC, jlaur commented on bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L930.xml
> +		<label>Ligth Effect Theme</label>
```suggestion
		<label>Light Effect Theme</label>
```

2023-03-20 08:06 UTC, jlaur commented on bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L920.xml
> +		<label>Ligth Effect Theme</label>
```suggestion
		<label>Light Effect Theme</label>
```

2023-03-20 08:06 UTC, jlaur commented on bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L920.xml
> +		<description>Name of LightningEffect</description>
```suggestion
		<description>Name of lightning effect</description>
```

2023-03-20 20:09 UTC, wildcs commented on bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
> +    public static final String CHANNEL_GROUP_EFFECTS = "effects";
Yes your right. But the channels wasn't used in XML-Files until now.
Integrated them for L9x0 LightStrips but didn't have one to test it.
Just in this PR fx is used for L530.

2023-03-20 20:09 UTC, wildcs commented on bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
> +    public static final String CHANNEL_FX_NAME = "fxName";
Same as above

2023-03-20 20:13 UTC, wildcs commented on bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceConnector.java
> +        queryCommand(DEVICE_CMD_GETENERGY, true);
trace is done in the "queryCommand"-function. no need to call it twice

2023-03-20 20:22 UTC, wildcs commented on bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
> +    public static final String PROPERTY_LIGHTNING_DYNAMIC_ID = "dynamic_light_effect_id";
this is not a property for a channel. This ist the name of json-key received from device.
maybe i can rename it, but then i should rename all "properties"

2023-03-20 20:34 UTC, wildcs commented on bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
> +    public static final String PROPERTY_LIGHTNING_DYNAMIC_ENABLE = "dynamic_light_effect_enable";
this is not a property for a channel. This ist the name of json-key received from device.
maybe i can rename it, but then i should rename all "properties"

2023-03-21 22:00 UTC, jlaur commented on bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceConnector.java
> +        queryCommand(DEVICE_CMD_GETENERGY, true);
Oh, missed that, was blindly comparing this method with `queryInfo` and `queryChildDevices` which still have trace logging and also calling `queryCommand`.

2023-03-21 22:02 UTC, jlaur commented on bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
> +    public static final String PROPERTY_LIGHTNING_DYNAMIC_ENABLE = "dynamic_light_effect_enable";
Ah, thanks for clarifying that. Yes, I think it would be a good idea to rename and change the prefix in order to avoid confusion.

2023-03-21 22:04 UTC, jlaur commented on bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
> +    public static final String PROPERTY_LIGHTNING_DYNAMIC_ENABLE = "dynamic_light_effect_enable";
I see now that `DEVICE_PROPERTY` was already used as prefix above. So the other ones just above are probably thing properties - for example `PROPERTY_LIGHTNING_EFFECT_DISPLAYCOLORS`?

2023-03-23 20:46 UTC, jlaur commented on bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoLightEffect.java
> +            this.custom = jsonObjectToBool(jsonObject, JSON_KEY_LIGHTNING_EFFECT_CUSTOM); // jsonObjectToBool
```suggestion
            this.custom = jsonObjectToBool(jsonObject, JSON_KEY_LIGHTNING_EFFECT_CUSTOM);
```

2023-03-23 20:49 UTC, jlaur requested changes
Can you please regenerate the I18N properties file? See https://www.openhab.org/docs/developer/utils/i18n.html#generating-i18n-properties-file

Otherwise LGTM.

2023-03-24 20:56 UTC, jlaur approved these changes
LGTM

2023-03-24 20:57 UTC, merged