[rustpotter] Use version 2
openhab/openhab-addons pull request #14615
Opened 2023-03-15 21:04 UTC by GiviMAD

Use new library version, which seems to perform better.

Note: Keyword files from the previous version are not compatibles.

2023-03-20 07:45 UTC, jlaur requested changes
Thanks! Only minor comments from my side.

2023-03-20 07:45 UTC, jlaur commented on bundles/org.openhab.voice.rustpotterks/README.md
> +You can test library in your browser, using these web pages:
```suggestion
You can test library in your browser using these web pages:
```

2023-03-21 20:21 UTC, GiviMAD commented on bundles/org.openhab.voice.rustpotterks/README.md
> +* [The model creation demo](https://givimad.github.io/rustpotter-create-model-demo/), it allows you to record compatible wav files and generate a wakeword file that you can test on the previous page.
Thank for the review @jlaur, I'm working on the change. 

Would you be able to explain to me this review? I'm using the '*' character for other lists just after this one. Should I change the others? Or there is a difference between them?

2023-03-21 20:33 UTC, jlaur commented on bundles/org.openhab.voice.rustpotterks/README.md
> +* [The model creation demo](https://givimad.github.io/rustpotter-create-model-demo/), it allows you to record compatible wav files and generate a wakeword file that you can test on the previous page.
Please see #14371 and #13858. I'm not sure about exact reason, but probably it's a matter of consistency. Yes, if you can fix all, that would be great - I believe I just commented changed lines.

2023-03-21 20:36 UTC, GiviMAD commented on bundles/org.openhab.voice.rustpotterks/README.md
> +* [The model creation demo](https://givimad.github.io/rustpotter-create-model-demo/), it allows you to record compatible wav files and generate a wakeword file that you can test on the previous page.
Thanks for the references! I didn't realize that was one of the md improvements. On it.

2023-03-21 21:55 UTC, jlaur approved these changes
LGTM

2023-03-21 21:55 UTC, merged