[easee] migrated charger state API endpoint, added channels
openhab/openhab-addons pull request #14614
Opened 2023-03-15 20:35 UTC by alexf2015

This PR implements some points mentioned in issue #14037

1. the charger state API endpoint is now migrated to the new API
2. some missing channels were added
3. changed behaviour in error case: instead of taking the bridge offline only the dedicated thing will be put offline. Thus a faulty charger config will not take down the whole bridge including all things.

2023-05-17 20:02 UTC, jlaur requested changes
Thanks! I have provided only some minor suggestions. Also, please add update instructions for the channel added - see https://next.openhab.org/docs/developer/bindings/thing-xml.html#updating-thing-types

2023-05-23 17:40 UTC, alexf2015 commented on bundles/org.openhab.binding.easee/src/main/resources/OH-INF/thing/charger-channel-groups.xml
> +			<channel id="wiFiRSSI" typeId="type-integer">
I am not sure if mW is the correct unit. Usually it is measured in dBm. Transformation to mW is not easy and in addition I am in doubt that people will understand the transformed values. people will now that -30dBm is a really good signal and -60dBm is still good. On the other hand values like 1 µW or 1 nW are not easy to understand.

2023-05-23 18:01 UTC, jlaur commented on bundles/org.openhab.binding.easee/src/main/resources/OH-INF/thing/charger-channel-groups.xml
> +			<channel id="wiFiRSSI" typeId="type-integer">
I agree dBm is the unit normally used for measuring RSSI, so hence my suggestion to apply it. See for example #14319.

2023-05-26 04:29 UTC, alexf2015 commented on bundles/org.openhab.binding.easee/src/main/resources/OH-INF/thing/charger-channel-groups.xml
> +			<channel id="wiFiRSSI" typeId="type-integer">
ok now I see that I overlooked that you suggested ```Units.DECIBEL_MILLIWATTS``` and not ```Units.MILLIWATTS``` which most likely does not exist at all...
I will change it accordingly.

2023-05-27 09:49 UTC, jlaur commented on bundles/org.openhab.binding.easee/src/main/resources/OH-INF/thing/easee-readonly-channel-types.xml
> +		<label>Received Signal Strength Indicator</label>
```suggestion
		<label>Received Signal Strength Indicator</label>
		<category>QualityOfService</category>
```

2023-05-27 09:51 UTC, jlaur commented
> Also, please add update instructions for the channel added - see https://next.openhab.org/docs/developer/bindings/thing-xml.html#updating-thing-types

Just in case you missed this - please provide also the update instructions.

2023-05-27 12:03 UTC, alexf2015 commented
Sure I will add migration. In general this is a really good idea. Unfortunately I discovered some issues in my other PR.
1. I am using Eclipse and there are some issues that prevent the whole thing from starting up (in Eclipse) as soon as there are migration statements present.
2. This should not affect this binding as the changes do not affect any channels that have properties but channel properties are not yet supported.

2023-05-27 20:06 UTC, alexf2015 commented
tested migration successfully.
```thingTypeVersion``` is now set to ```2``` as there is another pull request pending which already uses version 1. Depending on which is merged back earlier I need to adjust.

2023-07-13 06:43 UTC, Diapolo commented
Easee is changing their API endpoint to `api.easee.com` on September 1st 2023 (see here https://developer.easee.cloud/docs). @alexf2015 Perhaps you could integrate that change here or create a new pull for that? And any idea when this pull here will be merged? I'd love to kick out my own rule based query/parsing stuff and just use this nice addon :). Thanks for your work!

2023-08-17 05:56 UTC, Diapolo commented
What can be done to get this finally in? I'm waiting for this.

2023-08-17 14:58 UTC, jlaur commented
> tested migration successfully.
> `thingTypeVersion` is now set to `2` as there is another pull request pending which already uses version 1. Depending on which is merged back earlier I need to adjust.

Sorry for the long delay, I must have somehow missed it, since it looks quite up-to-date already with latest comments. Can you rebase towards main now that #15229 was merged?

2023-08-17 17:09 UTC, alexf2015 commented
> I mixed the two PR's - #14866 is now merged, so you can rebase and change `thingTypeVersion` to 1.
done

2023-08-18 11:32 UTC, jlaur approved these changes
Thank you for these improvements!

2023-08-18 11:33 UTC, merged

2023-10-15 09:44 UTC, Diapolo commented
@alexf2015 AFAIK there are still some values missing, could you take a look at:
localRSSI
outputPhase
chargerRAT
circuitTotalAllocatedPhaseConductorCurrentL1
circuitTotalAllocatedPhaseConductorCurrentL2
circuitTotalAllocatedPhaseConductorCurrentL3
circuitTotalPhaseConductorCurrentL1
circuitTotalPhaseConductorCurrentL2
circuitTotalPhaseConductorCurrentL3
wiFiAPEnabled
offlineMaxCircuitCurrentP1
offlineMaxCircuitCurrentP2
offlineMaxCircuitCurrentP3
eqAvailableCurrentP1
eqAvailableCurrentP2
eqAvailableCurrentP3
deratedCurrent
deratingActive
errors

I really don't know if these are used anymore, but they are still in the JSON reply from the deprecated endpoint (which I now replaced to just your addon, so I don't get them anymore).