Use deviceDiscoveryId instead of id
openhab/openhab-addons pull request #14661
Opened 2023-03-24 07:58 UTC by maihacke

# Change handling for device IDs in icloud binding

Lately users discover problems with changes in the device ID in the iCloud API.
See discussion here https://community.openhab.org/t/icloud-binding-communication-error/122131/597

I saved the device data json before and after this change happened.
Each device has three IDs in the json:

id, baUUID, deviceDiscoveryId

Currently we use id to identify devices. This id has changed lately (back and forth and now again, see discussion). That's why openhab identfies these devices as new and put them into the inbox. The other IDs did not change - at least between my two files. So we have some chances that changing the binding to use one of the other IDs this problem could be solved.

This PR changes the binding to use deviceDiscoveryId instead of id.

Should fix https://github.com/openhab/openhab-addons/issues/14660

2023-04-18 05:33 UTC, maihacke commented
@jlaur Without this change the icloud binding stops working after a few days. Maybe we could consider it for 4.0.0.

2023-04-27 19:35 UTC, jlaur requested changes
Thanks, only two minor suggestions added.

Do you think "Fix things reappearing in inbox" would be an accurate title for the PR (to go into the release notes)?

2023-04-27 19:35 UTC, jlaur commented on bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/discovery/ICloudDeviceDiscovery.java
> +            if (deviceDiscoveryId == null || "".equals(deviceDiscoveryId)) {
```suggestion
            if (deviceDiscoveryId == null || deviceDiscoveryId.isBlank()) {
```

2023-04-27 19:35 UTC, jlaur commented on bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudDeviceHandler.java
> +            if (currentId == null || "".equals(currentId)) {
```suggestion
            if (currentId == null || currentId.isBlank()) {
```

2023-04-28 12:45 UTC, maihacke commented
Thanks for the review.

2023-05-03 10:27 UTC, jlaur approved these changes
LGTM

2023-05-03 10:27 UTC, merged

2023-05-03 10:29 UTC, jlaur commented
@maihacke - for my understanding, why did the binding stop working after a few days? It seems that the "Fix things reappearing in inbox" does not fully cover the actual fix.

2023-05-03 10:59 UTC, maihacke commented
> @maihacke - for my understanding, why did the binding stop working after a few days? It seems that the "Fix things reappearing in inbox" does not fully cover the actual fix.

The reason is that the IDs which where used in the binding before that fix where no longer constant. So they changed from time to time in the API results. This lead to
A: New things appeared in the in inbox for the new IDs.
B: Existing things stopped working because there IDs where no longer valid in the iCloud API.

Maybe we could use

"Existing things stopped working and re-appeared as new in the inbox".

2023-05-03 11:48 UTC, jlaur commented
@maihacke - thanks.