[boschindego] Implement OAuth2 authorization
openhab/openhab-addons pull request #14745
Opened 2023-04-04 13:53 UTC by jlaur

Fixes #14536

2023-04-07 09:18 UTC, jlaur commented
@openhab/add-ons-maintainers, if this PR would be reviewed and completed during the Easter, I should be able to quickly backport it to 3.4.x so it could be included in 3.4.3.

2023-04-14 14:24 UTC, jlaur commented
My mower has been authenticated for more than a week now without any issues. I don't have any plans for the near future to improve the cumbersome authorization flow described in the README.

2023-04-14 21:13 UTC, jlaur commented
@openhab/add-ons-maintainers - since the binding is currently broken by cloud changes, please consider this PR for the upcoming milestone.

2023-04-15 07:02 UTC, wborn requested changes
Thanks for making it working again! I only have a few minor comments.

2023-04-15 07:02 UTC, wborn commented on bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschAccountHandler.java
> +        oAuthClientService = oAuthFactory.createOAuthClientService(this.getThing().getUID().getAsString(),
```suggestion
        oAuthClientService = oAuthFactory.createOAuthClientService(getThing().getUID().getAsString(),
```

2023-04-15 07:02 UTC, wborn commented on bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschAccountHandler.java
> +        this.oAuthFactory.ungetOAuthService(this.getThing().getUID().getAsString());
```suggestion
        oAuthFactory.ungetOAuthService(getThing().getUID().getAsString());
```

2023-04-15 07:02 UTC, wborn commented on bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
> +                    "@text/offline.conf-error.missing-brige");
```suggestion
                    "@text/offline.conf-error.missing-bridge");
```

2023-04-15 07:02 UTC, wborn commented on bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
> +                    "@text/offline.conf-error.missing-brige");
```suggestion
                    "@text/offline.conf-error.missing-bridge");
```

2023-04-15 07:02 UTC, wborn commented on bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/i18n/boschindego.properties
> +offline.conf-error.missing-brige = No bridge configured
```suggestion
offline.conf-error.missing-bridge = No bridge configured
```

2023-04-15 07:31 UTC, jlaur commented
@wborn - thanks for reviewing this. I have addressed your comments.

2023-04-15 07:35 UTC, wborn approved these changes
Very good! :+1:

2023-04-15 07:39 UTC, merged

2023-04-15 07:39 UTC, wborn commented
Now you can also create a PR to add an upgrade notice. :wink:

2023-04-15 09:23 UTC, BillGOH commented
@jlaur Thank you for your great work! First tests look very good.