[FolderWatcher] Formatting and write out of abbreviations in Docs
openhab/openhab-addons pull request #14793
Opened 2023-04-13 12:01 UTC by felixschndr

- `s` --> `in seconds`
- `h` --> `in hours`
- formatting of tables, things and rules
- Unifiy usage of `'` and `"`

2023-04-14 21:17 UTC, goopilot commented
@felixschndr could you hold on with this pull request as there is another one that is also fixing formatting in the readme. https://github.com/openhab/openhab-addons/pull/14669
Pls have a look at it.

2023-04-14 21:18 UTC, goopilot requested changes
@felixschndr could you hold on with this pull request as there is another one that is also fixing formatting in the readme. https://github.com/openhab/openhab-addons/pull/14669
Pls have a look at it.

2023-04-15 12:18 UTC, felixschndr commented
Okay, will rebase once the PR is merged and then updates this PR

2023-04-15 20:48 UTC, felixschndr commented
@goopilot I rebased the PR on your merge into main. Just some small cosmetics to the docs.

2023-04-23 09:37 UTC, felixschndr commented
Any news @goopilot ?

2023-05-02 17:31 UTC, felixschndr commented on bundles/org.openhab.binding.folderwatcher/README.md
>  FTP example:
Now good?

2023-05-02 19:55 UTC, goopilot approved these changes

2023-05-02 20:16 UTC, jlaur approved these changes
Thanks!

2023-05-02 20:17 UTC, merged