[nest] Remove the access token when the thing is removed
openhab/openhab-addons pull request #14940
Opened 2023-05-05 12:33 UTC by lolodomo

Related to #14818

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

2023-05-05 20:12 UTC, jlaur requested changes
Otherwise LGTM. I'll let @wborn have a look also.

2023-05-05 20:12 UTC, jlaur commented on bundles/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/sdm/api/PubSubAPI.java
> +    public void deleteServiceAndAccessToken() {
Perhaps to add some context:
```suggestion
    public void deleteOAuthServiceAndAccessToken() {
```

2023-05-05 21:10 UTC, lolodomo commented on bundles/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/sdm/api/PubSubAPI.java
> +    public void deleteServiceAndAccessToken() {
Method renamed

2023-05-05 21:23 UTC, jlaur approved these changes

2023-05-13 17:06 UTC, wborn approved these changes
LGTM!

2023-05-13 17:06 UTC, merged