[mercedesme] Remove the access token when the thing is removed
openhab/openhab-addons pull request #14942
Opened 2023-05-05 15:48 UTC by lolodomo

Related to #14818

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

2023-05-10 18:14 UTC, jlaur requested changes
Thanks! Only two minor suggestions. I'll let @weymann have a look also.

2023-05-10 18:14 UTC, jlaur commented on bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java
> +        }
```suggestion
        server.ifPresent(s -> s.deleteServiceAndAccessToken());
```

2023-05-10 23:30 UTC, lolodomo commented on bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/CallbackServer.java
> +    public void deleteServiceAndAccessToken() {
Renamed

2023-05-10 23:30 UTC, lolodomo commented on bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java
> +        }
Changed

2023-05-11 20:11 UTC, jlaur approved these changes

2023-05-15 21:20 UTC, weymann approved these changes
lgtm

2023-05-15 21:56 UTC, merged