[remoteopenhab] Use AbstractStorageBasedTypeProvider
openhab/openhab-addons pull request #14956
Opened 2023-05-08 22:24 UTC by lolodomo

Related to #14954

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

2023-05-11 08:29 UTC, lolodomo commented
Now tested and works well as expected using OH snapshot 3458.
Ready for review.

2023-05-11 12:32 UTC, lolodomo commented
I changed channel types ids, that is not a good idea, I will revert to the original ids.

2023-05-12 09:29 UTC, lolodomo commented
> I changed channel types ids, that is not a good idea, I will revert to the original ids.

Fixed.
Now ready again for a review.

2023-05-12 11:03 UTC, lolodomo commented
@J-N-K : can you please have a look ?

2023-05-12 11:45 UTC, J-N-K commented
I don't know much about the binding itself. Does it create a channel-type for each item or for each item-type?

2023-05-12 11:55 UTC, lolodomo commented
> I don't know much about the binding itself. Does it create a channel-type for each item or for each item-type?

For each remote item type having specific state description. That means you can have several for item type Number in case one remote item was read-only and another one was not.
All this is unchanged by this PR. The only change is to use the new storage.

2023-05-12 16:20 UTC, J-N-K requested changes
Otherwise looks good. I'm not sure some of the code ist most efficient, but I guess since new channel-types are only created on rare occasions (after the initial startup), it's fine.

2023-05-12 16:20 UTC, J-N-K commented on bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/RemoteopenhabChannelTypeProvider.java
> +    private final Pattern channelTypeIdPattern = Pattern.compile("^item([a-zA-Z]+)([0-9]+)$");
can be a `static` constant

2023-05-12 18:37 UTC, lolodomo commented on bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/RemoteopenhabChannelTypeProvider.java
> +    private final Pattern channelTypeIdPattern = Pattern.compile("^item([a-zA-Z]+)([0-9]+)$");
You're right.
Changed.

2023-05-12 18:41 UTC, J-N-K approved these changes

2023-05-12 18:51 UTC, merged