[evcc] Adjust to API changes & Add new channels for evcc 0.117.0
openhab/openhab-addons pull request #14983
Opened 2023-05-12 14:29 UTC by florian-h05

Fixes #14348.
Closes #14347.

- Removes `hasVehicle` channel because evcc removed it.
- Adjusts the API for evcc 0.117.0.
- Fixes `targetSoC` and `targetTime` channels not working.
- Adds the new `targetEnergy` channel.
- Makes the `batteryPrioritySoC` channel writable.
- Use new Java 17 features.

Thing type upgrade instructions are used, however I am not sure if I have them right, some feedback would be appreciated.

2023-05-12 14:31 UTC, florian-h05 commented on bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccHandler.java
Please note that most changed lines here are formatting due to the if statement.
Probably have a look at this in your IDE and not GitHub web.

2023-05-13 20:10 UTC, jlaur requested changes
Thanks! I've provided a few comments.

Perhaps it should be mentioned in the README that evcc version 0.117.0 (or higher) is required?

2023-05-13 20:10 UTC, jlaur commented on bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/update/thing-type-updates.xml
Update instructions are not needed since the binding creates the channels dynamically.

However, you need to implement removal of channel `hasVehicle` in the handler.

2023-05-13 20:10 UTC, jlaur commented on bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/thing/thing-types.xml
> +		<category>batterylevel</category>
```suggestion
		<category>BatteryLevel</category>
```

2023-05-13 20:10 UTC, jlaur commented on bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/thing/thing-types.xml
> +		<category>batterylevel</category>
```suggestion
		<category>BatteryLevel</category>
```

2023-05-13 20:10 UTC, jlaur commented on bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/i18n/evcc.properties
> +
This can be removed.

2023-05-13 20:12 UTC, jlaur commented on bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/update/thing-type-updates.xml
Additional feedback, in order for them to work (for statically defined channels), you would need to supply channel group id also, and the thing definition should contain this version property:
```xml
<property name="thingTypeVersion">1</property>
```

2023-05-14 15:24 UTC, florian-h05 commented on bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/update/thing-type-updates.xml
How to remove the `hasVehicle` channel in the handler?

2023-05-17 15:26 UTC, jlaur commented on bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/thing/thing-types.xml
> +		<category>batterylevel</category>
Please notice the capital L.

2023-05-17 15:26 UTC, jlaur commented on bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/thing/thing-types.xml
> +		<category>batterylevel</category>
Please notice the capital L.

2023-05-17 15:26 UTC, jlaur commented on bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/thing/thing-types.xml
> +		<category>batterylevel</category>
Please notice the capital L.

2023-05-17 15:31 UTC, jlaur commented on bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/update/thing-type-updates.xml
See for example:
https://github.com/openhab/openhab-addons/blob/353c154c1274b4a0da507bd184ae4f53d28628fe/bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java#L604-L650

2023-05-21 13:31 UTC, florian-h05 commented
@jlaur I addressed your review, please have another look!

2023-05-21 19:20 UTC, jlaur approved these changes
> I addressed your review, please have another look!

Excellent - thanks and LGTM!

2023-05-21 19:21 UTC, merged

2023-05-28 06:07 UTC, holgerfriedrich commented
@florian-h05 The new channels are missing on Crowdin... Would you care for the German translations?

2023-05-28 10:52 UTC, florian-h05 commented
I‘ve approved the translation proposals and added the missing ones, German translations are now complete!

2023-05-28 10:59 UTC, holgerfriedrich commented
Thanks, @florian-h05. I just created an issue for the other translations..... #15037