[opensprinkler] made http connection more resilient
openhab/openhab-addons pull request #14998
Opened 2023-05-16 10:08 UTC by wzbfyb

**Improvement**

-     connection timeout is now configurable
-     on connection timeout, retries are possible and configurable
-     retry delay is configurable

**Reason**
my OS has a flaky WiFi connection and sometimes goes offline due to timeouts.

2023-05-16 10:10 UTC, wzbfyb commented
sorry for the mess with multiple pull requests, I made a mistake when initially forking the code.

2023-05-20 07:11 UTC, Hilbrand reviewed
Also update the readme to include the new parameters.

2023-05-24 20:04 UTC, wzbfyb commented on bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV100.java
> +                        Thread.sleep(1000 * config.retryDelay);
Indeed. As it is not necessary to achieve the desired effect, I will just get rid of the delay. Working with appropriate timeouts should suffice.

2023-05-25 13:24 UTC, Hilbrand commented on bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/config/OpenSprinklerHttpInterfaceConfig.java
> +    public int retryDelay = 10;
The unused field `retryDelay` can be removed.

2023-05-25 13:25 UTC, Hilbrand commented on bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="timeout" type="integer">
I forgot to mention. But you can also add a unit to parameters.
```suggestion
			<parameter name="timeout" type="integer" unit="s">
```

2023-07-16 11:36 UTC, lolodomo commented
Was it finally ok for you @Hilbrand  ?

2023-10-17 14:01 UTC, jlaur commented
Gentle ping @Hilbrand 🙂

2023-10-19 21:10 UTC, lolodomo requested changes
Just one comment about i18n.

2023-10-19 21:10 UTC, lolodomo commented on bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="retry" type="integer">
Please update the i18n properties file to add these 2 new parameters.

2023-12-10 01:55 UTC, Skinah commented
Just in case the author @wzbfyb does not know how to do the last step to get this merged, please see the mvn command you need as well as other docs here:
https://www.openhab.org/docs/developer/utils/i18n.html#generating-i18n-properties-file

2023-12-10 10:42 UTC, wzbfyb commented
hi!

sorry, missed the notification. will take a look in the next days.
thanks a lot!



------ Originalnachricht ------
Von "Matthew Skinner" ***@***.***>
An "openhab/openhab-addons" ***@***.***>
Cc "wzbfyb" ***@***.***>; "Mention" 
***@***.***>
Datum 10.12.23, 02:55:32
Betreff Re: [openhab/openhab-addons] [opensprinkler] Make http 
connection more resilient (PR #14998)

>
>Just in case the author @wzbfyb <https://github.com/wzbfyb> does not 
>know how to do the last step to get this merged, please see the mvn 
>command you need as well as other docs here:
>https://www.openhab.org/docs/developer/utils/i18n.html#generating-i18n-properties-file
>
>—
>Reply to this email directly, view it on GitHub 
><https://github.com/openhab/openhab-addons/pull/14998#issuecomment-1848831699>, 
>or unsubscribe 
><https://github.com/notifications/unsubscribe-auth/ANT4DULDPQXUUGQXIBIE3VTYIUJBJAVCNFSM6AAAAAAYDNCR5SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNBYHAZTCNRZHE>.
>You are receiving this because you were mentioned.Message ID: 
>***@***.***>
>

2023-12-10 15:39 UTC, lolodomo commented on bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="retry" type="integer">
To do it simply, run: mvn i18n:generate-default-tramslations

2023-12-14 20:40 UTC, lolodomo commented on bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="retry" type="integer">
To accelerate process and merge this PR before OH 4.1 is released, I run the command myself and push the change.

2023-12-14 20:41 UTC, lolodomo approved these changes

2023-12-14 20:55 UTC, merged

2023-12-14 21:06 UTC, wzbfyb commented
Thanks a lot, highly appreciated.


------ Originalnachricht ------
Von "lolodomo" ***@***.***>
An "openhab/openhab-addons" ***@***.***>
Cc "wzbfyb" ***@***.***>; "Mention" 
***@***.***>
Datum 14.12.2023 21:55:24
Betreff Re: [openhab/openhab-addons] [opensprinkler] Make http 
connection more resilient (PR #14998)

>
>Merged #14998 <https://github.com/openhab/openhab-addons/pull/14998> 
>into main.
>
>—
>Reply to this email directly, view it on GitHub 
><https://github.com/openhab/openhab-addons/pull/14998#event-11252829391>, 
>or unsubscribe 
><https://github.com/notifications/unsubscribe-auth/ANT4DULBLO5WGPPMXZ3FBCLYJNRTZAVCNFSM6AAAAAAYDNCR5SVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRGI2TEOBSHEZTSMI>.
>You are receiving this because you were mentioned.Message ID: 
>***@***.***>
>