[onkyo] Support for more audio streams through the HTTP audio servlet
openhab/openhab-addons pull request #15117
Opened 2023-06-19 06:43 UTC by lolodomo

Related to #15113

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

2023-06-19 06:43 UTC, lolodomo commented
@dalgwen for information and feedback

2023-07-04 20:08 UTC, dalgwen commented
> @dalgwen for information and feedback

LGTM : the new capabilities are used as intended.

2023-07-05 06:17 UTC, lolodomo commented
Do we set the timeout for 5 or to 10 for more security ?

2023-07-07 11:33 UTC, lolodomo commented
By security, I finally set the timeout to 10s.

@kaikreuzer : this is ready for a final review.

2023-07-12 06:36 UTC, jlaur requested changes
Minor typo found.

2023-07-12 06:36 UTC, jlaur commented on bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoHandlerFactory.java
> +            OnkyoAudioSink audiSink = new OnkyoAudioSink(handler, audioHTTPServer, callbackUrl);
Variable name: audioSink

2023-07-12 07:02 UTC, lolodomo commented on bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoHandlerFactory.java
> +            OnkyoAudioSink audiSink = new OnkyoAudioSink(handler, audioHTTPServer, callbackUrl);
Fixed

2023-07-12 19:53 UTC, kaikreuzer approved these changes
lgtm, thanks!

2023-07-12 19:54 UTC, merged