[intesis] Add configurable polling intervall
openhab/openhab-addons pull request #15138
Opened 2023-06-26 10:09 UTC by hmerk

Signed-off-by: Hans-Jörg Merk [github@hmerk.de](mailto:github@hmerk.de)

2023-06-26 13:20 UTC, jlaur requested changes
Thanks. I have added some comments, but also have a concern that it doesn't work at all because of a typo: `thing-tyles.xml` defines parameters as "pollingInterval", but it's deserialized as "pollingInterval**l**".

2023-06-26 13:20 UTC, jlaur commented on bundles/org.openhab.binding.intesis/README.md
> +| pollingIntervall | Both                | Interval to retrieve updates from the connected devices        |
```suggestion
| pollingInterval  | Both                | Interval to retrieve updates from the connected devices        |
```

2023-06-26 13:20 UTC, jlaur commented on bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/config/IntesisBoxConfiguration.java
> +    public int pollingIntervall;
```suggestion
    public int pollingInterval = 45;
```

2023-06-26 13:20 UTC, jlaur commented on bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/config/IntesisHomeConfiguration.java
> +    public int pollingIntervall;
```suggestion
    public int pollingInterval = 30;
```

2023-06-26 13:20 UTC, jlaur commented on bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisBoxHandler.java
> +            pollingTask = scheduler.scheduleWithFixedDelay(this::polling, 3, config.pollingIntervall, TimeUnit.SECONDS);
```suggestion
            pollingTask = scheduler.scheduleWithFixedDelay(this::polling, 3, config.pollingInterval, TimeUnit.SECONDS);
```

2023-06-26 13:20 UTC, jlaur commented on bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisHomeHandler.java
> +        refreshJob = scheduler.scheduleWithFixedDelay(this::getAllUidValues, 0, config.pollingIntervall,
```suggestion
        refreshJob = scheduler.scheduleWithFixedDelay(this::getAllUidValues, 0, config.pollingInterval,
```

2023-06-26 13:20 UTC, jlaur commented on bundles/org.openhab.binding.intesis/src/main/resources/OH-INF/thing/thing-types.xml
> +					state of the connected devices. The minimum is 60
```suggestion
					state of the connected devices. The minimum is 30
```

2023-06-26 13:20 UTC, jlaur commented on bundles/org.openhab.binding.intesis/src/main/resources/OH-INF/thing/thing-types.xml
> +					Defines the time in seconds for openHAB to pull the
```suggestion
					Defines the time in seconds to pull the
```

2023-06-26 13:20 UTC, jlaur commented on bundles/org.openhab.binding.intesis/src/main/resources/OH-INF/thing/thing-types.xml
> +					state of the connected devices. The minimum is 60
```suggestion
					state of the connected devices. The minimum is 45
```

2023-06-26 13:20 UTC, jlaur commented on bundles/org.openhab.binding.intesis/src/main/resources/OH-INF/thing/thing-types.xml
> +					Defines the time in seconds for openHAB to pull the
```suggestion
					Defines the time in seconds to pull the
```

2023-07-02 13:29 UTC, hmerk commented
@jlaur Anything else ? All your suggestions have been committed.

2023-07-02 13:45 UTC, jlaur approved these changes
LGTM

2023-07-02 13:47 UTC, jlaur commented
> Anything else ? All your suggestions have been committed.

Sorry, I had missed your commits. Looks good now. 👍 Can you confirm it has been tested now, because I think it could not have worked with the initial commit?

2023-07-02 14:47 UTC, hmerk commented
Yes, tested and working.

2023-07-02 19:10 UTC, merged