[rrd4j] Improve event handling
openhab/openhab-addons pull request #15223
Opened 2023-07-11 16:10 UTC by J-N-K

Closes #15220

2023-07-11 16:12 UTC, J-N-K commented
@rkoshak Would you like to test that?

2023-07-12 06:42 UTC, lolodomo requested changes
The proposal looks good, I have just 2 comments.

2023-07-12 06:42 UTC, lolodomo commented on bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
> +        scheduler.schedule(() -> internalStore(name, value, null), 0, TimeUnit.SECONDS);
Please remove the line just before that set variable `now` that is no more used.

2023-07-12 06:42 UTC, lolodomo commented on bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
> -                }
Why is it no more needed ?

2023-07-12 18:04 UTC, J-N-K commented
I have done some further investigations. There is still an issue if a lot of events are created in a very short time (e.g. by a rule):

```
var item = items.getItem("Num");

for (var i=0; i<10; i++) {
  item.postUpdate(i);
}
```

There is a conceptual issue with that in core because `Item` is passed to the persistence service and updates that are faster than the event processing:

```
19:39:58.201 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Num' changed from 9.0 to 0
19:39:58.202 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Num' changed from 0 to 1
19:39:58.202 [DEBUG] [rd4j.internal.RRD4jPersistenceService] - Num (Type=NumberItem, State=4, Label=Num, Category=) 
19:39:58.202 [DEBUG] [rd4j.internal.RRD4jPersistenceService] - Num (Type=NumberItem, State=4, Label=Num, Category=) 
19:39:58.203 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Num' changed from 1 to 2
19:39:58.202 [DEBUG] [rd4j.internal.RRD4jPersistenceService] - Num (Type=NumberItem, State=5, Label=Num, Category=) 
19:39:58.202 [DEBUG] [rd4j.internal.RRD4jPersistenceService] - Num (Type=NumberItem, State=4, Label=Num, Category=) 
19:39:58.202 [DEBUG] [rd4j.internal.RRD4jPersistenceService] - Num (Type=NumberItem, State=4, Label=Num, Category=) 
19:39:58.203 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Num' changed from 2 to 3
19:39:58.203 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Num' changed from 3 to 4
19:39:58.204 [DEBUG] [rd4j.internal.RRD4jPersistenceService] - Num (Type=NumberItem, State=8, Label=Num, Category=) 
19:39:58.204 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Num' changed from 4 to 5
19:39:58.204 [DEBUG] [rd4j.internal.RRD4jPersistenceService] - Num (Type=NumberItem, State=8, Label=Num, Category=) 
19:39:58.204 [DEBUG] [rd4j.internal.RRD4jPersistenceService] - Num (Type=NumberItem, State=8, Label=Num, Category=) 
19:39:58.204 [DEBUG] [rd4j.internal.RRD4jPersistenceService] - Num (Type=NumberItem, State=8, Label=Num, Category=) 
19:39:58.204 [DEBUG] [rd4j.internal.RRD4jPersistenceService] - Num (Type=NumberItem, State=9, Label=Num, Category=) 
19:39:58.204 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Num' changed from 5 to 6
19:39:58.204 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Num' changed from 6 to 7
19:39:58.205 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Num' changed from 7 to 8
19:39:58.205 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Num' changed from 8 to 9
```

That aside: storing with `now+1` as timestamp will only help for the first "too fast" update, then we'll have the `last>now` issue again (because `last == now+1`). Increasing the timestamp until we find one that is possible feels also wrong, because that may result in very large offsets.

What would be the best case to handle that? "Replacing" the already stored value is not possible with RRD4J.

2023-07-12 19:23 UTC, kaikreuzer commented
> What would be the best case to handle that? "Replacing" the already stored value is not possible with RRD4J.

Maybe we could do something like a "delayed write" - i.e. keep the value in memory, wait for the next second and then write the latest then available update to the db (and discard any additional ones one might have received inbetween).

What I don't understand, though, is what is now different to before? We always had the situation that there are many more updates than rrd4j can persist and we had a solution for it in place - we should figure out how that worked and restore it to behave exactly the same way as before (in terms of what states get persisted with which timestamp).

2023-07-12 19:24 UTC, J-N-K commented
It worked because the persistence service blocked the event handler until it successfully wrote a datapoint.

2023-07-12 19:36 UTC, kaikreuzer commented
> blocked the event handler until it successfully wrote a datapoint.

This still didn't prevent new updates from occuring. So what happened with those? I'd assume that writing to the db didn't take a second, but new updates came in much faster?

2023-07-12 19:50 UTC, J-N-K commented
It just scheduled a new `store` with a timestamp one second later until it succeeds. This also messed up the order of the events but it didn't print warnings.

2023-07-12 20:01 UTC, kaikreuzer commented
so we essentially persisted all events and made sure there is always a second inbetween? But we persisted them in almost random order...? Ok, if that was the case, maybe we should not try to replicate exactly that behavior...

> we'll miss quickly changing on/off changes of a switch and the item may look unchanged in persistence also it did change in reality.

If something turns on for a fraction of a second only, we can anyhow not correctly persist this - if we extend it to being on for one second, it might be some wrong information already. With the same argument you could say you would want to see that something turned on 10 times within a second and we simply cannot do this. Imho, the most important thing is that the last persisted state is indeed the then valid one.

2023-07-12 20:10 UTC, J-N-K commented
Fine. I'll try to implement that.

2023-07-12 20:26 UTC, lolodomo commented
> Imho, the most important thing is that the last persisted state is indeed the then valid one.

I agree.

2023-07-12 21:38 UTC, rkoshak commented
I've been thinking on this most of the day and I come back and find a proposed solution. 🎉 

I think it's clear that rrd4j is simply unsuitable for rapidly changing data. We might consider adding a warning to that effect to the readme. If we cover the rapidly changing Switch with docs and make sure that the everyMinute batch doesn't cause problems I think that's as good as it gets for rrd4j.

2023-07-13 10:35 UTC, kaikreuzer commented
>  I come back and find a proposed solution. 🎉

I hope you can at least agree to that proposal as well!

2023-07-13 13:17 UTC, rkoshak commented
> I hope you can at least agree to that proposal as well!

Absolutely! It certainly makes a lot more sense than randomly saving the events like it was doing before or throwing warnings into the logs which for most end users are inexplicable and unclear how they can be handled.

When events are thrown away because a new one came in before it could be saved, it would be good I think to have a DEBUG level log statement explaining that's what's happening. I wouldn't want it to be WARN because it will freak out a bunch of end users over something most of them wouldn't notice in the first place. Couple that with adding the behavior to the docs and I think we are good.

2023-07-13 17:13 UTC, J-N-K commented
I think this should do it.

2023-07-13 19:53 UTC, kaikreuzer requested changes
Thank you - I've left a few small comments.

2023-07-13 19:53 UTC, kaikreuzer commented on bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
> +        storeJob = scheduler.scheduleWithFixedDelay(() -> doStore(false), 1, 1, TimeUnit.SECONDS);
Wouldn't this line better be placed in the activate() method behind `active = true`? Then there wouldn't be the need to set a 1 second delay either.

2023-07-13 19:53 UTC, kaikreuzer commented on bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
> +        storageMap.computeIfAbsent(now, t -> new ConcurrentHashMap<>()).put(name, value);
Would this be the right place to add debug logging as suggested by @rkoshak?

2023-07-13 19:53 UTC, kaikreuzer commented on bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
> +                return;
Could we run into trouble here once we have forecasts (or some other reason why we have a timestamp in the future) and this while loop runs in circles as the storageMap is not getting empty any time soon?

2023-07-13 20:09 UTC, kaikreuzer commented on bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
> +        storeJob = scheduler.scheduleWithFixedDelay(() -> doStore(false), 1, 1, TimeUnit.SECONDS);
Yes, that should work as well.

2023-07-13 20:09 UTC, kaikreuzer commented on bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
> +                return;
Ah, I somehow didn't consider the `return` here. Yeah, sure.

2023-07-13 20:10 UTC, kaikreuzer approved these changes
lgtm, thanks!

2023-07-13 20:11 UTC, merged