[sonnen] Fix wrong types. Energy should be Power
openhab/openhab-addons pull request #15384
Opened 2023-08-08 11:52 UTC by lochmueller

Also adapt the documentation and drop the batteryFeedIn in the documentation, which is not part of the binding.

Fix #15365 / https://github.com/openhab/openhab-addons/issues/15365

The binding define different things/channels in "Number:Energy" but these are regular "W" entries in the binding. So "Number:Power" is the right channel type. This fix should avoid the warnings in the log, that the binding try to put a "W" into the "Number:Energy" item: `Failed to update item 'Sonnen_Battery_Consumption' because '721 W' could not be converted to the item unit 'kWh'`

2023-08-08 12:07 UTC, chingon007 approved these changes
Ok, looks fine

2023-08-08 12:12 UTC, lochmueller commented
I added the "Signed-off-by"-thing to my commit. Sorry for the second round... is my first contribution to openHAB.

2023-08-08 13:20 UTC, lsiepel reviewed
LGTM

Only one comment, an upgrade instruction.xml could be added
https://www.openhab.org/docs/developer/bindings/thing-xml.html#updating-thing-types

2023-08-08 21:29 UTC, jlaur requested changes
Thanks for the fix!

As @lsiepel mentioned, update instructions are needed to fix the channel item types for managed things.

See the linked documentation, and perhaps a similar example in #15002.

2023-08-09 12:02 UTC, lochmueller commented
I added the instructions. I hope "targetVersion" => 2 is the right one? Regards, Tim

2023-08-09 12:20 UTC, jlaur commented
> I added the instructions. I hope "targetVersion" => 2 is the right one?

It seems right, but you also need to update it here:
https://github.com/openhab/openhab-addons/blob/3b9b0236b46436ce0d91bf95b153eb300f2f3f47/bundles/org.openhab.binding.sonnen/src/main/resources/OH-INF/thing/thing-types.xml#L35

It would be really nice if you could give it a test run in order to avoid regressions. You would need to create a managed Thing with the version prior to your changes. Then uninstall the binding and drop your JAR into the addons directory. The item type for those channels should then automatically change to `Number:Power` for your existing Thing.

2023-08-09 14:04 UTC, lsiepel approved these changes
LGTM
I leave the rest to the addons maintainers.

2023-08-10 06:22 UTC, chingon007 approved these changes

2023-08-12 09:43 UTC, jlaur commented
> It would be really nice if you could give it a test run in order to avoid regressions.

Just to be clear: Everything looks fine, I was only waiting for a confirmation of successful migration test. Let me know, and we can merge this PR. 🙂

2023-11-03 20:16 UTC, lolodomo commented
@jlaur : I assume noone wants to test the migration ! So maybe you can merge if you think the code looks fine.

2023-11-03 20:29 UTC, merged

2023-11-03 20:30 UTC, jlaur commented
> I assume noone wants to test the migration ! So maybe you can merge if you think the code looks fine.

All right, let's give it a wider audience. Fingers crossed. 🙂

2023-11-06 10:45 UTC, chingon007 commented
I tested it. It works. The change is indeed correct. Please merge