systeminfo: use DataAmount for dataSent and dataReceived in the example
openhab/openhab-addons pull request #15495
Opened 2023-08-24 19:58 UTC by dilyanpalauzov

as the text above does suggest so.

JSScripting: reword.

2023-08-24 20:15 UTC, jlaur commented
Regression of #13804

2023-08-24 20:18 UTC, jlaur requested changes
Thanks for correcting the example!

2023-08-24 20:18 UTC, jlaur commented on bundles/org.openhab.automation.jsscripting/README.md
I believe this should be changed in the [openhab-js repository](https://github.com/openhab/openhab-js) as otherwise it will be overwritten. @florian-h05, please correct me if I'm wrong.

2023-08-25 07:16 UTC, lolodomo commented
Please note there are other wrong number definition in the README documentation. 
I did not yet take the time to propose a doc fix. We should check the full example.

2023-09-03 20:21 UTC, florian-h05 commented on bundles/org.openhab.automation.jsscripting/README.md
Yes, there already is a PR for that.

2023-09-03 20:21 UTC, florian-h05 commented on bundles/org.openhab.automation.jsscripting/README.md
I would prefer to get those JS Scripting changes out of this PR.

2023-09-06 06:01 UTC, lolodomo approved these changes
LGTM

2023-09-06 06:01 UTC, lolodomo commented
Let's merge this fix even if other channels have to fixed in the full example.

2023-09-06 06:01 UTC, merged