Nanoleaf ipv6 address doc
openhab/openhab-addons pull request #15612
Opened 2023-09-17 10:56 UTC by stefan-hoehn

Add IPV6 note on discovery as mentioned in https://community.openhab.org/t/nanoleaf-binding-may-fail-when-upgrading-to-the-latest-nanoleaf-firmware-because-of-ipv6/148152

2023-09-17 20:14 UTC, kaikreuzer requested changes

2023-09-17 20:14 UTC, kaikreuzer commented on bundles/org.openhab.binding.nanoleaf/README.md
> +**Important note on the topic of IPV6 ip addresses:**
```suggestion
**Important note on the topic of IPv6 addresses:**
```

2023-09-17 20:14 UTC, kaikreuzer commented on bundles/org.openhab.binding.nanoleaf/README.md
> +Since at least firmware 8.5.2 panels may start to go offline and online.
```suggestion
With firmware version 8.5.2 or newer, panels may change between being OFFLINE and ONLINE. 
```

2023-09-17 20:14 UTC, kaikreuzer commented on bundles/org.openhab.binding.nanoleaf/README.md
> +After some investigation it turned down that the devices are discovered as IPV6 devices which then cannot be used correctly within the binding to run the API requests to the devices.
```suggestion
This is due to the fact that if they are discovered with IPv6 addresses, the binding is not able to correctly send API requests to the devices.
```

2023-09-17 20:14 UTC, kaikreuzer commented on bundles/org.openhab.binding.nanoleaf/README.md
> +For the time being it is therefore recommended, if this is an option for you, to disable IPV6 on the openhab server.
```suggestion
It is therefore recommended to disable IPv6 on the openHAB server. 
```

2023-09-17 20:14 UTC, kaikreuzer commented on bundles/org.openhab.binding.nanoleaf/README.md
> +For example this can be achieved on openhabian with the following
```suggestion
This can e.g. be achieved on openHABian the following way:
```

2023-09-17 20:14 UTC, kaikreuzer commented on bundles/org.openhab.binding.nanoleaf/README.md
> +then reboot.
```suggestion
Reboot your server after the change.
```

2023-09-23 13:34 UTC, stefan-hoehn commented
@kaikreuzer Thanks, you recommendations are much appreciated. Do you by chance know any other binding that has similar IPv6 issues and has this ever been addressed?

2023-10-01 19:50 UTC, kaikreuzer approved these changes
Thank you!

2023-10-01 19:51 UTC, merged

2023-10-01 19:52 UTC, kaikreuzer commented
> Do you by chance know any other binding that has similar IPv6 issues and has this ever been addressed?

No, I haven't come across this yet...