[mongodb]: fix quantity type storage, introduce new types
openhab/openhab-addons pull request #15617
Opened 2023-09-18 13:10 UTC by konradzawadka

To reproduce the issue:

```
Number:Temperature      supplyTemperature                                                             <temperature>    (gTemperature, gAir)       ["Point","Temperature"]    {channel="modbus:data:localhostTCP:temperature:supplyTemperature:number"}
```

Then value stored in mongodb is:
7.3 °C

Should be:
7.3

Following fix improve storage and also refactor other whole conversion based on InfluxDB implementation.

2023-09-26 18:13 UTC, konradzawadka commented
@jlaur do you see chance for fix, is the fix valid?

2023-10-07 22:03 UTC, jlaur requested changes
Thanks for your contribution, and welcome as a contributor. 🙂

I have provided some initial feedback. Unfortunately I don't know anything about MongoDB, and I'm a bit hesitant to introduce major changes in persistence services, especially those I'm not familiar with.

In the linked community thread you mention that "7.3 °C" is stored rather than "7.3". Can you show the schema for a `Number:Dimension` item, and also explain why you would rather store it without unit? If "7.3 °C" is stored, what will happen when unit is changed to °F to the item and the values are queried? Will values (or could it) be converted into the new configured unit, or what will actually happen?

How are migrations and backwards compatibility handled with this PR, i.e. users already having stored "7.3 °C" and now going forward storing values without unit?

2024-05-10 18:54 UTC, lsiepel commented
Gentle ping @konradzawadka can you proceed with this PR, by fixing the conflicts and addressing the comments?

2024-10-11 14:06 UTC, lsiepel commented
I guess this PR is related to https://github.com/openhab/openhab-core/issues/1954 Woudl be nice if we can proceed with this. Another ping @konradzawadka do you need anything to proceed?

2024-10-26 11:46 UTC, lsiepel commented
Also a ping to @marciseli @boomer41 and @ulbi who contributed to this persistence service in the past. Hopefully they can test, confirm, or assist in any way to get this PR finished.

2024-10-26 13:38 UTC, ulbi commented
@lsiepel Thanks for the ping - I think I've adressed this along with other challenges in #16333 - I recommend to reject this PR, since it does not fit to the current driver code anymore.

2024-10-26 14:45 UTC, lsiepel commented
Mainly superseded by https://github.com/openhab/openhab-addons/pull/16333

if there is anything left to fix @konradzawadka feel free to open a new PR or issue

2024-10-26 14:45 UTC, closed without merging