[knx] Bugfix problem with DPT 251.600
openhab/openhab-addons pull request #15723
Opened 2023-10-08 18:56 UTC by genesis81

In the old implementation the datatype was implemented with byte 0-255. 
The DPT 251.600 is defined with 0-100%, change this from byte to PercentType.

2023-10-08 19:05 UTC, J-N-K commented
Technically this is correct. The question is what actual problem occurs with the current implementation, because this change is breaking and I can't see any real issue with using 0-255.

2023-10-08 19:18 UTC, genesis81 commented
When i try to send a new color to the bus i have always an error out of range. 

See my detailed description in this threat: #https://community.openhab.org/t/rgbw-color-out-of-range-dpt-251-600/150055

2023-10-09 19:01 UTC, genesis81 commented
> Technically this is correct. The question is what actual problem occurs with the current implementation, because this change is breaking and I can't see any real issue with using 0-255.

I have checked the code again. I don't see that the change is breaking, actual we have a bug. When you send a value over 100 calimero reject the request. That means all value over 100 is not working and will not send to the knx bus.

2023-10-09 19:03 UTC, J-N-K commented
Correct, I misread the change. I would suggest a minor change though, to get higher accuracy.

2023-10-09 19:08 UTC, genesis81 commented
> Correct, I misread the change. I would suggest a minor change though, to get higher accuracy.

I'm complete open for any suggest, please tell me what we can optimize.

2023-10-09 19:09 UTC, holgerfriedrich commented
@J-N-K @genesis81 Give me some time, just trying to get a proper test which includes the Calimero part. Until now we have only tests for ValueEncoder decode/encode. With a custom KNXNetworkLink implementation, we should see everything down to the KNX frame level including the coding done in Calimero.

2023-10-09 19:09 UTC, J-N-K requested changes

2023-10-09 19:09 UTC, J-N-K commented on bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
> +                return String.format("%d %d %d - %%", rgbw[0].intValue(), rgbw[1].intValue(), rgbw[2].intValue());
```suggestion
                return String.format("%,.1f %,.1f %,.1f - %%", rgbw[0].doubleValue(), rgbw[1].doubleValue(), rgbw[2].doubleValue());
```

2023-10-09 19:11 UTC, J-N-K commented
@holgerfriedrich Really nice. I think this can be fixed anyway, I check in calimero code that a float in the range from 0 to 100 is expected here.

2023-10-09 19:22 UTC, J-N-K approved these changes
LGTM, @holgerfriedrich do you agree?

2023-10-09 19:22 UTC, J-N-K commented
I think you need to apply spotless

2023-10-09 19:44 UTC, J-N-K commented
Test failures are independent, I also see them in my local builds without any changes.

2023-10-09 19:44 UTC, J-N-K approved these changes

2023-10-09 20:21 UTC, genesis81 commented
> Test failures are independent, I also see them in my local builds without any changes.

Looks like changes in the core system that break the tests.

2023-10-09 20:23 UTC, J-N-K commented
I already commented in the PR that includes the cause of these problems.

2023-10-09 22:02 UTC, holgerfriedrich approved these changes
LGTM, thanks for providing this bugfix!

Just for reference: openhab/openhab-core#3834 (core change currently breaking CI test) and #15727 (WIP new tests)

2023-10-10 07:58 UTC, merged