- [romyrobot][WIP] Initial contribution
openhab/openhab-addons pull request #15738
Opened 2023-10-11 12:07 UTC by xeniter

2023-12-23 09:37 UTC, wborn commented on bundles/org.openhab.binding.romyrobot/pom.xml
> +    <version>4.1.0-SNAPSHOT</version>
```suggestion
    <version>4.2.0-SNAPSHOT</version>
```

2023-12-29 17:02 UTC, lsiepel requested changes
As it is a WIP, i had a very quick scan and did not do an extensive review. 

Just as a reminder; also run the i18n pluging, write the readme contents and adjust all the loggers to the right level if even needed to log at all.

2024-05-25 12:46 UTC, lolodomo commented
I added the tag "work in progress" as "WIP" is still in the PR title.
Let us know when this is no more "work in progress".

2024-10-02 18:28 UTC, lsiepel commented
Gentle ping @xeniter we are about to reach the one year marker without any change to this PR. Really hope you are ok and are able to continue work on this. Please let me know if you want to proceed with this PR. Eventually it might be closed due to inactivty.

2024-12-05 20:05 UTC, lsiepel commented
Closing due to inactivty. The code is not lost, just no longer directly visible from this repository. If someone decides to continue, please do. Me or another maintainer will be happy to review it as long as there is progress.

2024-12-05 20:05 UTC, closed without merging