[wemo] adapt to core StringUtils
openhab/openhab-addons pull request #15789
Opened 2023-10-20 18:25 UTC by lsiepel

some code deduplication now that there are some stringutils available in core.

From reading the code i think this is a drop in replacement, but the method was written totally different then elsewhere and wemo has some strange response formatting, so i would prefer that some one tests this change before merging:

Test jar: 4.1.0: https://1drv.ms/u/s!AnMcxmvEeupwjt0LqK17SvhP7E4vLA?e=wtze2p

2023-10-20 19:28 UTC, hmerk approved these changes
Thanks @lsiepel !
LGTM from my side. 
Unfortunately I cannot test your changes due to no longer using Wemo devices.

2023-10-20 22:16 UTC, jlaur requested changes
Unfortunately the core implementation is not a plug-in replacement for the method you are trying to replace here.

2023-10-20 22:16 UTC, jlaur commented on bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoUtil.java
> -    }
This method cannot be replaced by https://github.com/openhab/openhab-core/blob/14f8490d1cf67bcfce9d6b12e8997fb433317a03/bundles/org.openhab.core/src/main/java/org/openhab/core/util/StringUtils.java#L288-L310. Please check implementation.

2023-10-21 11:04 UTC, lsiepel commented
As there is enough reason to keep it as is, let’s close this.

2023-10-21 11:04 UTC, closed without merging

2023-10-21 11:06 UTC, jlaur commented
> As there is enough reason to keep it as is, let’s close this.

You could still remove the unused method, but other than that I agree we have to keep the current implementation for unescapeXml.