[Freeboxos] npe when updating inactive Player
openhab/openhab-addons pull request #15813
Opened 2023-10-27 13:01 UTC by clinique

It can happen (when using webhooks) that a poll is sent when the player is not reachable.
This leads to an npe : 

```
2023-10-27 08:35:00.680 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.IllegalArgumentException: path is null
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.doPath(UriBuilderImpl.java:549) ~[?:?]
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.path(UriBuilderImpl.java:544) ~[?:?]
	at org.openhab.binding.freeboxos.internal.api.rest.RestManager.buildUri(RestManager.java:59) ~[?:?]
	at org.openhab.binding.freeboxos.internal.api.rest.RestManager.get(RestManager.java:73) ~[?:?]
	at org.openhab.binding.freeboxos.internal.api.rest.RestManager.getSingle(RestManager.java:77) ~[?:?]
	at org.openhab.binding.freeboxos.internal.api.rest.PlayerManager.getPlayerStatus(PlayerManager.java:214) ~[?:?]
	at org.openhab.binding.freeboxos.internal.handler.ActivePlayerHandler.internalPoll(ActivePlayerHandler.java:71) ~[?:?]
	at org.openhab.binding.freeboxos.internal.handler.ApiConsumerHandler.handleCommand(ApiConsumerHandler.java:150) ~[?:?]
	at org.openhab.binding.freeboxos.internal.api.rest.WebSocketManager.lambda$1(WebSocketManager.java:112) ~[?:?]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
	at org.openhab.binding.freeboxos.internal.api.rest.WebSocketManager.lambda$0(WebSocketManager.java:112) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]

```

2023-10-29 17:50 UTC, lsiepel approved these changes
LGTM

2023-11-03 17:41 UTC, lolodomo requested changes

2023-11-03 17:41 UTC, lolodomo commented on bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ActivePlayerHandler.java
> +                updateStatus(ThingStatus.OFFLINE);
It seems to be already done at line 74

2023-11-04 09:20 UTC, lolodomo requested changes

2023-11-04 09:20 UTC, lolodomo commented on bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ActivePlayerHandler.java
> -import org.slf4j.Logger;
Import to be restored

2023-11-04 09:22 UTC, clinique commented on bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ActivePlayerHandler.java
> +                updateStatus(ThingStatus.OFFLINE);
Yes, you're correct

2023-11-04 09:22 UTC, clinique commented on bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ActivePlayerHandler.java
> -import org.slf4j.Logger;
Done

2023-11-04 09:28 UTC, lolodomo approved these changes
LGTM, thank you

2023-11-04 09:28 UTC, merged