[mqtt] Interpet incoming NaN as UNDEF for NumberValues
openhab/openhab-addons pull request #15897
Opened 2023-11-14 15:26 UTC by ccutrer

Since DecimalType and QuantityType don't support NaN, but when you're linking to a topic that the device is using floating point, NaN might happen.

2023-11-27 18:23 UTC, ccutrer commented
@antroids: this is actually coming from a Home Assistant compatible device (ESPHome)

2023-12-04 09:37 UTC, antroids requested changes

2023-12-04 09:37 UTC, antroids commented on bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
> +        if (config.postCommand && newState instanceof Command newCommand) {
`/**
     * If true, the channel state is not updated on a new message.
     * Instead a postCommand() call is performed.
     */
    public boolean postCommand = false;`

`<description>If the received MQTT value should not only update the state of linked items, but command them, enable
				this option.</description>`

By this contract the channel state should not be updated when postCommand is true.

UPDATE: probably field's commentary should be updated.

2023-12-10 10:01 UTC, lolodomo approved these changes
LGTM, thank you

2023-12-10 10:01 UTC, merged