[grundfosaphareader] Initial contribution
openhab/openhab-addons pull request #15907
Opened 2023-11-18 13:19 UTC by tisoft

This adds support for reading out the data of Grundfos Alpha Pumps with a Grundfos Alpha Reader (https://product-selection.grundfos.com/de/products/alpha-reader/mi401-alpha-reader-98916967?pumpsystemid=2213476387&tab=variant-specifications)

2023-11-18 13:23 UTC, tisoft commented
I had to disable the default filtering of duplicate data in blue, otherwise I could not get the data of the alpha reader. I only used blue on my development laptop, in my production environment I use a bluegiga dongle. That worked out of the box, so the configuration for the blue and bluegiga environment are different by default. The commit in this PR makes the blue implementation behave the same as the bluegiga implementation regarding duplicate data.

2023-11-18 15:12 UTC, jlaur requested changes
Thanks a lot for your contribution! It looks very good. I have added a few initial comments.

Do you know if the protocol for Grundfos Alpha Reader is similar to the one for Grundfos Alpha3, i.e. pumps with built-in Bluetooth support? I have an Alpha3 and would love to help testing and contributing if this could be supported as well. I already did a backport of your binding to 4.0.x to see if might communicate with my pump through BlueZ (Raspberry Pi 3), but unfortunately without success.

In order to be extensible in the future, I would already propose to rename to GrundfosAlpha, i.e. drop "Reader". If Alpha3 support could be added, this could then be a new thing type within the same binding.

I believe the binding id might need to be `org.openhab.binding.bluetooth.grundfosalpha` (i.e. with a bluetooth prefix), but I will need to get back to that to be sure.

Can you also add I18N properties? See https://www.openhab.org/docs/developer/utils/i18n.html#generating-i18n-properties-file.

There are a few compiler warnings and checkstyle warnings to address. You could take a look at target/code-analysis/report.html.

2023-11-18 15:12 UTC, jlaur commented on bundles/org.openhab.binding.grundfosalphareader/src/main/resources/OH-INF/thing/thing-types.xml
> +	<channel-type id="grundfos_flow">
Please adapt according to [naming convention](https://www.openhab.org/docs/developer/guidelines.html#naming-convention).
```suggestion
	<channel-type id="grundfos-flow">
```

2023-11-18 15:12 UTC, jlaur commented on bundles/org.openhab.binding.grundfosalphareader/src/main/resources/OH-INF/thing/thing-types.xml
> +	<channel-type id="grundfos_head">
Please adapt according to [naming convention](https://www.openhab.org/docs/developer/guidelines.html#naming-convention).
```suggestion
	<channel-type id="grundfos-head">
```

2023-11-18 15:12 UTC, jlaur commented on bundles/org.openhab.binding.grundfosalphareader/src/main/resources/OH-INF/thing/thing-types.xml
> +	<channel-type id="grundfos_temperature">
Please adapt according to [naming convention](https://www.openhab.org/docs/developer/guidelines.html#naming-convention).
```suggestion
	<channel-type id="grundfos-temperature">
```

2023-11-18 15:12 UTC, jlaur commented on bundles/org.openhab.binding.grundfosalphareader/src/main/resources/OH-INF/thing/thing-types.xml
> +		<description>Current Pump Temperature</description>
```suggestion
		<description>Current pump temperature</description>
```

2023-11-18 15:12 UTC, jlaur commented on bundles/org.openhab.binding.grundfosalphareader/src/main/resources/OH-INF/thing/thing-types.xml
> +		<description>An Grundfos Alpha Reader MI401</description>
```suggestion
		<description>A Grundfos Alpha Reader MI401</description>
```

2023-11-18 15:12 UTC, jlaur commented on bundles/org.openhab.binding.grundfosalphareader/src/main/resources/OH-INF/thing/thing-types.xml
> +			<channel id="flowRate" typeId="grundfos_flow"/>
Please adapt according to [naming convention](https://www.openhab.org/docs/developer/guidelines.html#naming-convention).
```suggestion
			<channel id="flow-rate" typeId="grundfos-flow"/>
```

2023-11-18 15:12 UTC, jlaur commented on bundles/org.openhab.binding.grundfosalphareader/src/main/resources/OH-INF/thing/thing-types.xml
> +			<channel id="pumpHead" typeId="grundfos_head"/>
Please adapt according to [naming convention](https://www.openhab.org/docs/developer/guidelines.html#naming-convention).
```suggestion
			<channel id="pump-head" typeId="grundfos-head"/>
```

2023-11-18 15:12 UTC, jlaur commented on bundles/org.openhab.binding.grundfosalphareader/src/main/resources/OH-INF/thing/thing-types.xml
> +			<channel id="pumpTemperature" typeId="grundfos_temperature"/>
Please adapt according to [naming convention](https://www.openhab.org/docs/developer/guidelines.html#naming-convention).
```suggestion
			<channel id="pump-temperature" typeId="grundfos-temperature"/>
```

2023-11-18 15:12 UTC, jlaur commented on bundles/org.openhab.binding.grundfosalphareader/src/main/resources/OH-INF/thing/thing-types.xml
> +			<channel id="batteryLevel" typeId="system.battery-level"/>
Please adapt according to [naming convention](https://www.openhab.org/docs/developer/guidelines.html#naming-convention).
```suggestion
			<channel id="battery-level" typeId="system.battery-level"/>
```

2023-11-18 15:12 UTC, jlaur commented on bundles/org.openhab.binding.grundfosalphareader/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="address" type="text">
Perhaps it should be renamed to `macAddress` for clarity?

2023-11-18 19:26 UTC, tisoft commented
Thanks for the review, I will work on your issues.

Regarding Grundfos Alpha 3:
Support should be possible, since it does use the same BLE implementation. It might use a slightly different protocol. I can't check that myself since I don't have one.
Have you tried the official app from Grundfos to check if that can read out the values?
- https://apps.apple.com/de/app/grundfos-go-balance-pump-tool/id1007147002
- https://play.google.com/store/apps/details?id=com.grundfos.go.balance&hl=de&gl=US

When that works, you could try to dump the bluetooth messages with:

1.	sudo hcitool lescan --duplicate > /dev/null &
2.	sudo hcidump --raw hci

And send me some of the messages, so that I can compare them to mine.

2023-11-18 20:16 UTC, tisoft commented on bundles/org.openhab.binding.grundfosalphareader/README.md
> +_*.sitemap examples are optional._
Will add an example as soon as everything else is finalized. :)

2023-11-18 21:39 UTC, jlaur commented
> Support should be possible, since it does use the same BLE implementation.

That sounds promising! Just to be clear, support for Alpha3 can be added in another PR as it's clearly out of scope for this one. But I'm very much interested in finally getting my pump online. 😄

> It might use a slightly different protocol. I can't check that myself since I don't have one. Have you tried the official app from Grundfos to check if that can read out the values?

I can read a lot of data with Grundfos Go Remote:
https://play.google.com/store/apps/details?id=com.grundfos.go

> * https://play.google.com/store/apps/details?id=com.grundfos.go.balance&hl=de&gl=US

I tried to install this one, but already at first step it seemed like it would start some major calibration, so didn't dare to go further.

> When that works, you could try to dump the bluetooth messages with:
> 
> 1. sudo hcitool lescan --duplicate > /dev/null &
> 2. sudo hcidump --raw hci
> 
> And send me some of the messages, so that I can compare them to mine.

Thanks. I've sent some messages by private mail.

Perhaps this might also be helpful, I had a brief look at that when previously collecting messages and trying to figure them out:
https://github.com/esphome/esphome/tree/dev/esphome/components/alpha3

2023-11-19 11:02 UTC, tisoft commented
I have renamed/moved the add-on to org.openhab.binding.bluetooth.grundfosalpha.

Could you help me with the following warnings? What do I have to do to fix them?

[WARNING] OH-INF.thing.thing-types.xml:[0]
Missing the supported bridge with id roaming
[WARNING] OH-INF.thing.thing-types.xml:[0]
Missing the supported bridge with id bluegiga
[WARNING] OH-INF.thing.thing-types.xml:[0]
Missing the supported bridge with id bluez

I had a quick look on your Alpha3 logs and I think they can be supported.

2023-11-19 19:22 UTC, jlaur requested changes
Not much found on second pass, only some minor comments.

2023-11-19 19:22 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/README.md
> +| batteryLevel    | Number:Percent            | R          | The battery level of the reader    |
Renamed to:
```suggestion
| flow-rate         | Number:VolumetricFlowRate | R          | The flow rate of the pump          |
| pump-head        | Number:Length             | R          | The water head above the pump      |
| pump-temperature | Number:Temperature        | R          | The temperature of the pump        |
| battery-level    | Number:Percent            | R          | The battery level of the reader    |
```

2023-11-19 19:22 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaReaderHandlerFactory.java
> +@Component(configurationPid = "binding.grundfosalphareader", service = ThingHandlerFactory.class)
```suggestion
@Component(configurationPid = "binding.bluetooth.grundfosalpha", service = ThingHandlerFactory.class)
```

2023-11-19 19:22 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/resources/OH-INF/addon/addon.xml
I'm not sure if this is needed anymore when adopted as a Bluetooth extension. It looks like the other bindings do not have it.

2023-11-19 19:22 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/resources/OH-INF/addon/addon.xml
> +	<description>This is the binding for GrundfosAlpha.</description>
```suggestion
	<description>This is the binding for Grundfos Alpha circulator pumps.</description>
```

2023-11-19 19:22 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/resources/OH-INF/thing/thing-types.xml
> +		<description>Current Head</description>
```suggestion
		<description>Current head</description>
```

2023-11-19 19:22 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/resources/OH-INF/thing/thing-types.xml
> +		<category>flow</category>
We usually provide them with first letter in uppercase:
```suggestion
		<category>Flow</category>
```

2023-11-19 19:22 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/resources/OH-INF/thing/thing-types.xml
> +		<category>water</category>
```suggestion
		<category>Water</category>
```

2023-11-19 19:22 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/resources/OH-INF/thing/thing-types.xml
> +		<category>temperature</category>
You could also provide semantic tags here:
```suggestion
		<category>Temperature</category>
		<tags>
			<tag>Measurement</tag>
			<tag>Temperature</tag>
		</tags>
```

2023-11-19 19:22 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/resources/OH-INF/thing/thing-types.xml
> +		<category>pump</category>
```suggestion
		<category>Pump</category>
```

2023-11-19 19:22 UTC, jlaur commented on bundles/pom.xml
> +    <module>org.openhab.binding.bluetooth.grundfosalpha</module>
One down for alphabetizing. 🙂

2023-11-19 19:22 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaReaderHandlerFactory.java
This file should probably be renamed to `GrundfosAlphaHandlerFactory`.

2023-11-19 19:22 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaReaderBindingConstants.java
This file should probably be renamed to `GrundfosAlphaBindingConstants`.

2023-11-19 19:22 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaReaderDiscoveryParticipant.java
This file should probably be renamed to `GrundfosAlphaDiscoveryParticipant`.

2023-11-19 19:22 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaReaderDiscoveryParticipant.java
> + * This discovery participant is able to recognize enoceanble devices and create discovery results for them.
```suggestion
 * This discovery participant is able to recognize Grundfos Alpha devices and create discovery results for them.
```

2023-11-19 19:25 UTC, jlaur commented
> I have renamed/moved the add-on to org.openhab.binding.bluetooth.grundfosalpha.

Great!

> Could you help me with the following warnings? What do I have to do to fix them?
> 
> [WARNING] OH-INF.thing.thing-types.xml:[0] Missing the supported bridge with id roaming [WARNING] OH-INF.thing.thing-types.xml:[0] Missing the supported bridge with id bluegiga [WARNING] OH-INF.thing.thing-types.xml:[0] Missing the supported bridge with id bluez

Sure, I will have a look.

> I had a quick look on your Alpha3 logs and I think they can be supported.

That would be awesome, let me know how I can help. 🙂

2023-11-19 19:27 UTC, jlaur commented
> > [WARNING] OH-INF.thing.thing-types.xml:[0] Missing the supported bridge with id roaming [WARNING] OH-INF.thing.thing-types.xml:[0] Missing the supported bridge with id bluegiga [WARNING] OH-INF.thing.thing-types.xml:[0] Missing the supported bridge with id bluez
> 
> Sure, I will have a look.

I think you are missing these in the thing type definition:
```xml
		<supported-bridge-type-refs>
			<bridge-type-ref id="roaming"/>
			<bridge-type-ref id="bluegiga"/>
			<bridge-type-ref id="bluez"/>
		</supported-bridge-type-refs>
```

2023-11-30 13:29 UTC, jlaur commented
@tisoft - just in case you missed them, there are still a few small comments to resolve. We can merge right after that. :)

2023-11-30 13:55 UTC, tisoft commented
Yeah I know. Was a bit busy with work the last days. Will get back to this as soon as possible.

2023-12-03 20:35 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaDiscoveryParticipant.java
> +        return Collections.singleton(GrundfosAlphaBindingConstants.THING_TYPE_MI401);
```suggestion
        return Set.of(GrundfosAlphaBindingConstants.THING_TYPE_MI401);
```

2023-12-03 20:38 UTC, jlaur commented on bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/resources/OH-INF/i18n/grundfosalpha.properties
> +
This should probably be removed after the removal of the addon.xml file. If you then regenerate this file (see
https://www.openhab.org/docs/developer/utils/i18n.html#generating-i18n-properties-file), the changed text for `channel-type.grundfosalpha.grundfos-head.description` below should also be updated.

2023-12-03 20:40 UTC, jlaur commented on bundles/org.openhab.binding.grundfosalphareader/README.md
> +_*.sitemap examples are optional._
Besides two minor comments I've just added, everything else now seems finalized. 🙂

2023-12-04 10:10 UTC, merged

2023-12-05 14:51 UTC, jlaur commented
@kaikreuzer - can you add @tisoft as contributor so we will be automatically assigned as code reviewer for the new Grundfos Alpha binding? 🙂

2023-12-05 15:05 UTC, kaikreuzer commented
Sure, done!