[roku] Improve exception handling for failed http connections
openhab/openhab-addons pull request #15932
Opened 2023-11-20 01:34 UTC by mlobstein

Improve handling of http exceptions. If the http GET request to the roku device fails, xml parsing will now be skipped.

2023-11-20 17:00 UTC, jlaur requested changes
Thanks for the fix! Only a few minor comments.

2023-11-20 17:00 UTC, jlaur commented on bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/communication/RokuCommunicator.java
> +            throw new RokuHttpException("Error executing POST command, URL: " + url + e.getMessage());
Also worth checking while refactoring this anyway: Restore the interrupted state of the thread by calling `Thread.currentThread().interrupt()`, see https://rules.sonarsource.com/java/RSPEC-2142/

2023-11-20 22:39 UTC, mlobstein commented
> Thanks for the fix! Only a few minor comments.

Comments have been addressed, Happy Thanksgiving!
I give thanks to you and all the maintainers for the innumerable reviews!

2023-11-21 07:36 UTC, jlaur approved these changes
LGTM. Will let @morph166955 have a look also.

2023-11-26 20:22 UTC, jlaur commented
@morph166955 - would you like to have a look before merging?

2023-11-27 01:05 UTC, morph166955 commented
Sorry I've been out of town for the holiday here.  I haven't had a chance to sit and go through anything in about a week now.

2023-11-28 23:36 UTC, morph166955 commented
LGTM!

2023-11-29 00:18 UTC, morph166955 approved these changes

2023-11-29 07:12 UTC, merged