[rustpotterks] Fix for Windows, avoid load library multiple times
openhab/openhab-addons pull request #15945
Opened 2023-11-22 18:36 UTC by GiviMAD

Hello, 
I would like to merge these minor fix as a user from the forum has let me know that the library fails on windows after the first run.

This commit is not need in the main branch because the new library version already fixes this.

Best regards!

2023-11-22 19:13 UTC, GiviMAD commented
Hello, I'm having some problems with spotlight in files I've not touch, any idea? thank you for the help.

2023-11-25 11:08 UTC, lolodomo requested changes

2023-11-25 11:08 UTC, lolodomo commented on bundles/org.openhab.voice.rustpotterks/src/main/java/org/openhab/voice/rustpotterks/internal/RustpotterKSService.java
> +    private static boolean libraryLoaded;
Please remove "static".

2023-11-25 11:34 UTC, lolodomo approved these changes
LGTM, thank you

2023-11-25 11:41 UTC, lolodomo commented
Please rebase your branch, it looks like you have an "invalid" pom.xml file in your branch (badly formatted).

2023-11-25 12:48 UTC, GiviMAD commented
When I run rebase it told me my branch is is up to date with 4.0.x.

If I run spotless:apply in the root of my folder it changes all the pom.xml files in the project on the first line.
It added a break line at the begging of each project tag.
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><project ...
```
Is it because I created my branch from the 4.0.x branch? I did it like that because the code was already different on main and the issue doesn't exist there.

2023-11-25 13:17 UTC, lolodomo commented
> Is it because I created my branch from the 4.0.x branch? I did it like that because the code was already different on main and the issue doesn't exist there.

I did not take about that ! Normally we should avoid merging in 4.0.x directly.
Is your fix really critical ?

@jlaur: an advice how to proceed ?

2023-11-25 13:27 UTC, GiviMAD commented
> Is your fix really critical ?

No, it prevents using it on windows and no one has complain until now, and it's already fixed on 4.1.0 because of the library update. And the person how wrote me about it is going to test it in the milestone instead, so I can just close it.

2023-11-25 13:38 UTC, jlaur approved these changes
Thanks!

2023-11-25 13:39 UTC, jlaur commented
> @jlaur: an advice how to proceed ?

We can accept PR's targeting a patch branch directly when cherry-picking is impossible - for example due to conflicts, or like in this case irrelevancy because of other factors.

2023-11-25 13:40 UTC, merged

2023-11-25 13:49 UTC, GiviMAD commented
Thank you for the review!