[mqtt.homeassistant] handle multiple availability topics
openhab/openhab-addons pull request #15977
Opened 2023-11-29 22:24 UTC by ccutrer

2023-12-04 16:40 UTC, ccutrer commented on bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
> +    private AtomicBoolean latestAvailability = new AtomicBoolean(false);
https://www.home-assistant.io/integrations/mqtt/#using-availability-topics (unroll the "Platform specific availability settings"; or it's also documented on the page for each component). Tl;dr: any component can have multiple availability topics (zigbee2mqtt uses one topic for zigbee2mqtt itself that it sets a LWT on, and one topic per device it manages, proxying the known state of the device). But it allows `all` (all topics must show available), `any` (any of the topics must show available), or `last` (use the status of the most recently published message on any of the topics). `all` and `any` are easy - we already did `all`; `any` was simply tabulating a slight different way; but to implement `last` I had to add this additional field to keep track of it.

2023-12-04 16:51 UTC, antroids commented on bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
> +    private AtomicBoolean latestAvailability = new AtomicBoolean(false);
Sorry, I didn't clarified. I'm about the `latestAvailability` field usage. Can see only one `latestAvailability.set(online);`. Probably should be used to calculate thing status.

2023-12-04 16:56 UTC, ccutrer commented on bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
> +    private AtomicBoolean latestAvailability = new AtomicBoolean(false);
🤦 . You're right. I started with this field, then ended up just passing a boolean to calculateThingStatus instead of reading the field. Removed.

2023-12-05 10:12 UTC, antroids requested changes

2023-12-05 16:26 UTC, antroids approved these changes
LGTM, 
Thank you!

2023-12-07 12:28 UTC, lolodomo requested changes
Just 2 ultra minor comments

2023-12-07 12:28 UTC, lolodomo commented on bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AvailabilityTracker.java
> +         * online
Very minor: please avoid the return to new line

2023-12-07 12:28 UTC, lolodomo commented on bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AvailabilityTracker.java
> +         * availability
Very minor: please avoid the return to new line

2023-12-07 19:21 UTC, lolodomo approved these changes
LGTM

2023-12-07 19:22 UTC, merged