[systeminfo] Add CPU frequency channels
openhab/openhab-addons pull request #16012
Opened 2023-12-06 16:53 UTC by mherwege

Resolves https://github.com/openhab/openhab-addons/issues/15844
Resolves https://github.com/openhab/openhab-addons/issues/15608

This PR adds CPU frequency (clock speed) channels to the binding, exposing underlying functionality from the OSHI library. Note that the availability of this information may vary by platform. In my tests on Windows, I could not get reliable information. It did work well on an RPi 4.

It also solves some documentation issues.

2023-12-06 17:31 UTC, mherwege commented
Build failed because of the integration tests that had minimal change. The failure was also not only in the added tests.
Is this a symptom of https://github.com/openhab/openhab-addons/issues/13524?

2024-01-16 16:19 UTC, J-N-K commented
Why is the thing handler initialization failing?

2024-01-16 16:49 UTC, mherwege commented
I am not entirely sure. The next line in the test (assertion on the thing handler) times out whereby the thing handler is null. That would indicate the thing handler initalization is not even running. However, running it through a debugger, the handler factory is called and the handler creation is called from there.
If you want to try, the last commit in this PR removes the update instructions again. But you could roll back that commit to test with update instructions.

2024-01-17 08:11 UTC, J-N-K commented
Just add `.withProperties(Map.of("thingTypeVersion", "1"))` to the thing builder to prevent updates. The other solution is to get the thing from the registry and before checking it has a handler. The thing changes during the upgrade, so the "original" thing is never initialized and never gets a handler.

2024-01-17 09:19 UTC, mherwege commented
DCO failure is because the revert commit was not signed off. If that is an issue, I can squash that with the original to solve it.

2024-03-15 11:46 UTC, lolodomo requested changes
Only an ultra minor comment

2024-03-15 11:46 UTC, lolodomo commented on bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoBindingConstants.java
> +     * Maximum frequency of the CPU
Please fix the description

2024-03-17 14:17 UTC, mherwege commented on bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoBindingConstants.java
> +     * Maximum frequency of the CPU
done

2024-03-17 15:11 UTC, lolodomo approved these changes
LGTM, thank you

2024-03-17 15:28 UTC, mherwege commented
Build is now failing and I don't understand why. I rebased but it didn't help. The last commit is only a javadoc change, so cannot have an impact.

I have the impression there are other addon PR's suddenly failing the build.

I also have a failed local build.

2024-03-18 10:15 UTC, lolodomo commented
Build was aborted after 240 minutes.
I try again.
I don't know if you have to rebase your branch or not after the Karaf changes of yesterday (my local builds are no more building today without a rebase).

2024-03-18 10:57 UTC, lolodomo commented
Build finally succeeded.

2024-03-18 10:58 UTC, merged

2024-03-18 12:59 UTC, jlaur commented
> I don't know if you have to rebase your branch or not after the Karaf changes of yesterday (my local builds are no more building today without a rebase).

This is not necessary. The PR build is performed on the PR branch merged with target branch.