[mqtt.homeassistant] Improve support for Lock component
openhab/openhab-addons pull request #16052
Opened 2023-12-11 20:01 UTC by ccutrer

* handle state and command payloads differing (as they do by default)
 * expose full state possibilities and OPEN command by adding a TextValue channel

2023-12-18 10:08 UTC, antroids approved these changes
LGTM, 
Thank you!

2024-01-01 18:59 UTC, kaikreuzer requested changes

2024-01-01 18:59 UTC, kaikreuzer commented on bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/TextValue.java
> +     *            will be allowed.
```suggestion
     *            values will be allowed.
```

2024-01-01 18:59 UTC, kaikreuzer commented on bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/TextValue.java
> +        s = Stream.of(commands).filter(not(String::isBlank)).collect(Collectors.toSet());
Maybe better call this variable `c` or even `commands`?

2024-01-01 18:59 UTC, kaikreuzer commented on bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/TextValue.java
> +            this.commands = this.states;
Not all states are always automatically allowed commands. If no commands are provided, why not simply leave the commands empty here?

2024-01-01 18:59 UTC, kaikreuzer commented on bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/TextValue.java
> +     *            will be allowed.
Maybe also mention that it is assumed that all states are also valid commands and that if this is not the case the other constructor should be used.

2024-01-02 18:59 UTC, kaikreuzer approved these changes
lgtm, thanks!

2024-01-02 18:59 UTC, ccutrer commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Lock.java
> +        lockValue = new OnOffValue(new String[] { channelConfiguration.stateLocked },
I could see an argument that UNLOCKING should be considered locked for this binary channel, but for now I took the conservative approach that anything that's not locked should be considered unlocked.

2024-01-02 19:02 UTC, merged