[influxdb] Add compatibility with InfluxDB Cloud Serverless
openhab/openhab-addons pull request #16151
Opened 2023-12-30 18:06 UTC by PLeusmann

Update influx client to 4.3.0 and use ping endpoint to check for database availability. Fixes https://github.com/openhab/openhab-addons/issues/16147

Chose not to go to newest client version since this will resolve to some vulnerabilities in the dependency tree according to maven central (https://mvnrepository.com/artifact/com.squareup.retrofit2/adapter-rxjava3/2.9.0)

Did not run all tests since they seem to require some running influx instances and i could not find information on how to setup those. 

Resulting jar: [org.openhab.persistence.influxdb-4.2.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab-addons/files/13798883/org.openhab.persistence.influxdb-4.2.0-SNAPSHOT.jar.zip)

2024-01-02 09:12 UTC, J-N-K requested changes
Otherwise LGTM, what do you mean by "did not run all tests"?

2024-01-02 09:12 UTC, J-N-K commented on bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java
> +                logger.warn(
If it's "normal", it should only be logged at DEBUG level.

2024-01-02 15:24 UTC, PLeusmann commented
> Otherwise LGTM, what do you mean by "did not run all tests"?

Probably I misinterpreted. Test runs raise a lot of stack traces such as `[main] WARN  o.o.p.i.i.i.InfluxDB1RepositoryImpl - database error: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8086`. I guessed there are some integration tests requiring influxdb-instances. This seems not to be the case. 

Tests still seem to pass, though.

2024-01-14 11:18 UTC, PLeusmann commented
@J-N-K I made the changes you requested.

2024-01-17 20:04 UTC, J-N-K approved these changes
LGTM

2024-01-17 20:05 UTC, merged