[myenergi] Initial contribution
openhab/openhab-addons pull request #16225
Opened 2024-01-06 23:53 UTC by renescherer

# myenergi Binding

This binding supports a number of devices provided by the company [myenergi](https://www.myenergi.com/). They include the Zappi car charger (EVSE), the Eddi solar diverter and the Harvi remote sensor for CT clamps.

- [myenergi] Initial contribution to support Zappi, Eddi and Harvi devices

# Description

Although this is the first official PR for this binding, it has been in the market place for a while for 3.x openHAB systems and has been used, tested and extended by various contributors.

Details about the binding can be found in the [market place](https://community.openhab.org/t/myenergi-myenergi-binding/139667)

# Testing

The latest build can be found in the market place here: https://community.openhab.org/t/myenergi-myenergi-binding/139667

2024-01-08 21:13 UTC, lsiepel commented
The issue [described here](https://github.com/openhab/openhab-addons/issues/12251), is that fixed?

2024-01-08 22:14 UTC, renescherer commented
Yes, volkmarnissen had provided a PR for my branch last year. There aren't any open issues at the moment.

8 Jan 2024 21:13:46 lsiepel ***@***.***>:

> 
> The issue described here[https://github.com/openhab/openhab-addons/issues/12251], is that fixed?
> 
> —
> Reply to this email directly, view it on GitHub[https://github.com/openhab/openhab-addons/pull/16225#issuecomment-1881830341], or unsubscribe[https://github.com/notifications/unsubscribe-auth/ACTKZ6H4JYLW4EHFEVHF3SLYNROPXAVCNFSM6AAAAABBP4IG2OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOBRHAZTAMZUGE].
> You are receiving this because you authored the thread.
> [Tracking image][https://github.com/notifications/beacon/ACTKZ6F35763Z4DPG24LFNDYNROPXA5CNFSM6AAAAABBP4IG2OWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTQFJZ4K.gif]
>

2024-04-27 20:39 UTC, lsiepel commented
Looking into some PR's and this is some interesting binding. Checked  6 files or so. And it showed that some channel id's are not following the naming convention described here: https://www.openhab.org/docs/developer/guidelines.html#naming-convention

You might also do some self-review to speed up the proces: https://github.com/openhab/openhab-addons/wiki/Review-Checklist

2024-05-20 21:10 UTC, lsiepel requested changes
Not sure if you have seen the previous comment. Would be nice if you can fix the naming convention first before i do a full review.

2024-05-26 10:01 UTC, jlaur commented on bom/openhab-addons/pom.xml
> +    <dependency>
This should be in alphabetic order.

2024-07-09 18:29 UTC, wborn commented on bundles/org.openhab.binding.myenergi/pom.xml
> +    <version>4.2.0-SNAPSHOT</version>
```suggestion
    <version>4.3.0-SNAPSHOT</version>
```

2024-09-09 19:55 UTC, lsiepel commented
Ping @renescherer 
As there has been some time without any updated / commits to this PR. Do you think you will be able to finish this or did you abandon this PR? At some time we will close this PR due to inactivity.

Or let me know if you need anything to finish this.

2025-02-20 19:34 UTC, lsiepel commented
After a year without any updates or comments I close this PR. It is not lost, you will still be able to work on it at your own branch. Feel free to re-open once you can move this PR forward.

2025-02-20 19:34 UTC, closed without merging