[shelly] Check for local interface IP for DHCP timeout
openhab/openhab-addons pull request #16306
Opened 2024-01-19 18:22 UTC by markus7017

The binding checks now the local ip to be != 169.254.x.x, which is the result of a failed DHCP assignment. The framework reports this in the list of interfaces and the binding had send this to the device as part of the callback url, which resulted in device functioning in general, but the binding is not receiving any events. Now the user sees a WARNING is the log, which is a clear indicator of a setup to be fixed.

2024-01-21 12:00 UTC, lsiepel requested changes
Minor comments.

2024-01-21 12:11 UTC, lsiepel commented on bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
> +            logger.warn("{}: An invalid local ip address {} was detected, check system and openHAB network settings",
As the thing state is allready set, there is no need to log a warn message.

2024-01-27 12:49 UTC, markus7017 commented on bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
> +            setThingOffline(ThingStatusDetail.CONFIGURATION_ERROR, "config-status.error.network-config");
changed

2024-01-27 12:49 UTC, markus7017 commented
@lsiepel requested changes applied

2024-01-27 12:50 UTC, markus7017 commented on bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
> +message.config-status.error.network-config = Invalid system / openHAB network configuration was detected.
changed

2024-01-27 20:58 UTC, lsiepel approved these changes
Thanks, LGTM

2024-01-27 20:58 UTC, merged