[modbus.studer] Some little markdown and grammar corrections
openhab/openhab-addons pull request #16324
Opened 2024-01-24 14:25 UTC by thopiekar

Nothing extra special, but some corrections to the docs.

2024-01-24 19:52 UTC, lsiepel requested changes
Two very minor details.

2024-01-24 19:52 UTC, lsiepel commented on bundles/org.openhab.binding.modbus.studer/README.md
> +| bsp            | For BSP that offers a highly precise measuring for Xtender, VarioTrack and VarioString systems                        | ![BSP](doc/bsp.png)                 |
```suggestion
| bsp            | For BSP that offers a highly precise measuring for Xtender, VarioTrack and VarioString systems                       | ![BSP](doc/bsp.png)                 |
```

2024-01-24 19:52 UTC, lsiepel commented on bundles/org.openhab.binding.modbus.studer/README.md
> +Studer Innotec, founded in 1987 by Roland Studer, is an ISO-certified company that develops and manufactures inverters, inverter/chargers and MPPT solar charge controllers to communicate over the Mod
```suggestion
Studer Innotec, founded in 1987 by Roland Studer, is an ISO-certified company that develops and manufactures inverters, inverter/chargers and MPPT solar charge controllers to communicate over the Modbus protocol entirely in Switzerland.
```

2024-01-24 21:48 UTC, giovannimirulla approved these changes
Thanks for your review @lsiepel

2024-01-24 22:30 UTC, lsiepel commented
> Thanks for your review @lsiepel and @thopiekar

@giovannimirulla  marked both comments as resolved, but I see no commit from @thopiekar

2024-02-01 07:11 UTC, lsiepel approved these changes
LGTM

2024-02-01 07:12 UTC, merged