[mongodb] Upgrade DB driver, add more type handlings, fix QuanitityType handling
openhab/openhab-addons pull request #16333
Opened 2024-01-28 16:05 UTC by ulbi

# [mongodb] Upgrade DB driver, add more type handlings, fix QuanitityType handling

# Description

This pull request addresses issues #16308 and #16310, introducing significant updates and improvements to the system:

## PR Classification
- **Improvement**: Updates the MongoDB driver for enhanced compatibility and adds comprehensive unit testing.
- **Bugfix**: Fixes handling for various item types, ensuring consistent behavior across different MongoDB versions.

## Goals and Motivation
The main objective is to modernize the MongoDB driver used within our system from the outdated `mongo-java-driver 2.13.1` (2015) to the current `mongo-driver-sync 4.11.1`. This upgrade not only extends support to MongoDB versions 3.6 through 6.0 but also addresses compatibility issues with MongoDB 5.0 and above, which is no longer adequately supported by the old driver.

## Noteworthy Changes for End Users
- **Database Driver Upgrade**: Transition to `mongo-driver-sync 4.11.1`, enhancing support for MongoDB versions 3.6 to 6.0 and ensuring better system performance and reliability.
- **Enhanced Item Support**: Improved handling for `NumberItem` with `QuantityTypes` and added support for `ColorItem`, `LocationItem`, `ImageItem`, `PlayerItem`, and `CallItem`, along with their respective state types, enhancing the system's versatility and user experience.

## Unit Testing Enhancements
- Added unit tests to validate type storage and querying, ensuring robustness and reliability.
- Expanded testing to cover all supported MongoDB versions (3.6, 4.4, 5.0, 6.0), guaranteeing compatibility across different database versions.

## Technical Improvements
- For consistency with InfluxDB and compatibility with charting tools like Grafana, `QuantityType` handling now stores only the number without the unit. This adjustment allows for more seamless integration with external tools that may not support string-based data types.

## Documentation and Guidelines
- Updated documentation to reflect these changes, ensuring users and developers can easily understand and adopt the new features and improvements.

2024-01-28 16:13 UTC, J-N-K reviewed
Regarding the change: I fear that all stored quantity-type will be  lost, is that correct? Do we have a chance to convert them or a "compatibilty mode" for accessing them?

2024-01-28 16:13 UTC, J-N-K commented on bundles/org.openhab.persistence.mongodb/pom.xml
> +    </dependency>
I don't think you need this one.

2024-01-28 16:13 UTC, J-N-K commented on bundles/org.openhab.persistence.mongodb/pom.xml
> +    </dependency>
These should be available from core

2024-01-28 16:15 UTC, ulbi commented
@J-N-K @jlaur just created this PR to address a couple of challenges with the current mongodb driver. I created this as draft in the first place, since I plan two more things:

1. add code to also handle the data stored by the current mongodb persistence as fas as possible e.g. QuantityType (currently stored as string, but not restored properly) and all other where "toString" provides the full context (ColorItem, LocationItem, ...) - this will not work for ImageItem, since a toString of RawType does not store everything
2. add exception handling to catch wrong data from the database
3. add exception handling if the ImageItem or anything else tries to store more than 16 MB (document size limit from MongoDB)
4. store the Unit for QuantityType if provided in a separate field and then restore it from there.
5. Address your comments ;-)

Once done, this should cover a couple of issues.

2024-01-28 16:17 UTC, ulbi commented
> Regarding the change: I fear that all stored quantity-type will be lost, is that correct? Do we have a chance to convert them or a "compatibilty mode" for accessing them?

You are too fast! I will add something for this as well, just wanted to create the PR already, since there are quite some changes already. And just figured out, that the online build environment does not contain docker, so all tests using "Testcontainers" do fail - too bad, this is a great way to verify the different mongodb versions.

2024-02-08 18:50 UTC, ulbi commented
@J-N-K Just a quick question, anything else required to get this merged? I'm asking because the changes required for #16338 are ready as well, should I put it in the PR as well?

2024-02-10 09:19 UTC, lsiepel commented
> @J-N-K Just a quick question, anything else required to get this merged? I'm asking because the changes required for #16338 are ready as well, should I put it in the PR as well?

As I don’t expect many users to test this persistence prior to stable. Maybe good to integrate it and get some mileage on both changes.

2024-02-10 10:03 UTC, J-N-K requested changes

2024-02-10 10:03 UTC, J-N-K commented on bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBTypeConversions.java
> +        }
```suggestion
        return switch (operator) {
            case EQ ->"$eq";
            case GT -> "$gt";
            case GTE -> "$gte";
            case LT -> "$lt";
            case LTE -> "$lte";
            case NEQ -> "$neq";
            default -> null;
        };
```

2024-02-10 10:03 UTC, J-N-K commented on bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceServiceTest.java
> +public class MongoDBPersistenceServiceTest {
```suggestion
@NonNullByDefault
public class MongoDBPersistenceServiceTest {
```

2024-02-10 10:03 UTC, J-N-K commented on bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/DatabaseTestContainer.java
> +public class DatabaseTestContainer {
```suggestion
@NonNullByDefault
public class DatabaseTestContainer {
```

2024-02-10 10:03 UTC, J-N-K commented on bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/DataCreationHelper.java
> +public class DataCreationHelper {
```suggestion
@NonNullByDefault
public class DataCreationHelper {
```

2024-02-10 10:03 UTC, J-N-K commented on bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBTypeConversions.java
> +public class MongoDBTypeConversions {
```suggestion
@NonNullByDefault
public class MongoDBTypeConversions {
```

2024-02-10 10:03 UTC, J-N-K commented on bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/SetupResult.java
> +public class SetupResult {
```suggestion
@NonNullByDefault
public class SetupResult {
```

2024-02-10 10:03 UTC, J-N-K commented on bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/VerificationHelper.java
> +public class VerificationHelper {
```suggestion
@NonNullByDefault
public class VerificationHelper {
```

2024-02-10 11:48 UTC, ulbi commented
@lsiepel Can do it, this will fix a couple of the requested changes as well, since I fixed most of the compiler warnings in there. Will just put it in here with the changes requested by @J-N-K .

2024-02-10 15:00 UTC, ulbi commented on bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBTypeConversions.java
> +            }
Done it. In order to increase readability I also move the inlinemethods to single private methods. This seems to be better

2024-02-10 16:37 UTC, ulbi commented
@J-N-K @lsiepel I should have covered all comments and added the enhancement for #16338 as well.

2024-02-17 09:57 UTC, J-N-K approved these changes
Thanks!

2024-02-17 09:58 UTC, merged