[Jellyfin] Overhaul README.md
openhab/openhab-addons pull request #16359
Opened 2024-02-03 14:59 UTC by felixschndr

# Overhaul Jellyfin README

Just some simple changes to the README
- Fix some typos
- Add some code brackets
- Some formatting changes

2024-02-03 19:28 UTC, jlaur requested changes
Thanks for improving the documentation. Only some minor corrections from proof-reading (please note English is not my first language, so I can also have made mistakes).

2024-02-03 19:28 UTC, jlaur commented on bundles/org.openhab.binding.jellyfin/README.md
> +## Known limitations
```suggestion
## Known Limitations
```

2024-02-03 19:28 UTC, jlaur commented on bundles/org.openhab.binding.jellyfin/README.md
> +This binding was tested against the android tv, and web clients.
```suggestion
This binding was tested against Android TV and web clients.
```

I think?

2024-02-03 19:28 UTC, jlaur commented on bundles/org.openhab.binding.jellyfin/README.md
> +The only problem that were found is that the channels `play-next-by-terms` and `play-last-by-terms` don't work currently on the android tv client.
```suggestion
The only problem that was found is that the channels `play-next-by-terms` and `play-last-by-terms` don't currently work on the Android TV client.
```

2024-02-03 19:28 UTC, jlaur commented on bundles/org.openhab.binding.jellyfin/README.md
> +Before open an issue please test you are able to correctly control your device from the Jellyfin web ui to identify whetter is an issue on the client itself.
```suggestion
Before opening an issue, please test that you are able to correctly control your device from the Jellyfin web UI to identify whether it's an issue on client side.
```

2024-02-03 19:28 UTC, jlaur commented on bundles/org.openhab.binding.jellyfin/README.md
> +It is recommended creating the clients using the discovery. For getting the device ids manually it is possible to use the Jellyfin web interface with the web inspector and look for the request that i
```suggestion
It is recommended to create the clients using the discovery.
For getting the device ids manually, it is possible to use the Jellyfin web interface with the web inspector and look for the request that is launched when you click the cast button (`<jellyfin url>/Sessions?ControllableByUserId=XXXXXXXXXXXX`).
```

2024-02-07 21:21 UTC, felixschndr commented
@jlaur thanks for the review. Indeed some sentences don't sounds particularly good. I just removed the `I` phrases from the README without any rewriting. 

I will take a closer look at this on the weekend

2024-02-10 12:09 UTC, felixschndr commented
@jlaur I checked the whole README again and found some typos, wrong grammar, etc. Did some overhauling, what do you think?

2024-02-10 14:44 UTC, jlaur requested changes
Thanks for the additional updates. I have added a few more minor comments.

2024-02-10 14:44 UTC, jlaur commented on bundles/org.openhab.binding.jellyfin/README.md
> +To discover clients, you must first configure a server (bridge). After that, device discovery will detect controllable clients.
```suggestion
To discover clients, you must first configure a server (bridge).
After that, device discovery will detect controllable clients.
```

2024-02-10 14:44 UTC, jlaur commented on bundles/org.openhab.binding.jellyfin/README.md
> +The default behavior is to search for movies, series or episodes whose name starts with the given text, if it finds results the bind will proceed as said before.
```suggestion
The default behavior is to search for movies, series or episodes whose name starts with the given text.
If it finds results, the bind will proceed as said before.
```

2024-02-11 12:24 UTC, felixschndr commented
I corrected the changes you requested. Some newlines you requested (like [this](https://github.com/openhab/openhab-addons/pull/16359#discussion_r1485144803)) are too much (in my opinion) so I left them as is.

2024-02-12 08:28 UTC, jlaur commented
> I corrected the changes you requested. Some newlines you requested (like [this](https://github.com/openhab/openhab-addons/pull/16359#discussion_r1485144803)) are too much (in my opinion) so I left them as is.

Thanks! What do you mean by "too much"? I should have mentioned that one sentence per line is preferred because it will make it easier to view diffs. It doesn't impact rendering.

2024-03-22 13:22 UTC, felixschndr commented
Looks good now @jlaur?

2024-03-22 13:36 UTC, jlaur approved these changes
LGTM

2024-03-22 13:37 UTC, merged