limit power compressor flags for water and heating
openhab/openhab-addons pull request #16446
Opened 2024-02-22 16:08 UTC by troem

# Limit power for heatpump
Addition of 4 new channels for limiting the power of the heatpump
Percent Water Power limit Min
Percent Water Power limit Max
Percent Heating Power limit Min
Percent Heating Power limit Min

2024-02-22 19:47 UTC, lsiepel requested changes
Left some comments. Please also provide Thing upgrade instructions: https://www.openhab.org/docs/developer/bindings/thing-xml.html#updating-thing-types

2024-02-22 19:47 UTC, lsiepel commented on bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/i18n/ecotouch_de.properties
> +channel-type.ecotouch.percent_water_limit_min.description = Warmwasser Leistungsbegrenzung Min Ausgang
Please revert changes to this file, translations should be made by crowdin.

2024-02-22 19:47 UTC, lsiepel commented on bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/i18n/ecotouch.properties
>  channel-type.ecotouch.temperature_water_set2.description = Temperature Water Setpoint BMS
New labels are midding to this file, can you re-run the i18n plugin?

2024-02-22 19:47 UTC, lsiepel commented on bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/thing/thing-types.xml
> +		<label>Percent Water limit min</label>
Please adjust label to 2-3 words, < 23 characters. and capitalized.

2024-02-22 19:47 UTC, lsiepel commented on bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/thing/thing-types.xml
> +		<label>Percent Water limit max</label>
Please adjust label to 2-3 words, < 23 characters. and capitalized.

2024-02-22 19:47 UTC, lsiepel commented on bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/thing/thing-types.xml
> +		<label>Percent Heating limit min</label>
Please adjust label to 2-3 words, < 23 characters. and capitalized.

2024-02-22 19:47 UTC, lsiepel commented on bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/thing/thing-types.xml
> +		<label>Percent Heating limit max</label>
Please adjust label to 2-3 words, < 23 characters. and capitalized.

2024-02-27 14:17 UTC, troem commented
> Left some comments. Please also provide Thing upgrade instructions: https://www.openhab.org/docs/developer/bindings/thing-xml.html#updating-thing-types
> 
> Edit: it also needs spotless and the commits needs to be signed off.

OK - thank you for all your comments - I tried to do all my homework now and followed your instructions. This is my very first pull request and I am sorry heaving not read all documents carefully enough. Thank you for your time!

2024-03-02 10:50 UTC, lsiepel requested changes
Some final comments.

After the labels have been adjusted also run the i18n plugin again to generate the properties file. 

Regarding the thing-type instructions one last bit is missing.  Add this to both Thing's. Doc here: https://www.openhab.org/docs/developer/bindings/thing-xml.html#updating-thing-types
```
<properties>
    <property name="thingTypeVersion">1</property>
  </properties>
```

2024-03-02 10:50 UTC, lsiepel commented on bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/thing/thing-types.xml
> +		<label>Water Powerlimit min</label>
```suggestion
		<label>Water Powerlimit Min</label>
```

2024-03-02 10:50 UTC, lsiepel commented on bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/thing/thing-types.xml
> +		<label>Water Powerlimit max</label>
```suggestion
		<label>Water Powerlimit Max</label>
```

2024-03-02 10:50 UTC, lsiepel commented on bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/thing/thing-types.xml
> +		<label>Heating Powerlimit min</label>
```suggestion
		<label>Heating Powerlimit Min</label>
```

2024-03-02 10:50 UTC, lsiepel commented on bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/thing/thing-types.xml
> +		<label>Heating Powerlimit max</label>
```suggestion
		<label>Heating Powerlimit Max</label>
```

2024-03-04 16:39 UTC, troem commented
> Some final comments.
> 
> After the labels have been adjusted also run the i18n plugin again to generate the properties file.
> 
> Regarding the thing-type instructions one last bit is missing. Add this to both Thing's. Doc here: https://www.openhab.org/docs/developer/bindings/thing-xml.html#updating-thing-types
> 
> ```
> <properties>
>     <property name="thingTypeVersion">1</property>
>   </properties>
> ```



> Some final comments.
> 
> After the labels have been adjusted also run the i18n plugin again to generate the properties file.
> 
> Regarding the thing-type instructions one last bit is missing. Add this to both Thing's. Doc here: https://www.openhab.org/docs/developer/bindings/thing-xml.html#updating-thing-types
> 
> ```
> <properties>
>     <property name="thingTypeVersion">1</property>
>   </properties>
> ```

Done with cf01ee5514154d08ba1afd193800dac0bbe9d9eb 
Thank you for your review

2024-03-04 17:39 UTC, lsiepel commented
Did you close this on purpose?

2024-03-04 17:46 UTC, troem commented
> Did you close this on purpose?

So I thought I did all my homework, obviously I created a mess, I am sorry. I saw the "Closed with unmerged commits" but I did not find a way to merge / to solve this situation ... could you give me a hint, please?

2024-03-04 17:57 UTC, lsiepel approved these changes
Thanks, LGTM

2024-03-04 17:58 UTC, merged