[intesis] Session Handling improved
openhab/openhab-addons pull request #16555
Opened 2024-03-21 20:19 UTC by fd0cwp

I have changed the login process so that the binding now only logs in at the beginning and logs out at the end of the lifetime. If a request fails due to a missing login or an invalid session ID, a new login attempt is made.

This ensures that
- Several requests can be sent in direct succession (if I switch the air conditioning from cooling to heating, I also want to change the slats at the same time)
- Less traffic is generated as there is not a constant logout and login again
- Ideally, the login credentials should only be visible once at startup

Last change: login and logout is now running asynchronously in a scheduled task (#16476).

This change fixes #15502. 

Signed-off-by: Christoph <fd0cwp@gmx.de>

2024-03-21 20:20 UTC, fd0cwp commented
@jlaur, @lsiepel: next try 🙄

2024-03-21 20:30 UTC, jlaur requested changes
Thanks. One small comment when reviewing this again in its entirety. Otherwise LGTM.

2024-03-21 20:30 UTC, jlaur commented on bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisHomeHandler.java
> +        logger.trace("logout() - session ID: {}", sessionId);
Last thing - if `sessionId.isEmpty()` it will not make sense to try to log out.

2024-03-24 20:48 UTC, fd0cwp commented
I don't get it with fixing PR change requests. :-(

2024-03-24 20:48 UTC, closed without merging