[openwebnet] add sendMessage rule actions to send generic OWN messages on the BUS
openhab/openhab-addons pull request #16691
Opened 2024-04-27 15:11 UTC by mvalla

This PR adds two new rule actions to allow sending generic OpenWebNet messages from Rules.
The new actions are:

- `Boolean sendMessage(String message)` returns a `Boolean` = `true` if the `message` (OpenWebNet frame) was successfully sent via the gateway, `false` otherwise.
- `Map<String, Object> sendMessageWithResponse(String message)` same as previous one, but returns a `Map<String, Object>` with following keys:
    - `success`: a `Boolean` = `true` if the `message` was sent successfully
    - `responseMessages`: a `List<String>` object containing all returned frames as response to command sent

`openwebnet4j` library has been updated to 0.14.0 to allow using `DefaultMessage` to send messages not yet supported by the binding.

Fixes #10431.

2024-04-27 18:21 UTC, lsiepel requested changes
Thanks, left some minor comments.

2024-04-27 18:21 UTC, lsiepel commented on bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/actions/OpenWebNetBridgeActions.java
> +
```suggestion
```

2024-04-27 18:21 UTC, lsiepel commented on bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/actions/OpenWebNetBridgeActions.java
> +            return ((OpenWebNetBridgeActions) actions).sendMessage(message);
```suggestion
        if (actions instanceof OpenWebNetBridgeActions openwebnetBridgeActions) {
            return openwebnetBridgeActions.sendMessage(message);
```

2024-04-27 18:21 UTC, lsiepel commented on bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/actions/OpenWebNetBridgeActions.java
> +            return ((OpenWebNetBridgeActions) actions).sendMessageWithResponse(message);
```suggestion
        if (actions instanceof OpenWebNetBridgeActions) {
            return ((OpenWebNetBridgeActions) actions).sendMessageWithResponse(message);
```

2024-04-28 09:44 UTC, mvalla commented
> Thanks, left some minor comments. Can you also fix the warnings from here https://github.com/openhab/openhab-addons/actions/runs/8860857344/artifacts/1453450970

Done.

> Besides the code review, why is there a need for sending generic message ? Is there a reason some datapoints/communication cannot be modelled as thing/channel within the openHAB domain ?

Until all automation areas will be supported by the binding (few complex ones like Video Door entry or Room Audio control are not yet handled), it is useful to let end-user send generic (=not supported) messages via the binding.
This empowers openHAB to work as generic message sender to the BTicino MyHOME BUS.

2024-04-28 09:55 UTC, merged

2024-05-21 18:43 UTC, Nils-github commented
@mvalla : Thanks for this nice feature!
Could it be that you forgot to release the dependency: openwebnet4j version 0.14.0 ?

2024-05-21 20:01 UTC, lsiepel commented
> @mvalla : Thanks for this nice feature! Could it be that you forgot to release the dependency: openwebnet4j version 0.14.0 ?

No, https://mvnrepository.com/artifact/io.github.openwebnet4j/openwebnet4j
If you refer to the github repo, please create an issue at that repository.