[mffan] Initial contribution
openhab/openhab-addons pull request #16786
Opened 2024-05-22 13:52 UTC by mark-brooks-180

I've developed a new binding for "Modern Forms" and "WAC Lighting" ceiling fans.  The binding implements communications , and control of these WIFI connected, smart fans.

2024-05-22 18:37 UTC, lsiepel requested changes
Thanks for your contribution. I'm not familiair with this device, but it looks familiair to the [bigassfan ](https://www.openhab.org/addons/bindings/bigassfan/) binding. Maybe that is something you can use for inspiration.

Anyway, besides the comments, you should add yourself to the codeowners file and add this binding to the bom/openhab-addons/pom.xml . I prefer that you respond (`done` is fine) to the comments and let me mark them as resolved. 
Let me know if you need anything.

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> +            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.COMMUNICATION_ERROR,
see earlier comment

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> +    private final class CommandHandlerRunnable implements Runnable {
Might be valid, but this is not a common pattern i see in most bindings, can you explain a bit on why it is moddled this way and not like many other bindings handling the commands inside the handdler class?

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/RestApiException.java
> +    private static final long serialVersionUID = 1L;
Would be nice if you can create/generate  a serialVersionUID other than 1L

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/ShadowBufferDto.java
> +/**
I would suggest to move the API to a different folder and package. 
bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/api/
Files `FanRestApi.java`, `RestApiException.java` and `ShadowBufferDto.java`

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/src/main/resources/OH-INF/addon/addon.xml
> +
Can you add connection tag and maybe country and discovery ? (last two might be more difficult)

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/src/main/resources/OH-INF/i18n/mffan.properties
> +# FIXME: please add all English translations to this file so the texts can be translated using Crowdin
FIXME :-)

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/src/main/resources/OH-INF/thing/mffan.xml
> +			<channel id="fanOn" typeId="fanOn"/>
See earlier comment about channel id's that should be lower-case-hyphen

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/src/main/resources/OH-INF/thing/mffan.xml
> +	<channel-type id="fanOn">
lower-case-hyphen naming convention also applies to channel type id's

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/src/main/resources/OH-INF/thing/mffan.xml
> +		<item-type>Dimmer</item-type>
```suggestion
		<item-type>Number:Dimensionless</item-type>
```

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/src/main/resources/OH-INF/thing/mffan.xml
> +		<state readOnly="false" min="1" max="100" step="1"/>
```suggestion
		<state readOnly="false" min="1" max="100" step="1"  pattern="%.0f %unit%" />
```

2024-05-22 18:37 UTC, lsiepel commented on bundles/pom.xml
>  <?xml version="1.0" encoding="UTF-8" standalone="no"?>
Something weird happend to this file, please revert / only change the line to add this binding.

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/README.md
> +
```suggestion
```

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/README.md
> +Supported things include: "Modern Forms" and "WAC Lighting" smart ceiling fans.  The binding has been tested with both.
This are the supported devices, not the supported `Things`. Maybe add these devices as tested or somehting and use the Thing Id listed in the thing-type.xml

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/README.md
> +To bind with a smart fan either the IP address of the fan, or the local host name of the fan must be provided.
```suggestion
```
Those details belong to the configuration section

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/README.md
> +The binding has been tested using an IPV4 local network address, and a host name served by a local DNS.
```suggestion
```
Not sure if this should be mentioned at all as the configuration explains hsotname/ipadres (maybe add IPV4 to that descritpion)

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/README.md
> +## Binding Configuration
```suggestion
## Thing Configuration
```

2024-05-22 18:37 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/README.md
> +| fanOn          | Switch | RW         | Channel that turns the fan on/off.  |
See other comment about lower-case-hyphen convention

2024-05-22 19:16 UTC, mark-brooks-180 commented
Thanks for your prompt reply.  I'll make the suggested changes.  I'll let
you know when I'm done.

Thank,
Mark B.

On Wed, May 22, 2024 at 2:37 PM lsiepel ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for your contribution. I'm not familiair with this device, but it
> looks familiair to the bigassfan
> <https://www.openhab.org/addons/bindings/bigassfan/> binding. Maybe that
> is something you can use for inspiration.
>
> Anyway, besides the comments, you should add yourself to the codeowners
> file and add this binding to the bom/openhab-addons/pom.xml . I prefer that
> you respond (done is fine) to the comments and let me mark them as
> resolved.
> Let me know if you need anything.
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/MfFanBindingConstants.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610402335>
> :
>
> > + * used across the whole binding.
> + *
> + * @author Mark Brooks - Initial contribution
> + */
> ***@***.***
> +public class MfFanBindingConstants {
> +
> +    private static final String BINDING_ID = "mffan";
> +
> +    // List of all Thing Type UIDs
> +    public static final ThingTypeUID THING_TYPE_MFFAN = new ThingTypeUID(BINDING_ID, BINDING_ID);
> +
> +    public static final Set<ThingTypeUID> SUPPORTED_THING_TYPES_UIDS = Set.of(THING_TYPE_MFFAN);
> +
> +    // List of all Channel ids
> +    public static final String CHANNEL_FAN_ON = "fanOn";
>
> Please use lower-case-hyphen naming convention for channel id's
> For reference:
> https://www.openhab.org/docs/developer/guidelines.html#naming-convention
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/MfFanBindingConstants.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610403993>
> :
>
> > +import org.eclipse.jdt.annotation.NonNullByDefault;
> +import org.openhab.core.thing.ThingTypeUID;
> +
> +/**
> + * The ***@***.*** MfFanBindingConstants} class defines common constants, which are
> + * used across the whole binding.
> + *
> + * @author Mark Brooks - Initial contribution
> + */
> ***@***.***
> +public class MfFanBindingConstants {
> +
> +    private static final String BINDING_ID = "mffan";
> +
> +    // List of all Thing Type UIDs
> +    public static final ThingTypeUID THING_TYPE_MFFAN = new ThingTypeUID(BINDING_ID, BINDING_ID);
>
> The Thing id might be the same as the binding, but for completenes it is
> better to have them split into two constants: BINDING_ID and THING_MFFAN_ID
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/FanRestApi.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610407002>
> :
>
> > +
> +    @Nullable
> +    public ShadowBufferDto setLightPower(boolean power) {
> +        return doPost(String.format("{\"lightOn\" : %s}", String.valueOf(power)));
> +    }
> +
> +    @Nullable
> +    public ShadowBufferDto setLightIntensity(int intensity) {
> +        return doPost(String.format("{\"lightBrightness\" : %d}", intensity));
> +    }
> +
> +    @Nullable
> +    private synchronized ShadowBufferDto doPost(String payloadJson) {
> +        try {
> +            this.logger.debug("Performing Post: 'URL: {}, Payload: '{}'", this.url, payloadJson);
> +            this.client.start();
>
> A start / stop should not be needed for each call.
>
> Can you make use of the common http client ? (injected from the factory
> class)
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/FanRestApi.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610407630>
> :
>
> > +    @Nullable
> +    public ShadowBufferDto setLightPower(boolean power) {
> +        return doPost(String.format("{\"lightOn\" : %s}", String.valueOf(power)));
> +    }
> +
> +    @Nullable
> +    public ShadowBufferDto setLightIntensity(int intensity) {
> +        return doPost(String.format("{\"lightBrightness\" : %d}", intensity));
> +    }
> +
> +    @Nullable
> +    private synchronized ShadowBufferDto doPost(String payloadJson) {
> +        try {
> +            this.logger.debug("Performing Post: 'URL: {}, Payload: '{}'", this.url, payloadJson);
> +            this.client.start();
> +            Request post = this.client.POST(this.url);
>
> ⬇️ Suggested change
>
> -            Request post = this.client.POST(this.url);
> +            Request postRequest= this.client.POST(this.url);
>
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/FanRestApi.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610408790>
> :
>
> > +    }
> +
> +    @Nullable
> +    public ShadowBufferDto setLightIntensity(int intensity) {
> +        return doPost(String.format("{\"lightBrightness\" : %d}", intensity));
> +    }
> +
> +    @Nullable
> +    private synchronized ShadowBufferDto doPost(String payloadJson) {
> +        try {
> +            this.logger.debug("Performing Post: 'URL: {}, Payload: '{}'", this.url, payloadJson);
> +            this.client.start();
> +            Request post = this.client.POST(this.url);
> +            post.header(HttpHeader.ACCEPT, MediaType.APPLICATION_JSON);
> +            post.header(HttpHeader.CONTENT_TYPE, MediaType.APPLICATION_JSON);
> +            post.content(new StringContentProvider(payloadJson, Charset.forName(StandardCharsets.UTF_8.name())));
>
> can you add an explicit timeout to the postRequest
> postRequest.timeout(10,SECONDS) (pseudo code)
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/FanRestApi.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610409987>
> :
>
> > +    @Nullable
> +    public ShadowBufferDto setLightIntensity(int intensity) {
> +        return doPost(String.format("{\"lightBrightness\" : %d}", intensity));
> +    }
> +
> +    @Nullable
> +    private synchronized ShadowBufferDto doPost(String payloadJson) {
> +        try {
> +            this.logger.debug("Performing Post: 'URL: {}, Payload: '{}'", this.url, payloadJson);
> +            this.client.start();
> +            Request post = this.client.POST(this.url);
> +            post.header(HttpHeader.ACCEPT, MediaType.APPLICATION_JSON);
> +            post.header(HttpHeader.CONTENT_TYPE, MediaType.APPLICATION_JSON);
> +            post.content(new StringContentProvider(payloadJson, Charset.forName(StandardCharsets.UTF_8.name())));
> +            ContentResponse resp = post.send();
> +            this.logger.debug("Response = '{}'", resp.getContentAsString());
>
> Not sure if any authentication is invoilved, but you might check resp for
> isSuccess (or http statuscode) before you proceed.
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/FanRestApi.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610413406>
> :
>
> > +    @Nullable
> +    public ShadowBufferDto setLightIntensity(int intensity) {
> +        return doPost(String.format("{\"lightBrightness\" : %d}", intensity));
> +    }
> +
> +    @Nullable
> +    private synchronized ShadowBufferDto doPost(String payloadJson) {
> +        try {
> +            this.logger.debug("Performing Post: 'URL: {}, Payload: '{}'", this.url, payloadJson);
> +            this.client.start();
> +            Request post = this.client.POST(this.url);
> +            post.header(HttpHeader.ACCEPT, MediaType.APPLICATION_JSON);
> +            post.header(HttpHeader.CONTENT_TYPE, MediaType.APPLICATION_JSON);
> +            post.content(new StringContentProvider(payloadJson, Charset.forName(StandardCharsets.UTF_8. [...]

2024-05-23 17:04 UTC, mark-brooks-180 commented
------------------------------


lsiepel,

I believe I have all of the changes you recommended completed.  The
corruption of file In bundles/pom.xml
<https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610444528>
was
resolved by resynchronizing my fork with the upstream and then recommitting
my changes.  The two issues listed below require some explanation:

  - I'm using a single thread executor to serialize command handler
execution.

  - The actual commands are executed by runnables submitted to the
executor.  This ensures the commands are executed in the order they are
received, and potential delays resulting from calls to the REST API
functions don't impact the performance of calls to handleCommand(ChannelUID
channelUID, Command command).

  - In a similar manner the polling thread calls a private version of
handleCommand to submit a REFRESH command.  This ensures commands are
serialized by the executor, and avoids any thread contention when updating
the state of the Thing.

Thanks,

Mark B.

In
bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
<https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610420282>
:

> +            // this.pollingJob = this.scheduler.scheduleWithFixedDelay(() -> update(this.api.getShadowBuffer()), 0,
+            // pollingPeriod, TimeUnit.SECONDS);

⬇️ Suggested change

-            // this.pollingJob =
this.scheduler.scheduleWithFixedDelay(() ->
update(this.api.getShadowBuffer()), 0,
-            // pollingPeriod, TimeUnit.SECONDS);



In
bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
<https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610428827>
:

> +    @SuppressWarnings("null")
+    @Override
+    public void handleCommand(ChannelUID channelUID, Command command) {
+        try {
+            this.executor.execute(new
CommandHandlerRunnable(channelUID, command));
+        } catch ***@***.***("unused") Exception e) {
+            updateStatus(ThingStatus.OFFLINE,
ThingStatusDetail.COMMUNICATION_ERROR,
+                    String.format("Could not control device at IP
address %s", this.config.getIpAddress()));
+        }
+    }
+
+    private void handleCommand(Command command) {
+        handleCommand(new ChannelUID("Null:Null:Null:Null"), command);
+    }
+
+    private final class CommandHandlerRunnable implements Runnable {

Might be valid, but this is not a common pattern i see in most bindings,
can you explain a bit on why it is moddled this way and not like many other
bindings handling the commands inside the handdler class?



On Wed, May 22, 2024 at 2:37 PM lsiepel ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for your contribution. I'm not familiair with this device, but it
> looks familiair to the bigassfan
> <https://www.openhab.org/addons/bindings/bigassfan/> binding. Maybe that
> is something you can use for inspiration.
>
> Anyway, besides the comments, you should add yourself to the codeowners
> file and add this binding to the bom/openhab-addons/pom.xml . I prefer that
> you respond (done is fine) to the comments and let me mark them as
> resolved.
> Let me know if you need anything.
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/MfFanBindingConstants.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610402335>
> :
>
> > + * used across the whole binding.
> + *
> + * @author Mark Brooks - Initial contribution
> + */
> ***@***.***
> +public class MfFanBindingConstants {
> +
> +    private static final String BINDING_ID = "mffan";
> +
> +    // List of all Thing Type UIDs
> +    public static final ThingTypeUID THING_TYPE_MFFAN = new ThingTypeUID(BINDING_ID, BINDING_ID);
> +
> +    public static final Set<ThingTypeUID> SUPPORTED_THING_TYPES_UIDS = Set.of(THING_TYPE_MFFAN);
> +
> +    // List of all Channel ids
> +    public static final String CHANNEL_FAN_ON = "fanOn";
>
> Please use lower-case-hyphen naming convention for channel id's
> For reference:
> https://www.openhab.org/docs/developer/guidelines.html#naming-convention
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/MfFanBindingConstants.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610403993>
> :
>
> > +import org.eclipse.jdt.annotation.NonNullByDefault;
> +import org.openhab.core.thing.ThingTypeUID;
> +
> +/**
> + * The ***@***.*** MfFanBindingConstants} class defines common constants, which are
> + * used across the whole binding.
> + *
> + * @author Mark Brooks - Initial contribution
> + */
> ***@***.***
> +public class MfFanBindingConstants {
> +
> +    private static final String BINDING_ID = "mffan";
> +
> +    // List of all Thing Type UIDs
> +    public static final ThingTypeUID THING_TYPE_MFFAN = new ThingTypeUID(BINDING_ID, BINDING_ID);
>
> The Thing id might be the same as the binding, but for completenes it is
> better to have them split into two constants: BINDING_ID and THING_MFFAN_ID
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/FanRestApi.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610407002>
> :
>
> > +
> +    @Nullable
> +    public ShadowBufferDto setLightPower(boolean power) {
> +        return doPost(String.format("{\"lightOn\" : %s}", String.valueOf(power)));
> +    }
> +
> +    @Nullable
> +    public ShadowBufferDto setLightIntensity(int intensity) {
> +        return doPost(String.format("{\"lightBrightness\" : %d}", intensity));
> +    }
> +
> +    @Nullable
> +    private synchronized ShadowBufferDto doPost(String payloadJson) {
> +        try {
> +            this.logger.debug("Performing Post: 'URL: {}, Payload: '{}'", this.url, payloadJson);
> +            this.client.start();
>
> A start / stop should not be needed for each call.
>
> Can you make use of the common http client ? (injected from the factory
> class)
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/FanRestApi.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610407630>
> :
>
> > +    @Nullable
> +    public ShadowBufferDto setLightPower(boolean power) {
> +        return doPost(String.format("{\"lightOn\" : %s}", String.valueOf(power)));
> +    }
> +
> +    @Nullable
> +    public ShadowBufferDto setLightIntensity(int intensity) {
> +        return doPost(String.format("{\"lightBrightness\" : %d}", intensity));
> +    }
> +
> +    @Nullable
> +    private synchronized ShadowBufferDto doPost(String payloadJson) {
> +        try {
> +            this.logger.debug("Performing Post: 'URL: {}, Payload: '{}'", this.url, payloadJson);
> +            this.client.start();
> +            Request post = this.client.POST(this.url);
>
> ⬇️ Suggested change
>
> -            Request post = this.client.POST(this.url);
> +            Request postRequest= this.client.POST(this.url);
>
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/FanRestApi.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1610408790>
> :
>
> > +    }
> +
> +    @Nullable
> +    public ShadowBufferDto setLightIntensity(int intensity) {
> +        return doPost(String.format("{\"lightBrightness\" : %d}", intensity));
> +    }
> +
> +    @Nullable
> +    private synchronized ShadowBufferDto doPost(String payloadJson) {
> +        try {
> +            this.logger.debug("Performing Post: 'URL: {}, Payload: '{}'", this.url, payloadJson);
> +            this.client.start();
> +            Request post = this.client.POST(this.url);
> +            post.header(HttpHeader.ACCE [...]

2024-05-23 19:11 UTC, lsiepel commented
I think something went wrong as the pr is closed due to no files. It should not be needed to do a force push. Can you fix this?

2024-05-24 13:26 UTC, mark-brooks-180 commented
Isiepel,

I believe I fixed the issue.  The pull request has been reopened.

Thanks,
Mark B.

On Thu, May 23, 2024 at 3:12 PM lsiepel ***@***.***> wrote:

> I think something went wrong as the pr is closed due to no files. It
> should not be needed to do a force push. Can you fix this?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openhab/openhab-addons/pull/16786#issuecomment-2127856767>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI3WWNUXLJ5WT2CMSUHFYRTZDY5RJAVCNFSM6AAAAABIDWOQMKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMRXHA2TMNZWG4>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-05-24 18:46 UTC, lsiepel requested changes
Some, but not all previous comments are addressed. I also see some comments being lost after the changes. Ping me when your are ready.

2024-05-26 12:30 UTC, mark-brooks-180 commented
Isiepel,

I believe I've made all the recommended changes and pushed them to main.  I
tested the binding.  Everything looks good on my end.

Thanks,
Mark B.

On Fri, May 24, 2024 at 2:46 PM lsiepel ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Some, but not all previous comments are addressed. I also see som
> ecomments being lost after the changes. Ping me when your are ready.
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/api/FanRestApi.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1613840942>
> :
>
> > +    private ShadowBufferDto doPost(String payloadJson) {
> +        try {
> +            this.logger.debug("Performing Post: 'URL: {}, Payload: '{}'", this.url, payloadJson);
> +            Request postRequest = this.client.POST(this.url);
> +            postRequest.timeout(10, TimeUnit.SECONDS);
> +            postRequest.header(HttpHeader.ACCEPT, MediaType.APPLICATION_JSON);
> +            postRequest.header(HttpHeader.CONTENT_TYPE, MediaType.APPLICATION_JSON);
> +            postRequest.content(new StringContentProvider(payloadJson, Charset.forName(StandardCharsets.UTF_8.name())));
> +            ContentResponse postResponse = postRequest.send();
> +            this.logger.debug("Response status: {}", postResponse.getStatus());
> +            if (postResponse.getStatus() == 200) {
> +                this.logger.trace("Post Response Content = '{}'", postResponse.getContentAsString());
> +                return this.gson.fromJson(postResponse.getContentAsString(), ShadowBufferDto.class);
> +            }
> +        } catch (JsonSyntaxException | InterruptedException | TimeoutException | ExecutionException e) {
> +
>
> ⬇️ Suggested change
>
> -
>
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/api/RestApiException.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1613841478>
> :
>
> > + * terms of the Eclipse Public License 2.0 which is available at
> + * http://www.eclipse.org/legal/epl-2.0
> + *
> + * SPDX-License-Identifier: EPL-2.0
> + */
> +package org.openhab.binding.mffan.internal.api;
> +
> +import org.eclipse.jdt.annotation.NonNullByDefault;
> +
> +/**
> + * The ***@***.*** RestApiException} is an exception thrown from the REST API.
> + *
> + * @author Mark Brooks - Initial contribution
> + */
> ***@***.***
> +public class RestApiException extends RuntimeException {
>
> ⬇️ Suggested change
>
> -public class RestApiException extends RuntimeException {
> +public class RestApiException extends Exception {
>
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1613842195>
> :
>
> > +
> +    public MfFanHandler(Thing thing, HttpClientFactory httpClientFactory) {
> +        super(thing);
> +        this.httpClientFactory = httpClientFactory;
> +        this.executor = Executors.newSingleThreadExecutor();
> +    }
> +
> +    @Override
> +    public void initialize() {
> +        this.logger.debug("Initializing MfFan handler '{}'", getThing().getUID());
> +        updateStatus(ThingStatus.UNKNOWN);
> +        this.config = getConfigAs(MfFanConfiguration.class);
> +        if (validateConfig(this.config)) {
> +            try {
> +                this.api = new FanRestApi(this.config.getIpAddress().trim(), this.httpClientFactory);
> +                // handleCommand(RefreshType.REFRESH);
>
> ⬇️ Suggested change
>
> -                // handleCommand(RefreshType.REFRESH);
>
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1613842791>
> :
>
> > +            } catch (Exception e) {
> +                updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.OFFLINE.COMMUNICATION_ERROR, e.getMessage());
> +            }
>
> this try/catch block is not needed as no exception is thrown.
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1613844559>
> :
>
> > +    private final ExecutorService executor;
> +
> +    private final HttpClientFactory httpClientFactory;
> +
> +    public MfFanHandler(Thing thing, HttpClientFactory httpClientFactory) {
> +        super(thing);
> +        this.httpClientFactory = httpClientFactory;
> +        this.executor = Executors.newSingleThreadExecutor();
> +    }
> +
> +    @Override
> +    public void initialize() {
> +        this.logger.debug("Initializing MfFan handler '{}'", getThing().getUID());
> +        updateStatus(ThingStatus.UNKNOWN);
> +        this.config = getConfigAs(MfFanConfiguration.class);
> +        if (validateConfig(this.config)) {
>
> Don't want to be too rigid, so this comment is for your consideration, but
> i think the MfFanConfiguration class should be responsible for validating
> itself, not the handler.
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1613847064>
> :
>
> > +        this.config = getConfigAs(MfFanConfiguration.class);
> +        if (validateConfig(this.config)) {
> +            try {
> +                this.api = new FanRestApi(this.config.getIpAddress().trim(), this.httpClientFactory);
> +                // handleCommand(RefreshType.REFRESH);
> +            } catch (Exception e) {
> +                updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.OFFLINE.COMMUNICATION_ERROR, e.getMessage());
> +            }
> +
> +            this.pollingJob = this.scheduler.scheduleWithFixedDelay(() -> handleCommand(RefreshType.REFRESH), 0,
> +                    this.config.getPollingPeriod(), TimeUnit.SECONDS);
> +
> +            this.logger.debug("Polling job scheduled to run every {} sec. for '{}'", this.config.getPollingPeriod(),
> +                    getThing().getUID());
> +        } else {
> +            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.CONFIGURATION_ERROR, "Invalid configuration detected.");
>
> I would recommend to change this if/else block
>
> if (validateConfig(this.config)) {
> // set thing state;
> return; // exit this method
> }
> // set pollingjob etc.
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1613847642>
> :
>
> > +
> +            this.logger.debug("Polling job scheduled to run every {} sec. for '{}'", this.config.getPollingPeriod(),
> +                    getThing().getUID());
> +        } else {
> +            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.CONFIGURATION_ERROR, "Invalid configuration detected.");
> +        }
> +    }
> +
> +    @Override
> +    public void dispose() {
> +        this.logger.debug("Disposing MF fan handler '{}'", getThing().getUID());
> +
> +        ScheduledFuture<?> job = this.pollingJob;
> +        if (job != null) {
> +            job.cancel(true);
> +        }
>
> ⬇️ Suggested change
>
> -        }
> +        this.pollingJob = null;
> +        }
>
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1613848342>
> :
>
> > +        ExecutorService exec = this.executor;
> +        exec.shutdown();
> +        try {
> +            exec.awaitTermination(2, TimeUnit.SECONDS);
> +         [...]

2024-05-26 20:03 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> +            this.api = new FanRestApi(this.config.getIpAddress().trim(), this.httpClientFactory);
Minor: The trim() should be part of the getIpAddress() as that method is responsible for returning a proper IpAddress

2024-05-26 20:09 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> +        if (MfFanConfiguration.validateConfig(this.config)) {
```suggestion
        if (!MfFanConfiguration.validateConfig(this.config)) {
        updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.CONFIGURATION_ERROR, "Invalid configuration detected.");
        return;
        }
```
Better to abort immediate. (last 3 lines of this method can be removed.

You could also consider to use a custom i18n key.
Reference: https://www.openhab.org/docs/developer/utils/i18n.html#using-custom-keys (last example)

2024-05-26 20:21 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/MfFanConfiguration.java
> +        if ((config == null) || config.getIpAddress().isBlank()) {
```suggestion
        if (config == null || config.getIpAddress().isBlank()) {
```

2024-05-26 20:28 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/README.md
> +
Not fixed yet

2024-05-27 19:44 UTC, mark-brooks-180 commented
Isiepel,

I believe I have made the recommended changes.  Furthermore, I eliminated
the use of the single thread executor from the MfFanHandler class.  Your
email had a bullet item that said

   - fix the build (see bottom of this page)

I didn't find anything at the bottom of the page indicating the build error
you are experiencing.

Thanks,
Mark B.

On Sun, May 26, 2024 at 4:35 PM lsiepel ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Making some progress! But the review summary is the same:
> Some, but not all previous comments are addressed. I also see some
> comments being lost after the changes. Ping me when your are ready.
>
> Also:
>
>    - fix the build (see bottom of this page)
>    - fix dco, some new commits are not signed off
>    - add yourself to the codeowners file
>    - add this binding to the bom/openhab-addons/pom.xml
>
> I think i might need one last (small) round after all these are fixed.
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1615319370>
> :
>
> > @@ -72,22 +73,15 @@ public void initialize() {
>          this.logger.debug("Initializing MfFan handler '{}'", getThing().getUID());
>          updateStatus(ThingStatus.UNKNOWN);
>          this.config = getConfigAs(MfFanConfiguration.class);
> -        if (validateConfig(this.config)) {
> -            try {
> -                this.api = new FanRestApi(this.config.getIpAddress().trim(), this.httpClientFactory);
> -                // handleCommand(RefreshType.REFRESH);
> -            } catch (Exception e) {
> -                updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.OFFLINE.COMMUNICATION_ERROR, e.getMessage());
> -            }
> -
> +        if (MfFanConfiguration.validateConfig(this.config)) {
> +            this.api = new FanRestApi(this.config.getIpAddress().trim(), this.httpClientFactory);
>
> Minor: The trim() should be part of the getIpAddress() as that method is
> responsible for returning a proper IpAddress
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1615320240>
> :
>
> > +    private ExecutorService executor;
> +
> +    private HttpClientFactory httpClientFactory;
> +
> +    public MfFanHandler(Thing thing, HttpClientFactory httpClientFactory) {
> +        super(thing);
> +        this.httpClientFactory = httpClientFactory;
> +        this.executor = Executors.newSingleThreadExecutor();
> +    }
> +
> +    @Override
> +    public void initialize() {
> +        this.logger.debug("Initializing MfFan handler '{}'", getThing().getUID());
> +        updateStatus(ThingStatus.UNKNOWN);
> +        this.config = getConfigAs(MfFanConfiguration.class);
> +        if (MfFanConfiguration.validateConfig(this.config)) {
>
> ⬇️ Suggested change
>
> -        if (MfFanConfiguration.validateConfig(this.config)) {
> +        if (!MfFanConfiguration.validateConfig(this.config)) {
> +        updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.CONFIGURATION_ERROR, "Invalid configuration detected.");
> +        return;
> +        }
>
> Better to abort immediate. (last 3 lines of this method can be removed.
>
> You could also consider to use a custom i18n key.
> Reference:
> https://www.openhab.org/docs/developer/utils/i18n.html#using-custom-keys
> (last example)
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1615320590>
> :
>
> > +        ExecutorService exec = this.executor;
> +        if (exec != null) {
> +            exec.shutdown();
> +        }
> +        this.executor = null;
>
> Why is this pattern not the same is with the pollingjob?
> Reference: #16786 (comment)
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1613848342>
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/MfFanConfiguration.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1615321675>
> :
>
> > +    }
> +
> +    public void setIpAddress(String ipAddress) {
> +        this.ipAddress = ipAddress;
> +    }
> +
> +    public Integer getPollingPeriod() {
> +        return this.pollingPeriod;
> +    }
> +
> +    public void setPollingPeriod(Integer pollingPeriod) {
> +        this.pollingPeriod = pollingPeriod;
> +    }
> +
> +    public static boolean ***@***.*** MfFanConfiguration config) {
> +        if ((config == null) || config.getIpAddress().isBlank()) {
>
> ⬇️ Suggested change
>
> -        if ((config == null) || config.getIpAddress().isBlank()) {
> +        if (config == null || config.getIpAddress().isBlank()) {
>
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1615320893>
> :
>
> > +            this.executor.execute(new CommandHandlerRunnable(channelUID, command));
> +        } catch ***@***.***("unused") Exception e) {
> +            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.COMMUNICATION_ERROR,
>
> Not commented on or resolved yet.
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1615320878>
> :
>
> > +    @SuppressWarnings("null")
> +    @Override
> +    public void handleCommand(ChannelUID channelUID, Command command) {
> +        try {
> +            this.executor.execute(new CommandHandlerRunnable(channelUID, command));
> +        } catch ***@***.***("unused") Exception e) {
> +            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.COMMUNICATION_ERROR,
> +                    String.format("Could not control device at IP address %s", this.config.getIpAddress()));
> +        }
> +    }
> +
> +    private void handleCommand(Command command) {
> +        handleCommand(new ChannelUID("Null:Null:Null:Null"), command);
> +    }
> +
> +    private final class CommandHandlerRunnable implements Runnable {
>
> Not commented on or resolved yet.
> ------------------------------
>
> In bundles/org.openhab.binding.mffan/README.md
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1615322752>
> :
>
> > @@ -0,0 +1,69 @@
> +# MfFan Binding
> +
> +This binding is used to enable communications between openHAB and "Modern Forms" or "WAC Lighting" WIFI connected, smart, ceiling fans.
> +
>
> Not fixed yet
> ------------------------------
>
> In bundles/org.openhab.binding.mffan/README.md
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1615322757>
> :
>
> > +# MfFan Binding
> +
> +This binding is used to enable communications between openHAB and "Modern Forms" or "WAC Lighting" WIFI connected, smart, ceiling fans.
> +
> +
> +## Supported Things
> +
> +Supported things include: "Modern Forms" and "WAC Lighting" smart ceiling fans.  The binding has been tested with both.
> +
> +## Discovery
> +
> +Auto discovery is not supported at this time.
> +To bind with a smart fan either the IP address of the fan, or the local host name of the fan must be provided.
> +The binding has been tested using an IPV4 local network address, and a host name served by a local DNS.
> +
> +## Binding Configuration
>
> Not fixed yet
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1615320444>
> :
>
> > +        this.config = get [...]

2024-05-27 20:16 UTC, lsiepel requested changes
Many comments are fixed, thanks. Left one new comment and besides that
- DCO is not signed (mandatory)
- build failed (run spotless)
- Unalbe to check now, but fix any SAT errors
- Unable to check now but fix any compile warnings

2024-05-27 20:16 UTC, lsiepel commented on bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> +        this.pollingJob = null;
```suggestion
        this.pollingJob = null;
        }
```

2024-05-28 21:12 UTC, mark-brooks-180 commented
Isiepel,

I've pushed the most recent set of changes.  Let me know if there is
anything else I need to do.

Thanks,
Mark B.

On Mon, May 27, 2024 at 4:16 PM lsiepel ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Many comments are fixed, thanks. Left one new comment and besides that
>
>    - DCO is not signed (mandatory)
>    - build failed (run spotless)
>    - Unalbe to check now, but fix any SAT errors
>    - Unable to check now but fix any compile warnings
>
> ------------------------------
>
> In
> bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
> <https://github.com/openhab/openhab-addons/pull/16786#discussion_r1616364006>
> :
>
> > +        }
> +        this.pollingJob = null;
>
> ⬇️ Suggested change
>
> -        }
> -        this.pollingJob = null;
> +        this.pollingJob = null;
> +        }
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openhab/openhab-addons/pull/16786#pullrequestreview-2081424580>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI3WWNSVQVL7DH5E6VJXSCLZEOIB5AVCNFSM6AAAAABIDWOQMKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAOBRGQZDINJYGA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-05-28 21:31 UTC, lsiepel commented
You could fix the errors below. (ALS listed in my previous comment)

2024-05-28 21:35 UTC, mark-brooks-180 commented
Fixed.

On Tue, May 28, 2024 at 5:31 PM lsiepel ***@***.***> wrote:

> You could fix the errors below. (Also listed in my previous comment)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openhab/openhab-addons/pull/16786#issuecomment-2136144337>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI3WWNUC55FMG5LDGP3HHM3ZETZT5AVCNFSM6AAAAABIDWOQMKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMZWGE2DIMZTG4>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-05-31 20:16 UTC, lsiepel approved these changes
Thanks, LGTM.

Only remaining issue is the DCO, if you click details next to the DCO you can see the related commits and how to fix those.

2024-06-14 19:38 UTC, lsiepel commented
> Thanks, LGTM.
> 
> Only remaining issue is the DCO, if you click details next to the DCO you can see the related commits and how to fix those.

@mark-brooks-180 you need any help with the DCO?

2024-06-15 15:52 UTC, mark-brooks-180 commented
Isiepel,

I believe the DCO issue is resolved.  All the commits are signed off.

M

On Fri, Jun 14, 2024 at 3:38 PM lsiepel ***@***.***> wrote:

> Thanks, LGTM.
>
> Only remaining issue is the DCO, if you click details next to the DCO you
> can see the related commits and how to fix those.
>
> @mark-brooks-180 <https://github.com/mark-brooks-180> you need any help
> with the DCO?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openhab/openhab-addons/pull/16786#issuecomment-2168647830>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI3WWNQ2XX6GX7AYFYEERQTZHNBE5AVCNFSM6AAAAABIDWOQMKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNRYGY2DOOBTGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-15 16:40 UTC, merged

2024-06-15 16:40 UTC, lsiepel commented
Now, you could add your binding's logo to the openHAB website. See https://next.openhab.org/docs/developer/addons/#add-your-add-on-s-logo-to-the-openhab-website-and-the-ui

2024-06-16 12:18 UTC, mark-brooks-180 commented
Isiepel,

Thanks for your help.

M

On Sat, Jun 15, 2024 at 12:41 PM lsiepel ***@***.***> wrote:

> Now, you could add your binding's logo to the openHAB website. See
> https://next.openhab.org/docs/developer/addons/#add-your-add-on-s-logo-to-the-openhab-website-and-the-ui
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openhab/openhab-addons/pull/16786#issuecomment-2170279913>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI3WWNWKTCJOYU4PZBWJPVTZHRVB7AVCNFSM6AAAAABIDWOQMKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNZQGI3TSOJRGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>