[sonyprojector] Add discovery through SDDP
openhab/openhab-addons pull request #16849
Opened 2024-06-06 06:53 UTC by lolodomo

Only applicable to projector models having a network connector

Not tested because my projector has no network connector

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

2024-06-06 19:37 UTC, mlobstein commented
The configuration option to enable SDDP in the projector is called 'Start SDDP Service'
https://helpguide.sony.net/vpl/xw5000/v1/en/contents/TP1000558242.html


Suggested verbiage for the **Discovery** section in the README:

_If the projector is connected via Ethernet and the 'Start SDDP Service' option is present and enabled in the projector's Advanced Settings->Service page, the thing using PJ Talk will be discovered automatically.
Serial or Serial over IP connections must be configured manually._

2024-06-07 21:16 UTC, mlobstein requested changes
LGTM except needing the README update

2024-06-08 08:54 UTC, lolodomo commented
> LGTM except needing the README update

Done now.

2024-06-08 13:14 UTC, mlobstein approved these changes
LGTM

2024-06-09 19:08 UTC, jlaur commented on bundles/org.openhab.binding.sonyprojector/README.md
> +If the projector is connected via Ethernet and the 'Start SDDP Service' option is present and enabled in the projector Advanced Settings->Service page, the thing using Ethernet connection and PJ Talk
```suggestion
If the projector is connected via Ethernet and the 'Start SDDP Service' option is present and enabled in the projector Advanced Settings->Service page, the Thing using Ethernet connection and PJ Talk will be discovered automatically.
```

2024-06-11 04:52 UTC, lolodomo commented on bundles/org.openhab.binding.sonyprojector/README.md
> +If the projector is connected via Ethernet and the 'Start SDDP Service' option is present and enabled in the projector Advanced Settings->Service page, the thing using Ethernet connection and PJ Talk
Changed

2024-06-14 15:47 UTC, jlaur approved these changes
Thanks!

2024-06-14 15:48 UTC, merged