[nibeheatpump] Updated NibeGW readme
openhab/openhab-addons pull request #16864
Opened 2024-06-11 14:45 UTC by paulianttila

Added build information for ProDiNo ESP32 Ethernet v1 board.

Signed-off-by: Pauli Anttila pauli.anttila@gmail.com

2024-06-11 21:07 UTC, jlaur requested changes
Thanks! Only some minor proof-reading comments.

2024-06-11 21:07 UTC, jlaur commented on bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/README.md
> +```
Perhaps syntax highlighting could be better if language is provided?
```suggestion
```c
```

2024-06-11 21:07 UTC, jlaur commented on bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/README.md
> +```
```suggestion
```c
```

2024-06-11 21:07 UTC, jlaur commented on bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/README.md
> +With 'h' you get a menue with all available options:
```suggestion
With 'h' you get a menu with all available options:
```

2024-06-11 21:07 UTC, jlaur commented on bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/README.md
> +## Dynamic configuration
```suggestion
## Dynamic Configuration
```

2024-06-11 21:07 UTC, jlaur commented on bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/README.md
> +When dynamic configuration is enabled (only ESP32 boards), NibeGW can be configured via WiFi connection.
```suggestion
When dynamic configuration is enabled (only ESP32 boards), NibeGW can be configured via Wi-Fi connection.
```

2024-06-11 21:07 UTC, jlaur commented on bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/README.md
> +Following libraries are required
```suggestion
The following libraries are required:
```

2024-06-11 21:07 UTC, jlaur commented on bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/README.md
> +When dynamic configuration mode is activated, login to the 'Bleeper' WiFi Access point.
```suggestion
When dynamic configuration mode is activated, login to the 'Bleeper' Wi-Fi access point.
```

2024-06-11 21:07 UTC, jlaur commented on bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/README.md
> +```
```suggestion
```c
```

2024-06-11 21:07 UTC, jlaur commented on bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/README.md
> +### Disable dynamic configuration
```suggestion
### Disable Dynamic Configuration
```

2024-06-12 17:43 UTC, jlaur approved these changes
LGTM

2024-06-12 17:45 UTC, merged

2024-06-14 04:01 UTC, ajaysanan commented
Having just started looking around github and trying to start my first binding, I'm certain I've clicked on something incorrectly and I apologize.  I really do not know what this push means that "referenced this pull request".  I hope it did not cause any issue; I had assumed everything I changed applied only to the fork I had created.