Update README.md
openhab/openhab-addons pull request #16945
Opened 2024-06-27 10:23 UTC by Linsenschisdre

Added full set of items for dishwasher, oven and washer.

I find it quite inconvenient to use the provided table in order so build up my .items file for my appliances. As I have a dishwasher, an oven and a washer in my home and prepared the whole items stack anyway, I decided to let other users make use of it and save them some time by just "copy & paste" what they need.

2024-06-27 17:21 UTC, lsiepel requested changes
Otherwise LGTM

2024-06-27 17:21 UTC, lsiepel commented on bundles/org.openhab.binding.homeconnect/README.md
> +String                 Dishwasher_basic_actions_state                     "Basic control"                      {channel="homeconnect:dishwasher:api_bridge_at_home:sgeschirrspuelmaschine:basic_actions
```suggestion
String                 Dishwasher_BasicActionsState                     "Basic Control"                      {channel="homeconnect:dishwasher:api_bridge_at_home:sgeschirrspuelmaschine:basic_actions_state"}
```

2024-06-27 17:21 UTC, lsiepel commented on bundles/org.openhab.binding.homeconnect/README.md
> +String                 Oven_basic_actions_state                           "Basic control"                      {channel="homeconnect:oven:api_bridge_at_home:oven1_:basic_actions_state"}
```suggestion
Number:Time            Oven_ElapsedProgramTime                          "Elapsed Program Time"               {channel="homeconnect:oven:api_bridge_at_home:oven1:elapsed_program_time"}
Number:Time            Oven_Duration                                      "Program Duration"                   {channel="homeconnect:oven:api_bridge_at_0home:oven1:duration"}
Number:Temperature     Oven_CurrentCavityTemperature               "Current Temperature"                {channel="homeconnect:oven:api_bridge_at_home:oven1:oven_current_cavity_temperature"}
Number:Temperature     Oven_SetpointTemperature                          "Set Temperature"                    {channel="homeconnect:oven:api_bridge_at_home:oven1:setpoint_temperature"}
String                 Oven_BasicActionsState                           "Basic Control"                      {channel="homeconnect:oven:api_bridge_at_home:oven1_:basic_actions_state"}
```

2024-06-27 17:21 UTC, lsiepel commented on bundles/org.openhab.binding.homeconnect/README.md
> +String                 Washer_basic_actions_state                         "Basic control"                      {channel="homeconnect:washer:api_bridge_at_home:washer1:basic_actions_state"}
similar comments as previous, please use consistent naming strategy, so it is a true copy paste solution.

2024-07-04 18:16 UTC, lsiepel commented
Minor request: would be nice if the example could be vertically aligned.

2024-07-07 08:20 UTC, jlaur commented on bundles/org.openhab.binding.homeconnect/README.md
> +String                 Dishwasher_BasicActionsState                     "Basic Control"                      {channel="homeconnect:dishwasher:api_bridge_at_home:sgeschirrspuelmaschine:basic_actions_s
```suggestion
String                 Dishwasher_BasicActionsState                       "Basic Control"                      {channel="homeconnect:dishwasher:api_bridge_at_home:dishwasher1:basic_actions_state"}
```

2024-07-07 08:20 UTC, jlaur commented on bundles/org.openhab.binding.homeconnect/README.md
> +Number:Time            Oven_Duration                                      "Program Duration"                   {channel="homeconnect:oven:api_bridge_at_0home:oven1:duration"}
```suggestion
Number:Time            Oven_Duration                                      "Program Duration"                   {channel="homeconnect:oven:api_bridge_at_home:oven1:duration"}
```

2024-07-07 08:21 UTC, jlaur commented on bundles/org.openhab.binding.homeconnect/README.md
> +Number:Time            Oven_ElapsedProgramTime                          "Elapsed Program Time"               {channel="homeconnect:oven:api_bridge_at_home:oven1:elapsed_program_time"}
```suggestion
Number:Time            Oven_ElapsedProgramTime                            "Elapsed Program Time"               {channel="homeconnect:oven:api_bridge_at_home:oven1:elapsed_program_time"}
```

2024-07-07 08:22 UTC, jlaur commented on bundles/org.openhab.binding.homeconnect/README.md
> +Number:Temperature     Oven_CurrentCavityTemperature               "Current Temperature"                {channel="homeconnect:oven:api_bridge_at_home:oven1:oven_current_cavity_temperature"}
```suggestion
Number:Temperature     Oven_CurrentCavityTemperature                     "Current Temperature"                {channel="homeconnect:oven:api_bridge_at_home:oven1:oven_current_cavity_temperature"}
```

2024-07-07 08:23 UTC, jlaur commented on bundles/org.openhab.binding.homeconnect/README.md
> +String                 Oven_BasicActionsState                           "Basic Control"                      {channel="homeconnect:oven:api_bridge_at_home:oven1_:basic_actions_state"}
```suggestion
String                 Oven_BasicActionsState                            "Basic Control"                      {channel="homeconnect:oven:api_bridge_at_home:oven1:basic_actions_state"}
```

2024-07-08 16:10 UTC, lsiepel approved these changes
LGTM

2024-07-08 16:11 UTC, merged