[gree] support for ASC/GCM encryption
openhab/openhab-addons pull request #16950
Opened 2024-06-28 13:32 UTC by lovery

New Gree AC uses ASC/GCM encryption and different general key Fixes #16949

Fixes #16949

# Testing
Link to a built [JAR](https://file.io/EzSrZOZaFIVy) file

2024-06-28 14:15 UTC, jlaur commented
@lovery - many thanks for your contribution!

@markus7017 - I know it's a stretch, but do you think you will find time for a review of this PR before the feature freeze tomorrow? 🙂

2024-07-09 06:11 UTC, markus7017 reviewed
Not essential, but you might encapsulate of ECB/GSM handling to GreeCryptoUtil, this hides details from the protocol layer

2024-07-09 06:11 UTC, markus7017 commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/discovery/GreeDeviceFinder.java
> +                    // If there is a tag property in the responce then use GCM decryption
could you move the logic to GreeCryptoUtil class, this layer here should not deal with it, just call a encrypt/decrypt method doing the details

2024-07-09 06:11 UTC, markus7017 commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
> +            if (encryptionType == EncryptionTypes.GCM) {
could you move the logic to GreeCryptoUtil class, this layer here should not deal with it, just call a encrypt/decrypt method doing the details

2024-07-09 06:11 UTC, markus7017 commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
> +            if (encryptionType == EncryptionTypes.GCM) {
move logic to GreeCryptoUtil

2024-07-09 06:11 UTC, markus7017 commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
> +            if (encryptionType == EncryptionTypes.GCM) {
same here

2024-07-09 06:11 UTC, markus7017 commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
> +            if (encryptionType == EncryptionTypes.GCM) {
and here

2024-07-09 06:11 UTC, markus7017 commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
> +            if (encryptionType == EncryptionTypes.GCM) {
move logic to decryptPack

2024-07-09 06:11 UTC, markus7017 commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
> +            if (encryptionType == EncryptionTypes.GCM) {
move logic to encryptPack()

2024-07-21 18:55 UTC, lsiepel commented
@markus7017 ping me when your finished

2024-07-22 09:09 UTC, lovery commented
@lsiepel @markus7017, sorry for the noise, I found a few things, I didn't like and fix them today, so I think now I addressed everything in the @markus7017 review.
Unfortunately I can't test with old equipment because I don't have it, but I will ask now in the community form if someone is willing to test my changes.

2024-07-22 09:19 UTC, lsiepel commented
> @lsiepel @markus7017, sorry for the noise, I found a few things, I didn't like and fix them today, so I think now I addressed everything in the @markus7017 review. Unfortunately I can't test with old equipment because I don't have it, but I will ask now in the community form if someone is willing to test my changes.

Great! Ping me when you think it is tested enough. If you get zero response we might need to get this into 4.3m1 so it can have some test mileages before 4.3 stable.

Sidenote: preferably don’t use git force push as we can’t track changes.

2024-07-25 09:57 UTC, lsiepel requested changes
Without deeper knowledge of the encryption used, i have added some minor comments.

2024-07-25 09:57 UTC, lsiepel commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeRequestDTO.java
>   * The GreeBindRequest4Gson class is used by Gson to hold values to be send to
```suggestion
 * The GreeRequest class is used by Gson to hold values to be send to
```

2024-07-25 09:57 UTC, lsiepel commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeReqStatusPackDTO.java
>  public class GreeReqStatusPackDTO {
While at it, can you adjust the javadoc to match the classname

2024-07-25 09:57 UTC, lsiepel commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeReqStatusDTO.java
> +public class GreeReqStatusDTO extends GreeRequestDTO {
While at it, can you adjust the javadoc to match the class name

2024-07-25 09:57 UTC, lsiepel commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeExecResponseDTO.java
> +public class GreeExecResponseDTO extends GreeResponseBaseDTO {
While at it, can you adjust the javadoc to match the class name

2024-07-25 09:57 UTC, lsiepel commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeBindResponseDTO.java
> +public class GreeBindResponseDTO extends GreeResponseBaseDTO {
While at it, can you adjust the javadoc to match the class name

2024-07-25 09:57 UTC, lsiepel commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeBaseDTO.java
> + * The GreeBase4Gson class is used as a base class for request and response classes
```suggestion
 * The GreeBaseDTO class is used as a base class for request and response classes
```

2024-07-25 09:57 UTC, lsiepel commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeScanResponseDTO.java
> +public class GreeScanResponseDTO extends GreeResponseBaseDTO {
Please correct javadoc

2024-07-25 09:57 UTC, lsiepel commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeScanResponsePackDTO.java
> +public class GreeScanResponsePackDTO {
Please correct javadoc method name

2024-07-25 09:57 UTC, lsiepel commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeStatusResponseDTO.java
> +public class GreeStatusResponseDTO extends GreeResponseBaseDTO {
Please correct javadoc method name

2024-07-25 09:57 UTC, lsiepel commented on bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
> +                logger.error("Missing string for tag property for GCM encryption data");
```suggestion
                logger.warn("Missing string for tag property for GCM encryption data");
```

2024-08-01 09:36 UTC, lsiepel approved these changes
Thanks, LGTM

2024-08-01 09:36 UTC, merged