Fix channel provider throwing exception
openhab/openhab-addons pull request #17030
Opened 2024-07-09 14:52 UTC by seime

Ref https://community.openhab.org/t/sensibo-binding-4-2-does-not-work/157116

2024-07-11 20:04 UTC, jlaur requested changes
Thanks for the fixes! I have made some small suggestions.

2024-07-11 20:04 UTC, jlaur commented on bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/model/SensiboModel.java
> +                .findFirst();
Could be simplified to:
```suggestion
        final String macAddressWithoutColons = macAddress.replace(":", "");
        return pods.stream().filter(pod -> macAddressWithoutColons.equalsIgnoreCase(pod.getMacAddress())).findFirst();
```

2024-07-16 16:39 UTC, lsiepel approved these changes
Thanks, LGTM

2024-07-16 16:40 UTC, merged

2024-07-16 17:25 UTC, jlaur approved these changes