[homekit] synthesize Thermostat.TargetTemperature in some cases
openhab/openhab-addons pull request #17060
Opened 2024-07-14 23:06 UTC by ccutrer

If HeatingThresholdTemperature or CoolingThresholdTemperature are provided, TargetTemperature doesn't have to be. in fact, TargetTemperature may not behave as your actual thermostat behaves. So document how HomeKit expects it, and then implement a synthesis of that behavior if your thermostat simply does not have it.

2024-07-15 11:52 UTC, lsiepel requested changes
Very minor, otherwise LGTM. Would be nice for @yfre to confirm.

2024-07-15 11:52 UTC, lsiepel commented on bundles/org.openhab.io.homekit/README.md
> +```xtend
Please use java for item code fences:
For reference: https://github.com/openhab/openhab-docs/issues/999

2024-07-16 18:25 UTC, lsiepel approved these changes

2024-07-22 15:42 UTC, ccutrer commented
ping @yfre

2024-07-22 18:16 UTC, merged

2024-07-23 06:57 UTC, grzegorz914 commented
Looks like if we use all operations mode include AUTO  and the heating and cooling threshold is not set then the accessory is not published 

```
2024-07-23 08:17:19.992 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:Biuro_Hvac (Type=GroupItem, Members=6, State=NULL, Label=Biuro HVAC, Category=heating, Tags=[HVAC], Groups=[Biuro])  HomeKit type: 'Thermostat' characteristic: 'Empty'
2024-07-23 08:17:20.055 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:Kuchnia_Hvac (Type=GroupItem, Members=6, State=NULL, Label=Kuchnia HVAC, Category=heating, Tags=[HVAC], Groups=[Kuchnia])  HomeKit type: 'Thermostat' characteristic: 'Empty'
2024-07-23 08:17:20.063 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:Jadalnia_Hvac (Type=GroupItem, Members=6, State=NULL, Label=Jadalnia HVAC, Category=radiator, Tags=[HVAC], Groups=[Jadalnia])  HomeKit type: 'Thermostat' characteristic: 'Empty'
2024-07-23 08:17:20.075 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:PrzedpokojDuzy_Hvac (Type=GroupItem, Members=6, State=NULL, Label=Przedpokój duży HVAC, Category=radiator, Tags=[HVAC], Groups=[PrzedpokojDuzy])  HomeKit type: 'Thermostat' characteristic: 'Empty'
2024-07-23 08:17:20.122 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:Cwu (Type=GroupItem, Members=16, State=NULL, Label=C.W.U., Category=faucet, Tags=[Equipment], Groups=[Dom])  HomeKit type: 'Thermostat' characteristic: 'Empty'
2024-07-23 08:17:20.138 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:Sypialnia_Hvac (Type=GroupItem, Members=6, State=NULL, Label=Sypialnia HVAC, Category=heating, Tags=[HVAC], Groups=[Sypialnia])  HomeKit type: 'Thermostat' characteristic: 'Empty'
2024-07-23 08:17:20.178 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:LazienkaPietro_Hvac (Type=GroupItem, Members=6, State=NULL, Label=Łazienka piętro HVAC, Category=heating, Tags=[HVAC], Groups=[LazienkaPietro])  HomeKit type: 'Thermostat' characteristic: 'Empty'
2024-07-23 08:17:20.191 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:Adam_Hvac (Type=GroupItem, Members=6, State=NULL, Label=Adam HVAC, Category=heating, Tags=[HVAC], Groups=[Adam])  HomeKit type: 'Thermostat' characteristic: 'Empty'
2024-07-23 08:17:20.280 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:Kamila_Hvac (Type=GroupItem, Members=6, State=NULL, Label=Kamila HVAC, Category=heating, Tags=[HVAC], Groups=[Kamila])  HomeKit type: 'Thermostat' characteristic: 'Empty'
2024-07-23 08:17:20.286 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:Garderoba_Hvac (Type=GroupItem, Members=6, State=NULL, Label=Garderoba HVAC, Category=heating, Tags=[HVAC], Groups=[Garderoba])  HomeKit type: 'Thermostat' characteristic: 'Empty'
2024-07-23 08:17:20.326 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:PrzedpokojMaly_Hvac (Type=GroupItem, Members=6, State=NULL, Label=Przedpokój mały HVAC, Category=radiator, Tags=[HVAC], Groups=[PrzedpokojMaly])  HomeKit type: 'Thermostat' characteristic: 'Empty'
2024-07-23 08:17:20.417 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:Salon_Hvac (Type=GroupItem, Members=6, State=NULL, Label=Salon HVAC, Category=radiator, Tags=[HVAC], Groups=[Salon])  HomeKit type: 'Thermostat' characteristic: 'Empty'
2024-07-23 08:17:20.435 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:LazienkaParter_Hvac (Type=GroupItem, Members=6, State=NULL, Label=Łazienka parter HVAC, Category=heating, Tags=[HVAC], Groups=[LazienkaParter])  HomeKit type: 'Thermostat' characteristic: 'Empty' ```