[http] Improve escaping of URLs
openhab/openhab-addons pull request #17110
Opened 2024-07-20 19:04 UTC by J-N-K

Related to #12350 
Related to #17039 

@jamesmelville FYI

2024-07-21 08:19 UTC, lsiepel requested changes
Otherwise LGTM. Will also wait for @jamesmelville to comment before merge.

2024-07-21 08:19 UTC, lsiepel commented on bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/Util.java
> +        String queryString = url.getQuery();
`queryString` does not seem to be used.

2024-07-21 09:14 UTC, lsiepel approved these changes

2024-07-24 07:01 UTC, jamesmelville approved these changes
Sorry I'm only on a phone but I think this looks good. I think you've now made the change backwards compatible for users using the old escapedURL flag which is great. Minor comments on naming. Thanks @J-N-K @lsiepel

2024-07-24 07:53 UTC, J-N-K commented
@jamesmelville Thanks!

2024-07-24 10:20 UTC, merged