[homekit] adjust default ranges for some characteristics
openhab/openhab-addons pull request #17157
Opened 2024-07-26 16:09 UTC by ccutrer

Fixes #15818

 * Illuminance can obviously get down to 0, instead of 0.0001lx (especially if your sensor only reports integer values)
 * Raise Illuminance ceiling slightly (from 100k lx)
 * Adjust default range of Color Temperature to the warmest and coolest bulbs I could find on Amazon (for settable characteristics, you don't want to have too large of a range because HomeKit will often use those ranges to determine the scale of the slider). Original is 50-400 mired/2500-20000 K
 * Lower min value of current temperature from 0°C to -100°C (going below freezing is not unusual. lowest recorded temperature on earth is -89.2°C. I just chose a nice round number)

2024-07-26 21:31 UTC, lsiepel commented
Best would be that these values are changed in HAP. Would be nice for @yfre to comment anyway, he’s away for some weeks, so let’s wait a bit before merge this

Code wise I would prefer to have these values in a constant for clarity and maintainability. Otherwise LGTM

2024-07-26 21:39 UTC, ccutrer commented
The values in HAP-Java match what's in the HAP specification, and should not change (really, we should be able to omit them in the JSON if it matches the default).

2024-08-13 14:52 UTC, lsiepel commented
https://github.com/openhab/openhab-addons/issues/15268 Makes me wonder. If 0.0 snaps to the min value. How would that work with persistence at startup as that could somehow lead to undesired results?!

2024-08-24 12:49 UTC, lsiepel commented
Gentle ping @yfre

2024-08-24 16:22 UTC, yfre commented
@lsiepel  thanks for the reminder. 
in general, Java-HAP has started as re-usable library for different projects.. not sure though if it is used somewhere else besides OpenHAB. 

nevertheless, i agree with Cody - Java-HAP should be a reference implementation for the HAP protocol and default values should be according to Apple HAP specification, even if they are not good. 

i support this PR and the approach of redefining default values in OH.  but i would also prefer them be defined as constant a not as numbers directly inline.

2024-08-24 16:23 UTC, yfre requested changes
please make default values to constants.

2024-09-09 21:52 UTC, lsiepel approved these changes
Thanks, LGTM

2024-09-09 21:53 UTC, merged