[basicprofiles] Add a CHAIN profile
openhab/openhab-addons pull request #17192
Opened 2024-08-01 18:33 UTC by J-N-K

This profile allows to chain transformations, similar to what MQTT or HTTP offer in the state and command transformation configurations.

2024-08-13 08:57 UTC, jlaur requested changes
Thanks! Only one comment for the documentation.

2024-08-13 08:57 UTC, jlaur commented on bundles/org.openhab.transform.basicprofiles/README.md
> +JSONPATH:$.device.status.temperature∩MAP:doorlock.map
Shouldn't it be:
```suggestion
JSONPATH:$.device.status.lock∩MAP:doorlock.map
```

?

2024-08-16 01:27 UTC, jimtng commented
Should `toChannel` be called `toHandler`, to be consistent with the Script Profile and also [Debounce time profile](https://www.openhab.org/addons/transformations/basicprofiles/#debounce-time-profile)?

2024-08-16 15:32 UTC, J-N-K commented
For the script profile we have `toItemScript`, `commandFromItemScript`, `stateFromItemScript`. So also different.

2024-08-17 03:48 UTC, jimtng commented
Maybe we can adopt `FromItem` and change the Debounce time profile, i.e. support the old `toHandlerDelay` with a deprecation warning, and add `fromItemDelay`?

2024-08-20 14:29 UTC, ccutrer commented
Is there a reason this is a profile, and not another transformation? Seems useful to be able to chain transformations anywhere a transformation can be used. And it should automatically be usable as a profile, no, since all transformations can be used as profiles?

2024-10-29 18:22 UTC, lsiepel commented
Ping @J-N-K please fox the conflict ? Also have  similar question as @ccutrer.

2024-10-29 18:32 UTC, J-N-K commented
I currently don't have time to work on this one. If someone wants implement that, I'm fine with it.

2024-10-29 18:32 UTC, closed without merging