[freeboxos] First big update of README
openhab/openhab-addons pull request #17279
Opened 2024-08-17 17:45 UTC by lolodomo

Fixes #17074
Fixes #17077
Fixes #17080

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

2024-08-18 08:59 UTC, clinique approved these changes
I love this ! LGTM

2024-08-18 20:27 UTC, lsiepel requested changes
Nice improvement has been done this binding and now also to the documentation! 
One minor comment is that all readme.md headers should be capitalized, otherwise LGTM

2024-08-19 06:51 UTC, lolodomo commented
> One minor comment is that all readme.md headers should be capitalized

You mean the first letter ?

2024-08-19 07:04 UTC, lolodomo commented
Done

2024-08-19 07:11 UTC, lsiepel commented
> > One minor comment is that all readme.md headers should be capitalized
> 
> You mean the first letter ?

Each word.

2024-08-19 07:13 UTC, lsiepel requested changes

2024-08-19 07:13 UTC, lsiepel commented on bundles/org.openhab.binding.freeboxos/README.md
> +### Api bridge
```suggestion
### Api Bridge
```

2024-08-19 07:13 UTC, lsiepel commented on bundles/org.openhab.binding.freeboxos/README.md
> +### Server things
```suggestion
### Server Thing
```

2024-08-19 07:13 UTC, lsiepel commented on bundles/org.openhab.binding.freeboxos/README.md
> +### Player things
```suggestion
### Player Thing
```

2024-08-19 07:13 UTC, lsiepel commented on bundles/org.openhab.binding.freeboxos/README.md
> +### Phone things
```suggestion
### Phone Thing
```

2024-08-19 07:13 UTC, lsiepel commented on bundles/org.openhab.binding.freeboxos/README.md
> +### Network device things
```suggestion
### Network Device Thing
```

2024-08-19 07:13 UTC, lsiepel commented on bundles/org.openhab.binding.freeboxos/README.md
> +### Freeplug thing
```suggestion
### Freeplug Thing
```

2024-08-19 07:13 UTC, lsiepel commented on bundles/org.openhab.binding.freeboxos/README.md
> +### Repeater thing
```suggestion
### Repeater Thing
```

2024-08-19 07:13 UTC, lsiepel commented on bundles/org.openhab.binding.freeboxos/README.md
> +### Virtual Machine thing
```suggestion
### Virtual Machine Thing
```

2024-08-19 07:13 UTC, lsiepel commented on bundles/org.openhab.binding.freeboxos/README.md
> +### Home node things
```suggestion
### Home Node Thing
```

2024-08-19 15:42 UTC, lolodomo commented
> Each word.

Done.
I kept the plural (Things) when the section concerns several thing types.

2024-08-19 17:05 UTC, lsiepel requested changes
Nevermind

2024-08-19 17:06 UTC, merged