[freeboxos] Add translatable labels for discovered things
openhab/openhab-addons pull request #17287
Opened 2024-08-18 15:26 UTC by lolodomo

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

2024-08-18 16:15 UTC, clinique approved these changes

2024-08-18 19:46 UTC, lsiepel requested changes
Just a typo, otherwise LGTM

2024-08-18 19:46 UTC, lsiepel commented on bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/discovery/FreeboxOsDiscoveryService.java
> +                                .orElse("@text/discovery.netwrok-device.label [ \"%s\" ]".formatted(macString)))
```suggestion
                                .orElse("@text/discovery.network-device.label [ \"%s\" ]".formatted(macString)))
```

Typo, also need a fix in properties file.

2024-08-19 07:19 UTC, lsiepel approved these changes

2024-08-19 07:19 UTC, merged