[melcloud] Improve null handling
openhab/openhab-addons pull request #17295
Opened 2024-08-19 14:58 UTC by lsiepel

- Fixes https://github.com/openhab/openhab-addons/issues/17268
- Adds null annotations
- Fixes SAT errors
Test jar (4.2.0+): https://1drv.ms/u/s!AnMcxmvEeupwjv9oizGjOiFJV0gIJw?e=Qi4RZT

2024-08-20 10:14 UTC, lucacalcaterra commented
> * Fixes [[melcloud] after update to openHAB 4.2.1: HANDLER_REGISTERING_ERROR #17268](https://github.com/openhab/openhab-addons/issues/17268)
> * Adds null annotations
> * Fixes SAT errors
>   Test jar (4.2.0+): https://1drv.ms/u/s!AnMcxmvEeupwjv9oizGjOiFJV0gIJw?e=Qi4RZT

@lsiepel I've tested it. Working. Great Work !

2024-08-29 15:12 UTC, lsiepel commented
Also a candidate for backporting to 4.2.x

2024-09-09 17:45 UTC, lolodomo requested changes

2024-09-09 17:45 UTC, lolodomo commented on bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/handler/MelCloudDeviceHandler.java
>              refreshTask = scheduler.scheduleWithFixedDelay(this::getDeviceDataAndUpdateChannels, 1,
this.refreshTask

2024-09-09 17:45 UTC, lolodomo commented on bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/handler/MelCloudHeatpumpDeviceHandler.java
>              refreshTask = scheduler.scheduleWithFixedDelay(this::getDeviceDataAndUpdateChannels, 1,
this.refreshTask

2024-09-09 18:22 UTC, lsiepel commented on bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/handler/MelCloudDeviceHandler.java
>              refreshTask = scheduler.scheduleWithFixedDelay(this::getDeviceDataAndUpdateChannels, 1,
Done

2024-09-09 18:22 UTC, lsiepel commented on bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/handler/MelCloudHeatpumpDeviceHandler.java
>              refreshTask = scheduler.scheduleWithFixedDelay(this::getDeviceDataAndUpdateChannels, 1,
Done

2024-09-09 19:21 UTC, lolodomo approved these changes
LGTM, thank you

2024-09-09 19:21 UTC, merged