[SenecHome] Add writeable Charging Modes
openhab/openhab-addons pull request #17474
Opened 2024-09-24 17:23 UTC by BigFood2307

This PR improves the SenecHome Binding by adding access to two writable charging modes for the battery systems.
This means adding the general capability of write commands to the binding and implementing the HTTPS commands for the necessary parameters.
It was shortly discussed in the [Bindings Forum thread](https://community.openhab.org/t/senechome-binding/108152/40?u=bigfood2307)
With this addition the user can now force the battery system to charge to full or enter it into storage/transport mode.

Only one other person was able to test the new version. They had issues, although that might have been due to missmatched openHab versions.
On my own system, the updated binding has been running for ~6 months without issue.
[Here](https://github.com/BigFood2307/openhab-addons/releases/tag/senechome-charge-modes-1) is the binary I have been using for oh 4.2

Direct link to jfrog for convenience, since the template asked me to :)
https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.senechome/

2024-09-26 09:25 UTC, BigFood2307 commented
> How do these two charging modes relate? From the descriptions they seem conflicting, If you turn on both switches, what will happen?

True, they are conflicting. I think I tested it some time ago and turning a second mode on, it would turn the first one back off.
I can test that again on the weekend.


> Did you consider to have one `chargeMode` channel, that contains a list of possible options like: `lithium charge`, `safe charge`, `nomale charge` mode etc. ?

A single channel with 3 options never entered my mind, but could actually be a good idea. I will look into how I can implement fixed state options for the channel.

2024-10-05 09:47 UTC, BigFood2307 commented
Thanks for the feedback!
I did some testing and can now confirm, that Storage Mode always just overrides Safe Charge Mode.
I still think the idea of combining them into one channel was good, so I implemented that now.

2024-10-05 11:21 UTC, lsiepel requested changes
Some textual improvements now this has changed. I think this was a good move to this list instead of the switches, thank you. We expect a milestone this weekend, so if you are able to look at it today we can get it into 4.3.0m2

2024-10-05 11:21 UTC, lsiepel commented on bundles/org.openhab.binding.senechome/README.md
> +|                               | STORAGE        | in liStorageMode, the battery will try to reach 25% SOC                  |
```suggestion
| chargeMode                | OFF/CHARGE/    | In `CHARGE` mode, the battery will try to fill as quickly as possible   |
|                               | STORAGE        | in `STORAGE` mode, the battery will try to reach 25% SOC                  |
```

You might need to adjust the whirespaces,

2024-10-05 11:21 UTC, lsiepel commented on bundles/org.openhab.binding.senechome/README.md
> +- Lithium Storage Mode is intended (according to the manual) for disassembly and transport. It is untested if it has any side effects.
```suggestion
- The chargeMode `STORAGE` also known as Lithium Storage Mode is intended (according to the manual) for disassembly and transport. It is untested if it has any side effects.
```

2024-10-05 11:21 UTC, lsiepel commented on bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeApi.java
> +        return Objects.requireNonNull(gson.fromJson(responseString, SenecHomeResponse.class));
```suggestion
        return Objects.requireNonNull(gson.fromJson(response.getContentAsString(), SenecHomeResponse.class));
```

2024-10-05 11:21 UTC, lsiepel commented on bundles/org.openhab.binding.senechome/src/main/resources/OH-INF/i18n/senechome.properties
> +channel-type.senechome.saveChargeMode.label = Save Charge Mode
These are old valuesw, don't forget to run the i18n tool: `mvn i18n:generate-default-translations`

2024-10-05 11:21 UTC, lsiepel commented on bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeHandler.java
> +
```suggestion
```

2024-10-05 11:21 UTC, lsiepel commented on bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeBindingConstants.java
> + * @author Lukas Pindl - Update for writing to safeChargeMode
```suggestion
 * @author Lukas Pindl - Update for writing to chargeMode
```

2024-10-05 11:21 UTC, lsiepel commented on bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeHandler.java
> + * @author Lukas Pindl - Update for writing to safeChargeMode
```suggestion
 * @author Lukas Pindl - Update for writing to chargeMode
```

2024-10-05 13:40 UTC, BigFood2307 commented
Should now be fixed 👍

2024-10-05 14:56 UTC, lsiepel approved these changes
Thanks LGTM

2024-10-05 14:57 UTC, merged