[pushbullet] Remove unimplemented channels and thing parameters
openhab/openhab-addons pull request #17482
Opened 2024-09-28 22:14 UTC by jsetton

This change removes unimplemented channels and thing parameters.

It also hardcodes the API Base URL parameter since there is no way to run your own Pushbullet server as far as I know.

2024-09-30 14:04 UTC, hakan42 commented
Did you check whether bot configurations with the "old" syntax will still work after your cleanup? If not, then this would be a breaking change which needs to be documented.

2024-09-30 16:20 UTC, jsetton commented
> Did you check whether bot configurations with the "old" syntax will still work after your cleanup?

The `token` parameter remains the same. As far as the other two parameters, the binding would no longer process them even though existing thing configuration may have a configuration for them.

For the `name` parameter, it was never used. So it has no impact. For the `apiUrlBase` parameter, it could have an impact if it was configured to point to another URL but I can't see how someone would do this. What was your original intent in making this setting configurable? The Pushbullet API isn't an open sources product as far as I know.

2024-09-30 17:50 UTC, hakan42 commented
> For the `name` parameter, it was never used. So it has no impact. For the `apiUrlBase` parameter, it could have an impact if it was configured to point to another URL but I can't see how someone would do this. What was your original intent in making this setting configurable?

For `apiUrlBase`, actually I had a mock server running at home. Not for making it publicly available but for testing the addon without running into rate limiting and bricking the bot.

And for `name` , actually I had a responding bot but the code for this never was mature enough, so I decided to keep it for later improvement but in the end did not have a valid use case anymore.

2024-10-05 13:20 UTC, lsiepel requested changes
Thanks, LGTM. This cleanup would require a thing structure upgrade by deleting the three channels and setting the thingtypeversion. 
For reference: https://www.openhab.org/docs/developer/bindings/thing-xml.html#updating-thing-types

2024-10-05 17:50 UTC, jsetton commented
> This cleanup would require a thing structure upgrade by deleting the three channels and setting the thingtypeversion.

Done.

2024-10-05 19:46 UTC, lsiepel approved these changes
Thanks, LGTM

2024-10-05 19:46 UTC, merged