[mqtt.homeassistant] fix newStyleChannels
openhab/openhab-addons pull request #17491
Opened 2024-10-01 19:42 UTC by ccutrer

This fixes a couple of problems. The biggest is that if multiple components were single channel OR no-name, they would all get mapped to a "groupId" of "", and the next time the Thing started, all but one of them would disappear unless new discovery information was received. While fixing that, I fixed two other issues:
 * Multi-channel components with a blank name were getting all their channels dumped into the top level of no group. In the newStyleChannels world, we don't care about the component's name anymore - multi-channel components get a group, single-channel components do not.
 * Instead of statically saying that certain components are only ever single or multi-channel components, determine at runtime if a component only added a single channel, and if so re-classify it as a single-channel component, moving its channel out of the group (and just naming it as the group was named)

2024-10-01 21:44 UTC, ccutrer commented
While this commit changes channel IDs, it shouldn't be considered breaking because it just further refines another breaking change to channel IDs introduced in 4.3

2024-10-02 20:42 UTC, lsiepel commented
> While this commit changes channel IDs, it shouldn't be considered breaking because it just further refines another breaking change to channel IDs introduced in 4.3

To what PR do you relate this comment?

2024-10-02 20:43 UTC, ccutrer commented
https://github.com/openhab/openhab-addons/pull/16600

2024-10-02 20:49 UTC, lsiepel commented
Thanks, that PR was not considered breaking due to:
_Existing things will not change their UID._ 

Before i look at the code i already wonder if that statement is still true. Not looking for an alltime backwards compatbility here, but just to be clear on the user impact. Ant to determine if an upgrade notification would be usefull.

2024-10-02 20:52 UTC, ccutrer commented
Right, I guess that is a bit confusing. So that PR is not-breaking to existing installations. New things created will get the new style channels. This PR "breaks" compatibility with those new style channels. But because that PR has not gone out in a proper release yet, it shouldn't be considered _actually_ breaking.

2024-10-02 20:57 UTC, lsiepel commented
> Right, I guess that is a bit confusing. So that PR is not-breaking to existing installations. New things created will get the new style channels. This PR "breaks" compatibility with those new style channels. But because that PR has not gone out in a proper release yet, it shouldn't be considered _actually_ breaking. Especially since I finally tracked down why I sometimes have channels missing, and it's due to that PR (i.e. new style channels never fully worked).

I don't consider it breaking compared to the previous PR as that is still the development branch, but just wanted to be sure that exising (openHAB 4.2.2 or before) installations are not affected.

2024-10-02 20:59 UTC, ccutrer commented
... and this can't be merged yet, either. I just found a bug that some components/channels don't send their updates on properly

2024-10-03 20:59 UTC, ccutrer commented
@lsiepel this _should_ be ready now. I'll continue testing over the next few days anyway, but things seem pretty happy and I've moved on to other fixes and enhancements. And I labeled it as a bug - this really needs to get in before 4.3 goes final, otherwise more complex Home Assistant things will be intermittently broken.

2024-10-04 15:24 UTC, lsiepel requested changes
Some small comments. As you are doing a ton of work to this binding, it would be nice if you could also try to reduce the compiler warnings while doing so. Not asking you to do it all in once, but just keep it in mind.

2024-10-04 15:24 UTC, lsiepel commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
> +                logger.error("Cannot restore component {}: {}", thing, e.getMessage());
```suggestion
                logger.warn("Cannot restore component {}: {}", thing, e.getMessage());
```

2024-10-04 15:24 UTC, lsiepel commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DefaultSchemaLight.java
> +                    HSBType hsb = (HSBType) (colorValue.getChannelState());
```suggestion
                if (colorValue.getChannelState() instanceof HSBType hsb) {
```

2024-10-04 15:24 UTC, lsiepel commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DefaultSchemaLight.java
> +                        : HSBType.WHITE;
```suggestion
                HSBType newOnState = colorValue.getChannelState() instanceof HSBType newOnStateTmp
                        ? newOnStateTmp
                        : HSBType.WHITE;
```

2024-10-07 18:19 UTC, lsiepel commented
itest seems to fail.

2024-10-07 21:21 UTC, ccutrer commented
fixed (I did have to rebase so that itests compiled correctly; presumably due to #17509

2024-10-07 21:28 UTC, merged