[WIP] Upgrade Karaf from 4.4.6 to 4.4.7
openhab/openhab-addons pull request #17515
Opened 2024-10-06 10:36 UTC by holgerfriedrich

Still WIP. Depends on Karaf 4.4.7 release.
Relates to https://github.com/openhab/openhab-core/pull/4406.
I updated a few commons libs in the addons as well to keep it in sync with core. Hope this does not break something.

* Sync runtime dependencies with Karaf 4.4.7, most notably:
   * BouncyCastle 1.78.1
   * CXF 3.6.4
   * Jackson 2.17.2
   * JNA 5.15.0
   * JAXB 2.3.9
   * commons-io 2.17.0
   * commons-lang3 3.17.0
   * commons-logging 1.3.4
 * Resolve itest runbundles

2024-11-24 14:13 UTC, david-pace approved these changes
Looks good for `boschshc` 👍

2024-11-24 15:16 UTC, ccutrer approved these changes
LGTM for mqtt.homeassistant and jinja

2025-01-18 13:35 UTC, david-pace requested changes
Found an assertion that should be slightly adapted in our `boschshc` tests.

2025-01-18 13:35 UTC, david-pace commented on bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClientTest.java
> +                "Received invalid content in response, expected type org.openhab.binding.boschshc.internal.devices.bridge.dto.SubscribeResult: com.google.gson.stream.MalformedJsonException: Untermina
Looking at this assertion again, I realize that only the first part comes from our openHAB code. We should not test messages from external libraries since this makes our tests unstable. Therefore I would propose to test only that the exception message starts with our message:

```java
assertThat(e.getMessage(), startsWith(
                "Received invalid content in response, expected type org.openhab.binding.boschshc.internal.devices.bridge.dto.SubscribeResult:"));
```

This check uses Hamcrest assertions as recommended in the [unit test guidelines](https://www.openhab.org/docs/developer/tests.html). The corresponding imports are:

```
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.StringStartsWith.startsWith;
```

2025-01-24 17:20 UTC, holgerfriedrich commented on bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClientTest.java
> +                "Received invalid content in response, expected type org.openhab.binding.boschshc.internal.devices.bridge.dto.SubscribeResult: com.google.gson.stream.MalformedJsonException: Untermina
@david-pace done as requested

2025-01-24 19:48 UTC, david-pace commented on bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClientTest.java
> +                "Received invalid content in response, expected type org.openhab.binding.boschshc.internal.devices.bridge.dto.SubscribeResult: com.google.gson.stream.MalformedJsonException: Untermina
Perfect, thank you very much :+1:

2025-01-24 19:50 UTC, david-pace approved these changes
Thank you for enhancing the unit test, looks good for `boschshc` 👍

2025-01-26 14:17 UTC, wborn approved these changes

2025-01-26 14:47 UTC, merged