[tesla] Add null annotations
openhab/openhab-addons pull request #17582
Opened 2024-10-17 18:13 UTC by lsiepel

- Fix null annotations
- Fix compile warnings
- Updated and moved DTO's to dto folder
 
Only form code perspective, needs some testing to be sure no regression occures.

Test jar 4.3.0 (should also work with 4.2.x) https://1drv.ms/u/s!AnMcxmvEeupwj4oOcmeYDamnLAcyAg?e=k2nzcw

2024-10-25 20:57 UTC, lsiepel commented
@kaikreuzer would you be able to test this binding? As you seem one of the few that not be forced to use the fleet api yet.

2024-10-26 21:41 UTC, kaikreuzer commented
Hey @lsiepel! Thanks for the clean-ups! I've installed this version on my production system and will watch it over the day tomorrow. So far, it seems to work and I do not see any issues in my logs. Will keep you posted.

2024-10-27 14:58 UTC, kaikreuzer commented
Unfortunately, I do not seem to receive any updates anymore - so I would say that this PR seems to break the functionality.
I'd need more time to deeply look into it in order to debug the issue...

2024-10-28 09:30 UTC, lsiepel commented
> ook into it in order to debug the issue...

Too bad, looking at the code again i can't spot the obvious error. If you can provide debug logs and your observations i can try to look at it. But maybe it is simpler for you to just debug it when having the car connected.

2024-11-20 21:12 UTC, lsiepel commented on bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaEventEndpoint.java
> -        }
@kaikreuzer  without a debug log it is hard to find the culprit. These lines might be related. I would not expect a runtimeexception here so i removed it. Maybe i shouldn't have done that.

Any way a log would be highly appreciated.

2024-12-08 11:26 UTC, kaikreuzer requested changes
Thanks @lsiepel, I finally got it running (my local development env was broken due to https://github.com/openhab/openhab-distro/pull/1697, which I only figured out today.

It seems that your code works well after all - there is just one small bug that causes it to break. Once this is fixed, it looks good!

2024-12-08 11:26 UTC, kaikreuzer commented on bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/VehicleData.java
> +    public int vehicleId;
This used to be a String and `int` is causing parsing exceptions. I assume this was changed by mistake?
```suggestion
    public String vehicleId;
```

2024-12-08 12:21 UTC, lsiepel commented
Done, I leave it to you if you want to merge it for 4.3.0 or not.

2024-12-08 13:35 UTC, kaikreuzer approved these changes
Let's merge, thanks!

2024-12-08 13:35 UTC, merged