Added totalKWH channels for Shelly Pro 3EM
openhab/openhab-addons pull request #17602
Opened 2024-10-21 12:58 UTC by JonathanvdGHU

# Added totalKWH channels for Shelly Pro 3EM
# Description
I added the missing `totalKWH` channels for the Shelly Pro 3EM, see [issue](https://github.com/openhab/openhab-addons/issues/16772). There is also a new `totalKWH` channel created for the entire device. The channels for `reactivewatts` are left untouched because I couldn't locate the associated data.

After linking items to the `totalKWH` channels I noticed that the values only update when you restart OpenHAB at least once.
This also happens for other channels so it's not related to this pull request.

I am btw not really familiar with the code so there are probably some improvements.

2024-10-21 16:17 UTC, JonathanvdGHU commented
@jlaur To be honest, it's a bug fix and an enchancement at the same time. The `totalKWH` channel for each meter already existed but some work was forgotten and that was why it didn't work.

2024-10-21 19:56 UTC, lsiepel requested changes
One question, otherwise LGTM

2024-10-21 19:56 UTC, lsiepel commented on bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly_de.properties
> +channel-type.shelly.totalKWH.description = Gesamtverbrauchte Energie in kWh (wird beim Neustart zurückgesetzt)
Please revert changes to this file. Translations are created in crowdin. 
For reference: https://www.openhab.org/docs/developer/utils/i18n.html#managing-translations

2024-10-22 05:58 UTC, JonathanvdGHU commented
> One question, otherwise LGTM Channels do not seem to be created dynamically, so this would also require thing upgrade instructions.
> 
> For future PR's it would be nice to seperate the bug fix and the enhancement. This would make it possible to 1. easy backport bug fixes and 2. list the changes/fixes speerately in the release notes.

The `totalKWH` channel for each meter is created when data is written to it. So those are created dynamically. The `totalKWH` channel for the entire device also pops-up without changing anything other than replacing the current Shelly binding.

I don't mind to creating an extra pull request, so would you prefer I make a new one?

2024-10-25 17:45 UTC, lsiepel approved these changes

2024-10-25 17:45 UTC, merged