Multiple bindings - Fix README formatting regression
openhab/openhab-addons pull request #17619
Opened 2024-10-23 02:46 UTC by mlobstein

Fix the formatting in the README for multiple bindings where two line breaks were used for formatting. Regression of #17422.

2024-10-23 18:48 UTC, jlaur commented
For reference: https://www.markdownguide.org/basic-syntax/#line-break-best-practices

I was not aware of that. [Before](https://www.openhab.org/addons/bindings/panasonicbdp/) #17422:

![image](https://github.com/user-attachments/assets/f17fa96e-0adb-4947-a529-dc03b55f17d6)

[After](https://next.openhab.org/addons/bindings/panasonicbdp/):

![image](https://github.com/user-attachments/assets/8e85c81f-d0e1-4e02-84e4-36d3c052e405)

@mlobstein - thanks for the fix. Do you actually want space between the paragraphs, or just a line break? If you want just a line break (as before), I guess you would need to either add the two spaces again, or `<br>`?

2024-10-23 19:03 UTC, mlobstein commented
> 
> @mlobstein - thanks for the fix. Do you actually want space between the paragraphs, or just a line break? If you want just a line break (as before), I guess you would need to either add the two spaces again, or `<br>`?

I fixed the MR description since it was not clear. I am fine with leaving this as is and not using two consecutive spaces to make a line break since they will likely get flagged again in future cleanup efforts.

2024-10-23 19:21 UTC, jlaur commented
> I am fine with leaving this as is and not using two consecutive spaces to make a line break since they will likely get flagged again in future cleanup efforts.

Thanks for the feedback. One more thing: I see you are binding maintainer for the five README's fixed in this PR. Just to be sure - was it only those five README's having this regression out of the 209 changed, or did you only check those for which you are code owner?

2024-10-23 19:28 UTC, lsiepel requested changes
Thanks for correcting the previous cleanup. This sometimes happens to bulk PR's, sorry.

Have one comment and one question. The list need a empty line before and after the list. Also check if you want the maintain the double star emphasis for the lists, not sure if they are still usefull in all cases.

2024-10-23 19:28 UTC, lsiepel commented on bundles/org.openhab.binding.kaleidescape/README.md
> +- `player` Any KPlayer, M Class [M300, M500, M700] or Cinema One 1st Gen player
If this is changed to a list, there should be an empty line:
MD032/blanks-around-lists: Lists should be surrounded by blank linesmarkdownlint[MD032](https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md032.md)

```suggestion

- `player` Any KPlayer, M Class [M300, M500, M700] or Cinema One 1st Gen player
```

2024-10-23 19:28 UTC, lsiepel commented on bundles/org.openhab.binding.panasonicbdp/README.md
> +- **Remote Device Operation: On**
See previous list comment.
```suggestion

- **Remote Device Operation: On**
```

2024-10-23 19:28 UTC, lsiepel commented on bundles/org.openhab.binding.panasonicbdp/README.md
> +- **Player Settings/Network/Voice Control: On**
See previous list comment.
```suggestion

- **Player Settings/Network/Voice Control: On**
```

2024-10-23 19:28 UTC, lsiepel commented on bundles/org.openhab.binding.panasonicbdp/README.md
> +- **Player Settings/System/Quick Start: On**
See previous list comment.
```suggestion

- **Player Settings/System/Quick Start: On**
```

2024-10-23 19:28 UTC, lsiepel commented on bundles/org.openhab.binding.roku/README.md
> +- Home
See previous list comment.
```suggestion

- Home
```

2024-10-23 19:28 UTC, lsiepel commented on bundles/org.openhab.binding.roku/README.md
> +- ChannelUp
See previous list comment.
```suggestion

- ChannelUp
```

2024-10-23 19:28 UTC, lsiepel commented on bundles/org.openhab.binding.tivo/README.md
> +- UP
```suggestion

- UP
```

2024-10-23 19:28 UTC, lsiepel commented on bundles/org.openhab.binding.vizio/README.md
> +- PowerOn
```suggestion

- PowerOn
```

2024-10-23 20:27 UTC, mlobstein commented
> > I am fine with leaving this as is and not using two consecutive spaces to make a line break since they will likely get flagged again in future cleanup efforts.
> 
> Thanks for the feedback. One more thing: I see you are binding maintainer for the five README's fixed in this PR. Just to be sure - was it only those five README's having this regression out of the 209 changed, or did you only check those for which you are code owner?

I only checked the ones where I am the owner since I knew what they had looked like before.

2024-10-23 20:51 UTC, jlaur commented
> I only checked the ones where I am the owner since I knew what they had looked like before.

@lsiepel - you might then want to somehow check for line endings with two spaces in other changed files in the original PR.

2024-10-24 04:20 UTC, lsiepel commented
> > I only checked the ones where I am the owner since I knew what they had looked like before.
> 
> @lsiepel - you might then want to somehow check for line endings with two spaces in other changed files in the original PR.

Yes, it’s in my list now.

2024-10-25 07:40 UTC, lsiepel approved these changes
Thanks for correcting. LGTM

2024-10-25 07:40 UTC, merged