[openaitts] OpenAI Text-to-Speech binding (new)
openhab/openhab-addons pull request #17733
Opened 2024-11-11 11:33 UTC by Artur-Fedjukevits

The OpenAI TTS (Text-to-Speech) addon for openHAB allows you to integrate OpenAI's Text-to-Speech capabilities into your openHAB system. The advantage of this service over others is that one selected voice can speak different languages. This is useful, for example, in conjunction with chatGPT binding, which will help in learning foreign languages.

Compiled jar - https://fedjukevitsh.com/s/TeaDeLCKSTjD7Yi

2024-11-11 12:54 UTC, jlaur commented on bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/addon/addon.xml
> +	<connection>none</connection>
```suggestion
	<connection>cloud</connection>
```

2024-11-11 12:55 UTC, jlaur commented on bundles/org.openhab.voice.openaitts/pom.xml
> +  <name>openHAB Add-ons :: Bundles :: Voice :: OpenAI Text to Speech</name>
```suggestion
  <name>openHAB Add-ons :: Bundles :: Voice :: OpenAI Text-to-Speech</name>
```

2024-11-11 12:58 UTC, jlaur commented on CODEOWNERS
> +/bundles/org.openhab.voice.openaitts/ @Artur-Fedjukevits
Please move this up before `org.openhab.voice.picotts` so that the list is in alphabetic order.

2024-12-08 09:49 UTC, wborn requested changes
Thanks for the PR! :+1: 

I also added a few comments:

2024-12-08 09:49 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSService.java
> +    private final static Logger logger = LoggerFactory.getLogger(OpenAITTSService.class);
```suggestion
    private final Logger logger = LoggerFactory.getLogger(OpenAITTSService.class);
```

2024-12-08 09:49 UTC, wborn commented on bundles/org.openhab.voice.openaitts/README.md
> +* **voice**  - The voice to use when generating the audio. Previews of the voices are available in the [text to speech guide.](https://platform.openai.com/docs/guides/text-to-speech/voice-options)
```suggestion
* **voice**  - The voice to use when generating the audio. Previews of the voices are available in the [text to speech guide](https://platform.openai.com/docs/guides/text-to-speech/voice-options).
```

2024-12-08 09:49 UTC, wborn commented on bundles/org.openhab.voice.openaitts/README.md
> +The OpenAI TTS (Text-to-Speech) addon for openHAB allows you to integrate OpenAI's Text-to-Speech capabilities into your openHAB system. The advantage of this service over others is that one selected
It's easier to diff future changes when sentences starts on a new line:

```suggestion
The OpenAI TTS (Text-to-Speech) addon for openHAB allows you to integrate OpenAI's Text-to-Speech capabilities into your openHAB system.
The advantage of this service over others is that one selected voice can speak different languages.
This is useful, for example, in conjunction with chatGPT binding, which will help in learning foreign languages.
```

2024-12-08 09:49 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSService.java
> +
Remove empty line after opening brace:

```suggestion
```

2024-12-08 09:49 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSService.java
> +
Remove empty line after opening brace:

```suggestion
```

2024-12-08 09:49 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSService.java
> +
Remove empty line before closing brace:

```suggestion
```

2024-12-08 09:49 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/config/config.xml
> +			<label>Api key</label>
```suggestion
			<label>API key</label>
```

2024-12-08 09:49 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/config/config.xml
> +			<description>OpenAI Api key.</description>
```suggestion
			<description>OpenAI API key.</description>
```

2024-12-08 09:49 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/config/config.xml
Please add all English translations for this file so the texts can be translated using Crowdin.
To generate the content of this file run: `mvn i18n:generate-default-translations`

See also: https://www.openhab.org/docs/developer/utils/i18n.html

2024-12-08 09:52 UTC, wborn commented on bundles/pom.xml
Please undo all changes in this file except for adding `<module>org.openhab.voice.openaitts</module>`  before `org.openhab.voice.picotts` so it's easier to find the module as they are sorted.

2024-12-08 09:54 UTC, wborn commented on pom.xml
> +      </dependency>
This  should not be necessary:

```suggestion
```

2024-12-08 09:57 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/addon/addon.xml
> +	<description>OpenAI TTS Service uses to perform text-to-speech in openHAB.</description>
This seems to be an incomplete sentence.

2024-12-08 10:00 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSService.java
> + * @author Artur Fedjukevits - Initial contribution
Is the API documented? If so add a link here.

2024-12-08 10:02 UTC, wborn commented on bundles/org.openhab.voice.openaitts/README.md
> +The OpenAI TTS (Text-to-Speech) addon for openHAB allows you to integrate OpenAI's Text-to-Speech capabilities into your openHAB system. The advantage of this service over others is that one selected
While you're at it:

* addon :arrow_right: add-on
* chatGPT :arrow_right: ChatGTT

2024-12-08 10:04 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSService.java
> +    private Gson gson = new Gson();
```suggestion
    private final HttpClient httpClient;
    private final Gson gson = new Gson();
```

2024-12-08 10:07 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSService.java
> +    }
As it does not change, just make the voices a constant using a one liner like:

```java
private final Set<Voice> VOICES = Stream.of("nova", "alloy", "echo", "fable", "onyx", "shimmer").map(OpenAITTSVoice::new).collect(Collectors.toSet());
```

2024-12-09 09:00 UTC, Artur-Fedjukevits commented
Thanks @wborn ! 
I hope I took all your comments into account.

2024-12-09 18:15 UTC, wborn commented
Thanks for addressing my comments. 👍 

This one is still open: https://github.com/openhab/openhab-addons/pull/17733#discussion_r1874726820

2024-12-09 20:59 UTC, Artur-Fedjukevits commented
> Thanks for addressing my comments. 👍
> 
> This one is still open: [#17733 (comment)](https://github.com/openhab/openhab-addons/pull/17733#discussion_r1874726820)

Yes, because after removing this, I am getting these errors:

`Error:  Could not find the selected project in the reactor: :org.openhab.addons.reactor.features.karaf @  Error:  Could not find the selected project in the reactor: :org.openhab.addons.reactor.features.karaf -> [Help 1]`

2024-12-09 21:07 UTC, wborn commented
Add it to the BOM instead:

https://github.com/openhab/openhab-addons/blob/main/bom/openhab-addons/pom.xml

2024-12-10 16:52 UTC, wborn commented on bom/openhab-addons/pom.xml
> +    </dependency>
```suggestion
    <dependency>
      <groupId>org.openhab.addons.bundles</groupId>
      <artifactId>org.openhab.voice.openaitts</artifactId>
      <version>${project.version}</version>
    </dependency>
```

2024-12-10 20:55 UTC, wborn requested changes
I saw a few more improvements after scrolling through the code again:

2024-12-10 20:55 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/config/config.xml
> +		</parameter>
Would be nice if you can select this in the UI by providing the options:

```xml
<options>
	<option value="alloy">Alloy</option>
	<option value="echo">Echo</option>
	<option value="fable">Fable</option>
	<option value="nova">Nova</option>
	<option value="shimmer">Shimmer</option>
	<option value="onyx">Onyx</option>
</options>
```

You can also allow other values by adding:

```xml
<limitToOptions>false</limitToOptions>
```

That way it is still possible to use other options if they become available in the future without first having to update the add-on.

2024-12-10 20:55 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/config/config.xml
> +		</parameter>
Can you also add the available options for this parameter so it can be selected in the UI?

2024-12-14 17:52 UTC, wborn requested changes

2024-12-14 17:52 UTC, wborn commented on .vs/openhab-addons/v17/.wsuo
Please remove this file.

2024-12-14 17:52 UTC, wborn commented on .vs/slnx.sqlite
Please remove this file.

2024-12-15 11:22 UTC, wborn requested changes
Thanks for addressing my comments!
I also gave it a brief test today and it seems to work fine. :+1: 
Here are a few more comments I ran into while testing the add-on:

2024-12-15 11:22 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSService.java
> +        content.addProperty("voice", config.voice);
It should synthesize text based on `voice.getUID()` otherwise it is ignoring the voice selected by the user.

2024-12-15 11:22 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/config/config.xml
> +		</parameter>
That also means that this config should be removed as the selected voice is part of the `synthesizeForCache` call:

```suggestion
```

2024-12-15 11:22 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSVoice.java
> +        return label;
Capitalizing the string would be nice using `org.openhab.core.util.StringUtils.capitalize`.

2024-12-15 11:22 UTC, wborn commented on bundles/org.openhab.voice.openaitts/README.md
> +This is useful, for example, in conjunction with ChatGPT binding, which will help in learning foreign languages.
Can you also explain or link to the pricing? That saves time for users who do not want to pay or enter credit card details.

2024-12-15 11:22 UTC, wborn commented on bundles/org.openhab.voice.openaitts/README.md
> +* **voice**  - The voice to use when generating the audio. Previews of the voices are available in the [text to speech guide](https://platform.openai.com/docs/guides/text-to-speech/voice-options).
```suggestion
```

2024-12-15 11:22 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSConfiguration.java
> +    public String voice = "nova";
```suggestion
```

2024-12-15 11:22 UTC, wborn commented on bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/config/config.xml
> +		</parameter>
It's a secret so it should not be displayed in the UI so to hide it add:

```xml
<context>password</context>
```

2024-12-15 20:42 UTC, wborn commented on bundles/org.openhab.voice.openaitts/pom.xml
> +    <version>4.3.0-SNAPSHOT</version>
```suggestion
    <version>5.0.0-SNAPSHOT</version>
```

2024-12-19 20:35 UTC, wborn commented
Yes yes very good. 👍
I'll soon have another look as it is almost holiday time. 🎄 ⛄

2024-12-24 17:15 UTC, wborn approved these changes
Thanks a lot! It works very well now. :slightly_smiling_face: :+1:

2024-12-24 17:19 UTC, merged

2024-12-26 21:50 UTC, felixschndr commented
> Compiled jar - https://fedjukevitsh.com/s/TeaDeLCKSTjD7Yi

Does this jar work for 4.3.0 as well or is it only compatible with 5.0?

2024-12-27 08:32 UTC, Artur-Fedjukevits commented
> > Compiled jar - https://fedjukevitsh.com/s/TeaDeLCKSTjD7Yi
> 
> Does this jar work for 4.3.0 as well or is it only compatible with 5.0?

Yes, that jar was compiled for 4.3