[Mideaac] Initial contribution- second try
openhab/openhab-addons pull request #17749
Opened 2024-11-15 15:08 UTC by apella12

This is a second attempt.  The first attempt is closed #17395. Essentially all of the previous comments have been addressed.  The main new change is the separation of the connection manager and the MideaACHandler, (largely rewritten by @lsiepel) these two files are basically new.  I have worked and tested with this version (made some modifications) for several weeks and it seems to work as well as the first attempt now. Also there were a number of new supporting files added by @lsiepel.

For reference the previous intro is here.
I’d like to put this out for new binding review.
This binding was started by the original author as a forum topic but has since had other contributors. I picked it up when I installed a mini-split AC that used the Midea protocol earlier this year, originally to allow for longer polling frequencies. Then as a retirement challenge (no formal java training), decided to attempt to clean it up for official status. I cleaned up the summary report from over 150 items and believe I conformed to current developer guidelines (Java docs, naming, tests, etc.). Along the way added some additional functionality and corrected some code issues.
The discovery and security classes remain largely unchanged from the original author (who I haven’t been able to contact), and work well. The other classes I understand pretty well at this point and hopefully can address any concerns.
As a note, to conform to the guidelines there are breaking changes in naming from the version I published on the forum thread.

2024-12-15 20:45 UTC, wborn commented on bundles/org.openhab.binding.mideaac/pom.xml
> +    <version>4.3.0-SNAPSHOT</version>
```suggestion
    <version>5.0.0-SNAPSHOT</version>
```

2024-12-16 15:15 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/pom.xml
> +    <version>4.3.0-SNAPSHOT</version>
done

2025-01-03 22:09 UTC, lsiepel commented
This is not forgotten, the time I have to spare is consumed by the ZUI binding at the moment. So don’t wait for me.

2025-01-03 23:31 UTC, apella12 commented
@lsiepel Well I'm not really waiting. I'm working on other things too.  There shouldn't be much to review after you rewrote the connection manager. I did a few things to make it more robust to run without the A/C connected to the cloud and fixed some things that you left hanging.  I have had it polling for months without issues.  It is not exactly A/C season, so no one is exactly clamoring for an update.  Hopefully you or someone else can have a look in a couple of months as we get towards spring.

2025-02-19 15:29 UTC, lsiepel commented
Forgot about this one, sorry. I might have some time to review in the next days.
It was tested and all works as expected?

2025-02-19 15:48 UTC, apella12 commented
Yes, it is working fine.  I have been using it since the last commit.  Decided to rebase today in case something in the OH5.0 causes a problem, but it passed checks

2025-02-19 19:11 UTC, lsiepel requested changes
Thanks for not leaving this PR/binding. It has improved, i also see more room for improvement. Besides some new minor issues that i probably missed before, i think the DTO and connection structure can benefit from some more work and thinking.

2025-02-19 19:11 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +        startScheduler(2, config.pollingTime, TimeUnit.SECONDS);
Reduce complexity and remove the startScheduler method too: 
```suggestion
        scheduledTask = scheduler.scheduleWithFixedDelay(this::pollJob, 2, config.pollingTime, TimeUnit.SECONDS);
```

2025-02-19 19:11 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                logger.info("Token and Key obtained from cloud, saving, back to initialize");
Prevend logging to info at all places
```suggestion
                logger.debug("Token and Key obtained from cloud, saving, back to initialize");
```

2025-02-19 19:11 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                logger.warn("Can't retrieve Token and Key from Cloud; email, password and/or cloud parameter error");
this logging is not needed when the thing state is set.
```suggestion
```

2025-02-19 19:11 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +    }
Remove this and use `String.isBlank()` wherever it is called.

2025-02-19 19:11 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +            logger.info("Failed to connect after {} tries. Try again with next scheduled poll", maxTries);
```suggestion
            logger.debug("Failed to connect after {} tries. Try again with next scheduled poll", maxTries);
```

2025-02-19 19:11 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                        logger.debug("An interupted error (socket retry) has occured {}", ex.getMessage());
Stop processing and exit immediate when an InterruptException occurs.

2025-02-19 20:48 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +        return ("0".equalsIgnoreCase(deviceId) || deviceId.isBlank() || ipPort <= 0 || ipAddress.isBlank()
OK

2025-02-19 20:48 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +        return (!email.isBlank() && !password.isBlank() && !"".equals(cloud));
Ok

2025-02-19 20:48 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +        return (!key.isBlank() && !token.isBlank() && !"".equals(cloud));
Ok

2025-02-19 20:48 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +
ok

2025-02-19 20:49 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +
OK

2025-02-19 21:13 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +		<description>Turn the AC on and off.</description>
OK

2025-02-19 21:15 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +    public static String bytesToHex(byte[] bytes) {
I inherited this from the Initial Contribution.  Will need study

2025-02-19 21:16 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +    }
I inherited this from the Initial Contribution. Will need study

2025-02-19 21:16 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +    }
I inherited this from the Initial Contribution. Will need study

2025-02-19 21:16 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +		<description>Target temperature.</description>
OK

2025-02-19 21:17 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +		<label>Target temperature</label>
Think I have them checked in next draft

2025-02-19 21:23 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/README.md
> +Once the Air Conditioner is on the network (WiFi active) the other required parameters can be discovered automatically.
Slight change; Once the Air Conditioner is on the network (WiFi active) most required parameters will be discovered automatically.  The nuance is that deviceId, token, key and version are discovered automatically if you added the cloud and password (unless V2), you still need to enter pollingTime and socket timeout and prompt tone (but they do have fault values).  Not really sure what you want here.

2025-02-19 21:24 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/README.md
> +}
I moved the curly bracket out, if that was what you meant

2025-02-19 21:25 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/README.md
> +Switch the log level to TRACE or DEBUG on the UI Settings Page (Add-on Settings)
ok

2025-02-19 21:25 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/security/Security.java
> +        }
ok

2025-02-19 21:30 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/dto/CloudDTO.java
> +        Request request = httpClient.newRequest(url).method(HttpMethod.POST).timeout(15, TimeUnit.SECONDS);
This was from the initial contributor.  There are several back and forth JSONs. I don't think there is a lot of logic except to satisfy the cloud connection.  I'm not going to be able to change this.  If it is a deal stopper, I'll just leave as a forum binding, sorry.

2025-02-19 21:31 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/discovery/MideaACDiscoveryService.java
> +            while (true) {
Probably, but also inherited code

2025-02-19 21:33 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/discovery/Connection.java
> +    public static final int MIDEAAC_RECEIVE_PORT = 6440;
Don't really know.

2025-02-19 21:39 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +            logger.warn("Configuration invalid for {}", thing.getUID());
I don't understand this comment.  Are you saying that because the Thing is INITIALIZING we don't need logging?

2025-02-19 21:40 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                logger.warn("Discovery needed, discovering....{}", thing.getUID());
Same question as above

2025-02-19 21:43 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    discoveryService.discoverThing(config.ipAddress, this);
IT has been months since I have studied this code.  Will need to think about this.  It has always been there.

2025-02-19 21:43 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                logger.debug("MideaACHandler config of {} is invalid. Check configuration", thing.getUID());
See above question?

2025-02-19 21:52 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                return;
I put that in to stop that thread since the get tokenKeyCloud calls initialize().

2025-02-19 21:52 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                return;
Ok I think

2025-02-19 21:59 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +            logger.warn("Configuration invalid for {}", thing.getUID());
The logging is duplicate information when the Thing state is also set. So remove the logging.

2025-02-19 22:00 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +        startScheduler(2, config.pollingTime, TimeUnit.SECONDS);
As noted above it has been a while.  However, I hate to mess with this section as I had issues with the original split of the connection manager with multiple schedulers getting started (one reason to kill the thread on line 220).  I need the logic in the startScheduler method.

2025-02-19 22:00 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                logger.info("Token and Key obtained from cloud, saving, back to initialize");
ok

2025-02-19 22:01 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                logger.warn("Can't retrieve Token and Key from Cloud; email, password and/or cloud parameter error");
See question above

2025-02-19 22:02 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                return;
Not a preferred pattern. The tolenKeyoud should do the token stuff and not start a initialize. That method should only be called by the framework

2025-02-19 22:08 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/discovery/Connection.java
> +    public static final int MIDEAAC_RECEIVE_PORT = 6440;
If the discovery works as expected we leave this as is

2025-02-19 22:09 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +    }
ok

2025-02-19 22:11 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +            logger.info("Failed to connect after {} tries. Try again with next scheduled poll", maxTries);
Ok.  Had that for testing, forgot to take out

2025-02-19 22:21 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                        logger.debug("An interupted error (socket retry) has occured {}", ex.getMessage());
As I recall that won't work as I intended (with 3 tries).  The exceptions aren't serious and ephemeral in nature.  I haven't had that INFO log message in months (after I went from 2 to three tries.  That's why I forgot it was there.

2025-02-20 09:35 UTC, lsiepel requested changes
Marked some previous comments as resolved. Found some new ones, but nothing big. Let's slowly continue and narrow the remaining issues down and fix them together.

2025-02-20 09:35 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +            logger.warn("Unable to proces command: {}", e.getMessage());
When an authentication exception occurs, i guess it is permanenet. When a timeout occurs, it is transient and the binding should recover. You might want to handle both cases seperate.
```suggestion
            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.COMMUNICATION_ERROR, e.getMessage());
```

2025-02-20 09:35 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                logger.warn("Discovery needed, discovering....{}", thing.getUID());
```suggestion
```

2025-02-20 09:35 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +
```suggestion
```

2025-02-20 09:35 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                    logger.warn("Authentication reponse unexpected data length ({} instead of 72)!", response.length);
As the exception bubbles up and should set the thing state, it would be enough to log this into debug.
```suggestion
                    logger.debug("Authentication reponse unexpected data length ({} instead of 72)!", response.length);
```

2025-02-20 09:35 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                                logger.warn("Processing response exception: {}", ex.getMessage());
What kind of exception do we expect here? This catches all kind of exceptions. I guess we should throw a `MideaException` here?

2025-02-20 09:35 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    logger.error("Discovery failure for {}: {}", thing.getUID(), e.getMessage());
Change it to debug as the message might contain valueable information for debugging.
```suggestion
                    logger.debug("Discovery failure for {}: {}", thing.getUID(), e.getMessage());
```

2025-02-20 09:35 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +        return (!key.isBlank() && !token.isBlank() && !"".equals(cloud) && !cloud.isBlank());
The `isBlank()` covers this. No need to double up.
```suggestion
        return (!key.isBlank() && !token.isBlank() && !cloud.isBlank());
```

2025-02-20 09:35 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +        return (!email.isBlank() && !password.isBlank() && !"".equals(cloud) && !cloud.isBlank());
```suggestion
        return (!email.isBlank() && !password.isBlank() && !cloud.isBlank());
```

2025-02-20 09:35 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/README.md
> +| power                        | Switch             | Turn the AC on and off.                                                                                |           |          |
```suggestion
| power                        | Switch             | Turn the AC on or off.                                                                                 |           |          |
```

2025-02-20 09:35 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/README.md
> +Once the Air Conditioner is on the network (WiFi active) the other required parameters can be discovered automatically.
Here you provide a lot more information then in the readme. This is what chatgpt makes out of it. Please check and adapt the text so that it gives the user enough guidance to set it up correctly.l

```
The key parameters—like deviceId, token, key, and version—are automatically discovered once the air conditioner is connected to the WiFi and you’ve provided the necessary cloud and password (unless it's a version 2 device).

However, you’ll still need to manually enter a few parameters such as: Polling time, Socket timeout, Prompt tone.
```

2025-02-20 09:35 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/README.md
> +    Selection item=swing_mode label="Midea AC Louver Swing Mode"
```suggestion
    Frame label="AC Unit" {
        Text item=outdoor_temperature label="Outdoor Temperature [%.1f °F]"
        Text item=indoor_temperature label="Indoor Temperature [%.1f °F]"
        Setpoint item=target_temperature label="Target Temperature [%.1f °F]" minValue=63.0 maxValue=78 step=1.0
        Switch item=power label="Midea AC Power"
        Switch item=temperature_unit label= "Temp Unit" mappings=[ON="Fahrenheit", OFF="Celsius"]
        Selection item=fan_speed label="Midea AC Fan Speed"
        Selection item=operational_mode label="Midea AC Mode"
        Selection item=swing_mode label="Midea AC Louver Swing Mode"
```

2025-02-20 09:35 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/README.md
> +}
Created a new comment with a suggestion. I meant to add indentation not removing a curly brace.

2025-02-20 09:35 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/discovery/MideaACDiscoveryService.java
> +            while (true) {
Will proceed for now, this can be adapted later on.

2025-02-20 13:58 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/README.md
> +Once the Air Conditioner is on the network (WiFi active) the other required parameters can be discovered automatically.
Made more of a step-by-step process in next commit.

2025-02-20 14:03 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/README.md
> +}
I didn't take it out, just tabbed it over.  Will look at new comment (I'm working from the top down)

2025-02-20 14:07 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                logger.warn("Discovery needed, discovering....{}", thing.getUID());
Ok in next commit

2025-02-20 14:09 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                logger.debug("MideaACHandler config of {} is invalid. Check configuration", thing.getUID());
Ok in next commit

2025-02-20 14:12 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                logger.warn("Can't retrieve Token and Key from Cloud; email, password and/or cloud parameter error");
Ok in next commit

2025-02-20 14:24 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +        logger.debug("Connected to IP {}", ipAddress);
What the intention here was one INFO for the first time and debug if it was recovering from some problem, but not disconnected. Otherwise there is nothing in the log to show it is running.  Note starting date.
`2025-01-24 16:45:59.796 [INFO ] [nternal.connection.ConnectionManager] - Connected to IP 192.168.0.246`
This is when I updated to the rebased binding
`2025-02-19 10:58:07.986 [INFO ] [nternal.connection.ConnectionManager] - Connected to IP 192.168.0.246`
This is when I deleted the email and password this morning to recheck that it could be done
`2025-02-20 08:54:25.405 [INFO ] [nternal.connection.ConnectionManager] - Connected to IP 192.168.0.246`

2025-02-20 14:29 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                    logger.info("Problem with reading response, skipping {} skipped count since startup {}", command,
ok.  I used that to track health, but probably no value to user

2025-02-20 14:35 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +            logger.warn("Unable to proces command: {}", e.getMessage());
Ok This was part of the code you rewrote and have never seen an exception, so don't know what else to say.

2025-02-20 14:38 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +
I think I have all these addressed in next commit

2025-02-20 14:51 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                                logger.warn("Processing response exception: {}", ex.getMessage());
I got an error message when with that 
![image](https://github.com/user-attachments/assets/99bd79ec-f0ef-4752-a9bc-57c90b255df7)

2025-02-20 14:54 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +        return (!key.isBlank() && !token.isBlank() && !"".equals(cloud) && !cloud.isBlank());
ok

2025-02-20 14:56 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/README.md
> +| power                        | Switch             | Turn the AC on and off.                                                                                |           |          |
ok

2025-02-20 14:58 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/README.md
> +    Selection item=swing_mode label="Midea AC Louver Swing Mode"
ok

2025-02-20 15:28 UTC, apella12 commented
In no particular order, 1) I'm not sure how to use the OH standard conversions and where to put the .toLowerCase since I do not see that in the documentation. 2) The exception in the retry I'm trying to address is simply a timeout. 3) Elsewhere, I was trying to avoid breaking something that I fixed earlier would cause me to go back and fix again.  It has been months and I'm not recalling all the issues I had getting to the fix. 4) I also attached a log of the DTO actions, it appears to me everything is needed.  The only logic is to pull from the cloud responses to compose the next message.

2025-02-20 18:08 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                                logger.warn("Processing response exception: {}", ex.getMessage());
Throw not catch

2025-02-21 16:12 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +    public static String bytesToHex(byte[] bytes) {
Ok figured this out. Testing now, but should be in next commit

2025-02-21 16:12 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +    }
Ok figured this out. Testing now, but should be in next commit

2025-02-21 16:13 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +    }
Ok figured this out. Testing now, but should be in next commit

2025-02-21 16:14 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/README.md
> +}
ok.  Should be in last commit

2025-02-21 16:16 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    logger.error("Discovery failure for {}: {}", thing.getUID(), e.getMessage());
ok

2025-02-21 23:52 UTC, apella12 commented
Figured out how to leverage the OH core util hex/byte and separated the socket timeout exception from anything else.  Seems to still work, but with the magnitude of changes am testing overnight. Have tested scan, retrieve key/token, normal polling and temperature changes. Had one timeout exception that worked as expected. 9 seconds = 4 for timeout and 5 delay for next try.
```
2025-02-21 17:19:56.320 [DEBUG] [nternal.connection.ConnectionManager] - Disconnecting from device at 192.168.0.246
2025-02-21 17:20:05.326 [DEBUG] [nternal.connection.ConnectionManager] - Socket retry count 1, Socket timeout connecting to 192.168.0.246: Connect timed out
2025-02-21 17:20:05.329 [DEBUG] [nternal.connection.ConnectionManager] - Device at IP: 192.168.0.246 requires authentication, going to authenticate
```
Normal connection is less that 10ms.
```
2025-02-21 17:09:53.751 [DEBUG] [nternal.connection.ConnectionManager] - Disconnecting from device at 192.168.0.246
2025-02-21 17:09:53.757 [DEBUG] [nternal.connection.ConnectionManager] - Device at IP: 192.168.0.246 requires authentication, going to authenticate
```

2025-02-21 23:53 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                                logger.warn("Processing response exception: {}", ex.getMessage());
Think I have that fixed

2025-02-21 23:54 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +        logger.debug("Connected to IP {}", ipAddress);
Added a comment to explain

2025-02-21 23:56 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                        logger.debug("An interupted error (socket retry) has occured {}", ex.getMessage());
I have separated the catches

2025-02-22 14:39 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                return;
I did have one thought on this.  If I make any change to the UI page, including the location (unrelated to the device itself), initialize() is triggered.  I don't understand why it is not automatically triggered when the key and token are updated from the internet and saved. (hence the need for the call)? Also without the call the new token and key aren't passed back and updated (authorization fails even though the UI shows token and key).

2025-02-24 00:32 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/dto/CloudDTO.java
> +        Request request = httpClient.newRequest(url).method(HttpMethod.POST).timeout(15, TimeUnit.SECONDS);
Eliminated the dto folder and DTO classes.  Made Cloud nonNull.

2025-07-06 11:19 UTC, lsiepel commented
Ok, so i'll try to reboot this review proces, where are we with this PR? Previously we tried to seperate the handler and the connection manager, how did that work out?

2025-07-15 20:11 UTC, apella12 commented
@lsiepel I didn't see your reopening comment.  Must not have been notified (or thought it was related to my ZUI nofications)...

To recap; you wrote code to separate the connection manager and the MideaAC handler and I got it working again and addressed all the comments from February 21 and before.   Since then I extracted several features from the HA version (and with the help of Copilot in VSC converted them to java). Also there have been a couple of new users of the forum version that had new messages that incorporated using some Lua code references.  also because of the new features reworked some part of the code.  All that is complete now, but the binding is 25% longer. I was just making a final pass to ensure the ReadMe matched with the additional capabilities

2025-07-15 20:25 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/security/Crc8.java
> +            }
Changed this in latest commit

2025-07-21 18:47 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/pom.xml
> +    <version>5.0.0-SNAPSHOT</version>
```suggestion
    <version>5.1.0-SNAPSHOT</version>
```

2025-08-23 11:46 UTC, jlaur commented
Please add yourself to the [CODEOWNERS](https://github.com/openhab/openhab-addons/blob/main/CODEOWNERS) file.

2025-10-30 15:01 UTC, apella12 commented
@lsiepel Since you are busy with the zwave-js, possibly someone else can review this. Coming up on 1 year anniversary.

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACBindingConstants.java
> +    public static final String CHANNEL_WATTS = "watts";
Usually we do not expose a channel as unit but the dimension.

I would expect.  `energy`,  `current` and `power` for these three. Usually they have a time aspect or treshold or whatever they represent.

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public String password = "password1";
i would remove the default and leave it blank

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public String email = "nethome+us@mailinator.com";
why not leave it blank?

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public int keyTokenUpdate = 0;
i would change this to hours. as lifecycle in days is uncommon and prevents future granular changes without breaking current configurations.

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +        return (Utils.validateIP(ipAddress));
```suggestion
        return Utils.validateIP(ipAddress);
```

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +        return (!email.isBlank() && !password.isBlank() && !cloud.isBlank());
```suggestion
        return !email.isBlank() && !password.isBlank() && !cloud.isBlank();
```

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +    public static String bytesToHex(byte[] bytes) {
The content of this method was adapted according to https://github.com/openhab/openhab-addons/pull/17749/files#r1961996508

Now it is just a proxy and everywhere it is called it should be replaced by the core variant directly.

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +        return HexUtils.hexToBytes(string);
Similar suggestion to remove this proxy.

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +    public static String tokenHex(int nbytes) {
Looks like this method can be replaced by the https://www.openhab.org/javadoc/latest/org/openhab/core/util/stringutils#getRandomHex(int)

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/cloud/Cloud.java
> +            logger.warn("an interupted error has occurred{}", e.getMessage());
interrupt flag should be reset. Also should return fast and stop exeecution (in a controlled manner)

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/cloud/Cloud.java
> +                logger.warn("Error {} logging to Cloud: {}", code, msg);
This logger shows that the interaction with this class and its callers can be improved.
How would the caller know that the login failed and route that to the thing lifecycle? 
 
Usually these type of classes throw a custom exception like `LoginFailedException` or `TimeOutException`. 
Either way it is good to make a distinction between transient and permanent problems so the caller can act on it.

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                Thread.sleep(5000);
Noticed two things:
1. the condition seems the reverse. currently it sleeps when not resending
2. a hardcoded sleep is a code smel, what other options did you consider?
3. both a synchronized method and a long (5 second) sleep are error prone.

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                    } catch (InterruptedException ex) {
Not fully fixed this comment: https://github.com/openhab/openhab-addons/pull/17749/files#r1962228100
The interupt flag needs to be restored and exit quickly

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +            ((CommandSet) command).setPromptTone(promptTone);
```suggestion
        if (command instanceof CommandSet cmdSet) {
            cmdSet.setPromptTone(promptTone);
```

2025-10-30 20:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                // Note, but continue anyway for second write if needed.
when interrupted it should stop processing and not retrying.

2025-10-30 21:18 UTC, lsiepel requested changes
Sorry i had you waiting this long. I got distracted many times and needed some focus time to finish this review. 
Finished all files. The handler might need some refactoring to create logical units that do a strict amount of work. especially around the initialize method and how it is called from other places.

Anyway, i think that depending on the follow-up there might be one more review, but as i have covered everything, it will not take as long as before.

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/discovery/MideaACDiscoveryService.java
> +            while (true) {
Atleast create a timer to break out of the loop.

var start = now
while(now < start+timeout){
.....

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/discovery/MideaACDiscoveryService.java
> +            while (true) {
See previous comment for breaking out of while loop.

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/CommandBase.java
> +        return (byte) sum;
```suggestion
        return (byte) ((255 - (sum % 256)) + 1);
```

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<channel id="watts" typeId="watts"/>
Additional to https://github.com/openhab/openhab-addons/pull/17749#discussion_r2479147336

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +				<default>password1</default>
See other comment about default password.

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="token" type="text" required="false">
I think we can drop this as it is retrieved by the binding, there is no need to make this a configuration option.

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="key" type="text" required="false">
I think we can drop this as it is retrieved by the binding, there is no need to make this a configuration option.

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="pollingTime" type="decimal" required="true" min="30" unit="s">
Can be marked advanced.

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="energyPoll" type="decimal" required="true" min="0" unit="m">
Can be marked advanced. (also applies to some other configuration options)

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +				<context>pollingTime</context>
Does not seem to be a valid context, why add this? (same to other configuration options)

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +				<label>Poll frequency in seconds</label>
Labels should be < 23 chars, 2-3 words and each word should be capitalized.  (please also check the other labels)
This is commonly labelled as `Refresh Interval`  (and the apramweter would be `refreshInterval`

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="keyTokenUpdate" type="decimal" required="false" min="0" unit="d">
When you get a token, it usually has an expiration date. A common pattern is to refresh it once it is at 80% or something  of that time has passed. This would make this configuration option obsolete.

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="energyDecode" type="boolean" required="true">
Would it be possible to detect this while decoding? It would make this parameter obsolete.

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +
```suggestion
```

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    discoveryService.discoverThing(config.ipAddress, this);
This previous comment has not been addressed:
https://github.com/openhab/openhab-addons/pull/17749/files#r1962212773

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                        "Configuration missing, discovery needed. Discovering...");
Please use i18n custom keys when setting the thing state. This would make it possible to add translations.
For reference: https://next.openhab.org/docs/developer/utils/i18n.html#using-custom-keys

(applies to all occurences of `updateStatus` with a thingstatusdetail)

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    getTokenKeyCloud(cloudProvider);
Blocking call should be run async

2025-10-30 21:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +        updateProperties(properties);
i ask myself how usefull it is to have all the above properties in openHAB. They are not used by the binding, only showed to the user by openHAB. When will a user look at this or need this static information?

2025-10-31 18:25 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACBindingConstants.java
> +    public static final String CHANNEL_WATTS = "watts";
changed in next commit

2025-10-31 18:37 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public String password = "password1";
Don't understand. This is used to get the token and key
```
    public boolean isTokenKeyObtainable() {
        return (!email.isBlank() && !password.isBlank() && !cloud.isBlank());
    }
```

2025-10-31 18:37 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public String email = "nethome+us@mailinator.com";
Don't understand. This is used to get the token and key (see above) and in handler 252 to 263
        // Check for valid token and key and/or contact cloud account to get them
```
        if (config.version == 3 && !config.isV3ConfigValid()) {
            if (config.isTokenKeyObtainable()) {
                try {
                    CloudProvider cloudProvider = CloudProvider.getCloudProvider(config.cloud);
                    getTokenKeyCloud(cloudProvider);
                    return;
                } catch (Exception e) {
                    updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.CONFIGURATION_ERROR,
                            "Token and key could not be obtained from Cloud");
                    return;
                }
```

2025-10-31 18:49 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public int keyTokenUpdate = 0;
Days or never seems right to me (hence the zero default). I only put this back in as an option. The original author had this as an option (in days).  
The other concern I picked up from the HA version is one of the websites for the token and key was shutdown and broke the integrations that were updating the token and key. I'd rather remove it.

2025-10-31 18:50 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +        return (Utils.validateIP(ipAddress));
done

2025-10-31 18:51 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +        return (!email.isBlank() && !password.isBlank() && !cloud.isBlank());
Done

2025-10-31 19:16 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +    public static String bytesToHex(byte[] bytes) {
I don't get the reference. It clicks back my PR 17749

2025-10-31 19:17 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +        return HexUtils.hexToBytes(string);
Same question. Remove from Utils and use org.openhab.core.util.HexUtils;?

2025-10-31 19:48 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/cloud/Cloud.java
> +                logger.warn("Error {} logging to Cloud: {}", code, msg);
Took a shot with AI help

2025-10-31 20:54 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                    } catch (InterruptedException ex) {
Made a change for review

2025-10-31 20:57 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +            ((CommandSet) command).setPromptTone(promptTone);
Done

2025-10-31 21:08 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/discovery/MideaACDiscoveryService.java
> +            while (true) {
Not sure I understand. There is a discovery timeout of 10 seconds.
`private static int discoveryTimeoutSeconds = 10;`

2025-10-31 21:12 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/CommandBase.java
> +        return (byte) sum;
done

2025-10-31 21:18 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<channel id="watts" typeId="watts"/>
Made changes for review

2025-10-31 21:24 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="token" type="text" required="false">
There are other ways outside of OH to get token and key (there is a HA python script) Also in the case the cloud goes down in the future, a previous token and key (stored elsewhere) can be added to restore operations. They are edge cases, but are easier to leave in now than have to add later.

2025-10-31 21:29 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="pollingTime" type="decimal" required="true" min="30" unit="s">
Good point. I don't have an example is this correct?
`<parameter name="token" type="text" required="false" advanced="true">`

2025-10-31 21:31 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +				<context>pollingTime</context>
Don't understand. Polling is the main thing going on.

2025-10-31 21:33 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="keyTokenUpdate" type="decimal" required="false" min="0" unit="d">
Note comment above. Token/key are permanent and reusable

2025-10-31 21:37 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="energyDecode" type="boolean" required="true">
Not sure which one you are asking about. The version (which is decoded in discovery) or the energyDecode which is not. HA has a flag I had to try both methods to figure out which one.

2025-10-31 21:38 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +
done

2025-10-31 21:43 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    getTokenKeyCloud(cloudProvider);
Added an AI suggestion.

2025-10-31 21:50 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +        updateProperties(properties);
It has helped me answer questions why can't my device do X? Generally the use is early. I learned a few things about my device that wasn't in the manual.  With Zwave, where I'm more familiar, there are all sorts of information that is similar.

2025-10-31 21:52 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    getTokenKeyCloud(cloudProvider);
Added an AI suggestion

2025-10-31 21:56 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    discoveryService.discoverThing(config.ipAddress, this);
I'm having problems with links to previous comments. I recall adding a catch in this area to address, Not enough?

2025-11-01 08:43 UTC, lsiepel requested changes
A follow up to the previous fixes.

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/cloud/Cloud.java
>                  logger.warn("Error {} logging to Cloud: {}", code, msg);
Now this logger can be changed to debug as the exception is thrown and handled upstream.

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="pollingTime" type="decimal" required="true" min="30" unit="s">
No, a child tag
For reference: https://www.openhab.org/docs/developer/addons/config-xml.html#xml-structure-for-configuration-descriptions

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +				<context>pollingTime</context>
The context tag has a limited set of allowed values.
For reference: https://www.openhab.org/docs/developer/addons/config-xml.html#supported-contexts

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public String password = "password1";
Are you saying that all devices have `Password1` as default password? I'm not asking you to remove the field `password`, but suggesting to remove the default value for that field.

```suggestion
    public String password = "";
```

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public String email = "nethome+us@mailinator.com";
Same as password comment. Talking about the default value, not the field itself.

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public int keyTokenUpdate = 0;
Not sure if i understand what you are saying, but i'm fine by either removing it or changing it to hours.
A default of 0 would (to me) look like a continuous refreshing of some sort.

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +    public static String bytesToHex(byte[] bytes) {
The link is referring to thisPR and it shows the file it is about, you might need to click 'load file' if it is to large to show the comment.
Anyway, it looks like all these occurences have been adapted in the mean time as i sugested. thanks

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +        return HexUtils.hexToBytes(string);
Yes, similar to what you did with the others. Looks good.

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                Thread.sleep(5000);
This one was left open.

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/discovery/MideaACDiscoveryService.java
> +            while (true) {
Good question. 
It triggered me as this while loop is never stopped if there is no device discovered. I watched the super implementation and that also puzzles me.
I'll need to re-visit this.

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="token" type="text" required="false">
Do you know what the lifetime is of those tokens? roughly?

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +				<label>Poll frequency in seconds</label>
While improved, the units are not needed
`<label>Poll Frequency</label>`

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="energyDecode" type="boolean" required="true">
This comment is for line 133 => `energyDecode` it has two options. Would it be possible to detect this in-line where the decopding takes place. It would make this parameter obsolete. The less parameters, the better.

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    discoveryService.discoverThing(config.ipAddress, this);
this is a blocking call and should run in a seperate thread. the initialize method should return fast.

In this image, you can see the comment just above this textbox and click show resolved (it was marked resolved while it is not)
<img width="1203" height="1033" alt="image" src="https://github.com/user-attachments/assets/36d7fe50-d254-40fc-bd07-5b58f2e90953" />

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                        "Configuration missing, discovery needed. Discovering...");
To be fixed

2025-11-01 08:43 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    getTokenKeyCloud(cloudProvider);
Did you test this?

As the call is now async, the method continuous before the token is obtained. (as that may take a second or two), this could lead to a race condition. A common procedure is to set the thing state to unknown, start an async thread-task that kicks off a private method that does the login procedure and according to the results update the thing state.

Pseudo code:
```
    //..... initialize method
    //set thing state to unknown
    Executors.newSingleThreadExecutor().submit(() -> getTokenAndResume());
    //exit initalize method
```

```
private void getTokenAndResume() {
    getTokenKeyCloud(cloudProvider);
    if (token == valid) {
        // do whatver is needed that is currently happening in initialize method
        // set thing state to online
    } else {
            // probably set thing status to offline (similar to what is happening in initialize)
    }
}
```

2025-11-01 20:41 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/cloud/Cloud.java
>                  logger.warn("Error {} logging to Cloud: {}", code, msg);
Ok

2025-11-01 20:48 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public String password = "password1";
Yes "password1" with "nethome+us@mailinator.com" will retrieve the token and key for any device.

2025-11-01 20:49 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public String email = "nethome+us@mailinator.com";
Yes "password1" with "nethome+us@mailinator.com" will retrieve the token and key for any device.

2025-11-01 20:53 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public int keyTokenUpdate = 0;
I just think someone in the OH community would like to change the token key even if it is unneeded. I have it clearly marked both as days and what zero means
```
Key token update frequency in days
0
Update the Key and Token from the cloud, default 0 to disable. (d)
```

2025-11-01 20:54 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/Utils.java
> +        return HexUtils.hexToBytes(string);
I think this is resolved then?

2025-11-01 21:11 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                Thread.sleep(5000);
I still need to think about it. What the issue I was addressing; I ran the binding while blocking the A/C device IP from accessing the internet. Commands all work fine, but the polling gets flaky (there will be dropped polls, more timeout retries or a few interrupts- and that causes the one info message to repeat).  I think there is some "phone home" communication every hour or so. The retry was to avoid a dropped poll and waiting for the new one. With internet access ON this really is not an issue, so one option is to remove the retry and not promote the idea of blocking the internet access. The SmartHome application also won't work if the internet is blocked. The sleep was from exhaustive trial and error testing. It was my Chinese paranoia.

2025-11-01 21:15 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/discovery/MideaACDiscoveryService.java
> +            while (true) {
Ok. I have had no problems with the UI scan stopping either with or without finding a(nother) device. I could dig through the logs but also recall a message indicating that discovery stopped, if that would help.

2025-11-01 21:16 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +				<default>password1</default>
As noted elsewhere. This is a live password for the default email address

2025-11-01 21:18 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="token" type="text" required="false">
AFAIK they never expire. I have used for months and reused them.

2025-11-01 21:19 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="pollingTime" type="decimal" required="true" min="30" unit="s">
I think I have token and key are advanced now.

2025-11-01 21:24 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="key" type="text" required="false">
If there is some problem with the cloud and the token key get corrupted, you can use a saved (offline) token key pair to restore the binding. Also, for the hard-core textual folks that may have a token key from another source (or an earlier OH pair) these should still be there. I have marked advanced for now.

2025-11-01 21:30 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="energyPoll" type="decimal" required="true" min="0" unit="m">
I'm assuming this is for the energy poll. Done

2025-11-01 21:43 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +				<context>pollingTime</context>
One question, are the context needed. Not sure where they came from. Will give a few a shot

2025-11-01 21:47 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +				<label>Poll frequency in seconds</label>
ok, changed

2025-11-01 21:49 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +			<parameter name="energyDecode" type="boolean" required="true">
No but I marked advanced. Not all devices report energy, mine only reports KWH

2025-11-01 22:12 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    getTokenKeyCloud(cloudProvider);
This was an AI suggestion, but it did work.  Will review, but beyond my java experience

2025-11-02 09:18 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public String password = "password1";
o whow, in that case the code is fine.

2025-11-02 09:20 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public int keyTokenUpdate = 0;
Ok, zero is fine, still hours is more future proof, please adapt.

2025-11-02 09:22 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                Thread.sleep(5000);
My point was that i expect the sleep when (resend == true), but the current condition is the opposite (resend == false)

2025-11-02 09:24 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/discovery/MideaACDiscoveryService.java
> +            while (true) {
ok, not fully understanding the inner works, but it seems to work and this binding is not on its own.

2025-11-02 09:26 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +				<context>pollingTime</context>
it is optional, they are helpfull for the browser / ui / controls.

2025-11-02 14:12 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/MideaACConfiguration.java
> +    public int keyTokenUpdate = 0;
Ok fine, moved to advanced too.

2025-11-02 14:26 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +				<context>pollingTime</context>
After reviewing the documents most can be removed. Left the unambiguous ones. Done in next commit

2025-11-02 14:39 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                        "Configuration missing, discovery needed. Discovering...");
Just to check. I have run `mvn i18n:generate-default-translations -pl :org.openhab.binding.mideaac`, but need to manually add the thing status details in the MideaACHandler.

2025-11-02 15:54 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/connection/ConnectionManager.java
> +                Thread.sleep(5000);
Reviewed. If the resend is true (as it normally is) and the response bytes are still null it hits this `else` (line 401) to start the retry.
```
            } else {
                if (resend) {
                    logger.debug("Resending Command {}", command);
                    resend = false;
                    sendCommand(command, callback);
```
The resend is set to false, so I needed a delay before it tries to create a new socket. As noted elsewhere, I had trouble with an immediate resend. The resend doesn't turn to true again until a successful poll (line 359)
```
            if (responseBytes != null) {
                resend = true;
```

2025-11-03 15:27 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    discoveryService.discoverThing(config.ipAddress, this);
Should be ready for rereview

2025-11-04 21:08 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +				<default>4</default>
Should also be marked advanced.

2025-11-04 21:13 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    getTokenKeyCloud(cloudProvider);
Spent some time to understand this AI suggestion and added some comments in the code. How this works; if the initialize() thread needs to do some discovery or retrieve the token-key it creates the async thread and exits (ends) with a return. If the async thread ends in success it calls initialize() again. The device doesn't go ONLINE (stays UNKNOWN or goes OFFLINE if the async thread has an exception) until one successful poll is completed. 

Also moved the capability properties commands to an async thread. They aren't needed except for diagnosis, so aren't on the critical path. Even if there is a problem, everything will still work, removed the device status from that code.

2025-11-04 21:14 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/resources/OH-INF/thing/thing-types.xml
> +				<default>4</default>
OK (next commit)

2025-11-04 21:24 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                        "Configuration missing, discovery needed. Discovering...");
I think I have this sorted out. With the limited slate of states and descriptions did some consolidation and removed some unnecessary ones. I have assumed that `e.getMessage()` override the content in the i18n.

2025-11-04 21:34 UTC, lsiepel requested changes
I think almost all comments are addressed, my main concern is the initialize method. 
The openHAB model seems stable, that is one of the most important parts.

2025-11-04 21:34 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +        updateStatus(ThingStatus.UNKNOWN);
First check if the configuration is valid, before setting the state to unknown.

2025-11-04 21:34 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    "Required configuration parameter(s) are missing or invalid.");
Please stick to the allowed thing state combinations:
For reference: https://www.openhab.org/docs/concepts/things.html#status-details

2025-11-04 21:34 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                                "Could not retrieve required parameters from device or the cloud.");
Please use i18n keys for all thing states. You where already looking into this, restating to not forget.

2025-11-04 21:34 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +    public void initialize() {
This initialize method needs some refactoring. I'm happy to help, but you should also need to understand what is going on here.

The `initialize()` method currently performs multiple responsibilities in one place:
- Validating configuration
- Attempting discovery or token/key retrieval
- Establishing device communication
- Fetching capabilities
- Starting scheduled background tasks

This makes the method long and a bit difficult to follow. The logic is solid, but readability and maintainability can be improved by splitting the flow into smaller, clearly named helper methods.


Together with early returns the method would be short, straight forward and simple to adapt to prevent multiple status updates. in a row.

2025-11-04 21:34 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                        "Configuration missing, discovery needed. Discovering...");
They keys are custom. So you are also able to use

`offline.configuration_error_discovery` are whatever you think is right. Obvously the key in the properties file needs to match the key in the updatestate string.

2025-11-04 21:53 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +        updateStatus(ThingStatus.UNKNOWN);
Would the state be initializing (I found that was not possible to assign). I thought it needed to be something, but will remove and see.

2025-11-04 22:01 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +        updateStatus(ThingStatus.UNKNOWN);
With this comment i mean setting to unknown is at the wrong place, not the wrong type.

2025-11-04 22:03 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                                "Could not retrieve required parameters from device or the cloud.");
I don't understand. What about this?        ```
 } catch (MideaAuthenticationException e) {
            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.CONFIGURATION_ERROR, e.getMessage());
        } catch (MideaConnectionException e) {
            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.COMMUNICATION_ERROR, e.getMessage());
        } catch (MideaException e) {
            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.COMMUNICATION_ERROR, e.getMessage());
        } catch (IOException e) {
            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.COMMUNICATION_ERROR, e.getMessage());
```

EDIT: maybe I didn't understand the docs

2025-11-04 22:06 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    "Required configuration parameter(s) are missing or invalid.");
This increases my concern for clarity. I'm basically down to only these two and the message has to cover several situations

```
offline.communication_error = Could not retrieve required parameters from device or the cloud.
offline.configuration_error = Invalid configuration parameters provided. Retrieval from device or cloud not possible.
```

EDIT: Saw your other comment: so I'm not restricted to the ThingStatusDetail in the table? Are the custom ones lower case then?

2025-11-04 22:17 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +        updateStatus(ThingStatus.UNKNOWN);
What if all config are good, then the thing is never set to anything but online? I thought it needed to be something while going through the initialization()

2025-11-04 22:22 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +    public void initialize() {
TBH last time you helped I almost decided to give up.
All these things need to be done and with the async threads it is happening fast.
I'd like to hold on this for now.

2025-11-04 22:27 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                                "Could not retrieve required parameters from device or the cloud.");
The suggestion is mainly for static text per commented line in the code. For an exception message like your example, it is possible to create translations, but that is rather difficult and i can understand that you leave those cases as is.

2025-11-04 22:30 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                    "Required configuration parameter(s) are missing or invalid.");
You can completely make up the key yourself, as long as it is consistent. A common practice is to use some kind of naming convention as sugggested. But as said, anything works:

`updateStatus(ThingStatus.UNKNOWN, ThingStatusDetail.CONFIGURATION_ERROR, "@text/smooth.operator")`

and a proprties file with

```
smooth.operator = fancy text
```

2025-11-04 22:34 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +    public void initialize() {
Íf i have time in the next days i'll create a PR against your branch. It is mainly re-ordering the code, so i guess this won;t be difficult without many device details.

2025-11-04 22:39 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +        updateStatus(ThingStatus.UNKNOWN);
In case all is fine, it is usually set to `unkown` just before the final async method is called. That method usually performs a data refresh and while doing so it is set to online. There are many ways, this is just a simple and common example. The initialize here is a little bit more complicated, but still it should be prevented that the thing state flips state many times.

pseudo code:

```
private void initialize() {
  if (config != valid) {
      updqateThingState(OFFLINE, CONFIGURATION_ERROR, "Configure the device");
      return
  }
  updateThingState(UNKNOWN);
  doAsyncDataRefresh();
}

private void doAsyncDataRefresh() {
    //get data
    //set thing state to online
}
```

2025-11-04 22:43 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                                "Could not retrieve required parameters from device or the cloud.");
I need an example because these shows as an error in vsc
```
updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.offline.communication_error_token,
                                "Could not retrieve required parameters from device or the cloud.");
```
 and 
```
updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.communication_error_token,
                                "Could not retrieve required parameters from device or the cloud.");
```
with in the i18n
`offline.communication_error_token = Could not retrieve required parameters from device or the cloud.`

message: communication_error_token cannot be resolved or is not a fieldJava(33554502)

2025-11-04 22:47 UTC, apella12 commented
I'll have to tackle the i18n tomorrow. Thanks

2025-11-04 23:00 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                                "Could not retrieve required parameters from device or the cloud.");
The method has three parameters. You are fiddling with the second. It should be the third. 

The third parameter is the detail text that can be replaced by a custom key.

2025-11-04 23:03 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                                "Could not retrieve required parameters from device or the cloud.");
Example was given here https://github.com/openhab/openhab-addons/pull/17749#discussion_r2492216600

2025-11-05 14:33 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +    public void initialize() {
I enhanced the documentation in the code to hopefully avoid this, but whatever.

2025-11-05 14:34 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                                "Could not retrieve required parameters from device or the cloud.");
Finally understood this.  Should be ok now with 8 custom messages in i18n

2025-11-05 14:37 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +        updateStatus(ThingStatus.UNKNOWN);
Moved to before the routine poll (basically a refresh). Will be UNKNOWN for about 4 seconds.

2025-11-05 16:32 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +                                "Could not retrieve required parameters from device or the cloud.");
Yep, confirmed!

2025-11-05 21:12 UTC, lsiepel commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +    public void initialize() {
Created the PR here: https://github.com/apella12/openhab-addons/pull/2

Please test and see if all is still working as expected, if so, merge it and we can finish this PR.

2025-11-05 23:20 UTC, apella12 commented on bundles/org.openhab.binding.mideaac/src/main/java/org/openhab/binding/mideaac/internal/handler/MideaACHandler.java
> +    public void initialize() {
Ran some tests to exercise the initialization. Seems to work as before. (Couldn't resist, could you?)
Edit; Personally, I prefer grouped code as easier to follow, rather than having to jump around to find the linked methods. (Ok this is false, now where do I find what happens next?) Also about 100 more lines.

2025-11-06 14:37 UTC, lsiepel commented
I think we are ready. @apella12 do you need some additional time to test / verify different scenario's after latest changes?

2025-11-06 14:37 UTC, lsiepel approved these changes
Thanks, LGTM

2025-11-06 19:40 UTC, apella12 commented
I have the latest version running. No more testing really needed IMO. Also, the underlying code looked the same, materially, just dispersed around the MideaACHandler class so the initialize() just had method calls.  Thanks for approving !

2025-11-06 21:07 UTC, lsiepel commented
> o is here.
> I’d like to put this out for new

The thingstatus handling did change a bit but the logic itself was not changed as that was solid. Anyway.

Now, you could add the binding's logo to the openHAB website. See https://www.openhab.org/docs/developer/addons/#add-your-add-on-s-logo-to-the-openhab-website-and-the-ui

2025-11-06 21:09 UTC, merged