[radiothermostat] Add next schedule setpoint display channel
openhab/openhab-addons pull request #17743
Opened 2024-11-13 03:00 UTC by mlobstein

The PR adds one last missing feature from the old mobile app. The next scheduled set point (temperature and time) from the programmed heating or cooling schedule can now be displayed in its own channel.
![image](https://github.com/user-attachments/assets/ea6bb378-c79e-4b74-bcbd-91bc6f7a6cf9)

Also the display name of the binding was normalized to have a space between Radio Thermostat in all places that were previously inconsistent.

Note to reviewer: The RadioThermostatScheduleJson class was renamed to RadioThermostatSchedule and the new file appears in the diff as a completely new even though the method signatures and much of the code is unchanged.

2024-11-13 20:46 UTC, jlaur commented
@mlobstein - many thanks! I'm wondering if it would be useful to split this into two separate channels, one for temperature and one for datetime? This would make it possible to make better use of this data, for example for automations.

2024-11-15 00:52 UTC, mlobstein commented
> @mlobstein - many thanks! I'm wondering if it would be useful to split this into two separate channels, one for temperature and one for datetime? This would make it possible to make better use of this data, for example for automations.

Good idea, I have updated the PR to have separate channels.

2024-11-15 22:33 UTC, jlaur requested changes
Only a few minor comments, otherwise LGTM.

2024-11-16 00:04 UTC, mlobstein commented on bundles/org.openhab.binding.radiothermostat/README.md
> +String Therm_NextTime             "Next Set Time [%s]" <time>                     { channel="radiothermostat:rtherm:mytherm1:next_time" }
I changed it to the string that I used in my example image.

2024-11-16 10:58 UTC, jlaur commented on bundles/org.openhab.binding.radiothermostat/README.md
> +String Therm_NextTime             "Next Set Time [%s]" <time>                     { channel="radiothermostat:rtherm:mytherm1:next_time" }
That's an additional advantage of having two channels: Possibility to format the datetime as desired. 🙂

2024-11-16 10:58 UTC, jlaur approved these changes
LGTM

2024-11-16 10:59 UTC, merged