Mercedesme socket decoupling
openhab/openhab-addons pull request #17753
Opened 2024-11-17 12:24 UTC by weymann

2024-11-20 22:24 UTC, lsiepel requested changes
Left some minor comments. Otherwise LGTM

2024-11-20 22:24 UTC, lsiepel commented on bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java
> +            logger.trace("Error caught {}", err.getMessage());
this can be debug instead of trace.

2024-11-20 22:24 UTC, lsiepel commented on bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandler.java
> +        //
```suggestion
```

2024-11-20 22:24 UTC, lsiepel commented on bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/MBWebsocket.java
> +            logger.trace("IOException reading input stream {}", e.getMessage());
```suggestion
            logger.debug("IOException reading input stream {}", e.getMessage());
```

2024-11-23 09:27 UTC, weymann commented
Got some [negative feedback](https://community.openhab.org/t/mercedes-me/136866/30) which I still want to investigate. Please wait with merging!

2024-11-23 09:28 UTC, weymann commented on bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/MBWebsocket.java
> +            logger.trace("IOException reading input stream {}", e.getMessage());
done

2024-11-23 09:28 UTC, weymann commented on bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandler.java
> +        //
removed

2024-11-23 09:28 UTC, weymann commented on bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java
> +            logger.trace("Error caught {}", err.getMessage());
done

2024-12-01 17:32 UTC, weymann commented
@lsiepel PR can be merged.
Feedback is clearly based on [decoding messages](https://community.openhab.org/t/mercedes-me/136866/31) which needs to be further analyzed but not related to these code changes.

2024-12-01 20:18 UTC, lsiepel approved these changes

2024-12-01 20:18 UTC, merged