Improve received signal strength indication channel
openhab/openhab-addons pull request #17845
Opened 2024-12-04 11:51 UTC by andrewfg

As mentioned in #17826 there are some bindings having a received signal strength indication channel -- **_where there is at least a strong suspicion_** -- that the UoM unit is `dBm` .. but where the thing type is currently not fully specified to reflect that.

This PR seeks to improve the thing type xml specification of those channels, and provide update instructions for existing things.

Clues leading to my suspicion that the unit is `dBm` are as follows:
- bluetooth binding(s): the channel type has a state description pattern `dBm` 
- airgradient binding: the channel type has a state description pattern `dBm` 
- surepetcare binding: the channel type has a state description pattern `dB` 

Note in #17826 I mentioned some other bindings that use received signal strength indication channels that could potentially have the same treatment as in this PR. HOWEVER I have decided not to address those since there are no direct clues that the unit could be `dBm`.

Signed-off-by: AndrewFG <software@whitebear.ch>

2024-12-04 12:02 UTC, jlaur requested changes
Thanks for adding UoM for these channels. Only some minor remarks to update the documentation as well, because item type `Number` is currently mentioned.

2024-12-04 12:02 UTC, jlaur commented on bundles/org.openhab.binding.surepetcare/src/main/resources/OH-INF/thing/things.xml
> +		<state readOnly="true" pattern="%.2f dBm"/>
```suggestion
		<state readOnly="true" pattern="%.2f %unit%"/>
```

2024-12-04 12:02 UTC, jlaur commented on bundles/org.openhab.binding.surepetcare/src/main/resources/OH-INF/thing/things.xml
> +		<item-type unitHint="dBm">Number:Power</item-type>
Please also update the README to reflect this new type.

2024-12-04 12:02 UTC, jlaur commented on bundles/org.openhab.binding.surepetcare/src/main/resources/OH-INF/thing/things.xml
> +		<item-type unitHint="dBm">Number:Power</item-type>
Please also update the README to reflect this new type.

2024-12-04 14:21 UTC, jlaur approved these changes
LGTM

2024-12-04 15:23 UTC, andrewfg commented
> Did you check all channel state updates if they already support UoM?

Oops. Good catch. I will add a fix for SurePetCare.
Plus I also found two more bindings which do already provide an RSSI channel with `Units.DECIBEL_MILLIWATTS` UoM.

2024-12-04 16:28 UTC, jlaur approved these changes

2024-12-04 17:19 UTC, andrewfg commented on bundles/org.openhab.binding.bluetooth/README.md
> +| rssi       | Number:Power | The "Received Signal Strength Indicator", the [RSSI](https://blog.bluetooth.com/proximity-and-rssi) |
Ok. I will make that change too.

2024-12-04 23:24 UTC, andrewfg commented
I will fix the unit test tomorrow..

2024-12-05 12:15 UTC, andrewfg commented
@jlaur I encountered a problem in the OSGI tests for the ruuvigateway (see code link below) which I do not know how to solve. The OSGI test creates a test thing based on a ManagedThingProvider and then confirms that the thing has been properly created. The problem -- I think -- is that with the new thing update instructions, the ManagedThingProvider detects those update instructions and therefore tries to delete the thing and recreate it. This means that the OSGI test now fails because it finds the thing as having been deleted and not yet recreated. I really don't know how to fix such issue. I suppose ideally one should either a) disable the thing update mechanism during the OSGI tests, or b) modify the OSGI test so that it waits for the recreated thing. (or c) -- dare I say it -- delete this particular test) => WDYT?

https://github.com/openhab/openhab-addons/blob/044e9a33882a54d5b8098ba79a2e7fffa414df36/itests/org.openhab.binding.mqtt.ruuvigateway.tests/src/main/java/org/openhab/binding/mqtt/ruuvigateway/RuuviGatewayTest.java#L198

2024-12-05 12:38 UTC, andrewfg commented
> this was already there when actually the item type for the channel was plain

Indeed. The code is fully prepared for the channel to be Number:Power -- and it is "only" the xml which is wrong.

> Is it verified, i.e. the tests are passing when the upgrade instructions are removed?

Not yet. I am testing the tests in order to find out. Problem is that on my computer it takes hours to test. So please be patient. 

Alternatively I am thinking of adding the following line to the test in order to trick the provider that the thing upgrade is not required. I will commit this change now to GitHub since the CI build and integration tests are much fatser on GitHub than they are locally on my computer.

```
thingBuilder.withProperty("thingTypeVersion", "1");
```

2024-12-05 14:21 UTC, andrewfg commented
@jlaur just to confirm that adding `thingBuilder.withProperty("thingTypeVersion", "1");` to the test thing did indeed fix the test run.

2024-12-05 18:05 UTC, jlaur commented
@andrewfg - it seems there is an issue with the sign-off in your latest PR's. Is it okay with you that I simply copy the sign-off from your most recent PR with proper sign-off, #17099?

2024-12-05 18:31 UTC, andrewfg commented
> it seems there is an issue with the sign-off in your latest PR's

What kind of issue? The DCO check says it is Ok. Where do you see it as not Ok?

> Is it okay with you that I simply copy the sign-off from your most recent PR

Sure.

2024-12-05 19:36 UTC, jlaur commented
> > it seems there is an issue with the sign-off in your latest PR's
> 
> What kind of issue? The DCO check says it is Ok. Where do you see it as not Ok?

Sign-off in this and recent PR's:
```
Signed-off-by: AndrewFG <software@whitebear.ch>
```

And in your prior PR's until #17099:
```
Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>
```

We have a [real name requirement](https://www.openhab.org/docs/developer/contributing.html#sign-your-work), and I'm currently trying to sort out if the documentation is indeed correct, or if a passing DCO is sufficient. Until I know for sure, I will go with the safest option and ask contributors to use real name.

2024-12-05 19:37 UTC, merged

2024-12-05 22:51 UTC, andrewfg commented
> We have a [real name requirement](https://www.openhab.org/docs/developer/contributing.html#sign-your-work)

Thankyou for the info. I think my sig got munged when I had to reinstall my Git client recently. I will adjust it back again.