[mqtt.homeassistant] Implement WaterHeater
openhab/openhab-addons pull request #17859
Opened 2024-12-06 21:54 UTC by ccutrer

2024-12-06 21:56 UTC, ccutrer commented
This is built on top of #17853, and once that is merged, this one will need to be rebased (including any additional changes that PR has, to ensure a clean rebase).

2024-12-07 12:02 UTC, lsiepel commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/thing/homeassistant-channels.xml
> +		<item-type unitHint="%">Number:Temperature</item-type>
The unitHint is wrong here.

2024-12-07 12:02 UTC, lsiepel requested changes
1 comment, otherwise LGTM

2024-12-07 15:12 UTC, ccutrer commented on bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/thing/homeassistant-channels.xml
> +		<item-type unitHint="%">Number:Temperature</item-type>
🤦 . I still had Humidity on my mind.

2024-12-07 15:34 UTC, merged