[mqtt.generic] create the proper item type for channels with units
openhab/openhab-addons pull request #17929
Opened 2024-12-20 00:16 UTC by ccutrer

Working to address https://community.openhab.org/t/openhab-4-3-zigbee2mqtt-color-temperature-in-mired-not-working/160911/8

2024-12-20 00:19 UTC, ccutrer commented
Build will fail until https://github.com/openhab/openhab-core/pull/4507 is merged.

2024-12-21 12:33 UTC, lolodomo commented
Waiting for the merge of the required change in core framework.

I assume the fix should be backported into 4.3 ?

2024-12-21 18:50 UTC, andrewfg commented
> the fix should be backported into 4.3

Yes. I think so. Both this PR in addons and the corresponding UnitUtils PR in core.

2024-12-29 00:04 UTC, andrewfg requested changes
As discussed in OH core

2024-12-29 00:04 UTC, andrewfg commented on bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java
> +        String dimension = UnitUtils.getDimensionName(unit);
You need to add your special Mirek case handler here. And only call getDimensionName() for other units.

2024-12-29 16:37 UTC, ccutrer commented
This is no longer dependent on the core PR

2024-12-29 18:18 UTC, merged

2024-12-29 18:35 UTC, lolodomo commented
Nack-ported to 4.3.x branch.

2024-12-29 18:40 UTC, andrewfg commented
@ccutrer congrats :) sorry that it was like squeezing water out of a stone :(