[xmpp] implement group message sending
openhab/openhab-addons pull request #17938
Opened 2024-12-20 19:41 UTC by akallabeth

my take on getting group messages to work.

did avoid updating smack (don´t know what that would trigger) and simply added a new function to be called

2024-12-20 22:22 UTC, akallabeth commented
ok, did have a bug with not properly joining the group chat, but now it is working nicely on my local installation.

2024-12-20 22:47 UTC, akallabeth commented
added optional setting of nickname for group chat as well now.

2024-12-21 20:31 UTC, lsiepel requested changes
Thanks for this contribution. Just one comment.

2024-12-21 20:31 UTC, lsiepel commented on bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/internal/client/XMPPClient.java
> +        if (!nick.isEmpty()) {
Guess you don't want whitespace names
```suggestion
        if (!nick.isBlank()) {
```

2024-12-22 09:06 UTC, akallabeth commented on bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/internal/client/XMPPClient.java
> +        if (!nick.isEmpty()) {
good point, updated.

2024-12-23 08:21 UTC, akallabeth commented
@lsiepel how can the ci be retriggered? looks like a glitch in the last run.

2024-12-31 19:35 UTC, lsiepel approved these changes
Thanks, LGTM

2024-12-31 19:36 UTC, merged