[insteon] Add modem database backup restore console commands
openhab/openhab-addons pull request #17958
Opened 2024-12-23 06:03 UTC by jsetton

This changes adds the ability to backup and restore a modem database via console commands. A console command to initiate a modem reset was added as well.

2024-12-31 19:34 UTC, lsiepel requested changes
Thanks for adding these console commands, Only Thing that seems to be missing is the updated documentation.

2024-12-31 20:42 UTC, jsetton commented
The documentation related to [console commands](https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.insteon#console-commands) doesn't go in details of every commands available with the new binding. If the expectation is to have all of them documented, then this should probably be handled in a separate PR.

2025-01-04 20:10 UTC, lsiepel approved these changes
Thanks, LGTM.

Would be nice if you can create a new PR for the documentation about the different console commands.

2025-01-04 20:10 UTC, merged

2025-03-02 06:23 UTC, jsetton commented
> Would be nice if you can create a new PR for the documentation about the different console commands.

#18348