Added example now to hide notifications again
openhab/openhab-addons pull request #17978
Opened 2024-12-25 09:20 UTC by ericbodden

I just added an example for the new notification API. It shows how to hide a message again.

2024-12-31 19:29 UTC, lsiepel reviewed
Thanks, LGTM.

Would be nice if @florian-h05 can confirm.

2025-01-01 17:43 UTC, florian-h05 requested changes
Thanks for the addition - please have a look at my comments and contribute this change as well to https://github.com/openhab/openhab-js README.

2025-01-01 17:43 UTC, florian-h05 commented on bundles/org.openhab.automation.jsscripting/README.md
> +//sends a notification about a temperature change...
```suggestion
// Sends a notification about a temperature change ...
```

2025-01-01 17:43 UTC, florian-h05 commented on bundles/org.openhab.automation.jsscripting/README.md
> +actions.notificationBuilder(str).withIcon("oh:temperature").withTag("Temperature change").withReferenceId("living room").send();
Use single quotes `'` instead of double quotes `"`.
Please provide a message, because this example won't work with `str` as argument to the notification builder.
And I would prefer to have the reference id without any spaces.

2025-01-01 17:43 UTC, florian-h05 commented on bundles/org.openhab.automation.jsscripting/README.md
> +//and clears it again after 10 minutes
```suggestion
// ... and hides it after 10 minutes
```

2025-01-01 17:43 UTC, florian-h05 commented on bundles/org.openhab.automation.jsscripting/README.md
> +  actions.notificationBuilder().withReferenceId("living room").hide().send();
```suggestion
  actions.notificationBuilder().hide().withReferenceId("living room").send();
```

This way it is better to read.

2025-01-09 09:17 UTC, florian-h05 approved these changes
LGTM, thanks!

Can you please create a PR to openHAB-js to introduce this change to the README there? This part of the add-on README is sourced from there.

2025-01-09 20:19 UTC, jlaur commented
> Can you please create a PR to openHAB-js to introduce this change to the README there? This part of the add-on README is sourced from there.

Does it make sense to merge this one, or should we rather wait for the upstream version? It will be need to be added there anyway, since otherwise it would be overwritten. So merging directly here introduces the risk of this overwrite.

2025-03-07 23:42 UTC, florian-h05 commented
@lsiepel I just merged your openhab-js PR 👍

2025-03-08 07:36 UTC, merged