[max] Added 'ThingActions' to handle reboot and other Cube actions
openhab/openhab-addons pull request #7526
Opened 2020-05-02 15:01 UTC by cweitkamp

- Added `ThingActions` to handle reboot and other Cube actions

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

2020-09-06 19:44 UTC, Hilbrand commented
Do you still want to do more testing? And do you want to add the actions invode work-around?

2020-09-06 21:18 UTC, marcelrv commented on bundles/org.openhab.binding.max/README.md
> -You can trigger these actions changing from 'No Action' in the dropdown to the action value.
This looks like still valid, and the way to trigger the action from the GUI or am I missing something?

2020-09-06 21:26 UTC, marcelrv requested changes
Sorry, did not see this PR earlier.
Can you check the readme, as I understand this PR adds the actions for use in rules, but does not remove the actions from the paperUI config, hence would keep that part of the description

2020-09-12 09:23 UTC, cweitkamp commented
@marcelrv Thanks for looking into this. My plan was indeed to remove the configuration too. But I first wanted to get an impression if others agree in it too. If you like it I will try to finalize this PR asap.

2020-09-12 19:22 UTC, marcelrv commented
my only worry with removing these from the options is that the regular gui currently has no way to trigger these actions.
(when writing the comment earlier I was still assuming there was already something in the UI that allowed it to trigger)

Dunno if that is planned in OH3 new UI, in that case, maybe it is better to remove these actions from the config once we arrive @OH3.0

2020-09-13 11:11 UTC, cweitkamp commented
@Hilbrand @marcelrv I incorporated your review comments.

2020-09-13 14:29 UTC, Hilbrand approved these changes
LGTM

2020-09-14 09:51 UTC, Hilbrand commented
@marcelrv Can you have a second look?

2020-09-15 19:14 UTC, marcelrv commented
Did functional as well, looks working well..... 
Unfortunately there is now some merge conflict to be resolved. 
Outside the merge conflict, LGTM

2020-09-15 19:15 UTC, marcelrv requested changes
besides the merge conflict LGTM

2020-09-16 15:06 UTC, cweitkamp commented
Thanks for your review. I rebased my PR.

2020-09-16 15:32 UTC, marcelrv approved these changes

2020-09-17 00:57 UTC, cpmeister approved these changes
LGTM

2020-09-17 06:02 UTC, merged