[opensprinkler] Add water level channel
openhab/openhab-addons pull request #8232
Opened 2020-07-31 15:05 UTC by pail23

This PR adds the water level channel to the opensprinkler device. This channel is calculated based on weather data and influences how long the watering will last

2020-07-31 15:08 UTC, TravisBuddy commented
## Travis tests were successful
Hey @pail23,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-07-31 15:11 UTC, TravisBuddy commented
## Travis tests were successful
Hey @pail23,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-07-31 15:17 UTC, TravisBuddy commented
## Travis tests were successful
Hey @pail23,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-08-14 17:40 UTC, fwolter commented on bundles/org.openhab.binding.opensprinkler/README.md
> +| waterlevel      | Number                 | RO | This channel shows the current water level. The water level calculated    |
Can you mention that it is percent?
```suggestion
| waterlevel      | Number:Dimensionless                 | RO | This channel shows the current water level. The water level calculated    |
```

2020-08-14 18:21 UTC, TravisBuddy commented
## Travis tests were successful
Hey @pail23,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-08-16 18:06 UTC, TravisBuddy commented
## Travis tests were successful
Hey @pail23,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-08-16 21:25 UTC, FlorianSW commented
Big sorry for not coming back to this earlier :( I'll look into this right now :)

2020-08-16 21:25 UTC, FlorianSW commented on bundles/org.openhab.binding.opensprinkler/README.md
> +| waterlevel      | Number:Dimensionless                 | RO | This channel shows the current water level. The water level calculated    |
probably align with other cells :)

2020-08-16 21:27 UTC, FlorianSW commented on bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV100.java
> +            JoResponse info = getOptions();
awesome for refactoring this as well :)

2020-08-17 05:37 UTC, pail23 commented on bundles/org.openhab.binding.opensprinkler/README.md
> +| waterlevel      | Number:Dimensionless                 | RO | This channel shows the current water level. The water level calculated    |
Fixed.

2020-08-17 05:39 UTC, TravisBuddy commented
## Travis tests were successful
Hey @pail23,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-08-20 16:18 UTC, fwolter requested changes
There are some formatting issues. You can view them with `mvn spotless:check -Dspotless.check.skip=false` and fix them with `mvn spotless:apply`.

2020-08-20 16:18 UTC, fwolter commented on bundles/org.openhab.binding.opensprinkler/README.md
> +|                 |                        |    | based on the weather and influences the duration of the water programs.   |
Can you mention, that this is percent?

2020-08-20 16:18 UTC, fwolter commented on bundles/org.openhab.binding.opensprinkler/src/main/resources/ESH-INF/thing/thing-types.xml
> +		<description>The current water level</description>
```suggestion
		<description>The current water level in percent</description>
```

2020-08-20 16:18 UTC, fwolter commented on bundles/org.openhab.binding.opensprinkler/src/main/resources/ESH-INF/thing/thing-types.xml
> +		<label>Water level</label>
Words in labels should be capitalized (except prepositions and so on). See https://www.openhab.org/docs/developer/bindings/thing-xml.html#formatting-labels-and-descriptions

2020-08-20 19:16 UTC, pail23 commented on bundles/org.openhab.binding.opensprinkler/src/main/resources/ESH-INF/thing/thing-types.xml
> +		<description>The current water level</description>
done

2020-08-20 19:17 UTC, pail23 commented on bundles/org.openhab.binding.opensprinkler/README.md
> +|                 |                        |    | based on the weather and influences the duration of the water programs.   |
yes, done

2020-08-20 19:17 UTC, pail23 commented
Thanks @fwolter for the review. The findings should be fixed now.

2020-08-20 21:31 UTC, fwolter approved these changes

2020-08-20 21:31 UTC, merged