add neato clean with map
openhab/openhab-addons pull request #8310
Opened 2020-08-18 20:25 UTC by Tukks

[NEATO] add option to clean house with map and no-go lines

Improvements to Add option Clean with map to binding neato to launch clean with no-go line activated.
I don't remove the old clean option because of legacy and I don't know if this code work on a Neato D5
Tested only on neato D7.

see issue for more info #5761

2020-08-18 20:58 UTC, Tukks commented
Where I can share the jar file for testing? What host do you recommend?

2020-08-19 06:23 UTC, HerzScheisse commented
Hey @Tukks ,

many thanks for adding this option.. 

maybe the community forum is the best way to provide the jar for testing... 

Eigther this thread https://community.openhab.org/t/neato-botvac-binding/50406
or start a new one...

I have a D5 and could help with testing...

2020-08-20 18:13 UTC, fwolter requested changes
Can you please sign-off your changes? See https://www.openhab.org/docs/developer/contributing.html#sign-your-work

@jjlauterbach As the code owner, do you agree with the changes?

2020-08-20 18:13 UTC, fwolter commented on bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/NeatoRobot.java
> +        logger.info("State neato : {}", this.state);
Logging to info should be used rarely. This could be debug. Same for below.

2020-08-20 18:13 UTC, fwolter commented on bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/Category.java
> + * @author Lapenta Giuseppe
```suggestion
 * @author Lapenta Giuseppe - Initial Contribution
```

2020-08-20 18:13 UTC, fwolter commented on bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/Category.java
> +public enum Category {
Please add the `@NonNullByDefault` annotation.

2020-08-20 18:13 UTC, fwolter commented on bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/Mode.java
> +public enum Mode {
See above

2020-08-20 18:13 UTC, fwolter commented on bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/NavigationMode.java
> +public enum NavigationMode {
See above

2020-08-20 18:26 UTC, jjlauterbach commented
LGTM

2020-08-20 18:57 UTC, Tukks commented
Thanks for the feedback, I will do every change requested Monday and I will put the jar file on the forum too.

2020-08-24 16:20 UTC, TravisBuddy commented
## Travis tests were successful
Hey @Tukks,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-08-24 16:24 UTC, Tukks commented
@fwolter I signed-off my change and resolved all the comment you made.
@HerzScheisse I Added the Jar file to the forum.

2020-08-24 16:32 UTC, TravisBuddy commented
## Travis tests were successful
Hey @Tukks,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-08-26 13:44 UTC, HerzScheisse commented
@Tukks Thanks for this PR...

I can confirm that it also works with the D5 Model...

2020-08-26 21:15 UTC, fwolter approved these changes

2020-08-26 21:16 UTC, merged