[miio] support for miot action commands
openhab/openhab-addons pull request #8387
Opened 2020-09-03 14:49 UTC by marcelrv

* support for miot action commands
* new conditional action
* Implement start/stop vacuum for dreame.vacuum.mc1808

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

2020-09-03 14:52 UTC, TravisBuddy commented
## Travis tests were successful
Hey @marcelrv,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-04 11:42 UTC, TravisBuddy commented
## Travis tests were successful
Hey @marcelrv,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-04 19:25 UTC, Hilbrand requested changes
Just some minor improvement comments.

2020-09-04 19:25 UTC, Hilbrand commented on bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/ActionConditions.java
> +                    LOGGER.trace("Matching '{}' with '{}': {}", matchvalue, command.toString(), matching);
```suggestion
                    LOGGER.trace("Matching '{}' with '{}': {}", matchvalue, command, matching);
```

2020-09-04 21:31 UTC, TravisBuddy commented
## Travis tests were successful
Hey @marcelrv,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-04 21:44 UTC, Hilbrand approved these changes

2020-09-05 10:37 UTC, fwolter commented
@Hilbrand can this be merged?

2020-09-05 12:47 UTC, TravisBuddy commented
## Travis tests were successful
Hey @marcelrv,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-05 19:23 UTC, merged