Added Absolute Setpoint Mode
openhab/openhab-addons pull request #8393
Opened 2020-09-04 04:20 UTC by silverfunk

[radiothermostat] Added Absolute Setpoint Mode

When controlled remotely Radio Thermostat's can function in 2 modes.  In temporary mode setpoint changes will be temporary; with the thermostat returning to run its program after a period of time.  In absolute mode setpoint changes are permanent.  The thermostat will maintain the given setpoint temperature until it is changed, completely ignoring the program.  With OpenHab controlling the thermostat it is often not desirable to have the thermostat run its own program.  Adding the absolute setpoint mode allows users to control the thermostat setpoint entirely through OpenHab. Added Absolute Setpoint Mode

When controlled remotely Radio Thermostat's can function in 2 modes.  In temporary mode setpoint changes will be temporary; with the thermostat returning to run its program after a period of time.  In absolute mode setpoint changes are permanent.  The thermostat will maintain the given setpoint temperature until it is changed, completely ignoring the program.  With OpenHab controlling the thermostat it is often not desirable to have the thermostat run its own program.  Adding the absolute setpoint mode allows users to control the thermostat setpoint entirely through OpenHab.

2020-09-04 04:24 UTC, TravisBuddy commented
## Travis tests were successful
Hey @silverfunk,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-04 04:38 UTC, TravisBuddy commented
## Travis tests were successful
Hey @silverfunk,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-04 06:41 UTC, Hilbrand commented
I'm not familiar with this device. But Is this something that is set once and than not changed? Or does it make sense for the user to sometimes change the setpoint temporary and other times permanent? In that case it might make more sense to have this as a channel parameter of a separate temporarySetPoint channel?

2020-09-04 09:00 UTC, marcelrv commented
Indeed afree with @Hilbrand  would suggest the same. 
Make some sort of 'mode' channel instead, which than would be like program mode or permanent instead of doing this via config option.

I would also recommend not to use 'absolute' as channel name, I don't think it well describes the intent of the functionality

2020-09-04 09:05 UTC, Hilbrand commented
I would opt for a specific channel for temporarySetPoint as it would be easier. The user can simply pick a channel. Otherwise the user must first make sure the correct mode is set and then set the setpoint.

2020-09-04 17:58 UTC, cpmeister requested changes

2020-09-04 17:58 UTC, cpmeister commented on bundles/org.openhab.binding.radiothermostat/src/main/resources/ESH-INF/thing/thing-types.xml
> +				<label>Run in absolute setpoint mode</label>
```suggestion
				<label>Run in Absolute Setpoint Mode</label>
```

2020-09-05 12:40 UTC, TravisBuddy commented
## Travis tests were successful
Hey @silverfunk,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-08 01:53 UTC, mlobstein commented
> 
> 
> I would opt for a specific channel for temporarySetPoint as it would be easier. The user can simply pick a channel. Otherwise the user must first make sure the correct mode is set and then set the setpoint.

I am not entirely sure this is needed. With the current implementation, the user can set the 'hold' switch on which will cause the temperature to maintain its current set point indefinitely. The thermostat will ignore its internal program schedule while in hold mode.

2020-09-08 01:56 UTC, mlobstein commented on bundles/org.openhab.binding.radiothermostat/README.md
> +| absolute        | Controls temporary or absolute mode. When false setpoint changes are temporary; the thermostat will return to its program after a time. When true setpoint changes are perminant; t
spelling: 'permanent'

2020-09-08 02:29 UTC, silverfunk commented
The main idea behind creating an absolute mode is to allow the thermostat to be operated primarily via a program in the thermostat (thermostat driven) vs. operated via a smart home controller (openHBB).  Without an absolute mode the thermostat only temporarily changes to the given setpoint, reverting later back to its program.  Yes, hold could be used to force this same behavior but then hold cannot be used for smart home controller operations.  For example I use hold on my thermostats to inform openHAB that it should maintain the setpoint regardless of whether or not people are home, e.g. it is hold for the thermostat and the smart home controller.  

The real point of adding an absolute mode is to essentially make the thermostat a dumb device.  In this mode it controls the temperature based solely on what openHAB tells it to do.  I do not want it to have other ideas of how and when the temperature should be changed.  In my house openHAB is able to tell the thermostat to control the temperature based on when people are home, whether or not we are in bed for the night, and the price I am paying for electricity.  In an absolute mode the thermostat's only function is to monitor the temperature and turn on the furnace or AC when it gets beyond the setpoint ranges.  I do not want the thermostat to be able to make decisions beyond what openHAB tells it to do.

When I originally contemplated this functionality I dithered between making it a parameter on the thing or a separate item channel.  Ultimately I decided to go with a parameter on the thing because I could not fathom a reason why anyone would want to switch between the two.  But that being said I am open to allowing for flexibility.  If there is a desire to make the absolute mode into an item channel I can do that.  I do think this would have to be an on/off switch though.  Creating separate temporary and absolute setpoint items, while possible, would be complicated for a user interface.  The thermostat is only able to maintain one active setpoint, either temporary or absolute.  If both setpoints were items you could have a sitemap where both are visible but there is no indication which one is active.  Changing one would inherently change the mode of the thermostat with no indication the thermostat was functioning differently.

2020-09-08 02:33 UTC, TravisBuddy commented
## Travis tests were successful
Hey @silverfunk,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-08 02:45 UTC, TravisBuddy commented
## Travis tests were successful
Hey @silverfunk,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-08 02:53 UTC, TravisBuddy commented
## Travis tests were successful
Hey @silverfunk,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-08 13:19 UTC, Hilbrand reviewed
Thank you for your extensive explanation. I now better understand it's usage. This is more about how to one wants to use the thermostat. I can image that if you want to run in absolute mode you never should send a temporary command as this will trigger the thermostat to start following it's program again. The naming of this option can be a discussion, but I guess it would best make sense to follow naming closely to what the thermostat uses and thus follow the terminology used as used in the pr.

I've one review request. Instead of using the a boolean to make it a options list. You can actually test this value in the initialize method and set the specific command, instead of testing it every time, since doesn't change anymore.

2020-09-08 13:19 UTC, Hilbrand commented on bundles/org.openhab.binding.radiothermostat/src/main/resources/ESH-INF/thing/thing-types.xml
> +			</parameter>
```suggestion
			<parameter name="setpointMode" type="text">
				<label>Setpoint Mode</label>
				<description>Run in absolute or temporary setpoint mode</description>
				<default>temporary</default>
				<options>
				    <option value="absolute">Absolute</option>
				    <option value="temporary">Temporary</option>
				</options>
			</parameter>
```

2020-09-08 16:07 UTC, mlobstein commented
> 
> 
> The main idea behind creating an absolute mode is to allow the thermostat to be operated primarily via a program in the thermostat (thermostat driven) vs. operated via a smart home controller (openHAB). Without an absolute mode the thermostat only temporarily changes to the given setpoint, reverting later back to its program. 

That makes sense. I had never explored 
[RadioThermostatHandler.java.txt](https://github.com/openhab/openhab-addons/files/5189488/RadioThermostatHandler.java.txt)
absolute mode myself. It is rather strange that there is no way to tell if the thermostat is using an absolute setpoint or not. So from the binding perspective it makes sense to chose one mode or the other and stick with it instead of providing a way to dynamically switch. I have attached some refactoring changes to the code to remove the SuppressWarnings mainly and improve a few little things. Please add them to your PR (note .java files renamed to .txt)

[RadioThermostatConfiguration.java.txt](https://github.com/openhab/openhab-addons/files/5189474/RadioThermostatConfiguration.java.txt)

[RadioThermostatStateDescriptionProvider.java.txt](https://github.com/openhab/openhab-addons/files/5189494/RadioThermostatStateDescriptionProvider.java.txt)

[RadioThermostatHandler.java.txt](https://github.com/openhab/openhab-addons/files/5189498/RadioThermostatHandler.java.txt)

2020-09-08 19:48 UTC, fwolter commented
@mlobstein You could also file a PR for the forked repo of @silverfunk

2020-09-09 02:02 UTC, TravisBuddy commented
## Travis tests have failed
Hey @silverfunk,
please read the following log in order to understand the failure reason. There might also be some helpful tips along the way.
It will be awesome if you fix what is wrong and commit the changes.

2020-09-09 02:18 UTC, mlobstein requested changes

2020-09-09 02:18 UTC, mlobstein commented on bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/handler/RadioThermostatHandler.java
> +        if (hostName == null || hostName == "") {
Should probably be hostName.equals(""), sorry about that.

2020-09-09 02:19 UTC, mlobstein commented on bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/handler/RadioThermostatHandler.java
> +                        cmdKey = this.setpointCmdKeyPrefix + "heat";
nice

2020-09-09 02:20 UTC, TravisBuddy commented
## Travis tests were successful
Hey @silverfunk,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-09 02:21 UTC, silverfunk commented
@mlobstein, I incorporated your refactoring changes.  Thank you for the updates.  

In temporary mode the thermostat displays "Temporary" on the thermostat's screen while it is adjusting to the given temporary setpoint.  In absolute mode it does not display "Temporary".  That's the only indication I've seen that differentiates between the two modes.  I have found nothing in the API to designate a difference between the modes.

2020-09-09 03:22 UTC, silverfunk commented on bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/handler/RadioThermostatHandler.java
> +                        cmdKey = this.setpointCmdKeyPrefix + "heat";
There you go, took care of it.

2020-09-09 03:24 UTC, TravisBuddy commented
## Travis tests were successful
Hey @silverfunk,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-09 03:36 UTC, TravisBuddy commented
## Travis tests were successful
Hey @silverfunk,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-09 05:35 UTC, Hilbrand approved these changes
LGTM

2020-09-09 06:32 UTC, marcelrv approved these changes
LGTM

2020-09-09 10:26 UTC, Hilbrand commented
@mlobstein any last words before I merge :wink:

2020-09-09 13:38 UTC, mlobstein commented
> 
> 
> @mlobstein any last words before I merge wink

LGTM

2020-09-09 14:08 UTC, merged