[shelly][WIP] Add channels device#deviceName, relay#channelName + refactoring
openhab/openhab-addons pull request #8396
Opened 2020-09-04 16:25 UTC by markus7017

This PR adds 2 new channels
- deviceName and
- channelName per relay channel

Those reflect the settings in the Shelly App and provide logical names for the device (all) and relay channels.

In addition Apache Comments (StringUtil+IOUtIOUtilsiul) was replaced by native code.

2020-09-04 16:29 UTC, TravisBuddy commented
## Travis tests were successful
Hey @markus7017,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-04 20:08 UTC, TravisBuddy commented
## Travis tests were successful
Hey @markus7017,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-05 11:00 UTC, fwolter requested changes
As spotless is enabled in the `2.5.x` branch now, you need to fix those formatting errors with `mvn spotless:apply`.

2020-09-05 16:29 UTC, markus7017 commented on bundles/org.openhab.binding.shelly/README.md
> +|device    |deviceName         |String  |yes      |Device name as configured in the Shelly App                                      |
The Shelly App allows to configure a logical device name. This becomes now a channel and can be used in the UI. If users are assigning logical names it makes sense to have them available on the OH side too. Properties can not be accessed by rules.

2020-09-05 16:30 UTC, markus7017 commented on bundles/org.openhab.binding.shelly/README.md
> +|          |channelName  |String   |yes      |Logical name of this channel as configured in the Shelly App                    ||
Similar to devices the Shelly App allows to assign a sysmbolic name to a relay channel. A 4Pro has 4x2 channels, each one gets it's own name.

2020-09-05 17:14 UTC, markus7017 commented on bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
> +        fwId = ShellyUtils.substringAfter(settings.fw, "@");
changed (and all others)

2020-09-08 08:13 UTC, markus7017 commented
@fwolter How do we proceed?

2020-09-08 08:14 UTC, TravisBuddy commented
## Travis tests have failed
Hey @markus7017,
please read the following log in order to understand the failure reason. There might also be some helpful tips along the way.
It will be awesome if you fix what is wrong and commit the changes.

2020-09-08 08:16 UTC, TravisBuddy commented
## Travis tests have failed
Hey @markus7017,
please read the following log in order to understand the failure reason. There might also be some helpful tips along the way.
It will be awesome if you fix what is wrong and commit the changes.

2020-09-08 08:21 UTC, TravisBuddy commented
## Travis tests were successful
Hey @markus7017,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-08 17:59 UTC, fwolter commented on bundles/org.openhab.binding.shelly/README.md
> +|          |channelName  |String   |yes      |Logical name of this channel as configured in the Shelly App                    ||
Could you point out that a Shelly channel is meant to avoid any confusion?

2020-09-08 18:00 UTC, fwolter commented on bundles/org.openhab.binding.shelly/README.md
> +|device    |deviceName         |String  |yes      |Device name as configured in the Shelly App                                      |
Ok

2020-09-08 22:09 UTC, markus7017 commented on bundles/org.openhab.binding.shelly/README.md
> +|          |channelName  |String   |yes      |Logical name of this channel as configured in the Shelly App                    ||
I could change the channel name to "outputName" and the description to
Changed it to "Logical name of this relay output as configured in the Shelly App "

Does that work better?

2020-09-09 07:12 UTC, fwolter commented on bundles/org.openhab.binding.shelly/README.md
> +|          |channelName  |String   |yes      |Logical name of this channel as configured in the Shelly App                    ||
That sounds better!

2020-09-11 13:04 UTC, markus7017 commented on bundles/org.openhab.binding.shelly/README.md
> +|          |channelName  |String   |yes      |Logical name of this channel as configured in the Shelly App                    ||
done

2020-09-11 13:05 UTC, markus7017 commented
@fwolter I changed channel channelName to outputName as dicussed

From my side we are ready to merge

2020-09-11 21:24 UTC, fwolter requested changes

2020-09-11 21:24 UTC, fwolter commented on bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/i18n/shelly_de.properties
> +channel-type.shelly.outputName.description = Name des Relais-Ausgangs/Kanals (Konfiguriation innerhalb der Shelly App)
```suggestion
channel-type.shelly.outputName.description = Name des Relais-Ausgangs/Kanals (Konfiguration innerhalb der Shelly App)
```

2020-09-12 12:41 UTC, markus7017 commented on bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/i18n/shelly_de.properties
> +channel-type.shelly.outputName.description = Name des Relais-Ausgangs/Kanals (Konfiguriation innerhalb der Shelly App)
fixed

2020-09-12 12:42 UTC, markus7017 commented
@fwolter change is done

2020-09-12 13:35 UTC, fwolter approved these changes
LGTM

2020-09-12 13:35 UTC, merged