[publictransportswitzerland] Public Transport Switzerland Initial contribution
openhab/openhab-addons pull request #8540
Opened 2020-09-22 08:59 UTC by jeremystucki

Continuation of #7524

# Public Transport Switzerland Binding

Connects to the "Swiss public transport API" to provide real-time public transport information. [Link to the API](https://transport.opendata.ch/)

For example, here is a station board in HABPanel. (Download [here](https://github.com/StefanieJaeger/HABPanel-departure-board))

## Supported Things

### Stationboard

Upcoming departures for a single station.

## Discovery

This binding does not support auto-discovery.

## Thing Configuration

### Stationboard

`Station` is the station name for which to display departures.

## Channels

### Stationboard

| channel | type   | description |
|---------|--------|-------------|
| departures#n   | String | A dynamic channel for each upcoming departure |
| tsv (advanced) | String | A tsv which contains the fields:<br />`identifier, departureTime, destination, track, delay` |

2020-09-22 10:14 UTC, TravisBuddy commented
## Travis tests have failed
Hey @jeremystucki,
please read the following log in order to understand the failure reason. There might also be some helpful tips along the way.
It will be awesome if you fix what is wrong and commit the changes.

2020-11-01 12:09 UTC, fwolter commented
Is this a draft by intention? If you like to get this reviewed, you should mark it as open.

2020-11-01 13:52 UTC, jeremystucki commented
@fwolter It's a draft on purpose. I still have to address a review from the old PR. I just didn't have the time

2020-11-24 08:39 UTC, jeremystucki commented
@fwolter Is it still possible to create dynamic channels from code? I don't see them appearing in my OH3 instance. I use `updateThing(editThing().withChannel(channel).build())`

2020-11-24 15:18 UTC, fwolter commented
It should, but I never tried it with OH3.

2021-02-14 14:48 UTC, jeremystucki commented
I can't seem to figure out why the dynamic channels don't show up in the UI.
If I look at `getThing().getChannelsOfGroup` they exist.

The static channel works as expected.

![2021-02-14-154803_784x409_scrot](https://user-images.githubusercontent.com/7629727/107879935-13dc5780-6edc-11eb-98f9-5e268e19d75f.png)

2021-02-14 16:06 UTC, fwolter commented
I have no idea either. You could ask in the developer section in the forum.

2021-02-23 04:22 UTC, Skinah commented
I have troubles with dynamic channels on the opensprinkler binding. This may be a bug in the core? as you can define them in the XML and remove them dynamically, but I could not add them.. I looked at other bindings for examples are could not see a reason why it should not work. Since it was only 1 binding that I did not write, I did not report it as a bug, but if your also having issues then it would pay to bring this up.

2021-11-28 21:47 UTC, jeremystucki commented
I had another go at this and figured out that I had to define a channel type for the dynamic channels to show up in OH3.

<img width=393 src=https://user-images.githubusercontent.com/7629727/143787232-e590045f-a4b8-4643-9e8c-de3f3f097695.png>

Feel free to try out this plugin out or to review my code. I consider it to be fully migrated now.

2021-11-29 08:37 UTC, fwolter requested changes
Great to see progress on this!

There are some compiler warnings left. You could take a look at `mvn clean install`.

There are some checkstyle warnings left. You could take a look at `target/code-analysis/report.html` after building it with `mvn clean install`.

2021-11-29 08:37 UTC, fwolter commented on bundles/org.openhab.binding.publictransportswitzerland/.classpath
> +<?xml version="1.0" encoding="UTF-8"?>
This file is generated automatically and should not be part of your PR.

2021-11-29 08:37 UTC, fwolter commented on bundles/org.openhab.binding.publictransportswitzerland/.project
> +<?xml version="1.0" encoding="UTF-8"?>
See above. Generated. Please remove.

2021-11-29 08:37 UTC, fwolter commented on bundles/org.openhab.binding.publictransportswitzerland/README.md
> +Upcoming departures for a single station. This is what you would usually see displayed at the train station.
You could mention the ThingTypeUID. You'll need it when using textual configuration. There are many users who use textual configuration.

2021-11-29 08:37 UTC, fwolter commented on bundles/org.openhab.binding.publictransportswitzerland/README.md
> +`Station` is the station name for which to display departures.
The config parameter names are case sensitive.
```suggestion
`station` is the station name for which to display departures.  
```

2021-11-29 08:37 UTC, fwolter commented on bundles/org.openhab.binding.publictransportswitzerland/README.md
> +This binding does not support auto-discovery.
A full example with .things and .items file should be part of your readme.

2021-11-29 08:37 UTC, fwolter commented on bundles/org.openhab.binding.publictransportswitzerland/src/main/resources/OH-INF/binding/binding.xml
> +	<author>Jeremy Stucki &amp; Stefanie Jäger</author>
The author tag is deprecated and should therefore be removed. See openhab/openhab-core#1844.

2021-11-29 08:37 UTC, fwolter commented on bundles/org.openhab.binding.publictransportswitzerland/src/main/feature/feature.xml
> +	<feature name="openhab-binding-publictransportswitzerland" description="PublicTransportSwitzerland Binding" version="${project.version}">
The description is displayed as binding name when installing it in MainUI.
```suggestion
	<feature name="openhab-binding-publictransportswitzerland" description="Public Transport Switzerland Binding" version="${project.version}">
```

2021-12-27 19:34 UTC, fwolter requested changes

2021-12-27 19:34 UTC, fwolter commented on bundles/org.openhab.binding.publictransportswitzerland/pom.xml
> +    <version>3.2.0-SNAPSHOT</version>
```suggestion
    <version>3.3.0-SNAPSHOT</version>
```

2021-12-27 20:19 UTC, fwolter approved these changes
LGTM

Now, you could add your binding's logo to the openHAB website. See https://www.openhab.org/docs/developer/bindings/#add-your-binding-s-logo-to-the-openhab-website

2021-12-27 20:19 UTC, merged

2021-12-28 07:46 UTC, jeremystucki commented
Thank you @fwolter for the fast and precise reviews, I'm so happy that it's gonna be in the next release :)

2022-01-09 12:08 UTC, lolodomo commented
Please create a subsequent PR to add the default translation properties file. 
You can produce it simply by running this command : `mvn i18n:generate-default-translations`