[lutron] Replace calls to methods deprecated in Java 11
openhab/openhab-addons pull request #8602
Opened 2020-09-28 22:06 UTC by bobadair

Replaces calls to methods deprecated in Java 11.

2020-09-28 22:12 UTC, TravisBuddy commented
## Travis tests were successful
Hey @bobadair,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-09-29 00:07 UTC, cpmeister requested changes
Might as well also take advantage of java's automatic boxing feature.

2020-09-29 00:07 UTC, cpmeister commented on bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/GreenModeHandler.java
> +                Integer step = Integer.valueOf(((Number) command).intValue());
```suggestion
                Integer step = ((Number) command).intValue();
```

2020-09-29 00:07 UTC, cpmeister commented on bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/TimeclockHandler.java
> +                Integer mode = Integer.valueOf(((DecimalType) command).intValue());
```suggestion
                Integer mode = ((DecimalType) command).intValue();
```

2020-09-29 00:07 UTC, cpmeister commented on bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/TimeclockHandler.java
> +                Integer index = Integer.valueOf(((DecimalType) command).intValue());
```suggestion
                Integer index = ((DecimalType) command).intValue();
```

2020-09-29 00:07 UTC, cpmeister commented on bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/TimeclockHandler.java
> +                Integer index = Integer.valueOf(((DecimalType) command).intValue());
```suggestion
                Integer index = ((DecimalType) command).intValue();
```

2020-09-29 00:07 UTC, cpmeister commented on bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/TimeclockHandler.java
> +                Integer index = Integer.valueOf(((DecimalType) command).intValue());
```suggestion
                Integer index = ((DecimalType) command).intValue();
```

2020-09-29 02:38 UTC, bobadair commented
> Might as well also take advantage of java's automatic boxing feature.

Yeah, I should have cleaned that up before.

2020-09-29 17:16 UTC, cpmeister approved these changes
LGTM

2020-09-29 17:16 UTC, merged