Fix disabled integration tests
openhab/openhab-addons pull request #8609
Opened 2020-09-29 18:23 UTC by wborn

Fixes and enables:

* org.openhab.binding.mqtt.homeassistant.tests
* org.openhab.binding.mqtt.homie.tests
* org.openhab.io.mqttembeddedbroker.tests

Fixes #8537

2020-09-29 19:33 UTC, cpmeister requested changes

2020-09-29 19:33 UTC, cpmeister commented on itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/HomieImplementationTest.java
> +    private ScheduledExecutorService scheduler = new ScheduledThreadPoolExecutor(6);
This scheduler instance isn't shutdown since it is immediately replaced by another instance in the `@BeforeEach` method.

2020-09-29 21:04 UTC, cpmeister approved these changes

2020-09-29 21:05 UTC, merged

2020-09-30 06:43 UTC, kaikreuzer commented
I am afraid we are still seeing a failing mqtt test: https://ci.openhab.org/job/openHAB-Addons/68/console