Fix memory leak in SNMP.
openhab/openhab-addons pull request #8623
Opened 2020-10-01 11:25 UTC by fab-kis

When receiving an async request it is placed in a pending request queue. Not canceling it leads to infinty life cycle for those requests, filling up memory.

2020-10-01 11:30 UTC, TravisBuddy commented
## Travis tests were successful
Hey @fab-kis,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-10-02 16:34 UTC, J-N-K requested changes
Thanks, good point. Also thanks for adding a test for that. But please raise this PR against `main`, we do not merge to `2.5.x` directly anymore.

2020-10-02 16:34 UTC, J-N-K commented on bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java
> +        if (event.getSource() instanceof org.snmp4j.Snmp) {
import `Snmp` instead of using a FQCN

2020-10-02 16:34 UTC, J-N-K commented on bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/SnmpTargetHandlerTest.java
> +    class SnmpMock extends org.snmp4j.Snmp {
See above

2020-10-02 22:08 UTC, closed without merging

2020-10-02 22:09 UTC, kaikreuzer commented
Please create this PR against the `main` branch, see https://github.com/openhab/openhab-addons/issues/8512.

2020-10-05 14:11 UTC, fab-kis commented
> 
> 
> Please create this PR against the `main` branch, see #8512.

Ok, sorry. It's the first time contributing in github for me :-).
It is under way now in #8672