remove embedded broker
openhab/openhab-addons pull request #8643
Opened 2020-10-03 14:51 UTC by J-N-K

As discussed before the embedded broker will be removed for OH3 as the underlying moquette library has issues and is not maintained anymore.

This leaves the code in place for the itests but removes the feature and the bundle from the addons-bom.

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

2020-10-03 15:55 UTC, kaikreuzer requested changes
No, this won't work - the whole bundle project should be removed.

2020-10-03 20:18 UTC, kaikreuzer commented
It seems to me that the only dependency of the itests to the embedded broker is to the constants class - I have simply moved that to the itests and I think we should be fine to completely remove the broker with that.

I have created https://github.com/openhab/openhab-addons/pull/8649 for it as a replacement for this PR here.

2020-10-03 20:18 UTC, closed without merging

2020-11-07 10:34 UTC, andsel commented
Hi I'm planning to fix some bugs on Moquette side to make it more reliable. Can we work together on this? 
Were you able to isolate a list of problem you experienced?

2022-07-29 19:38 UTC, kaikreuzer commented
Hi @andsel, it seems we all missed your message from Nov 2020 here - I just received a github notification for https://github.com/moquette-io/moquette/issues/473 from which I learned that Moquette isn't dead after all!

@openhab/add-ons-maintainers Do you happen to know which issues we had with Moquette that we decided to remove it? Could you point @andsel to according bug reports and see whether this might be fixed already by now?

2022-07-29 19:48 UTC, J-N-K commented
https://github.com/moquette-io/moquette/compare/main...J-N-K:moquette:master

These were the fixes we made in the past. But if IIRC there were other issues with lost connections/re-connection. There also were request for supporting MQTT5 on client side, so I believe this would also be a requirement for server-side.

2022-08-01 12:55 UTC, andsel commented
Hi @J-N-K 
a lot has changed in the concurrency model inside Moquette, now every session is handled only by one thread, it implements the concept of event loop. This should have fixed weird connection/disconnection execution. There is the possibility that you check against Moquette  `main` branch?

The plan is also to implement MQTT5, which is a pretty heavy task, so should take months :-( I can work on this only spare time