[snmp] Fix memory leak in SNMP
openhab/openhab-addons pull request #8672
Opened 2020-10-05 11:42 UTC by fab-kis

When receiving an async request it is placed in a pending request queue. Not canceling it leads to infinty life cycle for those requests, filling up memory.

2020-10-05 11:45 UTC, fab-kis commented
This PR fixes #8622.

2020-10-05 11:48 UTC, TravisBuddy commented
## Travis tests were successful
Hey @fab-kis,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-10-07 14:41 UTC, J-N-K requested changes
Otherwise ok

2020-10-07 14:41 UTC, J-N-K commented on bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java
> +        if (event.getSource() instanceof org.snmp4j.Snmp) {
```suggestion
        if (event.getSource() instanceof Snmp) {
```

2020-10-08 06:25 UTC, fab-kis commented on bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java
> +        if (event.getSource() instanceof org.snmp4j.Snmp) {
Oh, i miss this, sorry for that.

2020-10-10 17:10 UTC, J-N-K approved these changes

2020-10-10 17:11 UTC, merged