[miio] allow for device remarks in the readme from json db
openhab/openhab-addons pull request #8676
Opened 2020-10-06 07:16 UTC by marcelrv

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

2020-10-06 07:21 UTC, TravisBuddy commented
## Travis tests were successful
Hey @marcelrv,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-10-06 19:50 UTC, cpmeister requested changes

2020-10-06 19:50 UTC, cpmeister commented on bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ReadmeHelper.java
> +                sw.write(" | " + minLengthString(remark, 10) + " |\r\n");
```suggestion
                sw.write(" | ");
                sw.write(minLengthString(remark, 10));
                sw.write(" |\r\n");
```

2020-10-06 21:27 UTC, cpmeister approved these changes
LGTM

2020-10-06 22:04 UTC, merged

2020-10-07 07:24 UTC, Hilbrand commented
Please don't create branches in the repository!!!! And if you do clean up after it's merged.

2020-10-07 08:18 UTC, marcelrv commented
@Hilbrand I normally don't... it was wrong setting in my newly created OH3 eclipse instance.

2020-10-08 18:49 UTC, kaikreuzer commented
Is there anything we need to fix in the IDE setup?

2020-10-08 20:54 UTC, marcelrv commented
@kaikreuzer I'll do some checking this weekend, maybe setup a new one.
I had quite some difficulties getting my oh3 eclipse going, so maybe in my attempts to fix it ,I setup git wrong.