[deconz] retry full state request if initial request failed
openhab/openhab-addons pull request #8704
Opened 2020-10-09 13:55 UTC by J-N-K

Fixes #8434 

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

2020-10-09 14:00 UTC, TravisBuddy commented
## Travis tests were successful
Hey @J-N-K,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-10-09 21:03 UTC, fwolter requested changes

2020-10-09 21:03 UTC, fwolter commented on bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java
> +                scheduler.schedule(this::requestFullState, POLL_FREQUENCY_SEC, TimeUnit.SECONDS);
Shouldn't this be cancelled when the Bridge is disposed?

2020-10-10 07:35 UTC, J-N-K commented
I changed it to only retry if it is an initial request (i.e. when the thing is initialized) but not when it was issued by the discovery service. Then I can re-use the existing `scheduledFuture` field, because either no API-key request was necessary (already present) or it was finished before `requestFullState` is called.

2020-10-10 09:40 UTC, J-N-K commented
Jenkins fails unrelated (Formatting error in nuvo)

2020-10-10 20:56 UTC, fwolter approved these changes
LGTM

2020-10-10 20:56 UTC, merged

2020-10-10 20:57 UTC, fwolter commented
As you asked about the cherry-picking, I guess you want to cherry-pick it yourself?

2020-10-10 23:36 UTC, eric1905 commented
Will it also be merged to 2.5.x or only 3.0

2020-10-11 07:24 UTC, J-N-K commented
Already done.