[lcn] Fix status message of RollerShutter inversion
openhab/openhab-addons pull request #8735
Opened 2020-10-11 20:51 UTC by fwolter

The status of RollerShutter was not inverted when invertUpDown=true. Fixes #8680

Signed-off-by: Fabian Wolter <github@fabian-wolter.de>

2020-10-11 20:57 UTC, TravisBuddy commented
## Travis tests were successful
Hey @fwolter,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-10-13 00:20 UTC, cpmeister requested changes

2020-10-13 00:20 UTC, cpmeister commented on bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleHandler.java
> +                        || invertUpDown instanceof Boolean && invertUpDown.equals(true)) {
Minor optimization.
```suggestion
                if (Boolean.TRUE.equals(invertState) || Boolean.TRUE.equals(invertUpDown)) {
```

2020-10-13 07:42 UTC, fwolter commented on bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleHandler.java
> +                        || invertUpDown instanceof Boolean && invertUpDown.equals(true)) {
True! Done.

2020-10-18 18:39 UTC, cpmeister approved these changes

2020-10-18 18:39 UTC, merged

2020-10-18 18:41 UTC, cpmeister commented
Can you create another PR for the 2.5 branch? My git repo isn't in a good state to change branches right now.

2020-10-18 18:44 UTC, fwolter commented
I'll do the cherry-picking.