[Ip Camera] checkstyle fixes and openHAB3 improvements
openhab/openhab-addons pull request #8752
Opened 2020-10-14 12:13 UTC by Skinah

CheckStyle fixes.
Channel label improvements for better 'create equipment from thing' experience in V3.
Readme updated for the above change.
Remove openhab2 from a few places, one caused issues due to folder location not existing in V3.

Signed-off-by: Matthew Skinner matt@pcmus.com

2020-10-14 12:18 UTC, TravisBuddy commented
## Travis tests were successful
Hey @Skinah,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-10-15 06:57 UTC, Skinah commented
@fwolter 
You requested/suggested I take a look at `target/code-analysis/report.html` so this PR has done that and fixed up some issues I have noticed during testing under V3

Also what happens if I update the readme.md to better suit V3 users? Does the docs on the website allow the previous version to be viewed using the drop down list that is located in the top right hand corner?

If I select 2.5.x it does not show the current readme as I was hoping, probably as this binding was merged into 2.5.9 and did not exist in 2.5.0
See:
https://www.openhab.org/v2.5/addons/bindings/ipcamera/

2020-10-15 17:27 UTC, fwolter commented
> If I select 2.5.x it does not show the current readme as I was hoping, probably as this binding was merged into 2.5.9 and did not exist in 2.5.0

I can't answer this question, but it seems to be a general issue. As the purpose of the drop down field is to have dedicated readmes for different versions, I guess you can go for it and add some OH3 specific parts.

2020-10-15 17:54 UTC, fwolter requested changes
Please note that the title of this PR will appear in the changelog. You could express it a bit more user related. You could also include the word "refactor", to show that you made changes that don't affect the user.

If I see correctly, the only change, the user will see are the `advanced`s and some texts.

2020-10-15 17:54 UTC, fwolter commented on bundles/org.openhab.binding.ipcamera/README.md
> +In openHAB 3, if you use the `Create Equipment from Thing` feature to auto create your items, the following will need minimal editing to change the camera name from `BabyCam` to what you choose to na
```suggestion
If you use the `Create Equipment from Thing` feature to auto create your items, the following will need minimal editing to change the camera name from `BabyCam` to what you choose to name the camera.
```

2020-10-15 17:54 UTC, fwolter commented on bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/binding/binding.xml
> +	<description>This binding is useful if you wish to use IP cameras in openHAB.</description>
"openHAB" don't need to be part of the description. Here is another suggestion:
```suggestion
	<description>This binding interfaces IP cameras of various vendors via open protocols.</description>
```

2020-10-15 18:14 UTC, cpmeister requested changes

2020-10-15 18:14 UTC, cpmeister commented on bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/StreamServerHandler.java
> +                    System.arraycopy(content.content(), 0, incomingJpeg, recievedBytes, content.content().capacity());
`content.content()` isn't an array type, so I don't think `System.arraycopy` would work as written.
```suggestion
                    System.arraycopy(content.content().array(), 0, incomingJpeg, recievedBytes, content.content().capacity());
```

2020-10-16 18:39 UTC, cpmeister approved these changes

2020-10-18 17:39 UTC, fwolter approved these changes
LGTM. There are three `AvoidScheduleAtFixedRateCheck` warnings left. Can you fix these (in another PR)?

2020-10-18 17:40 UTC, merged