[miio] Allow for quantity Type [WIP]
openhab/openhab-addons pull request #8756
Opened 2020-10-14 23:36 UTC by marcelrv

e.g. use number:temperature

readonly temperature tested.
note: needs further testing on dimensionless and handle command

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

2020-10-14 23:42 UTC, TravisBuddy commented
## Travis tests have failed
Hey @marcelrv,
please read the following log in order to understand the failure reason. There might also be some helpful tips along the way.
It will be awesome if you fix what is wrong and commit the changes.

2020-11-05 22:21 UTC, marcelrv commented
@cpmeister do you know if there is a way to get the  unit, e.g. SIUnits.CELSIUS from the string "Celsius' or e.g.  SmartHomeUnits.AMPERE from the string "ampere"  I don't seem to find a 'Unit.getUnit(String)' sort of function.

In the end, I'm  want to  create a QuantityType<?> with the right format having the string "Celsius"... (note I found .toUnit but that takes °C to convert instead of celsius.)

Alternatively I can make my own enum to convert the string, but that feels like the wrong approach

2020-11-05 22:57 UTC, cpmeister commented
I tried looking for something that you could use but it seems that you are right, there is no easy utility in the core or the units library that would return a Units instance based off of the formal name of the unit. The primary reason for this is that the formal names of the units only exist as class field names. The only existing lookup method that is close to what you are looking for is `UnitUtils.parseUnit(String)`. But even that method is expecting the unit symbol, not the unit name. 

If you really need a way to create a unit based off of the unit name you would have to create it yourself right now. You can either create a mapping function or use reflection to lookup unit fields based off their field name.

2020-11-06 16:06 UTC, marcelrv commented
thanks @cpmeister for the response on the conversion. I thought I was crazy not to find such thing.
I indeed created my own little conversion, with the units I've seen so far. Works well in my testing and indeed does the automatic conversions for e.g. folks having imperial units.

2020-11-08 02:04 UTC, cpmeister requested changes
These changes look like a great start. Are you going to adjust more channels or are you just doing temperature for now?

2020-11-08 02:04 UTC, cpmeister commented on bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
> +                updateState(basicChannel.getChannel(), new DecimalType(val.getAsBigDecimal()));
you forgot to add break statements.

2020-11-08 17:37 UTC, marcelrv commented
This PR will be basically just looking at adding the functionality.
I still need to experiment a bit how OH is behaving if you have already your item definitions and you are changing it to a quantity type. (e.g what happens if you keep your definition files the old ones, but the thing expects a quanity type.)

If there is no adverse behavior, I'll start changing the json db files.

In the next few weeks I'm planning to add a next wave of new devices, those I'll create with these new quantity types from the gekko.

2020-11-09 03:26 UTC, cpmeister approved these changes
If you feel this is ready to merge let me know.

2020-11-09 07:59 UTC, marcelrv commented
thanks, would be great if it can be merged.

2020-11-09 16:39 UTC, merged