[neohub] added automatic discovery of NeoHubs
openhab/openhab-addons pull request #8805
Opened 2020-10-19 18:51 UTC by andrewfg

This PR adds an mDNS auto discovery service participant to discover NeoHubs

2020-10-19 19:33 UTC, TravisBuddy commented
## Travis tests were successful
Hey @andrewfg,
we found no major flaws with your code. Still you might want to look at this logfile, as we usually suggest some optional improvements.

2020-10-20 22:32 UTC, cpmeister requested changes

2020-10-20 22:32 UTC, cpmeister commented on bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubDiscoveryParticipant.java
> +@Component(immediate = true)
Components shouldn't be declared immediate anymore.

```suggestion
@Component
```

2020-10-20 22:32 UTC, cpmeister commented on bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubDiscoveryParticipant.java
> +        @Nullable
You can omit `@Nullable` for local variables.
```suggestion
```

2020-10-20 22:32 UTC, cpmeister commented on bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubDiscoveryParticipant.java
> +        @Nullable
```suggestion
```

2020-10-20 22:32 UTC, cpmeister commented on bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubDiscoveryParticipant.java
> +            logger.debug("Discovered a NeoHub on host '{}'", ipStr);
The discovery service is going to log this anyway, so I don't think this log is necessary.

2020-10-21 11:41 UTC, andrewfg commented
Many thanks for the feedback @cpmeister. I made the following changes..

- removed the underlying need for those null annotations
- eliminated the log message (and thus the logger instance)
- made the search filter potentially a bit more future proof

2020-10-21 15:50 UTC, cpmeister approved these changes

2020-10-21 15:50 UTC, merged