[kodi] Reduce polling by checking linkage first
openhab/openhab-addons pull request #8912
Opened 2020-10-31 07:36 UTC by cweitkamp

- 9d9fa59a7b3414f4867f230fa63346fe32f25dac

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

2020-10-31 15:02 UTC, J-N-K requested changes

2020-10-31 15:02 UTC, J-N-K commented on bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/handler/KodiHandler.java
> +        updateState(mutedChannelUID, muted ? OnOffType.ON : OnOffType.OFF);
```suggestion
        updateState(mutedChannelUID, OnOffType.from(muted));
```

2020-10-31 20:06 UTC, cpmeister approved these changes
Other than @J-N-K 's comment, it looks good to me.

2020-11-01 16:32 UTC, J-N-K approved these changes

2020-11-01 21:29 UTC, merged