[ipcamera] Improve ONVIF preset names
openhab/openhab-addons pull request #8948
Opened 2020-11-03 05:18 UTC by Skinah

Improvement: Display actual ONVIF preset names instead of generic "Preset 1" previously used.
Improvement: Allow `-rtsp_transport tcp` default option to be over-ridden.
Bug Fix: Camera may report an actual IP in responses that may not match what is given in setup. eg. Hostname used.
Bug Fix: Prevent possible endless loop.

The main change that users will notice is the ONVIF names will now display correctly with the custom name they gave when the preset was created. The other three changes 99% of users will not notice.

Signed-off-by: Matthew Skinner <matt@pcmus.com>

2020-11-09 03:11 UTC, cpmeister requested changes

2020-11-09 13:08 UTC, Skinah commented on bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/AmcrestHandler.java
> -                return;
Because it is already handled in the main class/handler as all camera things have this, so this is dead code it will never run.

2020-11-09 13:21 UTC, Skinah commented on bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraActions.java
>          }
Thanks much neater.

2020-11-09 17:20 UTC, cpmeister requested changes

2020-11-09 17:20 UTC, cpmeister commented on bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/StreamServerHandler.java
> +                            // ctx.close();
remove commented code

2020-11-11 07:51 UTC, Skinah commented on bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/StreamServerHandler.java
> +                            // ctx.close();
DONE

2020-11-17 02:25 UTC, cpmeister approved these changes

2020-11-21 06:27 UTC, merged

2020-12-10 20:08 UTC, paspiz85 commented
Sorry @Skinah but "Allow -rtsp_transport tcp default option to be over-ridden as it was hard coded and not able to be changed" is a bugfix not an improvment because some cameras cannot work with tcp but only with udp. My camera doesn't work without this fix, can you help me?