[meteoalerte] Adressing Issue #8543
openhab/openhab-addons pull request #8961
Opened 2020-11-05 08:29 UTC by clinique

Signed-off-by: clinique <gael@lhopital.org>

2020-11-05 08:30 UTC, clinique commented
Issue #8543

2020-11-05 12:04 UTC, lolodomo approved these changes
LGTM

2020-11-09 18:22 UTC, cpmeister requested changes

2020-11-09 18:22 UTC, cpmeister commented on bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/handler/MeteoAlerteHandler.java
> +                String resource = new String(bytes);
Please specify the charset used here

2020-11-09 18:22 UTC, cpmeister commented on bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/handler/MeteoAlerteHandler.java
> +                result = new RawType(resource.getBytes(), "image/svg+xml");
and here as well

2020-11-09 18:44 UTC, cpmeister approved these changes

2020-11-09 20:50 UTC, cpmeister commented
Strange, looks like the vigicrues build is failing. 

```
[ERROR] org.openhab.binding.vigicrues.internal.dto.hubeau.HubEauResponse.java:[1]
Header is missing
[ERROR] org.openhab.binding.vigicrues.internal.dto.hubeau.HubEauResponse.java:[7]
An author tag is missing
```

It isn't related to this PR but it is something that you should fix in another PR if it is still an issue.

2020-11-09 20:51 UTC, merged