[omnikinverter]fix missing dispose
openhab/openhab-addons pull request #9010
Opened 2020-11-12 16:28 UTC by J-N-K

Fixes #8703 

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

2020-11-13 06:57 UTC, cpmeister commented on bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/OmnikInverter.java
>          ArrayUtils.reverse(serialBytes);
flipping then reversing it?

2020-11-13 23:08 UTC, cpmeister requested changes

2020-11-13 23:08 UTC, cpmeister commented on bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/handler/OmnikInverterHandler.java
> +        updateStatus(ThingStatus.UNKNOWN);
```suggestion
        updateStatus(ThingStatus.UNKNOWN);
        pollJob = scheduler.scheduleWithFixedDelay(this::updateData, 0, 10, TimeUnit.SECONDS);
```

2020-11-14 23:27 UTC, merged

2021-08-01 19:12 UTC, hansbogert commented
late to the party, thanks for fixing this. I had no idea of this dispose method. In fact, the documentation is pretty sparse on making robust bindings, or did I just not look at the documentation correctly when I made the binding?