[ecobee] Updates in prep for Dec 1 changes to Ecobee authorization process
openhab/openhab-addons pull request #9065
Opened 2020-11-18 22:48 UTC by mhilbush

On 1 December 2020, Ecobee will make changes to their authorization process. Users who authorized the binding prior to December 1 will continue to work using the old process, however, Ecobee recommends that users reauthorize using the new process. In addition, any new installations of the binding after 1 Dec will use the new process.

The changes included in this PR support the new process, as well as include several small fixes that will help ensure the reauthorization process runs smoothly.

Also related to #9039

A similar set of changes will be pushed for 2.5.x.

Signed-off-by: Mark Hilbush <mark@hilbush.com>

2020-11-19 13:28 UTC, mhilbush commented
I added the M3 milestone tag. Given that the Ecobee back end changes take effect on 1 Dec, it's very desirable to get this into milestone 3.

2020-11-24 17:56 UTC, fwolter requested changes
I didn't see this in time. Next time you could add the critical label.

2020-11-24 17:56 UTC, fwolter commented on bundles/org.openhab.binding.ecobee/README.md
> +- At this point the Ecobee Account thing should be OFFLINE with a CONFIGURATION_PENING status.
```suggestion
- At this point the Ecobee Account thing should be OFFLINE with a CONFIGURATION_PENDING status.
```

2020-11-24 18:01 UTC, mhilbush commented on bundles/org.openhab.binding.ecobee/README.md
> +- At this point the Ecobee Account thing should be OFFLINE with a CONFIGURATION_PENING status.
Thanks for catching this.

2020-11-24 18:04 UTC, fwolter approved these changes
LGTM

2020-11-24 18:05 UTC, merged

2020-11-24 18:05 UTC, fwolter commented
Shall I cherry-pick this to the 2.5.x branch?

2020-11-24 18:06 UTC, mhilbush commented
I already submitted a separate PR for 2.5.x. It contains this change, as well as another fix.