[mail] Added translations for ThingActions
openhab/openhab-addons pull request #9121
Opened 2020-11-24 15:46 UTC by cweitkamp

- Added translations for ThingActions

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

2020-11-24 17:48 UTC, fwolter requested changes

2020-11-24 17:48 UTC, fwolter commented on bundles/org.openhab.binding.mail/src/main/resources/OH-INF/i18n/mail_de.properties
> +sendAttachmentsMessageActionDescription = Sendet eine E-Mail mit einigen Anh�ngen.
```suggestion
sendAttachmentsMessageActionLabel = eine E-Mail mit mehreren Anh�ngen senden
sendAttachmentsMessageActionDescription = Sendet eine E-Mail mit mehreren Anh�ngen.
```

2020-11-24 17:48 UTC, fwolter commented on bundles/org.openhab.binding.mail/src/main/resources/OH-INF/i18n/mail_de.properties
> +sendHTMLAttachmentsMessageActionDescription = Sendet eine HTML E-Mail mit einigen Anh�ngen.
```suggestion
sendHTMLAttachmentsMessageActionLabel = eine HTML E-Mail mit mehreren Anh�ngen senden
sendHTMLAttachmentsMessageActionDescription = Sendet eine HTML E-Mail mit mehreren Anh�ngen.
```

2020-11-24 22:39 UTC, cweitkamp commented on bundles/org.openhab.binding.mail/src/main/resources/OH-INF/i18n/mail_de.properties
> +sendHTMLAttachmentsMessageActionDescription = Sendet eine HTML E-Mail mit einigen Anh�ngen.
Sounds better, indeed.

2020-11-25 06:52 UTC, fwolter approved these changes

2020-11-25 06:52 UTC, merged