[nikobus] - added new trigger channels for Nikobus push button
openhab/openhab-addons pull request #9166
Opened 2020-11-29 11:03 UTC by crnjan

When a physical Nikobus push button is presssed&hold, it will send a new packet every ~50ms. Nikobus v2 binding simply forwards this events while Nikobus v1 filtered and converted them to short/long press(es). In order to add missing functionality (also requested by the community) new trigger channels are introduced to bridge this gap. 

Signed-off-by: Boris Krivonog <boris.krivonog@inova.si>

2020-12-01 01:37 UTC, cpmeister requested changes

2020-12-01 01:37 UTC, cpmeister commented on bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/config/config.xml
> +		<parameter name="period" type="integer" min="0">
```suggestion
		<parameter name="period" type="integer" min="0" unit="ms">
```

2020-12-01 01:37 UTC, cpmeister commented on bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/config/config.xml
> +		<parameter name="delay" type="integer" required="true" min="0">
```suggestion
		<parameter name="delay" type="integer" required="true" min="0" unit="ms">
```

2020-12-01 01:37 UTC, cpmeister commented on bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/config/config.xml
> +		<parameter name="threshold" type="integer" required="true" min="0">
```suggestion
		<parameter name="threshold" type="integer" required="true" min="0" unit="ms">
```

2020-12-01 01:37 UTC, cpmeister commented on bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/thing/pc-link.xml
> +			<parameter name="refreshInterval" type="integer" max="65535" min="10">
```suggestion
			<parameter name="refreshInterval" type="integer" max="65535" min="10" unit="s">
```

2020-12-03 21:27 UTC, crnjan commented
Accidentally pushed an unwanted commit, should be ready for review now.

2020-12-04 17:24 UTC, cpmeister requested changes
Please put nested classes at the end of the file. But other than that LGTM.

2020-12-04 22:24 UTC, crnjan commented
Build failure should not be related to this PR

```
[INFO] openHAB Add-ons :: Bundles :: Nikobus Binding ...... SUCCESS [02:43 min]
```

2020-12-07 23:05 UTC, merged