[Tankerkoenig] Documentation: Changed reference from Paper UI to Main…
openhab/openhab-addons pull request #9382
Opened 2020-12-14 16:06 UTC by JueBag

… UI.

Changed reference from Paper UI to Main UI.  

Signed-off-by: Jürgen Baginski <opus42@gmx.de>

2020-12-14 19:07 UTC, Confectrician commented
Maybe you could also remove the oh1 wiki reference at the bottom. (About line 190.)
We should be able to detect holidays with ephemeris feature nowadays.

2020-12-14 19:28 UTC, hmerk commented
@JueBag 
As the name MainUI might change, we should not use this term. Ui should be enough.

2020-12-14 20:48 UTC, Confectrician approved these changes
LGTM

2020-12-14 21:25 UTC, hmerk approved these changes
LGTM

2020-12-15 21:14 UTC, fwolter requested changes

2020-12-15 21:14 UTC, fwolter commented on bundles/org.openhab.binding.tankerkoenig/README.md
> +If the Tankerkönig return indicates an error a descriptive message (in German) is added next to the OFFLINE which will be displayed on the Webservice and Station(s) pages on UI. For further investiga
```suggestion
If the Tankerkönig return indicates an error a descriptive message (in German) is added next to the OFFLINE which will be displayed on the Webservice and Station(s) pages on UI. For further investigation the API Explorer can be used to show all data-fields of the things.
```

2020-12-15 21:19 UTC, fwolter commented
You filed your PR directly against the main branch in the upstream repository. The normal way would be to first fork the addons repository and then file the PR from your forked repository.

2020-12-15 21:27 UTC, Confectrician commented
Unfortunately that's the way it gets created, when you have access and use the github web ui for editing.
I have those problems too, when i just want to fix some small readme things and lazily use the web editor.

2020-12-15 21:31 UTC, fwolter commented
Does it have any impact when filing it directly?

2020-12-16 07:09 UTC, JueBag commented
> You filed your PR directly against the main branch in the upstream repository.

?? IMHO I pushed against https://github.com/openhab/openhab-addons/tree/JueBag-patch-1

2020-12-16 08:33 UTC, hmerk commented
Correctly you should have a fork of the repo, make your changes in that fork and then create a PR. This can also be done trough web interface.

2020-12-16 08:53 UTC, fwolter commented
That was the impact I was retrying to remember. You created a branch on the official repository. This is bad...

2020-12-16 09:31 UTC, fwolter approved these changes

2020-12-16 09:32 UTC, merged

2020-12-16 09:33 UTC, fwolter commented
I deleted your branch in the official repo, after merging.

2020-12-16 11:00 UTC, JueBag commented
> Correctly you should have a fork of the repo, make your changes in that fork and then create a PR. This can also be done trough web interface.

I'm sorry for that. @hmerk told me before, however I obviously missunderstood this autocreated branch as an own fork.