[pidcontroller] Initial Contribution
openhab/openhab-addons pull request #9512
Opened 2020-12-25 08:03 UTC by fwolter

This is a PID controller for openHAB.

See https://community.openhab.org/t/new-automation-pid-controller/111229

2020-12-25 10:46 UTC, J-N-K requested changes

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/README.md
> +If the output is the opening of a valve in %, you might want to set this parameter to higher values (`Kp=10` would result in 50%).
```suggestion
If the output is the opening of a valve in %, you might want to set this parameter to higher values (`kp=10` would result in 50%).
```

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/README.md
> +Tuning the `Kp`, `Ki` and `Kd` parameters can be done by appling science.
```suggestion
Tuning the `Kp`, `Ki` and `Kd` parameters can be done by applying science.
```

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/README.md
> +To be able to proceed with this method, you need to visualization the input and the output value of the PID controller over time.
```suggestion
To be able to proceed with this method, you need to visualize the input and the output value of the PID controller over time.
```

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/README.md
> +2. Increase `kp` as long as the system starts to oscillate (continuous over- and undershoot)
```suggestion
2. Increase `kp` until the system starts to oscillate (continuous over- and undershoot)
```

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerActionHandler.java
> +    public Map<String, Object> execute(Map<String, Object> context) {
```suggestion
    public @Nullable Map<String, Object> execute(Map<String, Object> context) {
```

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerTriggerHandler.java
> +        String inputItemName = (String) Objects.requireNonNull(config.get(CONFIG_INPUT_ITEM), "Input item is not set");
This throws an NPE and if I didn't overlook something, that is never catched.

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerTriggerHandler.java
> +        if (controllerjob != null) {
Assign to a local variable to prevent the null-warning.

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/template/PIDControllerRuleTemplate.java
> +        final List<Trigger> triggers = Collections.singletonList(ModuleBuilder.createTrigger().withId(triggerId)
```suggestion
        final List<Trigger> triggers = List.of(ModuleBuilder.createTrigger().withId(triggerId)
```

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/template/PIDControllerRuleTemplate.java
> +        final List<Action> actions = Collections.singletonList(ModuleBuilder.createAction()
```suggestion
        final List<Action> actions = List.of(ModuleBuilder.createAction()
```

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/template/PIDControllerRuleTemplate.java
> +        tags.add("PID Controller");
```suggestion
        Set<String> tags = Set.of("PID Controller");
```

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/template/PIDControllerTemplateProvider.java
> +    private final Map<String, RuleTemplate> providedRuleTemplates = new HashMap<String, RuleTemplate>();
```suggestion
    private static final RuleTemplate PROVIDED_RULE_TEMPLATE = PIDControllerRuleTemplate.initialize();
```

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/template/PIDControllerTemplateProvider.java
> +        return Collections.unmodifiableCollection(providedRuleTemplates.values());
```suggestion
        return Set.of(PROVIDED_RULE_TEMPLATE);
```

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/template/PIDControllerTemplateProvider.java
> +        return providedRuleTemplates.get(UID);
```suggestion
       
        return uid.equals(PIDControllerRuleTemplate.UID) ? PROVIDED_RULE_TEMPLATE : null;
```

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/template/PIDControllerTemplateProvider.java
> +        return providedRuleTemplates.values();
```suggestion
        return Set.of(PROVIDED_RULE_TEMPLATE);
```

2020-12-25 10:46 UTC, J-N-K commented on bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/type/PIDControllerModuleTypeProvider.java
> +    private final Map<String, ModuleType> providedModuleTypes = new HashMap<String, ModuleType>();
```suggestion
    private static final Map<String, ModuleType> PROVIDED_MODULE_TYPE = new Map.of(...)
```

2020-12-25 12:13 UTC, fwolter commented
@J-N-K Thanks! I incorporated all your feedback.

2020-12-27 12:32 UTC, J-N-K approved these changes
LGTM.

2020-12-28 17:30 UTC, cpmeister approved these changes
LGTM

2020-12-28 17:31 UTC, merged

2021-01-04 12:26 UTC, m0rgano commented
@fwolter 
Great news to find your work on this.
Is there any documentation on how to install and/or use it?
I am currently using V2.5 - is it compatible with this version?

2021-01-04 12:31 UTC, fwolter commented
You find the documentation here https://github.com/fwolter/openhab-addons/blob/pidcontroller/bundles/org.openhab.automation.pidcontroller/README.md

You need OH 3.x to run it.

2021-01-04 12:34 UTC, m0rgano commented
@fwolter 
Thanks for the link Fabian - unfortunately I get a 404 error on it.

2021-01-04 12:37 UTC, fwolter commented
Ha, that's why I just deleted the dev branch. Here is the link to the merged version: https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.automation.pidcontroller/README.md

2021-01-04 12:49 UTC, m0rgano commented
@fwolter  That link is working OK thanks. I'm familiar with the Rules engine - I have a lot of text-based rules.
Do you have a simple rule example you could paste here showing the use of the PID addon to get me (and others) started please?

2021-01-04 16:17 UTC, fwolter commented
I have no clue how to configure it text-based. The forum post linked in the initial message shows screenshots of an UI based configuration.

2021-01-04 16:48 UTC, m0rgano commented
@fwolter  OK thanks - I'll ask in the OH thread if it is possible via the Rules DSL or whether it has to be in the GUI.