Add Diagnostics indication channel
openhab/openhab-addons pull request #9516
Opened 2020-12-25 13:21 UTC by ArjenKorevaar

Signed-off-by: Arjen Korevaar <a.korevaar@mephix.com>

Add Diagnostics indication channel

See #9515

2020-12-27 14:50 UTC, J-N-K requested changes
Is this working without any code-changes?

2020-12-27 14:50 UTC, J-N-K commented on bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/OpenThermGatewayBindingConstants.java
> +            .collect(Collectors.toSet()));
```suggestion
           ;
```

2020-12-27 14:50 UTC, J-N-K commented on bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/OpenThermGatewayBindingConstants.java
> +            .of(CHANNEL_ROOM_TEMPERATURE, CHANNEL_ROOM_SETPOINT, CHANNEL_FLOW_TEMPERATURE, CHANNEL_RETURN_TEMPERATURE,
```suggestion
    public static final Set<String> SUPPORTED_CHANNEL_IDS = Set
            .of(CHANNEL_ROOM_TEMPERATURE, CHANNEL_ROOM_SETPOINT, CHANNEL_FLOW_TEMPERATURE, CHANNEL_RETURN_TEMPERATURE,
```

2020-12-28 08:45 UTC, ArjenKorevaar commented
> Is this working without any code-changes?

Yes, DataItemGroup.java contains a complete list of possible opentherm commands, based on the opentherm 2.2 specifications. So in this case adding a new channel to bind to the opentherm command was all that's needed.

2020-12-28 08:50 UTC, J-N-K approved these changes

2020-12-28 18:13 UTC, J-N-K commented
Jenkins failed unrelated.

2020-12-28 18:13 UTC, merged