[WiFi LED] Expanded example
openhab/openhab-addons pull request #9627
Opened 2021-01-01 17:48 UTC by banzaay

[WiFi LED] Expanded example

Added a detailed example

2021-01-03 13:17 UTC, fwolter requested changes

2021-01-03 13:17 UTC, fwolter commented on bundles/org.openhab.binding.wifiled/README.md
> +| LD686  |   ✓   |   ✓   |   ✓   |   ✓    |    ✓    | ✓  |
Can you fix the formatting of the tables?

2021-01-06 16:54 UTC, banzaay commented
I've made the changed requested. 

Bye

2021-01-06 20:11 UTC, fwolter approved these changes
Thanks!

2021-01-06 20:12 UTC, merged