[remoteopenhab] Consider the remote item pattern formatter
openhab/openhab-addons pull request #9657
Opened 2021-01-02 19:09 UTC by lolodomo

Fux #9645

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

2021-01-03 01:58 UTC, cpmeister requested changes

2021-01-03 01:58 UTC, cpmeister commented on bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/RemoteopenhabChannelTypeProvider.java
> +        }
```suggestion
        List<ChannelType> channelTypesForItemType = channelTypesForItemTypes.computeIfAbsent(itemType, type -> new CopyOnWriteArrayList<>());
        if (channelTypesForItemType != null) {
            channelTypesForItemType.add(channelType);
        }
```

2021-01-03 09:20 UTC, lolodomo commented on bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/RemoteopenhabChannelTypeProvider.java
> +        }
Good to know. Applied

2021-01-03 09:29 UTC, lolodomo commented
@cpmeister : do you think I should remove `List<ChannelType> channelTypes` ? I kept it only to have the method `getChannelTypes` simple (just returning it). But I could certainly build the returned value for `getChannelTypes` with my new hashmap.

2021-01-04 05:34 UTC, cpmeister commented
I don't think it matters all that much. As long as the code is simple and performant.

2021-01-04 05:34 UTC, cpmeister approved these changes

2021-01-04 05:35 UTC, merged