[innogysmarthome] NullPointerException fixed which could occur when no device state is available (#9660)
openhab/openhab-addons pull request #9677
Opened 2021-01-03 17:47 UTC by Novanic

This pull request fixes issue #9660, please see issue #9660 for more information.

The pull request contains also some refactorings (mainly to reduce duplicate code) and fixes potential bugs on setting the device reachable and low battery attributes.

2021-01-04 20:15 UTC, fwolter requested changes
You code doesn't compile because there are checkstyle errors. You could take a look at `target/code-analysis/report.html`.

2021-01-04 20:15 UTC, fwolter commented on bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/manager/FullDeviceManager.java
> +            capability.setCapabilityState(capabilityState); // TODO dangerous to change a state in a method called
Can you fix the TODO?

2021-01-07 19:25 UTC, Novanic commented on bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/manager/FullDeviceManager.java
> +            capability.setCapabilityState(capabilityState); // TODO dangerous to change a state in a method called
good hint, I have now solved it

2021-01-08 22:07 UTC, fwolter approved these changes

2021-01-08 22:07 UTC, merged