[tr064] Merge duplicate phone book entries
openhab/openhab-addons pull request #9739
Opened 2021-01-07 20:47 UTC by t2000

Fixes #9738

Signed-off-by: Stefan Triller <github@stefantriller.de>

2021-01-07 23:10 UTC, cpmeister requested changes

2021-01-07 23:10 UTC, cpmeister commented on bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java
> +                                (nameA, nameB) -> mergeSameContactNames(nameA, nameB)));
```suggestion
                                this::mergeSameContactNames));
```

2021-01-08 07:27 UTC, t2000 commented
Thanks, I have integrated your suggestion. (Though I used my git client instead of clicking on your suggestion on github, because I never know if the commit from github satisfies the DCO signature check...).

2021-01-09 09:38 UTC, cweitkamp approved these changes
LGTM. Thanks.

2021-01-09 09:39 UTC, merged