[mqtt] Fix availability topics subscription after Brige Restart
openhab/openhab-addons pull request #9851
Opened 2021-01-17 14:18 UTC by albrechtf

This is a Patch Proposal for #9850. It is the "easy" variant of the fix; the major design flaws in classes `AbstractMQTTThingHandler` and `GenericMQTTThingHandler` (especially regarding availability topics) are not addressed.

A Unit Test is included.

2021-01-17 16:44 UTC, albrechtf commented
CI build fails (stops) after 1 hour. Appreciate any support how to "fix" that :-)

2021-01-24 22:00 UTC, cpmeister requested changes

2021-12-11 11:48 UTC, fwolter commented
@albrechtf What's the state of this PR?

2021-12-11 12:00 UTC, albrechtf commented
@fwolter The state is that my PR was not good enough for the maintainers, and I currently don't have time to adjust it according to their comments. Feel free to provide additional changes / patches so it may be good enough for merging, that would be very much appreciated.

2021-12-11 16:57 UTC, fwolter approved these changes
The review comments are valid. In the meantime we lowered our quality standards a bit to accommodate the increasing number of PRs. If you find the time in the future to address the comments, please go ahead.

2021-12-11 16:57 UTC, merged