[miio] validate response id matching command id
openhab/openhab-addons pull request #9966
Opened 2021-01-26 11:38 UTC by marcelrv

This PR prevents out of sync issues in case devices are too slow to
respond or the timeout is set too short.

closes #9896

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

2021-01-26 16:01 UTC, fwolter requested changes

2021-01-26 20:04 UTC, marcelrv commented on bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
> +            timeStamp = (int) TimeUnit.MILLISECONDS.toSeconds(Calendar.getInstance().getTime().getTime());
thanks for the suggestion.
Done

2021-01-26 20:04 UTC, marcelrv commented on bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
> +            encr = MiIoCrypto.encrypt(command.getBytes(), token);
Done

2021-01-29 13:17 UTC, marcelrv commented
@cpmeister / @fwolter would you mind reviewing this, so it can still make the 3.1M1this weekend. Would be good to have this fix in.

2021-01-30 11:05 UTC, fwolter approved these changes

2021-01-30 11:05 UTC, merged