[xmppclient] Update Smack library to 4.3.5
openhab/openhab-addons pull request #9977
Opened 2021-01-28 10:09 UTC by Flowdalic

Update the used XMPP client library, Smack, to the latest version of
the 4.3 version series: 4.3.5.

2021-01-28 16:46 UTC, wborn requested changes
The feature.xml file also needs to be updated.

2021-01-28 16:50 UTC, Flowdalic commented
How do I do that?

2021-01-28 17:31 UTC, wborn commented
If you figure out all the dependencies that need to be updated, then you can update them in this file:

https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.xmppclient/src/main/feature/feature.xml

2021-01-28 17:42 UTC, Flowdalic commented
I see and I fear that I do not have the cycles to do that anytime soon.

I am also disappointed that updating a dependency can not be simply done by bumping the central version number. Instead I have to manually check every entry in another file if it is still correct (if I am not mistaken), which can become quite complex for dependencies with many transitive dependencies and/or a deep level of transitive depenencies. Furthermore that inconsistency does not seem to be catched by any check and the CI.

2021-01-28 17:56 UTC, wborn commented
Yes I agree that there is still room for improvement.

2021-02-07 16:48 UTC, Hilbrand commented
You can run `mvn dependency:tree` to see all transitive dependencies.

2021-04-24 11:18 UTC, wborn commented
Do you plan to continue this PR @Flowdalic or should we close it?

2021-05-06 21:18 UTC, wborn commented
Just reopen this PR if you plan to continue with it.

2021-05-06 21:18 UTC, closed without merging